### ISSUE TITLE
Hp SPP - bootup from iso showing vesamenu.c32

### ISSUE THREAD

**Issue by worldsdream** [pbatard/rufus#1021]
I have downloaded the Service Pack for Proliant. I did mount the .iso with rufus. As I always use Rufus for all iso files. When I booted up on my HP server, i did get: 

"Can not find kernel image vesamenu.c32"

Please fix this issue. Thanks. 

I had to format it with windows to fat32 and use unetbootin and that worked. I dont like to use any other software, I love rufus. That is why.

**Comment by pbatard** [comment]
Sorry, can't help you if you don't follow the checklist. I need a FULL log before I can do anything, and as mentioned when opening an issue _"Failure to perform these steps, WHICH ARE ONLY THERE TO HELP *YOU*, will result in the issue being dismissed without warning"_.
