### ISSUE TITLE
"Please click on  The disc button to select  bootable image"

### ISSUE THREAD

**Issue by neonkodak** [pbatard/rufus#1022]
Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [ ] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
<FULL LOG>
```

**Comment by neonkodak** [comment]
Hi I have a problem attaching an ISO file for windows 10 64-bit to Rufus. 

 It just gives me the following error in the picture above.  I am currently at the last step of downloading windows 10 on an Acer chrome book and have followed the YouTube video below "https://youtu.be/SyrNH_qcvJg" can someone let me know what I'm doing wrong. Thanks.

**Comment by neonkodak** [comment]
![Uploading IMG_8759.JPG…]()
![img_8760](https://user-images.githubusercontent.com/31911489/30359451-67ef4dd8-9810-11e7-9af9-654917b83421.JPG)
![Uploading IMG_8761.JPG…]()

**Comment by neonkodak** [comment]
![img_8759](https://user-images.githubusercontent.com/31911489/30359466-7f609bfc-9810-11e7-816d-a10e2cbf32cb.JPG)

**Comment by neonkodak** [comment]
![img_8761](https://user-images.githubusercontent.com/31911489/30359481-9dfa6444-9810-11e7-89c2-8f32361d00e0.JPG)

**Comment by pbatard** [comment]
As Rufus indicates:
_Please click on the disc button_:
![button](https://user-images.githubusercontent.com/1206968/30369559-dd00d658-986c-11e7-9526-20fd0d2a924b.JPG)
_to select a bootable image_.

**Comment by neonkodak** [comment]
Hi, I did attach threw that disc image and properly selected my iso file and it still gives me that option. I could upload a small clip of my process if need be. Thanks.

**Comment by pbatard** [comment]
No. You should follow the checklist and include the log. As specified when opening an issue, if you __choose__ not to follow the checklist, you shouldn't expect to receive support.

**Comment by neonkodak** [comment]
![img_8763](https://user-images.githubusercontent.com/31911489/30398400-d8105258-9895-11e7-9ce4-ecf275061f09.JPG)

**Comment by neonkodak** [comment]
Will this be sufficient or would you rather me resubmit an issue statement I am more than willing thanks for your time.

**Comment by pbatard** [comment]
> Will this be sufficient

No. I want a __FULL__ log, and I want you to attach it as a text file.

At any rate, it looks like the ISO you are trying to use is incompatible with Rufus. The problem is purely with the fact that either you're not using an official ISO or that it is broken, and this is precisely what this part of the checklist is about:

>  - [ ] If using an ISO image, I clicked on the # button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

I'm sorry but I have no time to support people who can't follow simple instructions, so please don't expect further help here. Google is your friend.
