### ISSUE TITLE
[Wiki] Kali Linux devs fixed UEFI boot problems in the version 2017.1

### ISSUE THREAD

**Issue by Conder000** [pbatard/rufus#1025]
In the Kali Linux version 2017.1, devs properly included the UEFI bootloader `/EFI/BOOT/bootx64.efi` and thus finally fixed the problems with booting Kali Linux in UEFI mode. I have tested creating a bootable USB flash disk with Rufus, in both ISO and DD modes, and both booted in UEFI mode correctly. So you can now delete Kali Linux from the [Incompatible Images](https://github.com/pbatard/rufus/wiki/FAQ#incompatible-images) list in the FAQ.

**Comment by pbatard** [comment]
Done. Thanks for testing.
