### ISSUE TITLE
USB drive is not booting to install Windows 7. (Rufus 2.16.1170 Portable) #1017

### ISSUE THREAD

**Issue by Joseph22a** [pbatard/rufus#1028]
.
Problem / Symptom:  
Most of the time the USB drive is not booting, the boot hangs "Windows is loading files…" : 
But, boots Ok on occasion, say 1 time in 50 boots is Ok; odd.  

Reference: 
https://github.com/pbatard/rufus/issues/1017
USB drive is not booting to install Windows 7. (Rufus 2.16.1170 Portable) #1017

1.	
Rufus 2.17 Portable was used to put ISO data on USB drive.  

2.	
The ISO:
Win7_Pro_SP1_English_COEM_x64.iso  
3.09 GB (3,320,903,680 bytes)  
the above ISO is from web site  
https://www.microsoft.com/en-us/software-download/windows7

3.	
Purpose was to Make Bootable USB flash drive to install Windows 7 without a DVD.  

4.	
Hardware = Hewlett Packard (HP) computer: 
HP Compaq dc7800p Convertible Minitower PC, BIOS date  7/18/2007 

5.	
The computer works Ok, because the computer boots fine from 
DVD-ROM optical drive with Windows 7 disc, and 
this disc installs Windows 7 correctly.  

6.	
Some investigation: What is the BIOS setting to make this ISO boot?

7.	
Some investigation: What is the Rufus 2.17 setting to make this ISO?  

8.	
Some investigation: How to get this win7 professional ISO to boot from USB stick?  

9.	
Some variables are: hardware 
different USB sticks (flash drives) used, 
2 USB drives: 16 GB and then 128 GB 
same problem most of the time booting hangs (stops)

10.	
Some variables are: ISOs 

11.	
Some variables are: 
Rufus 2.16 Portable, 
Rufus 2.17 Portable, 
Rufus 2.17 regular
same problem most of the time booting hangs (stops)

12.	
Some variables are: 
looking for missing USB drivers 

13.	
Some variables are: 
looking for missing disk drivers 

14.	
Different USB ports used; 
same problem most of the time booting hangs (stops)
but on occasion one (1) usb port boots Ok.  
So it appeared the usb ports were different, 
one port seemed to work better than others, 
but booting Ok was intermittent (irregular).

15.	
Solution / Success:
Update BIOS. 

16.	
BIOS version 1.04 from year 2007 was my old BIOS version and 8 years later   
BIOS version 1.35 from year 2015 is now my new BIOS version for:  
HP Compaq dc7800p Convertible Minitower PC.

17.	
The HP Hosted drivers: 
https://support.hp.com/us-en/drivers/selfservice/hp-compaq-dc7800-convertible-minitower-pc/3459240 

There are 3 BIOS drivers listed.

18.	
Only 1 of 3 BIOS drivers installed.  
You have to pinpoint, investigate, as to exactly what needs updating. 

ROM Firmware for HP Compaq dc7800 (786F1) 
v01.35 Rev.A
6.3 MB
Nov 27, 2015

19.	
Inside the 6.3 MB download are many files and 1 BIN file. 
The BIOS uses a BIN file.  
The BIN (Binary) file 
7F1_0135.bin     4.00 MB (4,194,304 bytes)  

20.	
A trick: 
put BIN file (7F1_0135.bin) in the root directory, not a sub directory, 
because the BIOS menu cannot drill down into a sub-directory. 

21.	
BIOS updates in minutes.

22.	
It was a long haul, over 2 years of noticing intermittent, odd, computer behavior. 
For the most part the HP computer was working fine, just now and then odd things noticed.  

23.	
Success!
Now Rufus and ISO boot from USB stick (flash drive).  

24.	
Success!  
Make Bootable USB flash drive to install Windows 7 without a DVD.  

25.	
This above project was to: 
Install Windows 7 from USB stick to a C: drive etc...

26.	
New project: 
Run Windows 7 on USB stick.  

27.	
Windows To Go drives 

about 4 hours to make, to Run Windows 7 on USB stick with: 
- low cost (slow speed) usb stick (flash drive) on 
- usb 2.0 port (slow port), not a usb 3.0 port (faster) 

28.	
Windows 7 To Go :   
11.5 GB (12,350,824,448 bytes) = size on disk, usb 
about 67000 files 
about 14000 folders 

29.	
WinToUSB version 3.7 build 7 August 2017 
https://hasleo.com/  
Windows 7 To Go drives 

--

**Comment by pbatard** [comment]
Your question is not clear (from what I gather you are reporting that you solved your issue) and you din't follow the checklist &rarr; Closed.
