### ISSUE TITLE
Section of documentation outdated?

### ISSUE THREAD

**Issue by Kaos-Industries** [pbatard/rufus#1038]
I came across the following in the FAQ:

> Alt-I (v1.4.7 or later) - Toggle ISO image support:
> By default, when an ISO image can be used as both a regular bootable ISO (Syslinux, WinPE, ...) or bootable flat disk image (DD), Rufus will choose the former method when copying the data. With this option, you can force DD image writing.

Is this not now outdated, since my understanding is that by default Rufus asks which of the options you want to select when working with a Hybrid-ISO?

**Comment by pbatard** [comment]
This option allows you to disable the prompt, if you always want to write in DD mode. So it's not actually outdated. As pointed out in the FAQ, this disables ISO handling, and if you test an ISOHybrid with and without <kbd>Alt</kbd>-<kbd>I</kbd>, you will find that the default behaviour of Rufus has changed.

So, no, this option is not outdated.
