### ISSUE TITLE
button layout issue

### ISSUE THREAD

**Issue by 424778940z** [pbatard/rufus#1048]
when I'm applying a dd image to usb_hdd, the [log] and [start] button at bottom of the window overlaps each other.

version 2.17.1198
system win10 1607 x64

**Comment by pbatard** [comment]
Please provide your __FULL__ log (__YES__, I do need to see your log, even for a cosmetic issue!!) and a screenshot, thank you. I can't do anything about this issue unless I get both these things.

**Comment by pbatard** [comment]
No update &rarr; Closed.

**Comment by 424778940z** [comment]
![000](https://user-images.githubusercontent.com/2379529/32086873-c386016e-ba9d-11e7-9d39-1641d1469e14.png)

here is the picture, but the usb hdd are already in use for data, I can't wipe it again, I tested on a vhd, but everything seems normal

**Comment by pbatard** [comment]
I tried with multiple drives, including HDDs, but I just can't replicate that issue.
