### ISSUE TITLE
Rufus not detecting internal hard drive

### ISSUE THREAD

**Issue by stefanbraem** [pbatard/rufus#1055]
Hi

I'm using Rufus to create an installation disk for a Linux distro. I'd like to use the internal mSSD for the job, since i'm not using that disk anymore as caching space. However, Rufus isn't detecting the mSSD, although I formatted it as a new normal ntfs drive with an active volume. Pressing ALT+F doesn't help either. Could anyone help me on this?

Thanks in advance

Stefan

**Comment by pbatard** [comment]
internal SSDs are __NOT__ supported.
