### ISSUE TITLE
Request: Can you provide a rufus.appimage?

### ISSUE THREAD

**Issue by Lvaskz** [pbatard/rufus#1056]
Hi, it´d be great see rufus for linux , using universal package for linux now, appimage. Watch it 
https://appimage.org/
or if you prefer flatpak

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxOS_XSome_other_OS

I'm not planning to produce a Linux version.

**Comment by LeandroStanger** [comment]
Wine
