### ISSUE TITLE
WIM disk image format support

### ISSUE THREAD

**Issue by Oleg-N-Cher** [pbatard/rufus#1064]
https://en.wikipedia.org/wiki/Windows_Imaging_Format

Sometimes the Windows distribution is supplied in WIM format, and therefore it would be good when Rufus could write a USB flash drive from image of WIM format, which will do without intermediate stages like converters, etc.

**Comment by pbatard** [comment]
Retail distributions are still being distributed in ISO format.

Do you have examples of downloadable official retail versions of Windows being supplied in WIM format?

If not, then I will have to ignore your request.
