### ISSUE TITLE
Write protection

### ISSUE THREAD

**Issue by UlviShukurzade** [pbatard/rufus#1066]
Rufus did not complete the process and also my USB pen drive became write protected.
I can not format my drive.
I have tried several ways to change the permissions but could not able to do

Please help me.

**Comment by pbatard** [comment]
Next time, please follow the check list.
See [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Rufus_cant_detectformat_my_drive_and_reports_that_it_is_readonly_or_contains_no_media) or [this existing issue](https://github.com/pbatard/rufus/issues/313#issuecomment-330818804).
