### ISSUE TITLE
Can't build Rufus with MS VS 2017 v15.5.0

### ISSUE THREAD

**Issue by skipik** [pbatard/rufus#1068]
I'm getting this:

error MSB8036: The Windows SDK version 10.0.16299.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".

Everything was fine on v15.4.5 though.

**Comment by pbatard** [comment]
Yup, you need to reinstall the 10.0.16299.0 SDK, as it seems Microsoft broke something in their 15.5 installer - just unselecting and selecting it might do:
![image1](https://user-images.githubusercontent.com/1206968/33682727-5a197cd6-dac0-11e7-99dc-28e63a798a08.png).

I had the same issue earlier, and sorted it once I got the VS installer to reinstall the SDK.

**Comment by skipik** [comment]
Yeah, it worked! Thanks a lot!
