### ISSUE TITLE
Dr.Web LiveCD .

### ISSUE THREAD

**Issue by Alexander1414x** [pbatard/rufus#1073]
Hello! Im Download Dr.Web LiveCD and go write .iso  and Rufus download Syslinux . This problem boot.
Please test .iso   http://repo.drweb.com/testing/livedisk/ -this download.
LOG:
[rufus.log](https://github.com/pbatard/rufus/files/1573000/rufus.log)

**Comment by Alexander1414x** [comment]
Rufus version: 2.18.1213
Windows version: Windows 10 64-bit (Build 16299)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0419
Will use default UI locale 0x0419
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'ru-RU'
NOTE: The Russian (Русский) translation requires an update, but the current translator hasn't submitted one. Because of this, some messages will only be displayed in English.
If you think you can help update this translation, please e-mail the author of this application
Found USB 2.0 device 'UFD 2.0 Silicon-Power4G USB Device' (13FE:3E00)
Using autorun.inf label for drive E: 'DrWeb LiveDisk'
1 device found
Disk type: Removable, Disk size: 3.9 Гб, Sector size: 512 bytes
Cylinders: 471, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x002927D3
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 3.6 GB (3879403520 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/syslinux/syslinux.cfg' for Syslinux
  Detected Syslinux version: 6.03/20151222 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'DrWeb LiveDisk'
  Size: 797.0  Мб (Projected)
  Uses: Syslinux/Isolinux v6.03
  Uses: EFI
Using image: live.iso (798  Мб)
Downloading 'ldlinux.sys' from http://rufus.akeo.ie/files/syslinux-6.03/20151222/ldlinux.sys
Unable to access file: 404
Extended version was not found, trying main version...
Downloading 'ldlinux.sys' from http://rufus.akeo.ie/files/syslinux-6.03/ldlinux.sys
File length: 68599 bytes
Successfully downloaded 'ldlinux.sys'
Downloading 'ldlinux.bss' from http://rufus.akeo.ie/files/syslinux-6.03/20151222/ldlinux.bss
Unable to access file: 404
Extended version was not found, trying main version...
Downloading 'ldlinux.bss' from http://rufus.akeo.ie/files/syslinux-6.03/ldlinux.bss
File length: 512 bytes
Successfully downloaded 'ldlinux.bss'

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE2 for exclusive write access
Requesting lock...
Will use 'E:' as volume mountpoint
I/O boundary checks disabled
Requesting lock...
Analyzing existing boot records...
Drive has a Syslinux Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (FAT32)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Partition is already FAT32 LBA...
Set bootable USB partition as 0x80
Using Syslinux MBR
Found volume GUID \\?\Volume{c5807c1b-d5fb-11e7-a6b9-240a6474715a}\
Installing Syslinux 6.03...
Opened \\?\Volume{c5807c1b-d5fb-11e7-a6b9-240a6474715a} for shared write access
Using existing './rufus_files/syslinux-6.03/20151222/ldlinux.sys' ✓
Using existing './rufus_files/syslinux-6.03/20151222/ldlinux.bss' ✓
Successfully wrote 'ldlinux.sys'
Successfully wrote Syslinux boot record
Successfully remounted \\?\Volume{c5807c1b-d5fb-11e7-a6b9-240a6474715a}\ on E:
Copying ISO files...
Extracting files...
Image is an ISO9660 image
This image will be extracted using Joliet extensions (if present)
Extracting: E:\.disk\casper-uuid-generic (37 bytes)
Extracting: E:\.disk\info (0 bytes)
Extracting: E:\.info.txt (52 bytes)
Extracting: E:\EFI\BOOT\BOOTIA32.EFI (625 KB)
Extracting: E:\EFI\BOOT\BOOTX64.EFI (1.1 MB)
Extracting: E:\EFI\BOOT\grubx64.efi (1.1 MB)
Extracting: E:\boot\grub\efi.img (4 MB)
Extracting: E:\boot\grub\font.pf2 (32.2 KB)
Extracting: E:\boot\grub\grub.cfg (707 bytes)
Extracting: E:\casper\drweb-10bin.squashfs (8.6 MB)
Extracting: E:\casper\drweb-25key.squashfs (4 KB)
Extracting: E:\casper\drweb-50bases.squashfs (145.3 MB)
Extracting: E:\casper\filesystem.squashfs (603 MB)
Extracting: E:\casper\initrd.lz (24.6 MB)
Extracting: E:\casper\vmlinuz (6.5 MB)
Extracting: E:\install\mt86plus (178.4 KB)
Extracting: E:\isolinux\16x16.fnt (69.6 KB)
Extracting: E:\isolinux\access.pcx (13.5 KB)
Extracting: E:\isolinux\adtxt.cfg (0 bytes)
Extracting: E:\isolinux\back.jpg (7.3 KB)
Extracting: E:\isolinux\blank.pcx (11.2 KB)
Extracting: E:\isolinux\boot.cat (2 KB)
Extracting: E:\isolinux\bootlogo (251 KB)
Extracting: E:\isolinux\chain.c32 (24.3 KB)
Extracting: E:\isolinux\dtmenu.cfg (1.4 KB)
Extracting: E:\isolinux\en.hlp (6.4 KB)
Extracting: E:\isolinux\en.tr (2 KB)
Extracting: E:\isolinux\exithelp.cfg (53 bytes)
Extracting: E:\isolinux\f1.txt (868 bytes)
Extracting: E:\isolinux\f10.txt (723 bytes)
Extracting: E:\isolinux\f2.txt (739 bytes)
Extracting: E:\isolinux\f3.txt (782 bytes)
Extracting: E:\isolinux\f4.txt (417 bytes)
Extracting: E:\isolinux\f5.txt (806 bytes)
Extracting: E:\isolinux\f6.txt (1.2 KB)
Extracting: E:\isolinux\f7.txt (916 bytes)
Extracting: E:\isolinux\f8.txt (1 KB)
Extracting: E:\isolinux\f9.txt (765 bytes)
Extracting: E:\isolinux\gfxboot.c32 (10.3 KB)
Extracting: E:\isolinux\gfxboot.cfg (115 bytes)
Extracting: E:\isolinux\init (105.5 KB)
Extracting: E:\isolinux\isolinux.bin (40 KB)
Extracting: E:\isolinux\isolinux.cfg (178 bytes)
Extracting: E:\isolinux\langlist (6 bytes)
Extracting: E:\isolinux\ldlinux.c32 (113.8 KB)
Extracting: E:\isolinux\libcom32.c32 (178.3 KB)
Extracting: E:\isolinux\libutil.c32 (23.1 KB)
Extracting: E:\isolinux\menu.cfg (437 bytes)
Extracting: E:\isolinux\po4a.cfg (83 bytes)
Extracting: E:\isolinux\prompt.cfg (175 bytes)
Extracting: E:\isolinux\rqtxt.cfg (135 bytes)
Extracting: E:\isolinux\ru.hlp (11.8 KB)
Extracting: E:\isolinux\ru.tr (4.0 KB)
Extracting: E:\isolinux\splash.pcx (13.5 KB)
Extracting: E:\isolinux\splash.png (2 KB)
Extracting: E:\isolinux\stdmenu.cfg (508 bytes)
Extracting: E:\isolinux\syslinux.cfg (178 bytes)
Extracting: E:\isolinux\txt.cfg (290 bytes)
Extracting: E:\isolinux\vesamenu.c32 (26.1 KB)
Extracting: E:\syslinux\16x16.fnt (69.6 KB)
Extracting: E:\syslinux\access.pcx (13.5 KB)
Extracting: E:\syslinux\adtxt.cfg (0 bytes)
Extracting: E:\syslinux\back.jpg (7.3 KB)
Extracting: E:\syslinux\blank.pcx (11.2 KB)
Extracting: E:\syslinux\boot.cat (2 KB)
Extracting: E:\syslinux\bootlogo (251 KB)
Extracting: E:\syslinux\chain.c32 (24.3 KB)
Extracting: E:\syslinux\dtmenu.cfg (1.4 KB)
Extracting: E:\syslinux\en.hlp (6.4 KB)
Extracting: E:\syslinux\en.tr (2 KB)
Extracting: E:\syslinux\exithelp.cfg (53 bytes)
Extracting: E:\syslinux\f1.txt (868 bytes)
Extracting: E:\syslinux\f10.txt (723 bytes)
Extracting: E:\syslinux\f2.txt (739 bytes)
Extracting: E:\syslinux\f3.txt (782 bytes)
Extracting: E:\syslinux\f4.txt (417 bytes)
Extracting: E:\syslinux\f5.txt (806 bytes)
Extracting: E:\syslinux\f6.txt (1.2 KB)
Extracting: E:\syslinux\f7.txt (916 bytes)
Extracting: E:\syslinux\f8.txt (1 KB)
Extracting: E:\syslinux\f9.txt (765 bytes)
Extracting: E:\syslinux\gfxboot.c32 (10.3 KB)
Extracting: E:\syslinux\gfxboot.cfg (115 bytes)
Extracting: E:\syslinux\init (105.5 KB)
Extracting: E:\syslinux\isolinux.bin (40 KB)
Extracting: E:\syslinux\isolinux.cfg (178 bytes)
Extracting: E:\syslinux\langlist (6 bytes)
Extracting: E:\syslinux\ldlinux.c32 (113.8 KB)
Extracting: E:\syslinux\libcom32.c32 (178.3 KB)
Extracting: E:\syslinux\libutil.c32 (23.1 KB)
Extracting: E:\syslinux\menu.cfg (437 bytes)
Extracting: E:\syslinux\po4a.cfg (83 bytes)
Extracting: E:\syslinux\prompt.cfg (175 bytes)
Extracting: E:\syslinux\rqtxt.cfg (135 bytes)
Extracting: E:\syslinux\ru.hlp (11.8 KB)
Extracting: E:\syslinux\ru.tr (4.0 KB)
Extracting: E:\syslinux\splash.pcx (13.5 KB)
Extracting: E:\syslinux\splash.png (2 KB)
Extracting: E:\syslinux\stdmenu.cfg (508 bytes)
Extracting: E:\syslinux\syslinux.cfg (178 bytes)
Extracting: E:\syslinux\txt.cfg (290 bytes)
Extracting: E:\syslinux\vesamenu.c32 (26.1 KB)
Created: E:\syslinux.cfg
Finalizing, please wait...
Created: E:autorun.inf
Created: E:autorun.ico

Found USB 2.0 device 'UFD 2.0 Silicon-Power4G USB Device' (13FE:3E00)
Using autorun.inf label for drive E: 'DrWeb LiveDisk'
1 device found
Disk type: Removable, Disk size: 3.9 Гб, Sector size: 512 bytes
Cylinders: 471, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x002CB2DF
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 3.6 GB (3879403520 bytes)
  Start Sector: 2048, Boot: Yes

**Comment by pbatard** [comment]
Have you tried `DD-mode` as suggested by Rufus?

![image2](https://user-images.githubusercontent.com/1206968/34230993-95404b44-e5da-11e7-8fa8-fbede7d20159.png)

Please don't ignore messages from Rufus that are there to help you.

If you see the same issue in `DD-mode`, you will need to contact the makers of the ISO.

**Comment by Alexander1414x** [comment]
Okay, I want to go test this.  Please Wait.

**Comment by pbatard** [comment]
I'm gonna close this issue now. However, you can still update it when you've had a chance to test.
