### ISSUE TITLE
Unable to use an "Extended Volume Tag"

### ISSUE THREAD

**Issue by stdedos** [pbatard/rufus#1074]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [x] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [x] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.
```
http://releases.ubuntu.com/16.04.3/SHA256SUMS
e28a99e1754a5b04741cd09ff557df2173a0177df79782aa0eb952d3d9803a2b
```

Issue description
-----------------
For the following image `ubuntu-16.04.3-desktop-i386.iso` I could not create an "extended" Volume Tag.
`Ubuntu 16.04.3 LTS i386` is not accepted (passing as `UBUNTU 16_0`), plain `Ubuntu` works (as `UBUNTU`).

"I don't care to fix this so as it is working in the end", but maybe there is a way that rufus can "understand" when that option is not "available" (for not-tech-savvy users)

I would like to run
```
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
```

but, I have now created my image, which I don't want to redo, unless 100% necessary (since creating "working" bootable USBs has always been a "real" challenge for me

Log
---

```
Rufus version: 2.18.1213 (Portable)
Windows version: Windows 10 64-bit (Build 16299)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0408
Will use default UI locale 0x0408
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'el-GR'
Found USB 2.0 device 'FLASH Drive AU_USB20 USB Device' (058F:6387)
1 device found
Disk type: Removable, Disk size: 16GB, Sector size: 512 bytes
Cylinders: 2028, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x000C99A0
Drive has an unknown Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 15.5 GB (16681795584 bytes)
  Start Sector: 2048, Boot: No
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.03/20151222 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Ubuntu 16.04.3 LTS i386'
  Size: 1.5 GB (Projected)
  Uses: Syslinux/Isolinux v6.03
  Note: This ISO uses symbolic links, which will not be replicated due to file system limitations.
  Because of this, some features from this image may not work...
Using image: ubuntu-16.04.3-desktop-i386.iso (1.5 GB)
Downloading 'ldlinux.sys' from http://rufus.akeo.ie/files/syslinux-6.03/20151222/ldlinux.sys
Unable to access file: 404
Extended version was not found, trying main version...
Downloading 'ldlinux.sys' from http://rufus.akeo.ie/files/syslinux-6.03/ldlinux.sys
File length: 68599 bytes
Successfully downloaded 'ldlinux.sys'
Downloading 'ldlinux.bss' from http://rufus.akeo.ie/files/syslinux-6.03/20151222/ldlinux.bss
Unable to access file: 404
Extended version was not found, trying main version...
Downloading 'ldlinux.bss' from http://rufus.akeo.ie/files/syslinux-6.03/ldlinux.bss
File length: 512 bytes
Successfully downloaded 'ldlinux.bss'

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE2 for exclusive write access
Requesting lock...
Will use 'F:' as volume mountpoint
I/O boundary checks disabled
Requesting lock...
Analyzing existing boot records...
Drive has an unknown Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (FAT32)...
Using cluster size: 8192 bytes
Quick format was selected
Creating file system...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Partition is already FAT32 LBA...
Set bootable USB partition as 0x80
Using Syslinux MBR
Found volume GUID \\?\Volume{fa9e59ec-e512-11e7-bfd6-94de80794835}\
Installing Syslinux 6.03...
Opened \\?\Volume{fa9e59ec-e512-11e7-bfd6-94de80794835} for shared write access
Using existing './rufus_files/syslinux-6.03/20151222/ldlinux.sys' ✓
Using existing './rufus_files/syslinux-6.03/20151222/ldlinux.bss' ✓
Successfully wrote 'ldlinux.sys'
Could not read sector 0: [0x00000001] Εσφαλμένη λειτουργία.
Syslinux FAT access error
\\?\Volume{fa9e59ec-e512-11e7-bfd6-94de80794835}\ was already mounted as F:\
Re-mounted volume as 'F:' after error

Found USB 2.0 device 'FLASH Drive AU_USB20 USB Device' (058F:6387)
1 device found
Disk type: Removable, Disk size: 16GB, Sector size: 512 bytes
Cylinders: 2028, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x01C226A5
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 15.5 GB (16681795584 bytes)
  Start Sector: 2048, Boot: Yes
Will reuse 'ldlinux.sys' and 'ldlinux.bss' from './rufus_files/rufus_files/syslinux-6.03/20151222/' for Syslinux installation

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE2 for exclusive write access
Requesting lock...
Will use 'F:' as volume mountpoint
I/O boundary checks disabled
Requesting lock...
Analyzing existing boot records...
Drive has a Syslinux Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (FAT32)...
Using cluster size: 8192 bytes
Quick format was selected
Creating file system...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Partition is already FAT32 LBA...
Set bootable USB partition as 0x80
Using Syslinux MBR
Found volume GUID \\?\Volume{fa9e59ec-e512-11e7-bfd6-94de80794835}\
Installing Syslinux 6.03...
Opened \\?\Volume{fa9e59ec-e512-11e7-bfd6-94de80794835} for shared write access
Using existing './rufus_files/syslinux-6.03/20151222/ldlinux.sys' ✓
Using existing './rufus_files/syslinux-6.03/20151222/ldlinux.bss' ✓
Successfully wrote 'ldlinux.sys'
Successfully wrote Syslinux boot record
Successfully remounted \\?\Volume{fa9e59ec-e512-11e7-bfd6-94de80794835}\ on F:
Copying ISO files...
Extracting files...
Image is an ISO9660 image
This image will be extracted using Rock Ridge extensions (if present)
Extracting: F:\.disk\base_installable (0 bytes)
Extracting: F:\.disk\casper-uuid-generic (37 bytes)
Extracting: F:\.disk\cd_type (15 bytes)
Extracting: F:\.disk\info (59 bytes)
Extracting: F:\.disk\release_notes_url (80 bytes)
Extracting: F:\README.diskdefines (229 bytes)
Extracting: F:\boot\grub\loopback.cfg (592 bytes)
Extracting: F:\casper\filesystem.manifest (65.5 KB)
Extracting: F:\casper\filesystem.manifest-remove (3.6 KB)
Extracting: F:\casper\filesystem.size (11 bytes)
Extracting: F:\casper\filesystem.squashfs (1.5 GB)
  Write error [0x000003EE] - retrying...
  Write error [0x000003EE] - retrying...
  Write error [0x000003EE]
  Error writing file: [0x000003EE] Ο τόμος ενός αρχείου έχει τροποποιηθεί εξωτερικά με τέτοιο τρόπο, ώστε το ανοιχτό αρχείο να μην είναι πλέον έγκυρο.
Extracting: F:\dists\stable (0 bytes)
  Ignoring Rock Ridge symbolic link to 'xenial'
Extracting: F:\dists\unstable (0 bytes)
  Ignoring Rock Ridge symbolic link to 'xenial'
Extracting: F:\dists\xenial\Release (1.7 KB)
Extracting: F:\dists\xenial\Release.gpg (819 bytes)
Extracting: F:\dists\xenial\main\binary-i386\Packages.gz (6.7 KB)
Extracting: F:\dists\xenial\main\binary-i386\Release (95 bytes)
Extracting: F:\dists\xenial\restricted\binary-i386\Packages.gz (2.6 KB)
Extracting: F:\dists\xenial\restricted\binary-i386\Release (101 bytes)
Extracting: F:\install\README.sbm (1.8 KB)
Extracting: F:\install\mt86plus (178.4 KB)
Extracting: F:\install\sbm.bin (1.4 MB)
Extracting: F:\isolinux\16x16.fnt (69.6 KB)
Extracting: F:\isolinux\access.pcx (3.3 KB)
Extracting: F:\isolinux\adtxt.cfg (0 bytes)
Extracting: F:\isolinux\am.tr (3.4 KB)
Extracting: F:\isolinux\ast.hlp (7.2 KB)
Extracting: F:\isolinux\ast.tr (2.3 KB)
Extracting: F:\isolinux\back.jpg (7.3 KB)
Extracting: F:\isolinux\be.hlp (11.4 KB)
Extracting: F:\isolinux\be.tr (3.9 KB)
Extracting: F:\isolinux\bg.hlp (11.4 KB)
Extracting: F:\isolinux\bg.tr (4.3 KB)
Extracting: F:\isolinux\blank.pcx (11.2 KB)
Extracting: F:\isolinux\bn.hlp (14.8 KB)
Extracting: F:\isolinux\boot.cat (2 KB)
Extracting: F:\isolinux\bootlogo (842.5 KB)
Extracting: F:\isolinux\bs.hlp (6.9 KB)
Extracting: F:\isolinux\bs.tr (2.3 KB)
Extracting: F:\isolinux\ca.hlp (7.9 KB)
Extracting: F:\isolinux\ca.tr (2.6 KB)
Extracting: F:\isolinux\chain.c32 (24.3 KB)
Extracting: F:\isolinux\cs.hlp (7.2 KB)
Extracting: F:\isolinux\cs.tr (2.4 KB)
Extracting: F:\isolinux\da.hlp (6.7 KB)
Extracting: F:\isolinux\da.tr (2.3 KB)
Extracting: F:\isolinux\de.hlp (7.6 KB)
Extracting: F:\isolinux\de.tr (2.5 KB)
Extracting: F:\isolinux\dtmenu.cfg (1.4 KB)
Extracting: F:\isolinux\el.hlp (13.1 KB)
Extracting: F:\isolinux\el.tr (4.6 KB)
Extracting: F:\isolinux\en.hlp (6.4 KB)
Extracting: F:\isolinux\en.tr (2 KB)
Extracting: F:\isolinux\eo.hlp (6.7 KB)
Extracting: F:\isolinux\eo.tr (2.2 KB)
Extracting: F:\isolinux\es.hlp (7.5 KB)
Extracting: F:\isolinux\es.tr (2.3 KB)
Extracting: F:\isolinux\et.hlp (6.6 KB)
Extracting: F:\isolinux\et.tr (2.2 KB)
Extracting: F:\isolinux\eu.hlp (7 KB)
Extracting: F:\isolinux\eu.tr (2.2 KB)
Extracting: F:\isolinux\exithelp.cfg (53 bytes)
Extracting: F:\isolinux\f1.txt (869 bytes)
Extracting: F:\isolinux\f10.txt (723 bytes)
Extracting: F:\isolinux\f2.txt (739 bytes)
Extracting: F:\isolinux\f3.txt (782 bytes)
Extracting: F:\isolinux\f4.txt (417 bytes)
Extracting: F:\isolinux\f5.txt (806 bytes)
Extracting: F:\isolinux\f6.txt (1.2 KB)
Extracting: F:\isolinux\f7.txt (916 bytes)
Extracting: F:\isolinux\f8.txt (1 KB)
Extracting: F:\isolinux\f9.txt (765 bytes)
Extracting: F:\isolinux\fa.tr (3.6 KB)
Extracting: F:\isolinux\fi.hlp (7.0 KB)
Extracting: F:\isolinux\fi.tr (2.3 KB)
Extracting: F:\isolinux\fr.hlp (7.8 KB)
Extracting: F:\isolinux\fr.tr (2.4 KB)
Extracting: F:\isolinux\ga.tr (2.5 KB)
Extracting: F:\isolinux\gfxboot.c32 (10.3 KB)
Extracting: F:\isolinux\gfxboot.cfg (369 bytes)
Extracting: F:\isolinux\gl.hlp (7.4 KB)
Extracting: F:\isolinux\gl.tr (2.3 KB)
Extracting: F:\isolinux\he.hlp (9.2 KB)
Extracting: F:\isolinux\he.tr (3.3 KB)
Extracting: F:\isolinux\hi.hlp (0 bytes)
Extracting: F:\isolinux\hr.tr (2.3 KB)
Extracting: F:\isolinux\hu.hlp (7.6 KB)
Extracting: F:\isolinux\hu.tr (2.7 KB)
Extracting: F:\isolinux\id.hlp (6.9 KB)
Extracting: F:\isolinux\id.tr (2 KB)
Extracting: F:\isolinux\is.hlp (7.3 KB)
Extracting: F:\isolinux\is.tr (2.4 KB)
Extracting: F:\isolinux\isolinux.bin (40 KB)
Extracting: F:\isolinux\isolinux.cfg (178 bytes)
Extracting: F:\isolinux\it.hlp (7.0 KB)
Extracting: F:\isolinux\it.tr (2.3 KB)
Extracting: F:\isolinux\ja.hlp (9.2 KB)
Extracting: F:\isolinux\ja.tr (3.4 KB)
Extracting: F:\isolinux\ka.hlp (12.1 KB)
Extracting: F:\isolinux\ka.tr (5.3 KB)
Extracting: F:\isolinux\kk.hlp (12.8 KB)
Extracting: F:\isolinux\kk.tr (4.1 KB)
Extracting: F:\isolinux\km.hlp (18.2 KB)
Extracting: F:\isolinux\kn.tr (6.4 KB)
Extracting: F:\isolinux\ko.hlp (8.1 KB)
Extracting: F:\isolinux\ko.tr (2.7 KB)
Extracting: F:\isolinux\ku.tr (2.4 KB)
Extracting: F:\isolinux\langlist (232 bytes)
Extracting: F:\isolinux\ldlinux.c32 (113.8 KB)
Extracting: F:\isolinux\libcom32.c32 (178.3 KB)
Extracting: F:\isolinux\libutil.c32 (23.1 KB)
Extracting: F:\isolinux\lo.tr (5.5 KB)
Extracting: F:\isolinux\lt.hlp (7.2 KB)
Extracting: F:\isolinux\lt.tr (2.4 KB)
Extracting: F:\isolinux\lv.hlp (7.7 KB)
Extracting: F:\isolinux\lv.tr (2.5 KB)
Extracting: F:\isolinux\menu.cfg (437 bytes)
Extracting: F:\isolinux\mk.tr (3.6 KB)
Extracting: F:\isolinux\mr.tr (6.1 KB)
Extracting: F:\isolinux\nb.hlp (6.8 KB)
Extracting: F:\isolinux\nb.tr (2.2 KB)
Extracting: F:\isolinux\nl.hlp (7.0 KB)
Extracting: F:\isolinux\nl.tr (2.5 KB)
Extracting: F:\isolinux\nn.hlp (7 KB)
Extracting: F:\isolinux\nn.tr (2.2 KB)
Extracting: F:\isolinux\pl.hlp (7.4 KB)
Extracting: F:\isolinux\pl.tr (2.5 KB)
Extracting: F:\isolinux\prompt.cfg (175 bytes)
Extracting: F:\isolinux\pt.hlp (7.4 KB)
Extracting: F:\isolinux\pt.tr (2.3 KB)
Extracting: F:\isolinux\pt_BR.hlp (7.3 KB)
Extracting: F:\isolinux\pt_BR.tr (2.5 KB)
Extracting: F:\isolinux\ro.hlp (8.4 KB)
Extracting: F:\isolinux\ro.tr (2.5 KB)
Extracting: F:\isolinux\rqtxt.cfg (135 bytes)
Extracting: F:\isolinux\ru.hlp (11.8 KB)
Extracting: F:\isolinux\ru.tr (4.0 KB)
Extracting: F:\isolinux\si.hlp (13.7 KB)
Extracting: F:\isolinux\si.tr (6.2 KB)
Extracting: F:\isolinux\sk.hlp (7.4 KB)
Extracting: F:\isolinux\sk.tr (2.6 KB)
Extracting: F:\isolinux\sl.hlp (6.8 KB)
Extracting: F:\isolinux\sl.tr (2.3 KB)
Extracting: F:\isolinux\splash.pcx (13.8 KB)
Extracting: F:\isolinux\splash.png (16.9 KB)
Extracting: F:\isolinux\sq.hlp (7.8 KB)
Extracting: F:\isolinux\sq.tr (2.3 KB)
Extracting: F:\isolinux\sr.hlp (11.4 KB)
Extracting: F:\isolinux\sr.tr (4.3 KB)
Extracting: F:\isolinux\stdmenu.cfg (508 bytes)
Extracting: F:\isolinux\sv.hlp (7.1 KB)
Extracting: F:\isolinux\sv.tr (2.3 KB)
Extracting: F:\isolinux\te.tr (6.4 KB)
Extracting: F:\isolinux\th.hlp (12.8 KB)
Extracting: F:\isolinux\tl.tr (2.1 KB)
Extracting: F:\isolinux\tr.hlp (7.6 KB)
Extracting: F:\isolinux\tr.tr (2.4 KB)
Extracting: F:\isolinux\txt.cfg (659 bytes)
Extracting: F:\isolinux\ug.hlp (11.6 KB)
Extracting: F:\isolinux\uk.hlp (11.5 KB)
Extracting: F:\isolinux\uk.tr (4.1 KB)
Extracting: F:\isolinux\vesamenu.c32 (26.1 KB)
Extracting: F:\isolinux\vi.hlp (9.5 KB)
Extracting: F:\isolinux\vi.tr (3.0 KB)
Extracting: F:\isolinux\zh_CN.hlp (6.1 KB)
Extracting: F:\isolinux\zh_CN.tr (2.1 KB)
Extracting: F:\isolinux\zh_TW.hlp (6.1 KB)
Extracting: F:\isolinux\zh_TW.tr (2.3 KB)
Extracting: F:\md5sum.txt (3.8 KB)
Extracting: F:\pics\blue-lowerleft.png (294 bytes)
Extracting: F:\pics\blue-lowerright.png (266 bytes)
Extracting: F:\pics\blue-upperleft.png (280 bytes)
Extracting: F:\pics\blue-upperright.png (290 bytes)
Extracting: F:\pics\debian.jpg (8.2 KB)
Extracting: F:\pics\logo-50.jpg (3.9 KB)
Extracting: F:\pics\red-lowerleft.png (353 bytes)
Extracting: F:\pics\red-lowerright.png (299 bytes)
Extracting: F:\pics\red-upperleft.png (321 bytes)
Extracting: F:\pics\red-upperright.png (344 bytes)
Extracting: F:\pool\main\b\b43-fwcutter\b43-fwcutter_019-2_i386.deb (22.5 KB)
Extracting: F:\pool\main\d\dkms\dkms_2.2.0.3-2ubuntu11.3_all.deb (64.6 KB)
Extracting: F:\pool\main\g\grub\grub_0.97-29ubuntu68_i386.deb (192.4 KB)
Extracting: F:\pool\main\l\lupin\lupin-support_0.57_i386.deb (13.6 KB)
Extracting: F:\pool\main\m\mouseemu\mouseemu_0.16-0ubuntu9_i386.deb (17.1 KB)
Extracting: F:\pool\main\s\setserial\setserial_2.17-49_i386.deb (35.9 KB)
Extracting: F:\pool\main\u\ubiquity\oem-config-gtk_2.21.63.4_all.deb (4.1 KB)
Extracting: F:\pool\main\u\ubiquity\oem-config_2.21.63.4_all.deb (13.8 KB)
Extracting: F:\pool\main\u\ubiquity-slideshow-ubuntu\oem-config-slideshow-ubuntu_113_all.deb (827.2 KB)
Extracting: F:\pool\main\u\user-setup\user-setup_1.63ubuntu4_all.deb (187.5 KB)
Extracting: F:\pool\main\w\wvdial\wvdial_1.61-4.1_i386.deb (74.8 KB)
Extracting: F:\pool\main\w\wvstreams\libuniconf4.6_4.6.1-7_i386.deb (129.7 KB)
Extracting: F:\pool\main\w\wvstreams\libwvstreams4.6-base_4.6.1-7_i386.deb (199.1 KB)
Extracting: F:\pool\main\w\wvstreams\libwvstreams4.6-extras_4.6.1-7_i386.deb (437 KB)
Extracting: F:\pool\restricted\b\bcmwl\bcmwl-kernel-source_6.30.223.271+bdcom-0ubuntu1~1.1_i386.deb (1.4 MB)
Extracting: F:\pool\restricted\i\intel-microcode\intel-microcode_3.20151106.1_i386.deb (591.0 KB)
Extracting: F:\pool\restricted\i\iucode-tool\iucode-tool_1.5.1-1ubuntu0.1_i386.deb (32.7 KB)
Extracting: F:\pool\restricted\s\sl-modem\sl-modem-daemon_2.9.11~20110321-12_i386.deb (421.6 KB)
Extracting: F:\preseed\cli.seed (266 bytes)
Extracting: F:\preseed\ltsp.seed (551 bytes)
Extracting: F:\preseed\ubuntu.seed (514 bytes)
Extracting: F:\ubuntu (0 bytes)
  Ignoring Rock Ridge symbolic link to '.'
Created: F:\syslinux.cfg
Finalizing, please wait...
Created: F:autorun.inf
Created: F:autorun.ico

Found USB 2.0 device 'FLASH Drive AU_USB20 USB Device' (058F:6387)
Using autorun.inf label for drive F: 'Ubuntu'
1 device found
Disk type: Removable, Disk size: 16GB, Sector size: 512 bytes
Cylinders: 2028, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x01C3C726
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 15.5 GB (16681795584 bytes)
  Start Sector: 2048, Boot: Yes
```

**Comment by pbatard** [comment]
> I could not create an "extended" Volume Tag

That's because the USB will use a FAT32 file system (as opposed to an ISO9660 file system), which severely limits how a drive can be labelled. As opposed to ISO9660, a FAT label can only be 11 characters long and uppercase. That's a limitation of the file system, and there is nothing Rufus can do about that.

> but maybe there is a way that rufus can "understand" when that option is not "available" (for not-tech-savvy users)

From my experience, non tech-savvy users are very confused by limitations that only occur in one file system (as far as they are concerned, all file systems "can" do the same thing, and I already have all the trouble in the world making them understand that conversion from bootable ISO to bootable USB is __way__ more tricky than they imagine), so, unless these limitations have a direct effect on their ability to boot the device (which is why Rufus has to present users with terms like BIOS, UEFI and CSM, which already cause a lot of gried to non tech-savy users), Rufus will do its best __not__ to involve the user with what is going on behind the scenes.

Furthermore, even as the file system itself has label limitations, in Windows, there is a mechanism (extended labels in `autorun.inf`) to make it __look__ like longer, mixed case labels are possible. So Rufus tries to use that by default, to keep users mostly oblivious to something they should not concern themselves with. But of course, the "extended" label thing only works when using Windows.

Oh, and before you mention that some distros do use the volume label to locate the installation drive, bear in mind that, as a result of the FAT label limitation, Rufus does look for config files that reference a volume label, and edit them behind the scenes so that they reference the FAT label. Again, this is a process that is designed to be transparent to the user, as we really want to hide the complexity that goes into the ISO &rarr; USB conversion process so as not to confuse regular users. From what I can see from the log above (and from what I remember), this volume label conversion is not needed for Ubuntu.

So, in summary:
1. You will never be able to use an extended volume label on FAT32. If you want to, then you will need to complain to Microsoft themselves so that they create a new version of the FAT file system and wait until everyone adopts that new version, as this is a pure file system limitation.
2. If you are accessing your drive from Windows, the `autorun.inf` trick used by Rufus should make it look __as if__ you can actually use extended labels. Won't work in Linux though.
3. If you really, really want your extended label, you can __try__ using NTFS instead of FAT32 for your file system. NTFS does have some label limitations, but they are not as drastic as the FAT32 ones, and, from what I could see (when testing Debian and Arch), modern Linux distros __may__ also support booting from NTFS. Note however that the use of NTFS is completely unsupported as far as I'm concerned, so if that doesn't work, you're 100% on your own.

As I believe I answered your question, I will close this issue.

PS: When you see multiple instances of write errors in your log, as you do, you __REALLY__ want to run a bad blocks check against your drive (which can be done without using an ISO), as it really looks to me like your drive is becoming defective and is bound to cause you trouble.

**Comment by stdedos** [comment]
@pbatard The reason I created this ticket, was to introduce a warning to the logging and a behind-the-scenes renaming of the flashdrive label (and not to talk FAT semantic/fuck-ups) :smile: 
Or wasn't this the reason that the process failed in the first place? :confused: 
<br>
Yeah, I get it (multiple times actually) that bootable ISO to bootable USB **is** way more tricky than I imagine (as I have exactly 0 ideas how it is done) as already I mentioned
> (since creating "working" bootable USBs has always been a "real" challenge for me)

<br>

PS: So, unchecking everything _but_ the bad blocks check, I could even do it now? :confused: Or you mean go manually with the Microsoft utility?

**Comment by pbatard** [comment]
> was to introduce a warning to the logging

The Log is only meant to provide data that will help the developer (me) troubleshoot issues. It's not actually designed to provide data that users may want to see there, but that isn't useful for problem resolution. For the record, when a config file that contains a volume label is modified, there will be an explicit line in the log (which you don't see with Ubuntu as no such conversion is needed).

> Or wasn't this the reason that the process failed in the first place?

Where does your process fail? You specifically mentioned that the label thing was not creating an actual problem (_"I don't care to fix this so as it is working in the end"_). So I'm not sure I understand what you are saying now...

> So, unchecking everything but the bad blocks check, I could even do it now?

Yup. Of course, you will lose the data from your drive, but you don't need to provide an ISO or anything to just run a bad blocks check.

**Comment by stdedos** [comment]
I think that
> Error writing file: [0x000003EE] Ο τόμος ενός αρχείου έχει τροποποιηθεί εξωτερικά με τέτοιο τρόπο, ώστε το ανοιχτό αρχείο να μην είναι πλέον έγκυρο.
this is where the process crashed. However, I didn't memorize exactly the message (since it crashed early).

While noticing the crashing, I saw that the label was changed and the message was saying something along the lines that "_Something_ cannot be found anymore". So then I made the connection that formatting & relabeling the drive (with a "different" volume tag) caused the issue.

My thought process went that:

1. Drive is formatted with the new label
1. In the process, it is "unmounted" for user applications
1. Drive finishes format, becomes available
1. Rufus tries a `strcmp` to verify that the drive it "commissioned" for format, is the one becomming available. After that Rufus, starts writing the files
1. `strcmp` fails, rufus crashed with the message

**Comment by pbatard** [comment]
4 & 5 are wrong. Looking for labels to recognize a drive would be a very flimsy mechanism. Instead we use GUIDs, that are guaranteed by Windows not to change between re-mounts.
I would advise against "guessing" what Rufus might be doing &mdash; again, it's not as straightforward (and prone to failure) as people imagine...

And the write error is just that, a __write__ error, which means that somewhere between the moment Windows asked the data to be written and the flash memory bloc where bits should have been flipped, an error occurred, which, considering you seem to experiencing further write errors down the line, looks like a pure hardware issue.

**Comment by stdedos** [comment]
> 4 & 5 are wrong. Looking for labels to recognize a drive would be a very flimsy mechanism.

I know, but my 0 knowledge and assuming-the-worst attitude lead me to wrong assumptions. Apologies for that :confused: 

Well, let's say that if I ever encounter something related, I will come back here :smile: 
Thank you for your patience and thorough explainations
