### ISSUE TITLE
Feature Request: Dialog notifying user of completed imaging operation.

### ISSUE THREAD

**Issue by jtrosper** [pbatard/rufus#1081]
Hello,

Current behavior of Rufus is that, when an imaging operation is completed, the progress bar is a solid green, and the status changes to "READY."

I would like to request that a dialog be added which appears when an imaging operation is completed, informing the user of the completed operation, which the user can then acknowledge.

Thank you!

**Comment by pbatard** [comment]
I already added a sound and toolbar flashing. There's only so far I'm willing to go with this. Rejected.
