### ISSUE TITLE
Hello Author and Authors of Rufus Program

### ISSUE THREAD

**Issue by glerinsonum** [pbatard/rufus#1082]
Can you make RUFUS with more options, that I to write ISO Image for All Bios into Local Hard Disk. Local Disk.

**Comment by pbatard** [comment]
See the list of [cheat modes](https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes) from the FAQ. That's about as far as we will go to add features. Writing to local (non USB) HDD will never be officially supported because there's too much risk of people losing data as a result.
