### ISSUE TITLE
hello, in USB 64Gb I try from Windows 8.1 64bit to create in persistent mode linux "maui-17.06-64bit" ...  but after 5-6 min "apt get upgrade" writes "no spaces left" ...  what  can I do to wan space?

### ISSUE THREAD

**Issue by spi6** [pbatard/rufus#1085]
hello, in USB 64Gb I try from Windows 8.1 64bit to create in persistent mode linux "maui-17.06-64bit" ...

but after 5-6 min "apt get upgrade" writes "no spaces left" ...

what  can I do to wan space?

**Comment by pbatard** [comment]
Sorry but you didn't follow the check list and this is clearly not a Rufus problem.

Try to ask for help in the Linux maui forums, as `apt-get` is a __pure__ Linux command that has nothing to do with Rufus.
