### ISSUE TITLE
Partition problem

### ISSUE THREAD

**Issue by soulessence** [pbatard/rufus#1090]
When i worked the usb on my computer, i have realized thet there were 4 parts of usb at 'This Computer' window. but when i opened the 'rufus' program, i saw just one part as the 4 part of usb (like E,F,G,H).May you fix that problem and set each part seperately?.

**Comment by pbatard** [comment]
Next time, follow the checklist. Your question [is answered in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiple_partition_support).
