### ISSUE TITLE
Why can not have this tool support SSD hard drives

### ISSUE THREAD

**Issue by nick-china** [pbatard/rufus#1094]
Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Why can not have this tool support SSD hard drives？I wish this tool can support SSD,because many peoples of china needs to use rufus to image a company system to a SSD,but not for a USB drive.The capacity of the company system ISO  is greater than 50GB,so sometimes we wish rufus can be support the SSD.
thanks!

Log
Found UAS (USB 3.0) device 'INTEL SS DSC2BB080G4 SCSI Disk Device' (2109:0715)
Device eliminated because it was detected as a Hard Drive (score 13 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives in 'Advanced Options' (after clicking the white triangle)
0 devices found

<FULL LOG>
```

**Comment by pbatard** [comment]
You didn't look at the FAQ, which tells you exactly what you should do to get an USB HDD (Your ` UAS (USB 3.0) device 'INTEL SS DSC2BB080G4 SCSI Disk Device'` is an USB HDD):
https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected

Next time, please try to follow the check list. USB hard drives, like USB SSDs are supported by Rufus. They just aren't enabled by default to avoid people formatting a backup drive by mistake.
