### ISSUE TITLE
Make USB bootable and copy image to specific partition (and leave the other partition alone)

### ISSUE THREAD

**Issue by basprins** [pbatard/rufus#1102]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Is it possible to use Rufus to copy an iso file to a specific partition on the USB drive? I read that Rufus will not support to install OSes on side-by-side partitions. Does that mean that it's also not possible to copy an iso to a specific partition? 

In my case, I want to copy the contents of an iso file to [USB] D:\ (which is used as Acronis tool). But, I also have the [USB] E:\ (NTFS) partition which I want to leave in tact. 

When I simply press the buttons now to choose the image I get the message that my complete USB will be wiped. At the end of the line my NTFS partition is wiped. (and thus I have to go through the trouble to resize the new partition and recreate my E: partition).

If it can't be done with Rufus that's fine, then I'll just have to figure out something else. 

Hope you can shed a light on this. thanks a bunch! 

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
[Answered in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiple_partition_support) as well as [here](https://github.com/pbatard/rufus/wiki/FAQ#Why_does_Rufus_need_to_delete_all_partitionsvolumes_when_creating_a_drive).
