### ISSUE TITLE
"UNDERTERMINED ERROR WHILE FORMATTING" error occurs when i am going to make a bootable usb. 

### ISSUE THREAD

**Issue by sjtomo07** [pbatard/rufus#1106]
Rufus version: 2.15.1117
Windows version: Windows 8.1 64-bit (Build 9600)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0409
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'USB Disk USB Device' (1221:3234)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 2039, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 15.6 GB (16776167424 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'WinALL_u_ISO_by_adguard'
  Size: 10.6 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr
Using image: Windows All In One 70in1 with update x86-x64_v15.12.19.iso

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE1 for exclusive write access
Requesting lock...
Will use 'F:' as volume mountpoint
I/O boundary checks disabled
Requesting lock...
Analyzing existing boot records...
Drive has a Windows 7 Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
Format error: Undetermined error while formatting.
Re-mounted volume as 'F:' after error

Found USB 2.0 device 'USB Disk USB Device' (1221:3234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 2039, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x057D756C
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 15.6 GB (16776167424 bytes)
  Start Sector: 2048, Boot: Yes

**Comment by pbatard** [comment]
As __clearly__ mentioned when opening an issue, if you don't follow the check list, your issue will be closed.

Especially, you [didn't look at the relevant entry from the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Format_error_Undetermined_error_while_formatting).
