### ISSUE TITLE
Wishlist dual Windows iso, add partition to GPT

### ISSUE THREAD

**Issue by necrose99** [pbatard/rufus#1112]
Dump 2 Windows iso's add boot menu for them. 

http://windowsmatters.com/2016/11/10/gandalfs-win10pe-x64-redstone-build-14393-version-10-24-2016/ 

add Windows 10 install ISO to same key , extract to different NTFS partitions. 
Add menu...  , add fat32 partion to key unpack Linux UEFI... , add menu... 

if windows 10 , takes a dirt nap or becomes infected Gandal 10 pe is quite handy to fix , however if you cann't fix , can scrape off the wreckage to the local nas drive/s and re-install ...  , restore files 

I have like 40 usb keys , trying to trim down number I cary  would be a plus.. 

github.com/mbusb/multibootusb  fail , dumps both to root , then nicely adds Linux ETC to other folders , ie iso etc.. works that way but not ..... with the PE with tools on roids , and Windows 10... 
which is a plus as you can append to a rufus built key.. but unfortunately overights pe with 10 install.

**Comment by pbatard** [comment]
Next time follow the check list. Your questions are answered in the FAQ.
