### ISSUE TITLE
Please update the first figure on this webpage

### ISSUE THREAD

**Issue by Kractal** [pbatard/rufus#1114]
Please update the first figure on this webpage:https://rufus.akeo.ie/?locale=zh_CN.
I download rufus-2.18.exe,which SHA256 value is  E82ABD7F2C8F8C866141634A1CE10DA8EBF3C58B68CB2EAA351345777BB3F67C, and run it on Windows 1709 16299.402.
The original figure is:
![default](https://user-images.githubusercontent.com/22289452/39171700-2c0f1b6e-47d2-11e8-805c-d442fe59dfc9.png),
Please update it to:
![e_ cg cwo o9q ip48 n](https://user-images.githubusercontent.com/22289452/39171756-4cdd014e-47d2-11e8-94eb-fcc1629f0025.png)

**Comment by pbatard** [comment]
Done. I'm probably going to update all the pictures once Rufus 3.0 is out anyway, as the interface will be completely different.

**Comment by Kractal** [comment]
Fine. I could provied the screenshot of the zh_CN version, please send me an email if you need my help.
