### ISSUE TITLE
(Help) /HBCD/menu.c32: not a com32r image

### ISSUE THREAD

**Issue by nothingvn** [pbatard/rufus#1115]
I make a usb bootable by rufu sorfware, the usb boot making process is ok but when i boot my laptop with that usb, it show message "/HBCD/menu.c32: not a com32r image". I googled but no answer is  helpfull. Pls help me.
Thank a lot!

**Comment by pbatard** [comment]
Didn't follow the check list &rarr; Closed.

**Comment by fanfan54** [comment]
@nothingvn I think the issue comes from this file in the ISO image you downloaded, not from Rufus.
