### ISSUE TITLE
README logo

### ISSUE THREAD

**Issue by eladkarako** [pbatard/rufus#1119]
from `https://raw.githubusercontent.com/pbatard/rufus/master/res/icon-set/rufus-128.png`
to `https://raw.githubusercontent.com/pbatard/rufus/master/res/icons/rufus-128.png`.

<sub><em>(although it's even better to just use path relative to README `res/icons/rufus-128.png`)</em></sub>

**Comment by pbatard** [comment]
I know.

I have already corrected it locally, but I don't want to push a commit just for that super minor issue.
I'll group this with whatever next commit I push.
