### ISSUE TITLE
Rufus cannot write to disk (ver 2.10 and 2.12 on Windows 7 Ultimate)

### ISSUE THREAD

**Issue by Phoenixinrage** [pbatard/rufus#1124]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive
  - [x] Plugging the USB into a different port
  - [x] Running Rufus on a different computer
- [x] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Hello I cannnot make a bootable flash.
I tried with versions 2.10 and 2.12. I get the error message indicating that the drive is being used by another process. 2.12 pointed that the process is windows\explorer.exe (r). While testing with 2.10 I used process hacker and got that my antivir (NOD32) was using the drive and smss service was using the drive.

PS After running the full check (1 pass) on 2.12 my Windows no longer wants to detect the flash as a drive. qq

PS2 The stick works on another system but on this one it is unusable.

PS3 Fixed the stick still cannot use rufus :(

Log
---
```
Rufus version: 2.18.1213 (Portable)
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0409
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'hp v165w USB Device' (03F0:5307)
1 device found
Disk type: Removable, Disk size: 8GB, Sector size: 512 bytes
Cylinders: 974, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x000188DD
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 7.5 GB (8018460672 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'Win7.X86.OEM.en-US.Nov2014'
  Size: 3.7 GB (Projected)
  Uses: Bootmgr
  Uses: Install.wim (version 0.13.1)
Using image: Win7.X86.OEM.en-US.Nov2014.iso (3.7 GB)

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE3 for exclusive write access
Requesting lock...
Will use 'J:' as volume mountpoint
I/O boundary checks disabled
Requesting lock...
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Bad Blocks: Checking from block 0 to 15663103
Bad Blocks: Using offset 363 for fake device check
Bad Blocks: Writing test pattern 0xAA
Bad Blocks: Reading and comparing
Bad Blocks: Check completed, 0 bad blocks found. (0/0/0 errors)
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Set bootable USB partition as 0x80
Using Rufus MBR
Found volume GUID \\?\Volume{153d3a4c-5ccd-11e6-b13d-da9f5fcd0ef4}\
J:\ already mounted, but volume GUID doesn't match:
  expected \\?\Volume{153d3a4c-5ccd-11e6-b13d-da9f5fcd0ef4}\, got \\?\Volume{69c008ef-66d9-11e6-bb7b-d8cb8a5d6527}\
Could not remount \\?\Volume{153d3a4c-5ccd-11e6-b13d-da9f5fcd0ef4}\ on J:\: [0x000000EA] More data is available.
J:\ already mounted, but volume GUID doesn't match:
  expected \\?\Volume{153d3a4c-5ccd-11e6-b13d-da9f5fcd0ef4}\, got \\?\Volume{69c008ef-66d9-11e6-bb7b-d8cb8a5d6527}\

Found USB 2.0 device 'hp v165w USB Device' (03F0:5307)
Found USB 3.0 device 'SanDisk Ultra Fit USB Device' (0781:5583)
2 devices found
Disk type: Removable, Disk size: 8GB, Sector size: 512 bytes
Cylinders: 974, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00173208
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 7.5 GB (8018460672 bytes)
  Start Sector: 2048, Boot: Yes

```

**Comment by pbatard** [comment]
Well, if Rufus is telling you that File Explorer is accessing the drive, and Process Hacker is also telling you that your antivirus may be keeping a lock to the drive, there's really not much Rufus can do. You will need to ensure that none of these applications are accessing the drive, as Rufus will not attempt to close them for you.

One thing you may want to make sure is that you don't have File Explorer opened to the drive you are trying to format.

You may also have a look at [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Error_0x00000005_Access_is_denied) and see if <kbd>Alt</kbd>-<kbd>,</kbd> helps, but if that doesn't work, it's really up to you to ensure that the applications that are running on your system aren't trying to access the drive you want to format.

You may also want to make sure you only have one drive plugged in. The log indicates that you have both and HP and SanDisk drive plugged in. Please only plug the drive you actually want to format.

**Comment by Phoenixinrage** [comment]
Hello,

Thanks for the reply.
I tried everything including closing all explorer windows and disabling all features of my anti-vir.
Tried also running rufus as an admin application.
Nothing gave results.

I am suspecting that it might be a Microsoft Update (maybe linked with Spectre/Meltdown).

Cheers :)

**Comment by pbatard** [comment]
> I am suspecting that it might be a Microsoft Update

That's doubtful. Rufus is downloaded more than 3 million times each month, so, if that was the case, there would be a lot more reports for this issue.

I'm afraid that the most logical conclusion is that it's something that is very specific to your environment... which you may have to figure out on your own.

**Comment by pbatard** [comment]
Have you tried <kbd>Alt</kbd>-<kbd>,</kbd>? This cheat mode tells Rufus to be less demanding about getting exclusive access before attempting to format the drive. Without having access to your system, it's the only thing I can think of that my help.

Otherwise, you may want to run [Process Hacker](https://sourceforge.net/projects/processhacker/) and start terminating processes that look like good candidates for interfering with Rufus (though terminating Windows processes at random is something you may want to be careful about).

**Comment by pbatard** [comment]
Since I don't think there's more I can do on this end, I'm going to close this issue.
