### ISSUE TITLE
How nice if Rufus have option to use the source in form as a "folder" 

### ISSUE THREAD

**Issue by BudiKusasi** [pbatard/rufus#1126]
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [ ] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
May I request a feature?
Can Rufus have option to use the source in form of being a "folder" in addition to being a "file" of ISO type ?
Thanks so much in advance.

**Comment by pbatard** [comment]
This has been requested before, but I just don't think it's enough of a showstopper to be added when there are more useful features to add (and my time is far from being unlimited!). This would require a __major__ rework of the way Rufus handles content, and I can't see myself spending the required time doing that, when you can just use any CD burning application out there and create an ISO image from your folder.

Also, please see [here](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want).

&rarr; Rejected.
