### ISSUE TITLE
Rufus Website is Down

### ISSUE THREAD

**Issue by ryannhg** [pbatard/rufus#1137]
Hey Pete!

I know this repo isn't for the website, but I thought this would be a decent way to reach out and let you know that https://rufus.akeo.ie/ isn't available at the moment.

I was about to download your tool, but couldn't download get to the `.exe` link.

On an unrelated note, __awesome__ work on Rufus! I love how simple and fast it is.

Have a great day,
Ryan

**Comment by pbatard** [comment]
This is due to planned network maintenance at the data center, so, yeah, the server is unreachable right now.

Should be back up in a few hours...

**Comment by pbatard** [comment]
Looks like it's back up right now. It's possible there will be other network outages, but I'm going to close this issue for now.
