### ISSUE TITLE
Windows Defender reports that Rufus 3.1 contains Trojan:Plutruption! or Trojan.Vigorf!

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#1169]
At least for `Plutruption`, this seems to occur with definitions `1.269.1834.0`.
Some users also report that they get `Vigorf` with `1.269.1846.0`.

Unfortunately, this is [not the first time](https://www.windows10forums.com/threads/windows-defender-seriously.17115/) we've been having a false positive from Windows Defender (which also reported `Plutruption` for Rufus 3.0, but that was cleared as a __false positive__ in later definitions), and we have of course reported the issue ([Submission ID: `b617cf91-4d99-409d-b5b4-4ebcba610237`](https://www.microsoft.com/en-us/wdsi/submission/b617cf91-4d99-409d-b5b4-4ebcba610237))

However, if you have the feeling that Microsoft are not doing enough to avoid these false positives, or not acting quickly enough, __you__ may also try to submit a false positive report at https://www.microsoft.com/en-us/wdsi/filesubmission, to bring it to their attention, using the "old" false positive executable from https://rufus.ie/testing/rufus-3.1_fp.exe (SHA-256 `a81cba62d55ee42f41303c138a439d5dc420753a8af12cb4753cf3df67dcd067`).

**Comment by pbatard** [comment]
Yeah, unfortunately it appears that someone, who wants to discredit our work, is "gaming" the Cloud reporting of Windows Defender, which in turns results in false positives in the definitions that Microsoft sends to Windows users.

For the time being, you can download the __updated__ 3.1 executable from the website, which is the same as the last one, but with newer timestamps (since Defender is obviously not looking at the actual behaviour of the executable to determine if it contains a trojan, but just trying to match the executable hash), and that shouldn't trigger Defender.

For the record, we have pre-emptively submitted that "new" executable to the defender team ([Submission ID: fc731445-c957-4bb3-b5cb-e388723116e6](https://www.microsoft.com/en-us/wdsi/submission/fc731445-c957-4bb3-b5cb-e388723116e6)) so that they aren't going to fall into the same trap...

**Comment by plambrechtsen** [comment]
I had the same problem this morning and have also submitted it as a false positive.
https://www.microsoft.com/en-us/wdsi/submission/8583c667-5616-4b98-883f-18c4b461ae4e
Local version: 1.269.1861.0
Submitting it is still detected as malware:
Protection	Current detection			Definition version
Cloud		Trojan:Win32/Plutruption!ARXep	Online
Client		Trojan:Win32/Plutruption!ARXep	1.269.1901.0

**Comment by pbatard** [comment]
Latest report for the original `.exe` (i.e. the one that was flagged as "malware"):

![image1](https://user-images.githubusercontent.com/1206968/41840944-f02a768a-785e-11e8-87f1-cfe4579dd97e.png)

As expected, their __Final determination__ is of course that there is nothing malicious about the software, though they have yet to provide Analyst comments and update their definitions to clear out the __false positive__.

**Comment by FaffeF** [comment]
FWIW, I got this alert in Windows Defender ATP, and the automated investigation service cleared it as benign inside an hour.

**Comment by pbatard** [comment]
Since it's been a week, and Microsoft cleared the false positive, I'm going to close the issue. Note that the "old" executable has been reinstated as the default download on the website.
