### ISSUE TITLE
Installing i386-pc using grub-install.exe from grub-2.02~rc2-for-windows 

### ISSUE THREAD

**Issue by BoQsc** [pbatard/rufus#1181]
This issue is not with supergrub nor Rufus, actually supergrub works perfectly using Rufus, but it feels bloated. 

So I have tried to install grub2 myself using **grub-install.exe** from _**_grub-2.02~rc2-for-windows.zip_**_  ([ftp://alpha.gnu.org/gnu/grub/](url))

And got stuck with these warnings: 

```
C:\Users\vaida\OneDrive\Stalinis kompiuteris\grub-2.02-for-windows>grub-install.exe  --boot-directory="F:\." --target="i
386-pc" "\\?\F:" --force
Installing for i386-pc platform.
grub-install.exe: warning: File system `fat' doesn't support embedding.
grub-install.exe: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  Ho
wever, blocklists are UNRELIABLE and their use is discouraged..

```

I wanted to ask how I could overcome these warnings as it seems that Rufus perfectly works with supergrub, but original grub-install.exe seems to give these warnings.

**Comment by pbatard** [comment]
Please ask this question on the GRUB user mailing list. This issue tracker is for Rufus only.
