### ISSUE TITLE
Please add verify the file checksum

### ISSUE THREAD

**Issue by theoryfate** [pbatard/rufus#1189]
Thank you very much for making such a good tool!

Please add SHA-256 verify the file checksum In the download page. 

because your website is using HTTP, it's easy to be MITM, to replace executable files. it's very dangerous, especially in an unsafe network environment, or in a hostile ISP.

**Comment by pbatard** [comment]
1. You can access the site either through HTTP or HTTPS.
2. The executable is digitally signed, with a SHA-256 certificate, which makes providing the SHA-256 on the web page completely redundant, as it will get __automatically__ validated by Windows during the digital signature validation process. The whole point of a digital signature is to ensure that, even if you download files through malicious network, you will get immediately notified if a file has been tampered with.

Closed as unneeded.
