### ISSUE TITLE
Feature Request Multiboot

### ISSUE THREAD

**Issue by AkitoTheGambler** [pbatard/rufus#1190]
Create Multiboot USB and add UEFI:NTFS with SecureBoot compatibility.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiboot_support

and

https://github.com/pbatard/uefi-ntfs

Next time please do your research, as you will find that both the features you requests have been answered time and time again.
