### ISSUE TITLE
Blacklist certain drives/usb sticks

### ISSUE THREAD

**Issue by cruzer619** [pbatard/rufus#1210]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
No real issue but more of an enhancement request.  My problem is that i'm on a tablet that I use a microsd card for extra HD space.   When I would make usb boot disks, I would accidentally overwrite my microsd card as it comes up first all the time.  Yah I know, thats a user issue, I should know better.  But would make my life easier :) if you can blacklist certain cards/usb sticks.  thats my request.

Thanks for reading my request.

Rich

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Sorry but no. If you spend enough time looking into it, you will see that this is not a receivable requests for too many reasons (will inconvenience more people than it will help __you__, Windows does not provide a way to know if a device is SD or something else, how the heck do you "guess" what the user really wants and report it to them in a manner that's not going to create zillions of user requests for "why is Rufus asking me such and such?", and so on).

Categorically rejected.

**Comment by cruzer619** [comment]
ok makes sense...  I know I was dreaming.. keep up the great work and product.

Thanks Again,

Rich
