### ISSUE TITLE
The checkbox for quick format is present in tab order during bootable pendrive creation.

### ISSUE THREAD

**Issue by lukaszgo1** [pbatard/rufus#1211]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Issue description
To reproduce
1. Launch Rufus 3.3
2. Click Show advanced format options.
3. Select an image and start creating a bootable pendrive.
4. move with a tab key during a creation process.
## expected behavior.
The quick format checkbox should be disabled.
## Actual behavior.
The Quick format checkbox is present in the tab order and it can be checked or unchecked, but without any noticeable effect.

**Comment by pbatard** [comment]
Thanks for the report. I have confirmed this small UI bug and will try to get it fixed in next version.
