### ISSUE TITLE
TF card reader not being displayed by default

### ISSUE THREAD

**Issue by jjboy32** [pbatard/rufus#1221]
In addition, there is a TF reader [Chuanyu USB3.0 TF reader], which is read normally under win10 x64 1803. But Rufus can't read the device. The information is as follows:
```
Rufus version: 3.1.1320
Windows version: Windows 10 64-bit (Build 17134)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0804
Will use default UI locale 0x0804
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'zh-CN'
Found USB 3.0 device 'SD Card Reader USB Device' (067B:2731)
Device eliminated because it was detected as a Hard Drive (score 7 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
0 devices found
```

**Comment by jjboy32** [comment]
Rufus version: 3.3.1400 (Portable)
Windows version: Windows 10 64-bit (Build 17134)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0804
Will use default UI locale 0x0804
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'zh-CN'
Found USB 3.0 device 'SD Card Reader USB Device' (067B:2731)
Device eliminated because it was detected as a Hard Drive (score 7 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
0 devices found

**Comment by pbatard** [comment]
I'll try to add an exception for the `067B:2731` card reader device in the next version of Rufus.

As indicated in the log, you can easily get it listed if you enable HDD listing in 'advanced drive properties'.
