### ISSUE TITLE
FAQ link is broken

### ISSUE THREAD

**Issue by alkhimey** [pbatard/rufus#1229]
﻿FAQ link on the README in master branch leading to a 404 page.

https://rufus.akeo.ie/FAQ

Either the page is missing from the website for some reason or the link should be updated to point to the correct location.

**Comment by alkhimey** [comment]
Just a minute after opening the issue, found this:
https://github.com/pbatard/rufus/wiki/FAQ
Guess the problem is only the link in the README.

**Comment by pbatard** [comment]
Thanks for reporting this. This is a byproduct of #1227. We'll fix this when we have a chance (but of course this is not our priority right now...).
