### ISSUE TITLE
Update AppxManifest.xml capabilities

### ISSUE THREAD

**Issue by dmex** [pbatard/rufus#1235]
Hi Pete,

Microsoft has finally fixed elevation for desktop applications installed via appx packages. We need to update the AppxManifest.xml file with the new 'allowElevation' capability:

`<rescap:Capability Name="allowElevation" />`

To the capabilities here:
https://github.com/pbatard/rufus/blob/204908f8e00053d5b007e25de7dab1d3f926b8de/res/appstore/AppxManifest.xml#L29-L31

I've been testing this on the latest 1809 update for Windows 10 and the new capability fixes the error dialogs when starting rufus from the appx package 🙂

**Comment by pbatard** [comment]
Closed in e3fb899f127fdb76307b3e5940e8008cbdd3c88c.
