### ISSUE TITLE
Access to the device is denied 

### ISSUE THREAD

**Issue by Hoho4227** [pbatard/rufus#1247]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>
Hi So I am having this issue here. And I am do not what to do next can any of you help me?

Log
---

```
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'CCCOMA_X64FRE_EN-GB_DV9'
  Size: 5073770496 bytes
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr
  Uses: Install.wim (version 0.13.1)
Using image: Win10_1809Oct_EnglishInternational_x64.iso

Format operation started
Notice: Large drive detected (may produce short writes)
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE2 for write access
ABORTED: Cannot use an image that is located on the target drive!
\\?\Volume{00249616-0000-0000-0000-100000000000}\ was already mounted as E:\
Re-mounted volume as 'E:' after error

Found USB 3.0 device 'StoreJet Transcend USB Device' (8564:7000)
1 device found
Disk type: Fixed, Sector Size: 512 bytes
Cylinders: 243201, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00249616
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 1.8 TB (2000396746752 bytes)
  Start Sector: 2048, Boot: No
```

**Comment by JonnyTech** [comment]
#1071

**Comment by pbatard** [comment]
> `ABORTED: Cannot use an image that is located on the target drive!`

That's your problem.

You can __NOT__ create a bootable USB from an ISO that resides on the same USB. It's exactly like sawing the branch you are sitting on, because, __of course__ Rufus will erase __ALL__ data from that drive during the creation process, so, if it was to let you proceed, it would have nothing to create your image from.

You need to move your ISO somewhere else than on the USB.
