### ISSUE TITLE
Haiku OS support in Rufus

### ISSUE THREAD

**Issue by x0rh** [pbatard/rufus#1250]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Adding support for BeOS and Haiku OS (mainly Haiku OS) in Rufus to create a successfull Haiku OS LiveUSB using its .iso . Haiku OS is not listed in Rufus webpage.
This OS reach beta stage and it is well designed.

No tests yet.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Have you tried the anyboot images in Rufus?

Also, you do realize that "non exhaustive" means in the _Non exhaustive list of ISOs Rufus is known to work with_ from the Rufus homepage right. In other words, it's not because something isn't listed that it means that it doesn't work.

Please test the anyboot Haiku images and report.

**Comment by pbatard** [comment]
No update &rarr; Closed.
