### ISSUE TITLE
[RTL] Hardcode file/drive sizes & drive letters to LTR

### ISSUE THREAD

**Issue by ItielMaN** [pbatard/rufus#1254]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I'm sure you hate people who don't post logs in here but I figured this is really not necessary for this issue. :)

Following our (fairly old) discussion about the directionality of the "Portable" text header of Rufus's window, there's a similar issue in Rufus GUI with file/drive sizes & drive letters, see screenshot:
![default](https://user-images.githubusercontent.com/18016656/50426277-bc5d7680-0892-11e9-8fc7-c8bb628ef7bc.png)
Current state:
[GB 32] (H:) (:G) מחיצות מרובות
&
(MB 11) G:\isolinux ...

Expected state:
[32 GB] (H:) (G:) מחיצות מרובות
&
(11 MB) G:\isolinux ...   (or "G:\isolinux ... (11 MB)" if no localized strings are expected; not really important)

I have checked Arabic and Persian and both of them have no translations for KB, MB, GB etc (same for Hebrew) so also for these languages the original LTR text will be used. So fixing this should not mess things up for other RTL languages.

P.S. A reminder to fix Rufus's download link text [for RTL](https://rufus.ie/he_IL.html) so it'd be "Rufus 3.4" & "נייד Rufus 3.4" and not the way it is now.
Tell me if you need a bug on file for that.

Thanks!
Itiel.

**Comment by pbatard** [comment]
Thanks. I'll look into this when I have a chance. Happy New Year to you! 😄 

PS: For the record I am only annoyed when people who open issues that deal with opening an image or a creating a drive, both of which see some processing done by Rufus and therefore critical log data generated, decide that I don't need to see their log. In your case (UI issue that is unrelated to drive creation or image handling), the log is of course optional.
