### ISSUE TITLE
FS changes when enabling HDD detection and doesn't revert on disable

### ISSUE THREAD

**Issue by ItielMaN** [pbatard/rufus#1255]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
STR:
1. Download [gparted-live-0.28.1-1-i686](https://sourceforge.net/projects/gparted/files/gparted-live-stable/0.28.1-1/gparted-live-0.28.1-1-i686.iso/download) and select it in Rufus. You'll see that under file system, FAT32 is selected by default
2. Enable listing USB hard drives (or Alt+F). File system now changes to NTFS
3. Disable it. File system remains as FAT32

... Now I notice the same happens also if you Alt+S (and probably to other shortcuts?).

This may very well be a non-issue, and an expected behaviour. Thought I'd let you know just in case.

Log
---
```
Rufus x86 v3.4.1430 (Portable)
Windows version: Windows 10 32 bit (Build 17763)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x040D
Will use default UI locale 0x040D
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'he-IL'
Found USB 3.0 device 'JetFlash Transcend 32GB USB Device' (8564:1000)
1 device found
Disk type: Removable, Disk size: ‏32‏ GB, Sector size: 512 bytes
Cylinders: 3840, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x91440B65
Drive has an unknown Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 29.4 GB (31575769088 bytes)
  Start Sector: 2048, Boot: Yes
Partition 2:
  Type: SpeedStor (0x21)
  Size: 31.5 KB (32256 bytes)
  Start Sector: 61673472, Boot: No
Scanning image...
ISO analysis:
  Image is an UDF image
  Will use '/syslinux/syslinux.cfg' for Syslinux
  Detected Syslinux version: 6.03/2014-10-06 (from '/syslinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'GParted-live'
  Size: ‏272.3‏ MB (Projected)
  Note: File on disk is larger than reported ISO size by ‏708‏ KB...
  Uses: Syslinux/Isolinux v6.03
  Uses: EFI
Using image: gparted-live-0.28.1-1-i686.iso (‏274‏ MB)
Found USB 3.0 device 'JetFlash Transcend 32GB USB Device' (8564:1000)
1 device found
Disk type: Removable, Disk size: ‏32‏ GB, Sector size: 512 bytes
Cylinders: 3840, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x91440B65
Drive has an unknown Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 29.4 GB (31575769088 bytes)
  Start Sector: 2048, Boot: Yes
Partition 2:
  Type: SpeedStor (0x21)
  Size: 31.5 KB (32256 bytes)
  Start Sector: 61673472, Boot: No
```

**Comment by pbatard** [comment]
Thanks for the report. I'll see what I can do.
