### ISSUE TITLE
BIOS is not proposed on the scrolling list "Target system"

### ISSUE THREAD

**Issue by arcadiabay** [pbatard/rufus#1257]
Hello,
First thank you so much for this wonderful software! I used it regularly associated with Ntlite and i enjoyed it really. It makes the work nicely. 
I'd like to submit an issue though or maybe it's not i don't know...
I made a Windows 7 iso with Ntlite, everything is working fine but i modified this iso file with a utility to inject usb3 drivers. I successfully made a bootable usb key with rufus (in GPT/UEFI mode). Later i decided to use the same iso on an older PC that does not have UEFI. When creating the usb key, Rufus proposes me MBR but not BIOS (UEFI-CSM), only UEFI... And of course i can not boot with this sort of prepared usb key. Well, i don't have this issue with a non modified Ntlite iso file. Is it normal or do you know a way to force Rufus to format the key in BIOS mode ? (or will it be possible in a future release?) Thanks.

**Comment by pbatard** [comment]
Ignored the checklist &rarr; Closed
