### ISSUE TITLE
Holiday Wishes...

### ISSUE THREAD

**Issue by ibuprophen1** [pbatard/rufus#1258]
I just wanted to wish @pbatard Family and Friends the Best Wishes, Happy Holidays and a Happy New Year!!! 

I hope this year ends even more Uplifting and Promising as the last (bumpy) year has ended with!! 

Take care My Friend. 

~Ibuprophen

**Comment by pbatard** [comment]
@ibuprophen1 

Thank you for your kind words. Let me also wish to you and your family the very best in 2019. Have an awesome year!
