### ISSUE TITLE
[RTL] Force the file size to appear last in MSG_085

### ISSUE THREAD

**Issue by ItielMaN** [pbatard/rufus#1279]
Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
When downloading files, the status bar shows MSG_085 which is "Downloading %s", but Rufus adds the file size afterwards.
Since the %s is the file name (which always [?] will in LTR), and the file size is also LTR, it causes the entire sentence to look like this:
![תמונה](https://user-images.githubusercontent.com/18016656/54320629-45648e00-45f6-11e9-9f0e-4391faa1aae1.png)
So for us RTL users this looks like "Downloading (29.6 KB) Fido.ps1".
Adding RLM at the end of MSG_085 doesn't seem to help.

I see 3 options:
1. In future Rufus versions include the file size in the string (same for other strings I'm not aware of that Rufus is adding file size to them), so the translator could do whatever he wants.
2. Add RLM after this string for RTL languages. Which is inefficient I think.
3. Other alternative I haven't thought about :)

Of course this is super low priority, just wanted to have this on file.

**Comment by pbatard** [comment]
I'll see what I can do.
