### ISSUE TITLE
Missing space between "4" and "GB" in MSG_100

### ISSUE THREAD

**Issue by ItielMaN** [pbatard/rufus#1281]
Issue description
-----------------
A minor inconsistency issue:
In MSG_100 there's "4GB", and on all other strings there's a space between the number and the size unit ("Because this file is more than **100 KB** in size" etc.); also file sizes which Rufus generates have space between the number and size unit.

**Comment by pbatard** [comment]
For various reasons, fixing this minor issue will have to be delayed until __after__ this translation round is over.
