### ISSUE TITLE
download button dependancy on enabling update is not exposed

### ISSUE THREAD

**Issue by pm73** [pbatard/rufus#1288]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Issue description
-----------------
I cannot find information in application that download function depends on enabling update. I've found it in FAQ, but I would propose including this information in update settings for less confusion of users.

Log
---
not applicable

**Comment by pbatard** [comment]
It'll be __explictly__ mentioned in the Log with the 3.5 release. I have already applied the change in [82bb497c1bbce644c739bc84a9f92a49b13c23a6] and you should be able to see that in 3.5 BETA 2 that I am planning to release later on today. And as you have found out I have created a FAQ entry for that, and I also made sure this was mentioned more explicitly in the Changelog. I am not planning to mention it in the settings.
