### ISSUE TITLE
I would like to use rufus to always record the same ISO preset, this is possible?

### ISSUE THREAD

**Issue by Jotamel0** [pbatard/rufus#1297]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
<FULL LOG>
```

**Comment by Jotamel0** [comment]
I would like to use rufus to always record the same ISO preset, this is possible

**Comment by Jotamel0** [comment]
I've seen about command lines, but maybe there's another way

**Comment by Jotamel0** [comment]
using rufus.ini maybe..

**Comment by pbatard** [comment]
> I've seen about command lines, but maybe there's another way

No, there's only the commandline. I have no plans to enable any other way to do so at the moment.

**Comment by pbatard** [comment]
As I believe I answered your issue, I will close it.
