### ISSUE TITLE
On my bootable Usb Flash Drive I Can't Connect To WiFi

### ISSUE THREAD

**Issue by RufusUser** [pbatard/rufus#1301]
So i just recently made a bootable flash drive with Rufus and I finished setting it up,  I can run it and use it like any other computer great awesome but I cannot connect to wifi.

**Comment by pbatard** [comment]
@RufusUser, this is an issue tracker for Rufus issues __ONLY__.

You should only post here __if__ you have an issue when using Rufus, and if you do so you should follow the check list.

Since this issue is clearly out of scope, I will close it.
