### ISSUE TITLE
Official windows ISO is over 4G, is there any plan to add exFAT support?

### ISSUE THREAD

**Issue by zhz1237ok** [pbatard/rufus#1306]
Official windows ISO is over 4G, is there any plan to add exFAT support?

**Comment by pbatard** [comment]
No. Rufus has long solved the issue of ISOs that contain files that are larger than 4 GB through [UEFI:NTFS](https://github.com/pbatard/uefi-ntfs).

The latest Windows 10 ISOs with an `install.wim` > 4.0 GB are handled without any issue in Rufus, so there's no need to do anything with exFAT, as it would completely duplicate what is __already__ being done with NTFS.

Next time, try to run a test or spend a little time doing some research.
