### ISSUE TITLE
v3.5 Crashes VirtualBox 5.2.26 on macOS 10.14.4

### ISSUE THREAD

**Issue by alexs77** [pbatard/rufus#1324]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------
I start Rufus 3.5 in a Windows 10 VirtualMachine under VirtualBox 5.2.28 on Mac. It crashes the VirtualMachien right away, even before the application window is shown.

I thus cannot attach a log.

**Comment by pbatard** [comment]
Well, I'm afraid you'll have to take this to the developers of VirtualBox.

If VirtualBox crashes whereas Windows does not, then clearly it's an issue with VirtualBox not properly emulating the hardware and/or software it's supposed to emulate.

I'm afraid I have neither the interest or the time to help figure out what's wrong with VirtualBox on Mac. As such I will close this issue.
