### ISSUE TITLE
Yes, I'm afraid this is one of the many ISOs that doesn't use isolinux or WinPE and is therefore not supported by Rufus (there are many bootable ISO formats, and adding them all in Rufus would be quite a task).

### ISSUE THREAD

**Issue by matejslivar** [pbatard/rufus#1325]
> Yes, I'm afraid this is one of the many ISOs that doesn't use isolinux or WinPE and is therefore not supported by Rufus (there are many bootable ISO formats, and adding them all in Rufus would be quite a task).
> 
> It seems to be DOS based however, so my advice would be:
> - Create a bootable USB with Rufus using FreeDOS or MS-DOS (i.e. without selecting any ISO)
> - Using [7-zip](http://www.7-zip.org/download.html), extract the ISO content onto the USB
> 
> I expect that if you do that, and provided that HDAT2 is not hardwired to use an optical drive, you should be able to run the image from USB.
> 
> Can you please try this and let me know if it works?

_Originally posted by @pbatard in https://github.com/pbatard/rufus/issues/110#issuecomment-11267513_     

i tried the method with zip7 and it works thanks

**Comment by pbatard** [comment]
Okay. There's also [this entry from the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Im_trying_to_work_with_an_ISO_but_Rufus_says_its_unsupported).
