### ISSUE TITLE
Rufus killed my NEW!!!!!!!!!!! flash drive.

### ISSUE THREAD

**Issue by Ska11er** [pbatard/rufus#1326]
Dear developers, i hope you will read it. IF YOU CAN'T DEVELOP AND PROGRAMMING, GO WORK IN MCDONALDS, THEY WAIT PEOPLE LIKE YOU.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive
