### ISSUE TITLE
Thanks :) 

### ISSUE THREAD

**Issue by thorncorona** [pbatard/rufus#1359]
Hi Pete, this isn't an issue but a small thank you for the countless hours you've put into developing Rufus. I absolutely love how rock solid and reliable Rufus is and it's always so easy to use.

Thank you so much for your work :)

**Comment by pbatard** [comment]
Thanks for the kind words, which are much appreciated!

I wish I could take all the credit for Rufus, but it's definitely more than the work of a single person. As you can see on the project page, Rufus currently counts more than 87 direct contributors. And that's before you add all the people who helped in one way or another in the issue tracker or elsewhere...

Also, considering some of my more [recent](https://github.com/pbatard/rufus/issues/1348) [screwups](https://github.com/pbatard/rufus/issues/1351), I can't say I'm entirely sure that _"rock solid"_ is exactly deserved for the 3.6 release... Still, I'll do my best to get these fixed soon to, hopefully, get a release that's worthy of the praise above...
