### ISSUE TITLE
Feature Request - Support persistent partition for Windows To Go

### ISSUE THREAD

**Issue by danbo** [pbatard/rufus#1369]
1. Add support, similar to how it works with linux images, which would be untouched by OS / used for data

![image](https://user-images.githubusercontent.com/16317860/63886802-4d986600-c9a9-11e9-8780-a30e129d9bf6.png)

2. If an existing persistent partition already exists, have an option to leave it alone - allowing to reinitialize an entire WTG installation without touching the persistent data.

**Comment by pbatard** [comment]
Sorry but I'm not planning to do that. Windows To Go is persistent by default (you can write to the system drive and get content persisted there, whereas on Linux this is not the case and the precise reason why you want persistence in the first place).

There's no realistic scenario where having a second partition for Windows To Go will help, as Windows is not designed to look for user directories and settings from that extra partition, and, if your goal is to be able to update the OS partition while keeping the data, you will find that it doesn't work quite like you expect.

Also, see [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want). I believe that when you look at the feature you request objectively, you'll find that it's not going to be useful for a lot of people, if any, therefore it makes very little sense to spend time adding it __and maintaining the extra complexity that would be associated it__.

&rarr; Rejected.

**Comment by danbo** [comment]
Understood, thanks for the quick response.
