### ISSUE TITLE
How to write to a hard disk or SSD device

### ISSUE THREAD

**Issue by narcisgarcia** [pbatard/rufus#1386]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
How can I make hard disk drives be selectable as target devices (non-USB)?
Sometimes I need to prepare old computers to work with only Live sessions in their hard disks, other times I need to experiment with disk images in a virtual machine. But Rufus only lists USB devices as target devices to write to.

**Comment by pbatard** [comment]
> How can I make hard disk drives be selectable as target devices (non-USB)?

You can't. This is by design. If you need to work with internal HDDs, please use a different utility or put your HDDs in a USB enclosure.
