### ISSUE TITLE
Download trough a Proxy Server

### ISSUE THREAD

**Issue by Loughty** [pbatard/rufus#1395]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Rufus can't use the internet connection on any of my office computers, but when I used in my home works fine. The computers of the office uses a _proxy sever_ to get the internet connection, so, that have to be. ¿There's a way to configure the proxy server on Rufus using the .ini file or something like that? There's nothing in the configurations.

Log
---
```
Rufus x86 v3.8.1580 (Portable)
Windows version: Windows 7 SP1 32 bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0C0A (es-ES)
Will use default UI locale 0x0C0A
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'es-ES'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found USB 2.0 device 'ADATA USB Flash Drive USB Device' (125F:CB10)
Using autorun.inf label for drive H: 'antiX-Live'
Removing H: from the list: This is the disk from which Rufus is running!
Found USB 2.0 device 'Generic STORAGE DEVICE USB Device' (05E3:0722)
Device eliminated because it appears to contain no media
0 devices found
Checking for Rufus updates...
Checking release channel...
Unable to send request: This system's SSL library is too old to be able to access this website.
Updates: Unable to access version data
Saved H:\# Portables\Rufus\rufus.log
```

**Comment by pbatard** [comment]
I'm afraid my take on proxy support is simple:
If someone wants to submit a patch that ads proxy support to Rufus (registry/`.ini` please, NO NEW UI ELEMENTS!), I will happily apply it. If not, then I'm just going to have to dismiss this feature as something that I'm never going to be adding to Rufus, as I can realistically state that it's never going to reach a priority level that's high enough on the list of all the things that are fighting for my time, for me to look into adding it myself. I'd rather not give a false promise than an _"I might do it"_ that I know will never materialize.

By the way, if you are getting `This system's SSL library is too old to be able to access this website`, it means that you haven't applied all the updates you need to apply to your Windows 7 system, so you may want to do that.

I will close this issue now.
