### ISSUE TITLE
Failed to extract iso Rufus 3.8

### ISSUE THREAD

**Issue by eggbath** [pbatard/rufus#1401]
So i wanted to install windows 7 on my Kingston DataTraveler 3.0 but everytime at 7 or 6% it says Failed to extract iso. Please help me fixing it. MD5: 56a26636ec667799f5a7f42f142c772d

**Comment by pbatard** [comment]
The checklist is __not__ optional, especially with regards to the issue you describe. As pointed out, if you __choose__ not to follow it, I will simply close the issue and devote my time to helping people who follow directions that are only there to help resolve their problem __faster__.

Especially, if you do follow the check list, then you are supposed to have run a bad blocks check to validate that your media is not the issue.
