### ISSUE TITLE
Syslinux

### ISSUE THREAD

**Issue by Burday** [pbatard/rufus#1414]
Can someone please for the love of god send me the syslinux-6.04 20190226 files? I can't find them anywhere and i cant download them from rufus as "unable to send request". I know this is a well known local problem and yada yada but can you send the files? Thanks.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/Usage-Notes#Where_to_manually_copy_the_SyslinuxGRUB_files_if_Rufus_cant_download_them
