### ISSUE TITLE
Make a "Write anyway" option, for images that the program fails to scan

### ISSUE THREAD

**Issue by goofyseeker311** [pbatard/rufus#1423]
test it with Android 10 aosp_arm64-Q "system.img" file, which the program fails to scan

add support for writing custom (Linux dd produced) custom images without scan success

**Comment by pbatard** [comment]
Please provide a log as well as a direct download link to the image that fails to scan.

As indicated in the checklist you ignored, failure to produce a log may result in an issue being closed without further notice.

**Comment by goofyseeker311** [comment]
How about I just convert this to a feature request, then both log and image
are not needed?

pe 20. jouluk. 2019 klo 9.19 Pete Batard (notifications@github.com)
kirjoitti:

**Comment by goofyseeker311** [comment]
The images can be found at (Android 10 GSI):

https://developer.android.com/topic/generic-system-image/
https://developer.android.com/topic/generic-system-image/releases

https://dl.google.com/developers/android/qt/images/gsi/aosp_arm64-exp-QJR1.191112.001-6004257.zip

**Comment by goofyseeker311** [comment]
Android 10 does not use a standard Linux file system, even a standard Linux kernel cannot read it.

**Comment by pbatard** [comment]
Exact duplicate of #1416.

Google should know better than create bootable images that don't have the `55` `AA` marker, that is the __de facto established way of signifying that an image is bootable__.

If Google decided that they are above established rules, then you need to complain to them as Rufus will never be designed to be a `dd` replacement (where any image is accepted). You may not realize this, but accepting any image would have a lot of negative ramifications.

Closed as _"not my problem"_.
