### ISSUE TITLE
Offline bundle

### ISSUE THREAD

**Issue by hytron00** [pbatard/rufus#1427]
Hello,

I saw the old post from 2017 where someone was looking and asking for an offline bundle. I am wondering if that is available for download, for example I ran into situation last night when I wanted to create a boot disk of VMware ESXi hypervisor, so the option GPT did not work, and when I used the optin MBR, the rufus program was looking for the internet connection and downloaded the isolinux folder from your server. Is an offline bundle or zipfile available to for download so if I use rufus on a different computer, it wont be going online and downloading the syslinux again?

Thanks!

**Comment by pbatard** [comment]
There's no offline bundle but you can simply clone https://github.com/pbatard/rufus-web where you will find all the downloadable files we currently serve.

It is then up to you to figure out where you should copy the files as per https://github.com/pbatard/rufus/wiki/Usage-Notes#Where_to_manually_copy_the_SyslinuxGRUB_files_if_Rufus_cant_download_them.
