### ISSUE TITLE
Feature Request: Native Linux Support.

### ISSUE THREAD

**Issue by xekon** [pbatard/rufus#1433]
I was curious if you have considered porting Rufus so that it could be natively used on linux. Rufus has been my goto tool for putting images onto usb flash drives for many years.

I have not used Windows for the last 10 years or so, but I still have a VM that I boot into for Windows specific things, and using Rufus is one of those things.

I love rufus! keep up the excellent work, and thank you.

**Comment by pbatard** [comment]
If you followed the checklist, you'd have [the answer](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS).
