### ISSUE TITLE
after making my USB Device bootable - it acts like it does not exist

### ISSUE THREAD

**Issue by miloszowi** [pbatard/rufus#1436]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [-] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [-] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [X] Plugging the USB into a different port.
  - [-] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

After successful booting my USB Device via RUFUS, it made the USB not visible everywhere, I can not see it in device manager, through disk part in windows, nowhere. 
I have no idea what happened, this USB was used for years without any problems till booting with Rufus. 
Do you have any ideas how can I restore my USB to make it work again?

I was not able to checkbox all of the above because immediately closed Rufus.

**Comment by gdegliesposti** [comment]
Hello.
This is a FAQ.
https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected

ciao
G

**Comment by miloszowi** [comment]
@gdegliesposti - this is not helping either, no USB shows up in the dropdown

**Comment by pbatard** [comment]
Can you see it under Linux or MacOS?

Also, what was the exact image you used to write your USB? Some images (e.g. Chrome OS x86) play weird tricks with Windows (Microsoft bug), that can make it look like the flash drive is unusable.

However, it does look to me, from what you described, that your flash drive simply failed and that you will have to replace it...

**Comment by miloszowi** [comment]
I've checked in MacOS - without positive results - it is not visible there too, not sure about Linux.
I used Windows 10 image.

I am aware that flash memory has a data retention of about 20 years but it was not even close. I am just wondering how did it come to entirely kill the device.

**Comment by pbatard** [comment]
> I am just wondering how did it come to entirely kill the device.

Because hardware failures are random, and don't happen right at the MTBF that the manufacturer specifies... Consumer USB flash drive memory is __a lot__ less reliable than people imagine, and I've seen score after score of users asking themselves _"How can my flash drive be dead when it was almost brand new?"_ (and not just people using Rufus) to be able to state this as a fact.

**Comment by miloszowi** [comment]
I've never encountered such a thing previously. 
If it is what you have up in your head - then it definitely should display some kind of notice/error to the end-user because right now I am confused - Rufus did not display anything other than the process went successful.

**Comment by pbatard** [comment]
> Rufus did not display anything other than the process went successful.

That's because the failure intervened after Rufus got to write the drive.

It occurred sometime between when you used the drive to boot and when you plugged it back to your computer to reuse it for something else.

There's nothing Rufus can do to alert users about failures that occur __after__ it's done its job.

**Comment by pbatard** [comment]
I will close this issue now, as I believe I answered your question.
