### ISSUE TITLE
MBR/FAT32

### ISSUE THREAD

**Issue by roddy20** [pbatard/rufus#1439]
![Аннотация 2020-01-26 124336](https://user-images.githubusercontent.com/5681302/73134083-b78d6800-403a-11ea-8331-47c42cf6f8fe.jpg)

Hello!
Default format for Windows 7/10 install media is MBR, FAT32 (like MS Media Creation Tool does)
it is bootable both as MBR legacy and UEFI depending of BIOS)
why Rufus cannot create USB with these parameters ?

**Comment by pbatard** [comment]
Next time, please read the FAQ as advised.

Dual BIOS + UEFI boot is [disabled by design in Rufus](https://github.com/pbatard/rufus/wiki/FAQ#Why_doesnt_Rufus_create_a_Windows_installation_USB_that_can_be_booted_in_dual_BIOSUEFI_mode) but it can be enabled with <kbd>Alt</kbd>-<kbd>E</kbd>.
