### ISSUE TITLE
Add a program-specific sound at the end of the recording process

### ISSUE THREAD

**Issue by TDHster** [pbatard/rufus#1442]
For long writting proces will be very usefull not simple system sound, but something interesting and uniquely recognizable.

Like this (maybe part of this files):
https://freesound.org/people/toiletrolltube/sounds/419898/
https://freesound.org/people/Timbre/sounds/92321/
https://freesound.org/people/nixeno/sounds/440582/ (second wayform at 3s or 16s or 51s )
https://freesound.org/people/nixeno/sounds/427552/ (at 0s or 7s)

**Comment by pbatard** [comment]
I don't think I want to do that. Rufus produces the standard system sound when it finishes a task, and also offers independent visual cues to indicate completion (including on the task bar, so you don't have to have the application in the foreground to find if it's process completed or not) and I don't think adding custom sounds is going to be as helpful as you believe it is.

Rejected.
