### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by Kawaii-KM** [pbatard/rufus#1451]
Hope to add support for hard drives.

**Comment by pbatard** [comment]
* https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected
* https://github.com/pbatard/rufus/wiki/FAQ#Why_doesnt_Rufus_list_external_HDDs_by_default
* https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_support_internal_HDDsSSDs

Next time, please follow the check list. You'll find that, as opposed to being an annoyance, it is there to make sure the same questions don't get asked over and over and over again in the issue tracker, when they have been answered at length in the FAQ.
