### ISSUE TITLE
Rufus detects WinPE ISO as Windows installation

### ISSUE THREAD

**Issue by gtumanyan** [pbatard/rufus#1463]
I'm using your program very long time and aware of Alt-E Cheat. Just asking you not to treat **every** **custom** ISO as Microsoft **official**.
![image](https://user-images.githubusercontent.com/24494814/75111621-359a5a00-564d-11ea-857e-2294523bc3e6.png)
[WinPE](https://s150vla.storage.yandex.net/rdisk/7bf87b989543ac9d644cca20bf6c12d2703c173fe7b82b2acb07c1004b3b4b20/5e528f73/3_kMTKZ-LikS4O7xBuuHCsvXXdvTTsWbth8QOqc9FcSWf3uwGlBtJoQNT59LuGfTqEzutqnb-wUiXDRINFAi8A==?uid=0&filename=Win10PE_x86x64%28EFI%29_mini%282019%29.iso&disposition=attachment&hash=NDIeFqxe7R3lxmtSo/ih1dMlShrfyPulGvTijqqni1s%3D%3A/Win10PE_x86x64%28EFI%29_mini%282019%29.iso&limit=0&content_type=application%2Fx-iso9660-image&owner_uid=92672393&fsize=375472128&hid=e496b5135c5ab33fa2d382040ad5ed6a&media_type=diskimage&tknv=v2&rtoken=K3gXruxKwP9Z&force_default=no&ycrid=na-0be98a5a6bc476cef88fe3d2f056682f-downloader17e&ts=59f3f455c82c0&s=3a7f887abae13ed59ecee6d3ce64e5b3ddce496d3977bf360440efc4dfb9e847&pb=U2FsdGVkX1_nXzDqP4KVftPzwnq8k4kQoBjDZ4CZVx8clVPLWIckhY0vp-WpdWE-BNpYmH8RfaAkTFkssbc2a0Dsj8TQo1LgSHmSLHgYpCw
) Log:
Rufus x86 v3.9.1622 (Beta) (Portable)
Windows version: Windows 10 64-bit (Build 17763.292)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0419 (ru-RU)
Will use default UI locale 0x0419
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'ru-RU'
Found USB 2.0 device 'USB DISK 30X USB Device' (13FE:1D00)
Using autorun.inf label for drive D: 'WIN10PEX32X64MINI'
1 device found
Disk type: Removable, Disk size: 4.1Гб, Sector size: 512 bytes
Cylinders: 494, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0076FCE0
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 3.8 GB (4063232000 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an ISO9660 image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'WIN10PEX32X64MINI'
  Size: 262.0 Мб (Projected)
  Uses: EFI
  Uses: Bootmgr (BIOS only)
Using image: Win10PE_x64_EFI_(2020).iso (264.9 Мб)

Format operation started
Requesting disk access...
Will use 'D:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive1':
● Partition 1 (offset: 1048576, size: 3.8 Гб)
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has a Rufus Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
● Creating Main Data Partition (offset: 1048576, size: 3.8 GB)
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing Master Boot Record...
Set bootable USB partition as 0x80
Using Windows 7 MBR
Found volume \\?\Volume{68ec3dea-53ae-11ea-946f-001a7dda7113}\
Disabling file indexing...
Waiting for access on \\?\Volume{68ec3dea-53ae-11ea-946f-001a7dda7113} [\Device\HarddiskVolume4]...
Opened \\?\Volume{68ec3dea-53ae-11ea-946f-001a7dda7113} for exclusive write access
Writing Partition Boot Record...
Using Standard NTFS partition boot record
Confirmed new volume has an NTFS boot sector
Successfully remounted \\?\Volume{68ec3dea-53ae-11ea-946f-001a7dda7113}\ as D:
Extracting files...
Image is an ISO9660 image
This image will be extracted using Joliet extensions (if present)
Extracting: D:\Boot\1064.wim (256 MB)
Extracting: D:\Boot\BCD (28 KB)
Extracting: D:\Boot\Fonts\boot.ttf (46.3 KB)
Extracting: D:\Boot\Fonts\wgl4_boot.ttf (46.3 KB)
Extracting: D:\Boot\boot.sdi (960 KB)
Extracting: D:\Boot\bootmgr (388.8 KB)
Extracting: D:\Boot\memtest.exe (762.3 KB)
Extracting: D:\Boot\start_os.bin (263.6 KB)
Extracting: D:\bootmgr (388.8 KB)
Extracting: D:\efi\boot\bootx64.efi (1.5 MB)
Extracting: D:\efi\microsoft\boot\BCD (40 KB)
Extracting: D:\efi\microsoft\boot\Fonts\boot.ttf (46.3 KB)
Extracting: D:\efi\microsoft\boot\Fonts\wgl4_boot.ttf (46.3 KB)
Extracting: D:\efi\microsoft\boot\memtest.efi (1.4 MB)
Extracting: D:\efi\microsoft\boot\ru-ru\memtest.efi.mui (43.8 KB)
Finalizing, please wait...
Created: D:autorun.inf
Created: D:autorun.ico
NTFS Fixup (Checkdisk)...
Volume label is WIN10PEX32X64MINI.

Stage 1: Examining basic file system structure ...
  256 file records processed.
File verification completed.
  0 large file records processed.
  0 bad file records processed.

Stage 2: Examining file name linkage ...
  294 index entries processed.
Index verification completed.
  0 reparse records processed.
  0 reparse records processed.

Stage 3: Examining security descriptors ...
Security descriptor verification completed.
  20 data files processed.
CHKDSK is verifying Usn Journal...
  5056 USN bytes processed.
Usn Journal verification completed.

Windows has scanned the file system and found no problems.
No further action is required.

   3967999 KB total disk space.
    273508 KB in 24 files.
        80 KB in 21 indexes.
      9595 KB in use by the system.
      8544 KB occupied by the log file.
   3684816 KB available on disk.
      4096 bytes in each allocation unit.
    991999 total allocation units on disk.
    921204 allocation units available on disk.
NTFS Fixup completed.

Found USB 2.0 device 'USB DISK 30X USB Device' (13FE:1D00)
Using autorun.inf label for drive D: 'WIN10PEX32X64MINI'
1 device found
Disk type: Removable, Disk size: 4.1Гб, Sector size: 512 bytes
Cylinders: 494, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x000C2744
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 3.8 GB (4063232000 bytes)
  Start Sector: 2048, Boot: Yes

Format operation started
Requesting disk access...
Will use 'D:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive1':
● Partition 1 (offset: 1048576, size: 3.8 Гб)
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has a Windows 7 Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
● Creating Main Data Partition (offset: 1048576, size: 3.8 GB)
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing Master Boot Record...
Set bootable USB partition as 0x80
Using Rufus MBR
Found volume \\?\Volume{68ec3dea-53ae-11ea-946f-001a7dda7113}\
Disabling file indexing...
Opened \\?\Volume{68ec3dea-53ae-11ea-946f-001a7dda7113} for exclusive write access
Writing Partition Boot Record...
Using Standard NTFS partition boot record
Confirmed new volume has an NTFS boot sector
Successfully remounted \\?\Volume{68ec3dea-53ae-11ea-946f-001a7dda7113}\ as D:
Extracting files...
Image is an ISO9660 image
This image will be extracted using Joliet extensions (if present)
Extracting: D:\Boot\1064.wim (256 MB)
Extracting: D:\Boot\BCD (28 KB)
Extracting: D:\Boot\Fonts\boot.ttf (46.3 KB)
Extracting: D:\Boot\Fonts\wgl4_boot.ttf (46.3 KB)
Extracting: D:\Boot\boot.sdi (960 KB)
Extracting: D:\Boot\bootmgr (388.8 KB)
Extracting: D:\Boot\memtest.exe (762.3 KB)
Extracting: D:\Boot\start_os.bin (263.6 KB)
Extracting: D:\bootmgr (388.8 KB)
Extracting: D:\efi\boot\bootx64.efi (1.5 MB)
Extracting: D:\efi\microsoft\boot\BCD (40 KB)
Extracting: D:\efi\microsoft\boot\Fonts\boot.ttf (46.3 KB)
Extracting: D:\efi\microsoft\boot\Fonts\wgl4_boot.ttf (46.3 KB)
Extracting: D:\efi\microsoft\boot\memtest.efi (1.4 MB)
Extracting: D:\efi\microsoft\boot\ru-ru\memtest.efi.mui (43.8 KB)
Finalizing, please wait...
Created: D:autorun.inf
Created: D:autorun.ico
NTFS Fixup (Checkdisk)...
Volume label is WIN10PEX32X64MINI.

Stage 1: Examining basic file system structure ...
  256 file records processed.
File verification completed.
  0 large file records processed.
  0 bad file records processed.

Stage 2: Examining file name linkage ...
  294 index entries processed.
Index verification completed.
  0 reparse records processed.
  0 reparse records processed.

Stage 3: Examining security descriptors ...
Security descriptor verification completed.
  19 data files processed.

Windows has scanned the file system and found no problems.
No further action is required.

   3967999 KB total disk space.
    273508 KB in 24 files.
        80 KB in 21 indexes.
      9339 KB in use by the system.
      8544 KB occupied by the log file.
   3685072 KB available on disk.
      4096 bytes in each allocation unit.
    991999 total allocation units on disk.
    921268 allocation units available on disk.
NTFS Fixup completed.

Found USB 2.0 device 'USB DISK 30X USB Device' (13FE:1D00)
Using autorun.inf label for drive D: 'WIN10PEX32X64MINI'
1 device found
Disk type: Removable, Disk size: 4.1Гб, Sector size: 512 bytes
Cylinders: 494, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x001BD454
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 3.8 GB (4063232000 bytes)
  Start Sector: 2048, Boot: Yes

**Comment by pbatard** [comment]
And I'm asking you to read the FAQ, and especially [point 2 of this section](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want).

Please understand that it's not because the application is free that my time also is. As such I have to decide what features I should spend it on, and I don't see trying to get your custom ISOs supported as a a feature I want to invest my limited development time on, sorry.
