### ISSUE TITLE
Does storing an ISO ALWAYS AUTOMATICALLY remove ALL partitions?

### ISSUE THREAD

**Issue by pstein** [pbatard/rufus#1479]
When I store an ISO onto an USB Flash Drive: 
Does Rufus ALWAYS AUTOMATICALLY remove ALL existing partitions on this USB-Flash Drive?

﻿Or does Rufus try to store the ISO content e.g.only on the first found partition?

Or does Rufus leave just any kind of (boot or reserve) partition untouched?

Or do I need to tick "Quick format" to achieve a real full removal?

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Why_does_Rufus_need_to_delete_all_partitionsvolumes_when_creating_a_drive

Everything is removed. Next time follow the checklist and see if your question is answered in the FAQ.
