### ISSUE TITLE
Would it be possible to not ask for application update policy at the start of Rufus?

### ISSUE THREAD

**Issue by BoQsc** [pbatard/rufus#1480]
![image](https://user-images.githubusercontent.com/21064622/76769094-a7754780-67a4-11ea-87b3-53920bc796df.png)
Could there be command line option to stop showing application update policy window at the start of Rufus?

**Comment by pbatard** [comment]
Rename the application to `rufus.exe` and you won't see it (update check will be enabled by default).

**Comment by JonnyTech** [comment]
@pbatard don't you mean `rufusp.exe`?

**Comment by pbatard** [comment]
No. I do mean `rufus.exe`: https://github.com/pbatard/rufus/wiki/FAQ#Rufus_connects_to_the_internet_but_I_never_allowed_it_to__why

**Comment by pbatard** [comment]
That's actually the reason why, on the old server, I used to have 2 symbolic links, one for the portable version (`rufusp-#.##.exe`) and one for the "no-prompt" version, which is always named `rufus.exe`, that all linked to the same binary. In other words, we're using the "check the application name" trick for more than portable vs. non-portable...

**Comment by JonnyTech** [comment]
Gotcha. It's just that I do not ever recall the portable version asking the question. Thanks for the clarification.

**Comment by pbatard** [comment]
The portable version does ask. Easiest way to confirm this is to launch Rufus, then press <kbd>Alt</kbd>-<kbd>R</kbd> (this deletes __all__ the registry keys created by Rufus) as well as delete any `rufus.ini` file you may have in your directory. Then you will see the default behaviour, and you can validate things like `rufus.exe` not prompting for the update check, whereas any other version will do so.
