### ISSUE TITLE
Command line option for changing Partition Scheme to GPT

### ISSUE THREAD

**Issue by BoQsc** [pbatard/rufus#1481]
As far as I see, there is seems to be no command line option to change Partition Scheme to GPT
![image](https://user-images.githubusercontent.com/21064622/76770465-af35eb80-67a6-11ea-970d-72e2a8f7646d.png)

![image](https://user-images.githubusercontent.com/21064622/76770654-f6bc7780-67a6-11ea-82ed-d5ce74fa2a14.png)

**Comment by pbatard** [comment]
As per #111 command line support is very low priority. I will therefore close this issue. GPT override will be added when I tackle commandline support, which, in all fairness, is probably still a couple more years from now, as I want to do that properly.
