### ISSUE TITLE
Command line option to choose ISOHybrid image

### ISSUE THREAD

**Issue by BoQsc** [pbatard/rufus#1483]
I would like to ask to have Command line option that will silently approve this option at the start of Rufus.
![image](https://user-images.githubusercontent.com/21064622/76772141-118feb80-67a9-11ea-8508-820f2062ac23.png)

**Comment by pbatard** [comment]
See my previous answer to your last commandline request. Note that if you are going to create request for every small feature and element you can think of, I'm going to have to take measures.
