### ISSUE TITLE
My request I am waiting for multiple boot functionality in the next release

### ISSUE THREAD

**Issue by illegun06** [pbatard/rufus#1486]
No multi-Boot Function. Why? adding this feature should not be too difficult. It would be nice if you add the feature. I'd be happy. google translate used.

**Comment by pbatard** [comment]
Explained [in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiboot_support), which you are asked to check out when creating a new issue.
