### ISSUE TITLE
XP won't install on old laptop

### ISSUE THREAD

**Issue by vorob1** [pbatard/rufus#1489]
Hi, i've got Fujitsu AMILO Xi 1546 laptop and i've got flash with win xp created via rufus. I've already used it to install XP to IBM R60 and hand no issue, but on AMILO I'm getting this:

My settings: https://sun9-30.userapi.com/c857124/v857124581/10e5ce/Dd_x8Tx08I0.jpg
After I'm trying boot from it: https://sun9-72.userapi.com/c858520/v858520581/12c656/WDZqeJEdX1M.jpg

That's kinda weird. I've successfully installed Vista and 7 but Win XP won't go.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_Windows_Vista_NO_LONGER_SUPPORTED
