### ISSUE TITLE
Goddammit Ubuntu 20.04!

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#1499]
You have now managed to completely revert the persistence implementation that was working fine with 19.10.

- [x] Regardless of how everything is created (i.e. even when not using Rufus at all but creating everything manually) your current persistence scripts only seem to manage to mount `casper-rw` [about once in a blue moon](https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1863672). &rarr; _Fixed by the Ubuntu devs (hopefully)_
- [x] [045f590c3bead6b66dcbde09afedaab6c046120d] That idiotic new `vmlinuz$casper_flavour` of yours broke the expected location where we tried to add the `persistent` keyword (and, __NO__, even when this is fixed, the above issue still applies!)
- [x] [1e6e38b18075adc8527b08e7ab8a6c99946cf415] You found nothing better than add a forced MD5 validation for the config files, meaning that we'll have to recompute the bloody hashes, if we ever actually manage to work around your utter breakage and somehow work behind your back to add some kind of __stable__ persistence... Oh and one has to wonder why you validate `grub.cfg` but not `isolinux.cfg`...
- [x] [1e6e38b18075adc8527b08e7ab8a6c99946cf415] You broke the GRUB config further by introducing a new `loopback.cfg` that we probably need to modify for persistence as well (where the hell is this used?!?)
- [x] You introduced a race condition by __unilaterally__ deciding that _"people don't understand where the well documentd `casper-rw` comes from, so let's introduce a NEW SUPER GENERIC `writable` label, that does provide any actual hint of persistence in any way, and tell folks out of the blue that this is what they should use now"_ &rarr; _Still waiting for a reply on https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1872065..._

All I can say is: well done. You left persistence utterly broken [FOR YEARS](https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1489855), then finally managed to fix it 6 months ago, only to completely undo the whole thing yet again. _BRA-VO!_

**Comment by FardinA143** [comment]
Well done Ubuntu Inc.
