### ISSUE TITLE
[req] Update link in FAQ for PNY Ufix tool

### ISSUE THREAD

**Issue by ilike2burnthing** [pbatard/rufus#1508]
RE: https://github.com/pbatard/rufus/wiki/FAQ#incompatible-hardware

Current link redirects to homepage.

I would have made this a PR, but there's 2 possible links, so I'll leave that choice up to you.

Search for tool - https://www.pny.com.tw/en/search/index.php?search=USB+Flash+Driver

FAQ (and then scroll half way down) - https://www.pny.com.tw/en/support-detail/usb-flash-drives/

**Comment by pbatard** [comment]
I've updated the link. Thanks.
