### ISSUE TITLE
[req] a few more links to updates

### ISSUE THREAD

**Issue by ilike2burnthing** [pbatard/rufus#1509]
Sorry, should have checked before I posted the last one.

https://github.com/pbatard/rufus/wiki/FAQ#why-did-you-create-rufus
Link to HPUSBFW is dead. Only HP link I could find was [this](https://support.hp.com/gb-en/document/c02715961), but that doesn't really help. It's dotted about on several 3rd party download sites if you want a link though.

https://github.com/pbatard/rufus/wiki/FAQ#grub
bugs.manjaro.org is definitely [still](https://forum.manjaro.org/t/so-what-the-heck-happened-to-the-bug-tracker/83789) dead... *pokes with stick* ...yep, dead

https://github.com/pbatard/rufus/wiki/FAQ#incompatible-software
Seems to have been removed. You could try [this](https://docs.sophos.com/central/Customer/help/en-us/central/Customer/concepts/ConfigureDeviceControl.html), or [this](https://docs.sophos.com/esg/endpoint-security-and-control/10-6/help/en-us/esg/common/references/What_types_of_device_can_be_controlled_.html), or maybe something in [here](https://community.sophos.com/kb?TopicId=1469)

Hopefully that's all of some use.

As an aside, it turns out that Kaspersky and Malwarebytes think libusb.info is a dangerous site for some reason 🙄 

Ta from up north!

**Comment by pbatard** [comment]
Thanks for this. I think I have updated all the links now. If you find any additional dead links, don't hesitate to let me know.
