### ISSUE TITLE
Suppport for "dangerous mode" / Question

### ISSUE THREAD

**Issue by PeterHindes** [pbatard/rufus#1512]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
How does this application manage to run badblocks under windows? I frequently use badblocks to test drives on my linux systems, and I would like to be able to use it on partitions and internal disks. Is there a way that I could make rufus target a blank partition on my system drive for testing? Or maybe a way to compile badblocks so that it can be used as a command line tool in cmd/powershell.

**Comment by pbatard** [comment]
Rufus uses the bad blocks code from e2fsprogs (which we altered to integrate into Rufus).

If you are running Linux, you should be able to test your disks using e2fsprogs as well. However, I am not planning to produce a standalone version of the bad blocks check for Windows, and especially, I am not planning to __ever__ let Rufus access system disks for any purpose.

See also [here]](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want).

As I have answered your question, I will close this issue.
