### ISSUE TITLE
[Feature Request] prevent standby / sleep mode

### ISSUE THREAD

**Issue by chris400** [pbatard/rufus#1519]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I do use rufus to check my thumbdrives for bad blocks. This sometimes takes long time (depending on size and speed of the drive). I would be very happy, if rufus would prevent Windows from going into standby while working.
I do know how to configure windows, it would be nicer, if rufus would handle this automatically.

Log
---
```
Rufus x86 v3.9.1624 (Portable)
Windows version: Windows 10 64-bit (Build 18363.815)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'SMI USB DISK USB Device' (090C:1000)
1 device found
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 985, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x154E69C4
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 7.5 GB (8102346752 bytes)
  Start Sector: 2048, Boot: Yes
Checking for Rufus updates...
Checking release channel...
No new release version found.

Format operation started
Requesting disk access...
Will use 'F:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive2':
● Partition 1 (offset: 1048576, size: 7.5 GB)
Opened \\.\PhysicalDrive2 for exclusive write access
Analyzing existing boot records...
Drive has a Windows 7 Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Bad Blocks: Checking from block 0 to 61823 (1 block = 128 KB)
Bad Blocks: Using offset 7747 for fake device check
Bad Blocks: Writing test pattern 0x00
Bad Blocks: Reading and comparing
Bad Blocks: Writing test pattern 0xFF

```

**Comment by pbatard** [comment]
I don't think I want to add that feature, as it seems to be something that few people will request, and disabling standby without asking is generally frowned upon, which means that now I'd have to add 37 translations to pop up a question about standby whenever a bad blocks check is selected, and which, I will assert, most people will see as an annoyance rather than something else.

Therefore, I am going to reject this request for now. My opinion is that it's really up to the user to ensure that the computer doesn't go to standby if they are starting a task that may take a long time, and don't want it to be interrupted by sleep.

But I start receiving a fair amount of requests for standby prevention, I may reconsider.
