### ISSUE TITLE
UEFI:NTFS "Could not locate '\efi\boot\bootx64.efi': [14] Not Found" 2020

### ISSUE THREAD

**Issue by Ricktek31** [pbatard/rufus#1522]
[rufus.log](https://github.com/pbatard/rufus/files/4519910/rufus.log)
![WhatsApp Image 2020-04-23 at 4 37 45 AM](https://user-images.githubusercontent.com/64179853/80053058-503d6200-851c-11ea-85cc-c41be2bb7e4d.jpeg)

**Comment by pbatard** [comment]
`win_10_pro_edition_retail_1809_x86`

This is a 32-bit image, so it is not compatible with 64-bit UEFI, which __is__ what you are using, since it is looking for `bootx64.efi`.

You __MUST__ use 64-bit Windows if you want to install it in UEFI mode on that machine. 32-bit Windows will __not__ work.
