### ISSUE TITLE
my flash memory card not recognized by windows and i cant format it (Could not delete drive layout: [0x000001E3] The request failed due to a fatal device hardware error)

### ISSUE THREAD

**Issue by mahdigoodarzis** [pbatard/rufus#1527]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

hello
my English is not good, so I'm sorry for that.
yesterday i used my flash memory for created a bootable windows 10 pro and suddenly i saw an error in middle of flashing process.
now my memory recognize by windows and when i click in it or try to format it, i see this error: the request failed due to fatal  device hard error
i already tried many solutions but none of them is working for me: minitool app, diskpart cmd cleaning, ubunto gparted app, test disk ,...
what should i do now?

Log
---
```
Requesting disk access...
Will use 'Z:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive2':
● Partition 1 (offset: 1048576, size: 14.7 GB)
Opened \\.\PhysicalDrive2 for exclusive write access
Analyzing existing boot records...
Drive has a Windows 7 Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
write_sectors: Write error [0x000001E3] The request failed due to a fatal device hardware error.
  StartSector: 0x01d73780, nSectors: 0x1, SectorSize: 0x200
Retrying in 5 seconds...
Deleting partitions...
Could not delete drive layout: [0x000001E3] The request failed due to a fatal device hardware error.
Could not reset partitions
Re-mounted volume as Z: after error

Found USB 2.0 device 'SanDisk Cruzer Blade USB Device' (0781:5567)
Found USB 2.0 device 'MXT-USB Storage Device USB Device' (AAAA:8815)
2 devices found
No volume information for drive 0x82
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1922, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x007367D2
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 14.7 GB (15810428928 bytes)
  Start Sector: 2048, Boot: Yes
Found USB 2.0 device 'SanDisk Cruzer Blade USB Device' (0781:5567)
Found USB 2.0 device 'MXT-USB Storage Device USB Device' (AAAA:8815)
2 devices found
No volume information for drive 0x82
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1922, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x007367D2
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 14.7 GB (15810428928 bytes)
  Start Sector: 2048, Boot: Yes
```

**Comment by pbatard** [comment]
>  and suddenly i saw an error in middle of flashing process.

This indicates that your flash memory card has an issue.

> the request failed due to fatal device hard error

Also this.

I'm afraid all signs point to a hardware failure of your media, and it is not something that can be recovered. If you tried reformatting it with different utilities and none of them work, your card is most likely dead, so you will just have to use a new one.

See also [this](https://github.com/pbatard/rufus/wiki/FAQ#Rufus_cant_detectformat_my_drive_and_reports_that_it_is_readonly_or_contains_no_media).
