### ISSUE TITLE
Rufus for Linux

### ISSUE THREAD

**Issue by viniciusjl** [pbatard/rufus#1530]
How could someone compile Rufus for Linux?

There are [EDITED: FAKE] sites like [EDITED: LINK REMOVED] that say that it has a Rufus for Linux, but it has only download for Windows.

Even the instructions here in github are for Windows.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS
