### ISSUE TITLE
Understanding the code - What file do I start in?

### ISSUE THREAD

**Issue by caelwithcats** [pbatard/rufus#1535]
What is the file in rufus that contains the entry point (the main function)?

**Comment by pbatard** [comment]
It's a Win32 application, so it starts with [`WinMain()` in `rufus.c`](https://github.com/pbatard/rufus/blob/bcca9144b79782d319ef2398785586fb085de44d/src/rufus.c#L2889-L2897) which, by the way, is clearly tagged as the application entrypoint with a comment...
