### ISSUE TITLE
Rufus - Missing privileges

### ISSUE THREAD

**Issue by Dhanraj99** [pbatard/rufus#1540]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>
I am not able to open rufus at all. I am using rufus 2.18 on windows xp to create bootable usb for windows 7. I am getting the error - Missing elevated privileges. I was trying with admin account only. I also created new account with admin privileges. Still it's giving same error. I am stuck as I have the admin rights and still not able to run rufus, so requesting your help on this.
Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_Windows_Vista_NO_LONGER_SUPPORTED
