### ISSUE TITLE
My portable ssd partition is not recognized

### ISSUE THREAD

**Issue by aaramg** [pbatard/rufus#1547]
Hi.
It would be nice if Rufus also could recognize portable drives and asl their PARTITIONS too. For example I have Sandisk Extreme portable SSD drive and have created a partition for bootable images. It would be great if I could choose that partition and make it bootable with a given image.

P.S. Nowadays it is more popular to have portable SSD drives instead of legacy USB drives. That could make your product value higher.

**Comment by pbatard** [comment]
Next time, please follow the check list, __even__ if you believe that it should not apply to you. I'm pretty sure all your questions are already answered in the FAQ, which the check list specifically asked you to consult. Especially:

* https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected
* https://github.com/pbatard/rufus/wiki/FAQ#Why_does_Rufus_need_to_delete_all_partitionsvolumes_when_creating_a_drive
* https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiple_partition_support
