### ISSUE TITLE
Error: Undetermined error while formatting AND The device is in used by another process.  [001388] C:\Windows\Explorer.EXE(r)

### ISSUE THREAD

**Issue by Cro-Magnon28** [pbatard/rufus#1558]
> The problem here (and this is one I am struggling with a lot as I am introducing ext2/ext3 formatting) is that Windows, and especially Windows 10, appears to be aggressively caching the partition data from drives, and besides ejecting the media, there doesn't seem to exist an efficient way to make it refresh its view of the partition layout after it's been modified. The partition caching is problematic because as long as Windows thinks there is a partition occupying this or that range of sectors, it may prevent access to said sectors being written to even by its own APIs.
> 
> None of the things I've tried to implement so far (calling on VDS refresh API calls, simulating a disable + enable of the disk as you would do in Device Manager) have yielded much success. For one thing, VDS seems to be completely hopeless as clearing the partition data cache, even as it is supposed do so with calls such as [`IVdsService_Refresh()`](https://docs.microsoft.com/en-us/windows/desktop/api/vds/nf-vds-ivdsservice-refresh) or [`IVdsService_Reenumerate()`](https://docs.microsoft.com/en-us/windows/desktop/api/vds/nf-vds-ivdsservice-reenumerate), and thanks to Windows' weirdness, the device disable+enable trick may appear to work fine, but can leave the device disabled the next time you replug it...
> 
> So what you want, really, is Windows to acknowledge that the partition layout it is trying to use is obsolete and should be discarded. IMO, the most efficient way to do that is to use the 2 following cheat modes in Rufus:
> 
> 1. First, you should issue <kbd>Alt</kbd>-<kbd>Z</kbd>. This writes zeroes to the whole drive which should ensure that the partition table gets zapped (though one should know that, if a drive is GPT, there does exist a backup partition table near the end of the drive that could theoretically be used. However, from my experience, Windows does tend to ignore it if it finds there is no primary GPT table.
> 2. Let the zeroing run for a little while and then cancel it.
> 3. Issue <kbd>Alt</kbd>-<kbd>C</kbd>, which will cycle the USB port for the currently selected device. Of course, this only works for USB devices, and what's more, only on Windows 8 or later, as Microsoft decided to remove USB port reset, which they introduced in Windows XP, from Windows 7, only to reintroduce it back in 8... Or if you can't cycle the port just eject and reinsert the device.
> 
> If you do the steps above, then you will usually find that whatever formatting issue you were having goes away.
> 
> It should be pointed out that, obviously, Rufus does zero the partition tables (and a few more sectors just to be safe) before it repartitions and reformats a drive, but as I pointed out, it does appear that Windows was never really designed for on-the-fly changes to partition data, so, even though we apply this and pretty much all the tricks in the book we can think of to tell Windows that it should refresh its vision of the drive layout, the only consistent way we found to make it do that is to make it actively disconnect and reconnect the device (which we can't really automate, even on Windows 8 or later, as a USB port cycle can take up to 30 seconds, and, as I mentioned, disable + enable of a device can lead to that device remaining in a "zombie state").
> 
> So if you are getting errors, try the zeroing + cycle trick described above, as it will probably help.

_Originally posted by @pbatard in https://github.com/pbatard/rufus/issues/1319#issuecomment-496481875_

**Comment by Cro-Magnon28** [comment]
Sir?
How exactly this step to be applied?

**Comment by Cro-Magnon28** [comment]
Sir @pbatard can you help me?

Rufus x86 v3.10.1647
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'USB2.0 Flash Disk USB Device' (1221:3234)
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 2039, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00193820
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 15.6 GB (16776167424 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: '02_17_2019'
  Size: 10.6 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.esd (version 0.14.0+)
Using image: Windows AllinOne.iso (10.6 GB)
Checking for Rufus updates...
Network is unavailable: Internet has not be initialized.
Updates: Unable to connect to the internet

Format operation started
Requesting disk access...
Will use 'E:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive1':
● Partition 1 (offset: 1048576, size: 15.6 GB)
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Bad Blocks: Checking from block 0 to 127999 (1 block = 128 KB)
Bad Blocks: Using offset 58702 for fake device check
Bad Blocks: Writing test pattern 0x00
Bad Blocks: Reading and comparing
Bad Blocks: 8115
Bad Blocks: 8116
Bad Blocks: 8117
Bad Blocks: 8118
Bad Blocks: 8119
Bad Blocks: 8120
Bad Blocks: 8121
Bad Blocks: 8122
Bad Blocks: 8123
Bad Blocks: 8124
Bad Blocks: 8125
Bad Blocks: 8126
Bad Blocks: 8127
Bad Blocks: 8128
Bad Blocks: 8129
Bad Blocks: 8130
Bad Blocks: 8131
Bad Blocks: 8132
Bad Blocks: 8133
Bad Blocks: 8134
Bad Blocks: 8135
Bad Blocks: 8136
Bad Blocks: 8137
Bad Blocks: 8138
Bad Blocks: 8139
Bad Blocks: 8140
Bad Blocks: 8141
Bad Blocks: 8142
Bad Blocks: 8143
Bad Blocks: 8144
Bad Blocks: 8145
Bad Blocks: 8146
Bad Blocks: 8147
Bad Blocks: 8148
Bad Blocks: 8149
Bad Blocks: 8150
Bad Blocks: 8151
Bad Blocks: 8152
Bad Blocks: 8153
Bad Blocks: 8154
Bad Blocks: 8155
Bad Blocks: 8156
Bad Blocks: 8157
Bad Blocks: 8158
Bad Blocks: 8159
Bad Blocks: 8160
Bad Blocks: 8161
Bad Blocks: 8162
Bad Blocks: 8163
Bad Blocks: 8164
Bad Blocks: 8165
Bad Blocks: 8166
Bad Blocks: 8167
Bad Blocks: 8168
Bad Blocks: 8169
Bad Blocks: 8170
Bad Blocks: 8171
Bad Blocks: 8172
Bad Blocks: 8173
Bad Blocks: 8174
Bad Blocks: 8175
Bad Blocks: 8176
Bad Blocks: 8177
Bad Blocks: 8178
Bad Blocks: 8179
Bad Blocks: 8180
Bad Blocks: 8181
Bad Blocks: 8182
Bad Blocks: 8183
Bad Blocks: 8184
Bad Blocks: 8185
Bad Blocks: 8186
Bad Blocks: 8187
Bad Blocks: 8188
Bad Blocks: 8189
Bad Blocks: 8190
Bad Blocks: 8191
Bad Blocks: 8192
Bad Blocks: 8193
Bad Blocks: 8194
Bad Blocks: 8195
Bad Blocks: 8196
Bad Blocks: 8197
Bad Blocks: 8198
Bad Blocks: 8199
Bad Blocks: 8200
Bad Blocks: 8201
Bad Blocks: 8202
Bad Blocks: 8203
Bad Blocks: 8204
Bad Blocks: 8205
Bad Blocks: 8206
Bad Blocks: 8207
Bad Blocks: 8208
Bad Blocks: 8209
Bad Blocks: 8210
Bad Blocks: 8211
Bad Blocks: 8212
Bad Blocks: 8213
Bad Blocks: 8214
Bad Blocks: 8215
Bad Blocks: 8216
Bad Blocks: 8217
Bad Blocks: 8218
Bad Blocks: 8219
Bad Blocks: 8220
Bad Blocks: 8221
Bad Blocks: 8222
Bad Blocks: 8223
Bad Blocks: 8224
Bad Blocks: 8225
Bad Blocks: 8226
Bad Blocks: 8227
Bad Blocks: 8228
Bad Blocks: 8229
Bad Blocks: 8230
Bad Blocks: 8231
Bad Blocks: 8232
Bad Blocks: 8233
Bad Blocks: 8234
Bad Blocks: 8235
Bad Blocks: 8236
Bad Blocks: 8237
Bad Blocks: 8238
Bad Blocks: 8239
Bad Blocks: 8240
Bad Blocks: 8241
Bad Blocks: 8242
Bad Blocks: 8243
Bad Blocks: 8244
Bad Blocks: 8245
Bad Blocks: 8246
Bad Blocks: 8247
Bad Blocks: 8248
Bad Blocks: 8249
Bad Blocks: 8250
Bad Blocks: 8251
Bad Blocks: 8252
Bad Blocks: 8253
Bad Blocks: 8254
Bad Blocks: 8255
Bad Blocks: 8256
Bad Blocks: 8257
Bad Blocks: 8258
Bad Blocks: 8259
Bad Blocks: 8260
Bad Blocks: 8261
Bad Blocks: 8262
Bad Blocks: 8263
Bad Blocks: 8264
Bad Blocks: 8265
Bad Blocks: 8266
Bad Blocks: 8267
Bad Blocks: 8268
Bad Blocks: 8269
Bad Blocks: 8270
Bad Blocks: 8271
Bad Blocks: 8272
Bad Blocks: 8273
Bad Blocks: 8274
Bad Blocks: 8275
Bad Blocks: 8276
Bad Blocks: 8277
Bad Blocks: 8278
Bad Blocks: 8279
Bad Blocks: 8280
Bad Blocks: 8281
Bad Blocks: 8282
Bad Blocks: 8283
Bad Blocks: 8284
Bad Blocks: 8285
Bad Blocks: 8286
Bad Blocks: 8287
Bad Blocks: 8288
Bad Blocks: 8289
Bad Blocks: 8290
Bad Blocks: 8291
Bad Blocks: 8292
Bad Blocks: 8293
Bad Blocks: 8294
Bad Blocks: 8295
Bad Blocks: 8296
Bad Blocks: 8297
Bad Blocks: 8298
Bad Blocks: 8299
Bad Blocks: 8300
Bad Blocks: 8301
Bad Blocks: 8302
Bad Blocks: 8303
Bad Blocks: 8304
Bad Blocks: 8305
Bad Blocks: 8306
Bad Blocks: 8307
Bad Blocks: 8308
Bad Blocks: 8309
Bad Blocks: 8310
Bad Blocks: 8311
Bad Blocks: 8312
Bad Blocks: 8313
Bad Blocks: 8314
Bad Blocks: 8315
Bad Blocks: 8316
Bad Blocks: 8317
Bad Blocks: 8318
Bad Blocks: 8319
Bad Blocks: 8320
Bad Blocks: 8321
Bad Blocks: 8322
Bad Blocks: 8323
Bad Blocks: 8324
Bad Blocks: 8325
Bad Blocks: 8326
Bad Blocks: 8327
Bad Blocks: 8328
Bad Blocks: 8329
Bad Blocks: 8330
Bad Blocks: 8331
Bad Blocks: 8332
Bad Blocks: 8333
Bad Blocks: 8334
Bad Blocks: 8335
Bad Blocks: 8336
Bad Blocks: 8337
Bad Blocks: 8338
Bad Blocks: 8339
Bad Blocks: 8340
Bad Blocks: 8341
Bad Blocks: 8342
Bad Blocks: 8343
Bad Blocks: 8344
Bad Blocks: 8345
Bad Blocks: 8346
Bad Blocks: 8347
Bad Blocks: 8348
Bad Blocks: 8349
Bad Blocks: 8350
Bad Blocks: 8351
Bad Blocks: 8352
Bad Blocks: 8353
Bad Blocks: 8354
Bad Blocks: 8355
Bad Blocks: 8356
Bad Blocks: 8357
Bad Blocks: 8358
Bad Blocks: 8359
Bad Blocks: 8360
Bad Blocks: 8361
Bad Blocks: 8362
Bad Blocks: 8363
Bad Blocks: 8364
Bad Blocks: 8365
Bad Blocks: 8366
Bad Blocks: 8367
Bad Blocks: 8368
Bad Blocks: 8369
Bad Blocks: 8370
Bad Blocks: 8371
Bad Blocks: 8372
Bad Blocks: 8373
Bad Blocks: 8374
Bad Blocks: 8375
Bad Blocks: 8376
Bad Blocks: 8377
Bad Blocks: 8378
Bad Blocks: 8379
Bad Blocks: 8380
Bad Blocks: 8381
Bad Blocks: 8382
Bad Blocks: 8383
Too many bad blocks, aborting test
Bad Blocks: Check completed, 269 bad blocks found. (0/0/269 errors)
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
● Creating Main Data Partition (offset: 1048576, size: 15.6 GB)
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
[0x0000007E] The specified module could not be found. - Retrying...
[0x0000007E] The specified module could not be found. - Retrying...
[0x0000007E] The specified module could not be found. - Retrying...
[0x0000007E] The specified module could not be found. - Retrying...
Format error: Undetermined error while formatting.
Re-mounted volume as E: after error

Found USB 2.0 device 'USB2.0 Flash Disk USB Device' (1221:3234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 2039, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00893ED6
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 15.6 GB (16776167424 bytes)
  Start Sector: 2048, Boot: Yes
Found USB 2.0 device 'USB2.0 Flash Disk USB Device' (1221:3234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 2039, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00893ED6
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 15.6 GB (16776167424 bytes)
  Start Sector: 2048, Boot: Yes

**Comment by Cro-Magnon28** [comment]
Rufus x86 v3.10.1647
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found USB 2.0 device 'USB2.0 Flash Disk USB Device' (1221:3234)
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 2039, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00C06D66
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 15.6 GB (16776167424 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: '02_17_2019'
  Size: 10.6 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.esd (version 0.14.0+)
Using image: Windows AllinOne.iso (10.6 GB)

Format operation started
Requesting disk access...
Will use 'E:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive1':
● Partition 1 (offset: 1048576, size: 15.6 GB)
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
● Creating Main Data Partition (offset: 1048576, size: 15.6 GB)
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
[0x0000007E] The specified module could not be found. - Retrying...
[0x0000007E] The specified module could not be found. - Retrying...
[0x0000007E] The specified module could not be found. - Retrying...
[0x0000007E] The specified module could not be found. - Retrying...
Format error: Undetermined error while formatting.
Re-mounted volume as E: after error

Found USB 2.0 device 'USB2.0 Flash Disk USB Device' (1221:3234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 2039, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00D5A8B1
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 15.6 GB (16776167424 bytes)
  Start Sector: 2048, Boot: Yes
Found USB 2.0 device 'USB2.0 Flash Disk USB Device' (1221:3234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 2039, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00D5A8B1
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 15.6 GB (16776167424 bytes)
  Start Sector: 2048, Boot: Yes

**Comment by pbatard** [comment]
Your device has bad blocks, which means its flash memory is failing. It's a pure hardware issue. You need to use a different flash drive because this one is dead.

Also next time, please follow the check list.
