### ISSUE TITLE
workaround regarding UPX (requires no effort from dev.s)

### ISSUE THREAD

**Issue by eladkarako** [pbatard/rufus#1563]
I've made a workaround that does not require any effort from rufus-dev.s  
regarding providing an unupx-ed version of Rufus (without building it).

https://github.com/eladkarako/unupx_deep

it is related to https://github.com/pbatard/rufus/issues/1120 (and @JonnyTech might find it helpful too).

I hope someone else will find it useful.

**Comment by pbatard** [comment]
Or, as explained in #1120 you can just download and install the `.appx` version, which is not UPX compressed. No need to use third party tools.
