### ISSUE TITLE
I just wanted to say thanks

### ISSUE THREAD

**Issue by jaamak** [pbatard/rufus#1565]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Hi! 

I just wanted to say thank you. 

I needed a computer to work with spreadsheets, and remembered that I had an old Windows Vista from 2009, which had been stuffed into a cupboard since about 2015. Thanks to the instructions I was able to find here and there, I managed to set up an USB stick with Rufus 2.18, which thankfully works with this Windows version! Now I'm running Linux Mint in Live mode to test, how it works (like a charm). With this, I will save at least 450 euros, or at least will not have to spend it yet on a new laptop. 

If you could hint on the Rufus page, which version fits older Windows versions, it would be great. Not for me any more, but perhaps someone else might benefit. 

Wishing you a lovely midsummer!

Best regards
Jaana 

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Thanks for the post! 😄
