### ISSUE TITLE
Does Rufus support making ARM USB for Pro X?

### ISSUE THREAD

**Issue by PylotLight** [pbatard/rufus#1588]
Hey,

I didn't see anything identical to my question, but sorry if I missed something.
I seemingly bricked my Pro X, so just seeing if Rufus s﻿upports making a linux or Windows USB with ARM for imaging.

Cheers,
Lochy.

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Rufus supports ARM and ARM64 images of Operating Systems, including Windows or Linux images.

Especially, Rufus has been designed to detect ARM or ARM64 UEFI bootloaders for about as long as we've been supporting UEFI, and if your image contains a file that is larger than 4 GB, and therefore requires the use of our custom UEFI:NTFS bootloader to boot, you should know that UEFI:NTFS has full support for ARM and ARM64 systems.

We've also been providing ARM and ARM64 versions of Rufus (i.e. versions of Rufus that you can use on Windows ARM or Windows ARM64) for years now.

Now, whether the bootable ARM or ARM64 USB created by Rufus actually works with your ARM or ARM64 system is a question you will need to answer by yourself, as we simply don't have the resources to test every system on earth. But there is nothing in Rufus that will prevent it from booting an ARM or ARM64 system, on the contrary.
