### ISSUE TITLE
After Rufus prompt error, flash drive went unreachable and prompts "no media" error

### ISSUE THREAD

**Issue by smilhas** [pbatard/rufus#1589]
﻿Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.

Issue description
-----------------
I had a functioning Kingston Flash Drive of 16 GB. I tried to create a bootable usb for Ubuntu 20.04 (I followed the steps on Ubuntu's page). When it was almost 80% done, Rufus prompt an error message. After that I closed Rufus and since then my Flash Drive is totally unreachable, with a "no media" error. I tried: 
- Disk Management
- MiniTool Partition Wizard
- chkdsk & DISKPART on cmd

Any recommendation?

PS: Thank you very much for your software!

Log
---
```
Rufus x86 v3.11.1678
Windows version: Windows 10 64-bit (Build 19041.388)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Processing Hub 1:
  Hub[1] = '\\?\usb#root_hub20#4&156a8c6a&0#{69c6562e-8579-4652-a57b-96ad56dbf7bb}'
  Found ID[061]: USB\VID_8087&PID_8000\5&1C87A7E&0&1
Processing Hub 2:
  Hub[2] = '\\?\usb#vid_8087&pid_8000#5&1c87a7e&0&1#{69c6562e-8579-4652-a57b-96ad56dbf7bb}'
  Found ID[249]: USB\VID_046D&PID_
  Found ID[128]: USB\VID_13FE&PID_
Processing Hub 3:
  Hub[3] = '\\?\usb#root_hub30#4&8f56b2a&0&0#{69c6562e-8579-4652-a57b-96ad56dbf7bb}'
  Found ID[077]: USB\VID_0489&PID_E069\1.0
  Found ID[146]: USB\VID_0BDA&PID_
  Found ID[147]: USB\VID_0457&PID_
  USB\VID_13FE&PID_
Processing 'SCSI' device:
  Hardware ID: 'SCSI\Disk________KINGSTON_SA400'
Found non-USB non-removable device 'KINGSTON SA400' => Eliminated
Processing 'USBSTOR' device:
  Hardware ID: 'USBSTOR\Disk________USB_DISK_2.0____PMAP'
  Matched with ID[128]: USB\VID_13FE&PID_
  Matched with Hub[2]: '\\?\usb#vid_8087&pid_
**Found USB 2.0 device 'USB DISK 2.0 USB Device' (13FE:4300)
Device eliminated because it appears to contain no media**
0 devices found
```

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Rufus_cant_detectformat_my_drive_and_reports_that_it_is_readonly_or_contains_no_media
