### ISSUE TITLE
No option to create to create a Windows To Go flash drive when using a 32bit Windows 7 ISO.

### ISSUE THREAD

**Issue by okh-mzny** [pbatard/rufus#1590]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [NA] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [NA] I also tried one or more of the following:
  - [NA] Using a different USB drive.
  - [NA] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
When selecting any Windows 7 x86 ISO, Rufus does not give the option to create a Windows To Go flash drive.
The FAQ states that creating Windows 7 To Go drives is supported, but does talk about 32bit vs 64bit at all.

Log
---
```
Rufus x86 v3.11.1678
Windows version: Windows 10 64-bit (Build 14393)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found non-USB removable device 'WDC WD1002FBYS' => Eliminated
Found non-USB removable device 'WDC WD20EZRZ' => Eliminated
Found USB 2.0 device 'JetFlash Transcend 32GB USB Device' (8564:1000)
NOTE: This device is a USB 3.0 device operating at lower speed...
Could not get device number for device \\.\A:: [0x00000001] Incorrect function.
Could not get device number for device \\.\A:: [0x00000001] Incorrect function.
Found non-USB removable device 'Samsung SSD 750 EVO 250GB' => Eliminated
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3840, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 29.4 GB (31590449152 bytes)
  Start Sector: 2048, Boot: No
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'GRMCPRFRER_EN_DVD'
  Size: 2.3 GB (Projected)
  Uses: Bootmgr (BIOS only)
  Uses: Install.wim (version 0.13.1)
Using image: en_windows_7_professional_x86_dvd_x15-65804.iso (2.3 GB)

```

**Comment by pbatard** [comment]
From the [relevant entry of the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Windows_To_Go):

> As of Rufus 2.0, Windows To Go is only available if you are running Rufus on Windows 8 or later. If you are running Rufus on Windows 7 or earlier, the option will not be offered (though you can create Windows To Go drives from Windows 7 ISOs if you run Rufus on Windows 8 or later).

And, no, regardless of what other utilities might do, I am not going to add Windows To Go support for an Operating System that has been obsoleted by its manufacturer. If you want to create Windows To Go drives in Rufus, then you need to run Rufus on Windows 8 or later.
