### ISSUE TITLE
please add a refresh button that did the same action as Alt+F (I cannot memorise each shortcut in each application)

### ISSUE THREAD

**Issue by droumanet** [pbatard/rufus#1596]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
The disk (peripheric) field still always empty. The only way to use it, is to find the shortcut Alt+F : just enhance the application with a button for that. Thanks.

Log
---
```
<FULL LOG>Rufus x86 v3.10.1647 (Portable)
Windows version: Windows 10 64-bit (Build 18363.959)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x040C (fr-FR)
Will use default UI locale 0x040C
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'fr-FR'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
0 devices found
Found USB 2.0 device 'General UDisk USB Device' (ABCD:1234)
Using autorun.inf label for drive F: 'Linux Mint 19.3 Xfce 64-bit'
Device eliminated because it was detected as a Hard Drive (score 3 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
0 devices found
Found USB 2.0 device 'General UDisk USB Device' (ABCD:1234)
Using autorun.inf label for drive F: 'Linux Mint 19.3 Xfce 64-bit'
Device eliminated because it was detected as a Hard Drive (score 3 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
0 devices found
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Detected Grub version: 2.04~manjaro
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'MANJARO_XFCE_200'
  Size: 2.6 Go (Projected)
  Uses: GRUB2
  Uses: EFI
Note: ISO mode will be disabled because this ISOHybrid is not compatible with ISO boot.
Using image: manjaro-xfce-20.0-200426-linux56.iso (2.6 Go)
Checking for Rufus updates...
Checking release channel...
New release version found!
Found USB 2.0 device 'General UDisk USB Device' (ABCD:1234)
Using autorun.inf label for drive F: 'Linux Mint 19.3 Xfce 64-bit'
1 device found
Disk type: FIXED, Disk size: 16 Go, Sector size: 512 bytes
Cylinders: 1937, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x013D6887
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15937306624 bytes)
  Start Sector: 2048, Boot: Yes
```

**Comment by pbatard** [comment]
<kbd>Alt</kbd>-<kbd>F</kbd> is only one way to do it.
The other way is through the UI, as explained [in this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected).

You don't have to memorize a shortcut if you don't want to.
