### ISSUE TITLE
usb to iso

### ISSUE THREAD

**Issue by MAiNPRoToCoL** [pbatard/rufus#1607]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] Everything else is not applicable

Issue description
-----------------
That's right! From USB to ISO! Stick yer properly bootable USB, run Rufus, click something to turn that USB into an ISO!

It'd be a wonderful enhancement! Related to what Rufus currently does. There is nothing like this idea currently. Many tools create a bootable USB but what if the computer can't boot to USB. 

Log
---
```
<Not applicable>
```

**Comment by pbatard** [comment]
> There is nothing like this idea currently.

There is. Just save your existing bootable drive to a VHD, and rufus will happily be able to use that image, like you would use an ISO, to recreate it. See the [relevant FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Saving_an_existing_drive_to_VHD).

And just so you know the ISO ⟷ USB is a **conversion** process that is a lot more complex than it looks (if it wasn't, an application like Rufus would have no reason to exist), and there is a lot of **dedicated** code, that took a long time to write to ensure that ISO → USB works. Considering that there is little demand (yes, that is how it is, regardless of how badly **you** think you and others need it) for USB → ISO, and that it would require me A LOT of time to add and be limited/flawed in many ways, I have absolutely no plans to add that when you can just save to VHD. If anything, I'll provably add save to [Full Flash Update format](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-windows-using-full-flash-update--ffu) or `.vhdx` at some stage in the future, at it produces smaller images, but I if you need USB → ISO, you will just have to use a different application.
