### ISSUE TITLE
RUFUS DD Image Write failed at 64.1% with flash drive becoming undetectable/unsuble by both Rufus and Windows Disk Managemment

### ISSUE THREAD

**Issue by itz-jameel** [pbatard/rufus#1610]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I am trying to burn a Kali 2020.3 to a flash drive using DD write option as usual ISO write isn't booting correctly. However, the write failed at 64.1% with my flash drive becoming undetectable by both windows and Rufus. The drive does not appear in Windows Disk Management or Command Line DiskPart tool. On checking device manager, it appears as an "Unknown USB device (Device Descriptor Request Failed.)
The logs I have below are not the ones when the write failed happened as Rufus wasn't responding upon failure and then it finally crashed. So I just restarted Rufus with the Flash Plugged in and  while "List USB Hard Drives" is checked. It seemed to kind of picked the flash as a DD image from the logs though but couldn't get a way to access it or reformat it.
Note that this is the second flash drive that this issue is happening to. So basically I now have two unusable flash drives as a result of this.

Log
---
```
Rufus x86 v3.11.1678 (Portable)
Windows version: Windows 10 64-bit (Build 14393.105)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
0 devices found
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.04/20191223 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Kali Linux amd64 1'
  Size: 3.7 GB (Projected)
  Has a >64 chars filename
  Uses: Syslinux/Isolinux v6.04
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system limitations.
  Because of this, some features from this image may not work...
Using image: kali-linux-2020.3-installer-amd64.iso (3.7 GB)
0 devices found
```

**Comment by pbatard** [comment]
The flash memory used in USB flash drives is a lot less reliable than people realize, so failures while copying data can and do happen independently of the application being used (you can have a look at the people swearing off Etcher for having "destroyed their media", whereas it's just the nature of flash based media to fail during usage). And yes, if you are unlucky, this can happen repeatedly, though, if that is the case, I would also seriously investigate as to whether you may not have been sold "fake drives", i.e. drives that have had their firmware maliciously modified to present more capacity than they actually have, in order for unscrupulous sellers to sell them for a high profit margin, even though they know that these drives will fail as soon as the user writes beyond the actual capacity of the flash memory.

I'm afraid that, no, it is not possible for an application like Rufus or Etcher to destroy drives on their own, even if they have a major bug. The nature or USB read and write access as well as the abstraction that the Operating System makes of disk media simply makes this impossible, as the only thing an application can see is a set of blocks, and there are **no** blocks that the Operating System sees from a USB flash based media that are more "special" than others (meaning that you can write complete garbage to any of the data blocks that the OS sees, and you will **always** be able to write valid data back again, even if those blocks contains partition data or critical file system information).

All in all, this means that there's literally I can do for you here. If you are unable to recover your media, then it means that your media simply happened to **coincidentally** fail while you were using Rufus, and you will simply have to purchase a new one. And if you have been experiencing multiple failures, you may also want to ensure that you purchase your media from reputable sellers and test them for bad blocks.

I should also point out that, in some rare cases, failures may also be incurred by a buggy firmware, but I really only know one example of that (PNY 16GB Retract USB), and all in all, it is a lot more likely that you are going to purchase a "fake" drive (as these are unfortunately a lot more common than people realize, especially for cheap drives) than you would purchase an original one with a buggy firmware.

You may also want to read [this relevant FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive) as well as google for complaints of other software than Rufus "destroying" flash drives, if you need more convincing than, despite what you may be inclined to think, Rufus simply does not have the capability to destroy a flash drive and that, if you happened to end up with a failed drive, the failure would have happened regardless of the software being used.
