### ISSUE TITLE
[Question] Release linux version?

### ISSUE THREAD

**Issue by VaGNaroK** [pbatard/rufus#1618]
Do you have any intention of launching binaries for linux? an appimage for example to be compatible with several distros or flatpak? Why having to dual boot just to be able to use this tool is a headache.

**Comment by pbatard** [comment]
The checklist is **NOT** optional. If you had followed it, you would have found the [answer to your question](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS).

If someone asks you to do something before you ask a question, it's not to annoy you, but to make sure that you don't end up asking something that gets asked OVER and OVER and OVER again.

**Comment by rzr** [comment]
What about supporting ReactOS too  or wine ?

**Comment by pbatard** [comment]
It's up to ReactOS and/or Wine to provide the Windows APIs Rufus needs to work, not the other way around. I can't magically work around **missing** APIs (such as device enumeration or low level disk access or native Windows file systems) and pop out some kind of replacement of thin air &mdash; That's just not how it works.

If you want Rufus to work on ReactOS or Wine, then you have to ask their developers to provide the APIs it needs to make it so. As long as these API's don't exist or aren't properly implemented, you're pretty much asking me the same as creating a pure Linux version of Rufus, which isn't going to happen.
