### ISSUE TITLE
Injection of simple, small text file into ISO file before USB creation possible?

### ISSUE THREAD

**Issue by pstein** [pbatard/rufus#1622]
Is it possible to inject a small text file into the ISO file before Rufus will create the actual USB flash drive?

The text file should be later automatically copied by Rufus to the root directory of the USB flash drive.

Or does adding a new file destroy some automatic hash value comparison?

If it is possible:  Into exactly which directory should I add the new text file ....
...for Legacy BIOS-based ISOs
...for UEFI-based ISOs

?

Peter

**Comment by pbatard** [comment]
Injecting a new file is no issue. But you don't really need Rufus to do that, you can add it yourself afterwards.

There's a new non-publicized feature in Rufus 3.11 that allows you to inject additional data (when copying in ISO mode, **NOT** dd mode) from a zip file.

If you press <kbd>Ctrl</kbd>-<kbd>Select</kbd> you can select a zip file and its content will be extracted by Rufus on top of the ISO content, so, if you zip the text file you want and use <kbd>Ctrl</kbd>-<kbd>Select</kbd>, it will be added by Rufus. But, no, there is currently no feature allowing you to select the zip file automatically (i.e. you will have to use <kbd>Ctrl</kbd>-<kbd>Select</kbd> every time), and any plans to do something like that will happen a lot more slowly than you expect (i.e. it'll probably be months or years, before you see such a feature if I ever add it).

As I believe I have answered your question, I will close this issue.
