### ISSUE TITLE
USB Damaged after Rufus with Ubuntu 20.04

### ISSUE THREAD

**Issue by jok3rg** [pbatard/rufus#1625]
The instalation process stopped at 85% more or less, after that i tried to format USB in Windows and Mac OS, without luck.
Tried with windows option, diskpart, disk utility in Mac and from mac terminal with no luck.
How can i fix the usb? If i plug the usb, its shows in Windows and Mac (wont load Finder or Utility Disk eternal loading)

**Comment by pbatard** [comment]
> The instalation process stopped at 85% more or less,

This is indicative of a hardware failure. Your drive failed, therefore Rufus wasn't able to write to it past the 85% mark, as opposed to what you are assuming of Rufus having damaged your drive. If your drive becomes defective (and you should know that the flash memory used in USB drives is a lot less reliable than people think), then, of course, an application that is attempting to write a large chunck of data to it will fail. But this has nothing to do with the application.

> How can i fix the usb?

It's most likely dead. You can try a bad blocks check in Rufus (as suggested by the check list that you chose to disregards) or with any other application that allows for block level validation, but it's unlikely that you'll be able to recover it.

**Comment by jok3rg** [comment]
Rufus log, my drive is not defective, its an Sandisk Ultra and i have been using it for a long time with 0 fails, i just used it yesterday with Etcher in Mac OS and worked fine, it just crashed this morning with Rufus and now is dead.

`Rufus x86 v3.11.1678
Windows version: Windows 10 64-bit (Build 19041.508)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0C0A (es-ES)
Will use default UI locale 0x0C0A
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'es-ES'
0 devices found
Checking for Rufus updates...
Checking release channel...
No new release version found.
Found USB 3.0 device 'SanDisk Ultra USB Device' (0781:5581)
1 device found
Disk type: Removable, Disk size: 64 GB, Sector size: 512 bytes
Cylinders: 7789, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x97DEC749
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 59.7 GB (64066945024 bytes)
  Start Sector: 2048, Boot: Yes
1 device found
Disk type: Removable, Disk size: 64 GB, Sector size: 512 bytes
Cylinders: 7789, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x97DEC749
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 59.7 GB (64066945024 bytes)
  Start Sector: 2048, Boot: Yes
1 device found
Disk type: Removable, Disk size: 64 GB, Sector size: 512 bytes
Cylinders: 7789, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x97DEC749
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 59.7 GB (64066945024 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.03/20171017 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Ubuntu 18.04.5 LTS amd64'
  Size: 2 GB (Projected)
  Has a >64 chars filename
  Uses: Syslinux/Isolinux v6.03
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system limitations.
  Because of this, some features from this image may not work...
Using image: ubuntu-18.04.5-desktop-amd64.iso (2 GB)
Downloading https://rufus.ie/files/syslinux-6.03/20171017/ldlinux.sys
Unable to access file: 404
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.03/ldlinux.sys
File length: 67.0 KB
Successfully downloaded 'ldlinux.sys'
Download signature is valid ✓
Downloading https://rufus.ie/files/syslinux-6.03/20171017/ldlinux.bss
Unable to access file: 404
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.03/ldlinux.bss
File length: 512 bytes
Successfully downloaded 'ldlinux.bss'
Download signature is valid ✓

Format operation started
Requesting disk access...
Will use 'D:' as volume mountpoint
Deleting partitions (puede tardar un rato)...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive2':
● Partition 1 (offset: 1048576, size: 59.7 GB)
Opened \\.\PhysicalDrive2 for exclusive write access
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Syslinux Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 2048 sectors
Initializing disk...
Bad Blocks: Checking from block 0 to 488799 (1 block = 128 KB)
Bad Blocks: Using offset 82545 for fake device check
Bad Blocks: Writing test pattern 0x00
write_sectors: Write error Windows error code 0x0000045D (FormatMessage error code 0x00003AFC)
  StartSector: 0x00000000, nSectors: 0x40, SectorSize: 0x20000
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 0
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000001, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 1
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000002, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 2
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000003, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 3
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000004, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 4
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000005, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 5
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000006, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 6
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000007, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 7
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000008, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 8
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000009, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 9
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000000a, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 10
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000000b, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 11
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000000c, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 12
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000000d, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 13
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000000e, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 14
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000000f, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 15
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000010, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 16
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000011, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 17
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000012, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 18
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000013, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 19
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000014, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 20
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000015, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 21
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000016, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 22
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000017, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 23
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000018, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 24
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000019, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 25
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000001a, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 26
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000001b, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 27
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000001c, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 28
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000001d, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 29
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000001e, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 30
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000001f, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 31
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000020, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 32
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000021, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 33
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000022, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 34
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000023, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 35
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000024, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 36
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000025, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 37
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000026, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 38
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000027, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 39
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000028, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 40
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000029, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 41
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000002a, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 42
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000002b, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 43
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000002c, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 44
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000002d, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 45
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000002e, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 46
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000002f, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 47
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000030, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 48
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000031, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 49
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000032, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 50
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000033, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 51
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000034, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 52
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000035, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 53
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000036, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 54
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000037, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 55
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000038, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 56
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000039, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 57
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000003a, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 58
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000003b, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 59
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000003c, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 60
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000003d, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 61
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000003e, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 62
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000003f, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 63
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000040, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 64
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000041, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 65
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000042, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 66
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000043, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 67
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000044, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 68
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000045, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 69
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000046, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 70
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000047, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 71
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000048, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 72
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000049, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 73
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000004a, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 74
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000004b, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 75
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000004c, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 76
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000004d, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 77
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000004e, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 78
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000004f, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 79
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000050, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 80
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000051, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 81
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000052, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 82
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000053, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 83
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000054, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 84
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000055, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 85
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000056, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 86
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000057, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 87
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000058, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 88
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000059, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 89
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000005a, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 90
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000005b, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 91
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000005c, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 92
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000005d, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 93
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000005e, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 94
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000005f, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 95
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000060, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 96
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000061, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 97
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000062, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 98
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000063, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 99
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000064, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 100
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000065, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 101
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000066, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 102
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000067, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 103
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000068, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 104
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x00000069, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 105
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000006a, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 106
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000006b, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 107
write_sectors: Write error Windows error code 0x00000079 (FormatMessage error code 0x00003B01)
  StartSector: 0x0000006c, nSectors: 0x1, SectorSize: 0x20000
Bad Blocks: 108
`

**Comment by pbatard** [comment]
The bad block test shows that your hardware __is__ defective.

And yes, things tend to work until the day they break. But that doesn't mean that the last application you used was responsible for it. If you had happened to experience this failure while copying a file in Windows File Explorer, I doubt you'd be contacting Microsoft to tell them that you think File Explorer broke your drive. Well, the thing is, despite what you might think, Rufus is actually as safe as using File Explorer, so I can guarantee that, whatever you think might have happened, Rufus was not the cause of your hardware failure.

For more on this, please see [this relevant FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive).
