### ISSUE TITLE
Allowance of not formatting the usb drive

### ISSUE THREAD

**Issue by lauris0910** [pbatard/rufus#1648]
Hello, because the MiniTool Partition Wizard helps with NTFS formatting, could formatting be disabled in Rufus or atleast be optional? This can help with the pepole that cant format it with cmd or windows explorer and that use this tool to add ISO without formatting the whole usb. If its not possible, i will accept my fail and try to find any other ways to do it.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Why_does_Rufus_need_to_delete_all_partitionsvolumes_when_creating_a_drive
