### ISSUE TITLE
Windows 7 (Windows to Go)

### ISSUE THREAD

**Issue by PaulNevada** [pbatard/rufus#1650]
Hello!
Is it possible to have a working usb-drive with that OS via this Tool?
PS: I've tried a couple of my images for Win7 and Rufus 3.11 - was getting my OS breaking its first-time booting... Made it as BIOS-UEFI one... Any help, please...

**Comment by pbatard** [comment]
Sorry, but just like Microsoft, I no longer support Windows 7. If you use Rufus with Windows 7 and it works, great. If not, I'm afraid that you are on your own.

**Comment by PaulNevada** [comment]
Hm-m-m, thanks for answering!
