### ISSUE TITLE
rufos dont create vmlinuz

### ISSUE THREAD

**Issue by brunothedev** [pbatard/rufus#1655]
﻿
i try all,exec with admin,uninstall my avira and windows defender,and dont create vmlinuz

**Comment by pbatard** [comment]
Not enough data provided. As mentioned in the checklist that you __chose__ to ignore, if you don't provide the required data, I will close your request without further explanation.

**Comment by brunothedev** [comment]
> Não foram fornecidos dados suficientes. Conforme mencionado na lista de verificação que você **optou** por ignorar, se você não fornecer os dados necessários, encerrarei sua solicitação sem maiores explicações.

is all infos
