### ISSUE TITLE
GB, MB, KB - small fix for Russian Language (maybe, not only)

### ISSUE THREAD

**Issue by PaulNevada** [pbatard/rufus#1660]
Hello, Author!
In Russian it is Gb, Mb, Kb and that's not right... Maybe, not with one language only... Thank you very much!

**Comment by pbatard** [comment]
So you're saying the Russian abbreviation for GigaByte should be Gb and not GB?
If that is the case, what is the Russian abbreviation for Gigabit (as in network speed for instance)?

**Comment by PaulNevada** [comment]
No! It is fow now is incorrect - Gb, Mb, Kb... :)))

**Comment by PaulNevada** [comment]
When a flash drive is selected, in English it appers ok - 64 GB, but in Russian (haven't checked other languages) it shows up 64 Gb and that is wrong...

**Comment by pbatard** [comment]
Hmm, this is what is being used right now: https://github.com/pbatard/rufus/blob/master/res/loc/po/ru-RU.po#L287-L323
So I'm not seeing `Gb` being used but `Гб`. Is that not correct?

Or is it for the website? But there too I am seeing things like `Мб` being used.

Here's what I see in Rufus:

![Image2](https://user-images.githubusercontent.com/1206968/101427643-3019b200-38f7-11eb-8ed9-e5f47ad76070.png)

And here's what I see for the website:

![Image1](https://user-images.githubusercontent.com/1206968/101427678-3a3bb080-38f7-11eb-8248-ed5627128775.png)

So where exactly are you seeing `Mb` or `Gb`? And are you sure it isn't the _potential fonts missing on your side_ (which is an issue on **your** computer that has nothing to do with either Rufus or the web site) that is the issue?

**Comment by PaulNevada** [comment]
By Gb I meant Russian Гб...

**Comment by pbatard** [comment]
So what should it be???

**Comment by PaulNevada** [comment]
> So what should it be???

Should be ГБ, МБ, КБ. The second letter should be high as it is in English.

**Comment by pbatard** [comment]
Okay. So `Б` is the capitalization of `б` in Russian. Okay, I'll try to fix that when I get a chance.

**Comment by PaulNevada** [comment]
Yes. Exactly. Thanks!

**Comment by maykimayk** [comment]
dil programı ekleme
