### ISSUE TITLE
Ubuntu MATE 20.04.1 LTS persistent installation won’t boot the second time

### ISSUE THREAD

**Issue by TinaRussell** [pbatard/rufus#1661]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image. (Note: I downloaded the image manually, and pointed Rufus to it. Just now I ran `sha256sum` and found that the hash of the image I used indeed matches the corresponding hash found on the Ubuntu MATE download page.)

Issue description
-----------------
So, I used an official Ubuntu MATE 20.04.1 LTS amd64 ISO to create a persistent image with 12 GB of partition space. (I don’t have a log, since, well, nothing went wrong in Rufus itself, as far as I knew at the time.) I rebooted, everything worked, and I was running Ubuntu MATE off USB. But just to make sure persistence was working, I created a file on the desktop (a blank file called `meow.meow`) and then restarted. Now, booting from the USB stick (and I made sure, in the BIOS, that it was still booting off USB as before) only shows a blinking underscore; there isn’t even the usual “ISOLINUX blah blah” message you usually see, just a blinking cursor as though the system is _just about_ to boot and never does.

Anyway, I’m not sure if it’s a problem with Rufus or with Ubuntu MATE, and I don’t really have time to troubleshoot it (dammit, I’ve spent too much time trying to get persistent USB Linux working already, and nothing flamin’ works), but I thought I should make note of it in case there’s a systemic problem.

Log
---
[N/A]

**Comment by pbatard** [comment]
Just tested Ubuntu MATE 20.04.1 LTS with 10 GB persistence on an Intel NUC in UEFI mode, and saw no issue. I was able to reboot without trouble and the files/folders created on the desktop were still present after reboot.

This indicates that this is an issue with your environment, that is unlikely to have anything to do with Rufus. I will therefore close it.
