### ISSUE TITLE
Rufus for linux Support

### ISSUE THREAD

**Issue by WitherCubes** [pbatard/rufus#1670]
Please give support for linux because I love Rufus, but want to use in linux

**Comment by pbatard** [comment]
Next time follow the checklist because if you had done so, you would have found [the answer to your SUPER FREQUENTLY ASKED QUESTION](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS).
