### ISSUE TITLE
Windows Setup Edition Configuration

### ISSUE THREAD

**Issue by pyasmani** [pbatard/rufus#1674]
The edition configuration (EI.cfg) file and the product ID (PID.txt) file are optional configuration files that you can use to specify the Windows® product key and the Windows edition during Windows installation. You can use these files to automate the product-key entry page in Windows Setup instead of using an answer file. If you use an EI.cfg file to differentiate volume license media, but you do not include a PID.txt file, the user receives a prompt for a product key to continue Windows Setup.
I would like to have this option available on Rufus configuration or just by default.

Thanks for this awesome software.

Here is the full aticle by Microsoft https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-edition-configuration-and-product-id-files--eicfg-and-pidtxt

**Comment by pbatard** [comment]
Hopefully the following will help:

1. Create a `.zip` file with any of the files you want to add (here `EI.cfg` and `PID.txt`)
2. Select your ISO in Rufus normally
3. Press <kbd>Ctrl</kbd>-<kbd>SELECT</kbd> in Rufus to select your `.zip` file
4. Create the media. The content from the `.zip` will be extracted on top of the one from the ISO.

As I expect that this should achieve what you need, I will close this issue.
