### ISSUE TITLE
Adding News Operation System

### ISSUE THREAD

**Issue by DemonRem** [pbatard/rufus#1681]
hey i wonder how i can add another windows or linux OS for example windows servers hmm 2003 2008 2012 etc
or any other kind of linux

**Comment by benjaminjacobreji** [comment]
Please read the FAQ in the Wiki.
[FAQ:Do you plan to port Rufus to Linux/MacOS/SomeotherOS](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS)

Have a great day :)

**Comment by pbatard** [comment]
If you're asking for multiboot the see https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiboot_support
