### ISSUE TITLE
You do not have permission to access the folder/usb

### ISSUE THREAD

**Issue by xXxDragonz1xXx** [pbatard/rufus#1693]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
I used Rufus to make my USB viewable but then I got the You do not have permission to access the folder error I pressed to continue and You have been denied access to this folder and then I said ok the USB I done idc but when I plugged another USB and tried to access it the same thing again (I had made it bootable months ago) I tried formatting it, done but the error still occurred
I plugged an External Hard Drive and I could access it
EDIT
I could Access both of the USBs in safe mode and I formatted them went back to normal but still the same error in both of them

**Comment by pbatard** [comment]
Did not follow the checklist and did not provide a log &rarr; Closed.
