### ISSUE TITLE
HDD list 0 devices 

### ISSUE THREAD

**Issue by gruianovac** [pbatard/rufus#1703]
i want support for HDD./ssd
USBs are becoming unreliable.  
(also support for partitions not full disks)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected

**Comment by pbatard** [comment]
Also https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_support_internal_HDDsSSDs
