### ISSUE TITLE
A disk read error occurred when booting from USB

### ISSUE THREAD

**Issue by Nikita-stepan0v** [pbatard/rufus#1708]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
A disk read error occurred when booting from USB

Log
---
```
Rufus x86 v3.13.1730 (Portable)
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0419 (ru-RU)
Will use default UI locale 0x0419
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'ru-RU'
Found VHD device 'Msft Virtual Disk SCSI Disk Device'
Removing C: from the list: This is the system disk!
Found USB 2.0 device 'JetFlash Transcend 8GB USB Device' (8564:1000)
1 device found
Disk type: Removable, Disk size: 7.6Гб, Sector size: 512 bytes
Cylinders: 929, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0007A9D5
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 7.1 GB (7643070464 bytes)
  Start Sector: 2048, Boot: Yes
Found VHD device 'Msft Virtual Disk SCSI Disk Device'
Removing C: from the list: This is the system disk!
Found USB 2.0 device 'JetFlash Transcend 8GB USB Device' (8564:1000)
1 device found
Disk type: Removable, Disk size: 7.6Гб, Sector size: 512 bytes
Cylinders: 929, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0007A9D5
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 7.1 GB (7643070464 bytes)
  Start Sector: 2048, Boot: Yes

```
[rufus.log](https://github.com/pbatard/rufus/files/6222565/rufus.log)

**Comment by pbatard** [comment]
Please follow the check list and run a bad blocks check on your media. As detailed by the check list, Rufus can perform that bad blocks check for you.

A disk read error usually indicates that your USB drive or the ISO you used have an issue, and it is therefore not something that Rufus can do anything about.

Also, if you encounter a problem when booting media created by Rufus, then your log should show the ISO you used and how you created the media. Without that information, it's next to impossible to help you.

**Comment by pbatard** [comment]
No update &rarr; Closing.
