### ISSUE TITLE
Not working with Manjaro

### ISSUE THREAD

**Issue by OrangeTurtle197** [pbatard/rufus#1710]
﻿

Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [X] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [X] I also tried one or more of the following:
  - [X] Using a different USB drive.
  - [X] Plugging the USB into a different port.
  - [X] Running Rufus on a different computer. (I don't own a separate computer that I am allowed administrative privileges on, other than my sibling's laptop, which I doubt they will let me use. My workaround was using VMware and Windows 8.1.)
- [X] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

Attempting to create a Manjaro Linux ISO seems to not work. The options are grayed out, and it only copies the bootloader (`E:\EFI\Boot\bootx64.efi`). Booting the drive doesn't work as the ASRock UEFI boot tool (as well as rEFInd) does not work.
Here's a screenshot from after the flash: 

![unknown 1](https://user-images.githubusercontent.com/45678161/113366065-030d6700-930d-11eb-9d6d-e0f4b1a74486.png)

Here's what the directory structure looks like: 
```
E:\>tree
Folder PATH listing for volume MISO_EFI
Volume serial number is F3B8-EFD5
E:.
└───efi
    └───boot
```
---------------------------------------

Log
---
```

Rufus x86 v3.13.1730 (Portable)
Windows version: Windows 10 64-bit (Build 19043.906)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found USB 2.0 device 'Verbatim STORE N GO USB Device' (18A5:0302)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Found USB 2.0 device 'FLASH Drive SM_USB20 USB Device' (090C:1000)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found UAS (USB 2.0) device 'PHD 3.0 Silicon-Power SCSI Disk Device' (174C:55AA)
NOTE: This device is a USB 3.0 device operating at lower speed...
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Device eliminated because it was detected as a Hard Drive (score 16 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
2 devices found
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Disk type: Removable, Disk size: 7.8GB, Sector size: 512 bytes
Cylinders: 950, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has an unknown Master Boot Record
Partition 2:
  Type: EFI FAT (0xef)
  Size: 4 MB (4194304 bytes)
  Start Sector: 5520424, Boot: No
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Detected Grub version: 2.04~22~manjaro
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'MANJARO_KDE_210'
  Size: 2.6 GB (Projected)
  Uses: GRUB2
  Uses: EFI
Note: ISO mode will be disabled because this ISOHybrid is not compatible with ISO boot.
Using image: manjaro-kde-21.0-210318-linux510.iso (2.6 GB)
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Detected Grub version: 2.04
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Kubuntu 20.10 amd64'
  Size: 2.5 GB (Projected)
  Has a >64 chars filename
  Uses: GRUB2
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system
  limitations. Because of this, some features from this image may not work...
Using image: kubuntu-20.10-desktop-amd64.iso (2.6 GB)
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Detected Grub version: 2.04~22~manjaro
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'MANJARO_KDE_210'
  Size: 2.6 GB (Projected)
  Uses: GRUB2
  Uses: EFI
Note: ISO mode will be disabled because this ISOHybrid is not compatible with ISO boot.
Using image: manjaro-kde-21.0-210318-linux510.iso (2.6 GB)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)

Format operation started
Requesting disk access...
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Will use 'E:' as volume mountpoint
Deleting partitions:
● Partition 1 (offset: 2826457088, size: 4 MB)
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Opened \\.\PhysicalDrive6 for exclusive write access
Requesting logical volume handle...
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Bad Blocks: Checking from block 0 to 59639 (1 block = 128 KB)
Bad Blocks: Using offset 71509 for fake device check
Bad Blocks: Writing test pattern 0x55
Bad Blocks: Reading and comparing
Bad Blocks: Check completed, 0 bad blocks found. (0/0/0 errors)
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Writing Image:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Remounted \\?\Volume{5aa02696-8ff9-11eb-89cb-24ee9afeb310}\ as E:

Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found USB 2.0 device 'Verbatim STORE N GO USB Device' (18A5:0302)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Found USB 2.0 device 'FLASH Drive SM_USB20 USB Device' (090C:1000)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found UAS (USB 2.0) device 'PHD 3.0 Silicon-Power SCSI Disk Device' (174C:55AA)
NOTE: This device is a USB 3.0 device operating at lower speed...
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Device eliminated because it was detected as a Hard Drive (score 16 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
2 devices found
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Disk type: Removable, Disk size: 7.8GB, Sector size: 512 bytes
Cylinders: 950, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has an unknown Master Boot Record
Partition 2:
  Type: EFI FAT (0xef)
  Size: 4 MB (4194304 bytes)
  Start Sector: 5520424, Boot: No
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found USB 2.0 device 'Verbatim STORE N GO USB Device' (18A5:0302)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Found USB 2.0 device 'FLASH Drive SM_USB20 USB Device' (090C:1000)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found UAS (USB 2.0) device 'PHD 3.0 Silicon-Power SCSI Disk Device' (174C:55AA)
NOTE: This device is a USB 3.0 device operating at lower speed...
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\D:' as it spans multiple disks (RAID?)
Device eliminated because it was detected as a Hard Drive (score 16 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
2 devices found
Ignoring volume '\\?\Volume{86631ba7-690f-11eb-9bf4-806e6f6e6963}' because it has more than one extent (RAID?)...
Disk type: Removable, Disk size: 7.8GB, Sector size: 512 bytes
Cylinders: 950, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has an unknown Master Boot Record
Partition 2:
  Type: EFI FAT (0xef)
  Size: 4 MB (4194304 bytes)
  Start Sector: 5520424, Boot: No


```
[rufus.log on MEGA](https://mega.nz/file/va5T3AwR#nIGqkaQuytDjCVdXbOmCm-mWvdByo93HrPBnJNAYD5w)

**Comment by pbatard** [comment]
> The options are grayed out

That's how it's supposed to work, because the Manjaro people have created an ISO that is only compatible with DD mode, so it gets flat copied to the USB drive "as is" (rather than having each file from the ISO extracted), and therefore, you cannot change the file system, partitions or any other parameters.

> and it only copies the bootloader (`E:\EFI\Boot\bootx64.efi`).

It didn't "only" copy the bootloader. It's just that the Manjaro image creates 2 partitions when flat-copied to the USB (DD mode), and Windows can only "see" the smallest of these partitions, which is the one that contains the `EFI\Boot\bootx64.efi` bootloader.

So there is other content that was properly copied, you just can't see it from Windows!

As a matter of fact, because this is confusing for a lot of users like you, this is why Rufus recommends using ISO mode (i.e. ISO individual file copy) over DD mode (flat copy), as when using ISO mode, you can see all of the individual files like they exist on the ISO. But some people, including the Manjaro maintainers who don't seem to realize that this is confusing for a lot of people, think that DD mode is always the best, and therefore make their images incompatible with ISO mode. Which is why most of the Rufus options are greyed out and, when it is done writing the drive, the only thing you'll be able to see is the EFI bootloader.

However, if the maintainers did their job properly, an image written in DD mode should still work (and, most Manjaro users don't seem to have much of an issue booting these drives), so it looks like there is a compatibility issue between your specific computer and the Manjaro image.

You may want to report that issue to the Manjaro people, as it really doesn't matter what application you used to write the image (for instance, if you try with Etcher, you should see the same issue), and it is therefore not a problem that is related to Rufus.

I would therefore encourage you to post in the Manjaro user forums. Be forewarned that you'll probably find a lot of people there that are likely to point the finger at Rufus, and that will advise you not to use it (because they don't appear to understand that what Rufus does write the Manjaro image in the same way as `dd` or `Etcher` will), but once you show them that you still have the issue when using a different USB creation application, they may actually start to listen to your problem...

Now, because I am confident that this is not related to Rufus (especially if you ran the bad blocks check and it came negative) I will close this issue.
