### ISSUE TITLE
my flashdisk write-protected forever

### ISSUE THREAD

**Issue by abin1769** [pbatard/rufus#1711]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
i was tried to make windows to go flash disk with windows 10 pro image but when the formatting progress is running its encountered an error that i forgot the message .i have to try to format again but it say Write error [0x0000045D] The request could not be performed because of an I/O device error. what must i do to fix it

-sorry for bad English

Log
---
```
Rufus x86 v3.13.1730
Windows version: Windows 8.1 64-bit (Build 9600)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
0 devices found
Found USB 3.0 device 'SanDisk Ultra USB Device' (0781:558A)
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3738, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00024DF7
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 28.6 GB (30751588352 bytes)
  Start Sector: 2048, Boot: Yes

Format operation started
Requesting disk access...
Will use 'F:' as volume mountpoint
Deleting partitions:
● Partition 1 (offset: 1048576, size: 28.6 GB)
Could not delete partition: [0x8007045D] The request could not be performed because of an I/O device error.
Opened \\.\PhysicalDrive1 for exclusive write access
Requesting logical volume handle...
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Rufus Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Write error [0x0000045D] The request could not be performed because of an I/O device error.
Retrying in 5 seconds...
Write error [0x0000045D] The request could not be performed because of an I/O device error.
Retrying in 5 seconds...
Write error [0x0000045D] The request could not be performed because of an I/O device error.
Retrying in 5 seconds...
Write error [0x0000045D] The request could not be performed because of an I/O device error.
write_sectors: Write error [0x0000045D] The request could not be performed because of an I/O device error.
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Could not reset partitions
Re-mounted volume as F: after error

Found USB 3.0 device 'SanDisk Ultra USB Device' (0781:558A)
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3738, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00024DF7
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 28.6 GB (30751588352 bytes)
  Start Sector: 2048, Boot: Yes
Found USB 3.0 device 'SanDisk Ultra USB Device' (0781:558A)
1 device found
```

**Comment by pbatard** [comment]
This would tend to indicate a hardware failure.

Please be very mindful that the flash memory used in a flash drive is not everlasting (it is a loss less reliable than people tend to imagine) and that, when a flash drive controller detects that the flash memory is failing, it may set the drive to read-only so that you can at least attempt to recover your data.

You may want to try to reformat your drive on a different computer, but if that doesn't work, you'd just going to have to recycle this drive.

As this is not an issue that is related to Rufus ([Rufus simply cannot damage a flash drive](https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive) or make it read-only), I am going to close this issue.
