### ISSUE TITLE
Compile size 3 mb while https://rufus.ie/downloads/ here 1.1 mb

### ISSUE THREAD

**Issue by maxmod** [pbatard/rufus#1718]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Thank you for building great application
Compile size 3 mb while https://rufus.ie/downloads/ here 1.1 mb so please tell me how to reduce .exe file and also how to compile portable version also
Thank You

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
> please tell me how to reduce .exe file

https://upx.github.io/

> and also how to compile portable version

The regular and portable versions are the **same** binary. The way Rufus detects if it should run in portable or regular mode is by checking is the name of the executable contains a `p`. This is explained [in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#How_comes_the_portable_and_regular_versions_are_binary_identical).
