### ISSUE TITLE
There is no option to download windows iso!

### ISSUE THREAD

**Issue by Mehul-N265** [pbatard/rufus#1719]
![Capture](https://user-images.githubusercontent.com/76092343/115680317-17271000-a371-11eb-9cc1-000c3b713df7.PNG)

**Comment by pbatard** [comment]
If you had followed the checklist, instead of thinking it does not apply to you, [you would have found your answer in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Help_I_dont_see_the_ISO_download_button).
