### ISSUE TITLE
Device eliminated because it didn't report itself as a non fixed USB disk

### ISSUE THREAD

**Issue by RollingStar** [pbatard/rufus#172]
I have a 2GB flash drive with World Cup branding on it. Chances are good that it's not a very good drive. The read/write speeds certainly point in that direction.

I've also been unable to get UnetBootIn or Rufus to do anything with the drive. Both Rufus versions I've tried never give me the option of selecting the drive. After the drive initially wasn't recognized, I did a full format to NTFS and then another full format to FAT.

```
Rufus version 1.3.4.270
Windows version: Windows 7 64-bit
Found device 'USB Flash Disk USB Device'
A device was eliminated because it didn't report itself as a non fixed USB disk
0 devices found.
```

```
Rufus version 1.3.1.220
Found drive 'USB Flash Disk USB Device'
0 devices found.
```

I am never able to select the drive, and the start button within Rufus is always unselectable.

UNetbootin v494 allows me to check a box and select any drive, regardless of whether it is recognized as a USB flash drive or not. Definitely risky! However it does allow me to write to the drive. I have not yet tried booting from the drive after v494 formats it.

**Comment by lesonwon** [comment]
Hello I am looking for the correct thread to post in for a similar issue. Below is my log report

Found USB 2.0 device 'SanDisk Cruzer Glide USB Device' (0781:5575)
Could not open '\\?\usbstor#disk&ven_sandisk&prod_cruzer_glide&rev_1.27#20044323000f11208b2c&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}': [0x00000005] Access is denied.
A device was eliminated because it didn't report itself as a disk
0 devices found

**Comment by pbatard** [comment]
1. You could always have created a new issue
2. Please always provide the __FULL__ log. I have no idea what version of Rufus or Windows you are using (as well as the build number of Windows). If you create a new log, please also enable USB Debug using <kbd>Alt</kbd>-<kbd>.</kbd>. You should see _USB Debug enabled_ at the bottom of Rufus.
3. `[0x00000005] Access is denied` usually means that __another__ application (could be a security solution, something else) has exclusive access to the device. So you may have to figure which one. For instance, are you using any of the applications listed [at the very end of the Rufus FAQ](https://github.com/pbatard/rufus/wiki/FAQ#List_of_software_and_hardware_Rufus_isnt_compatible_with)? (NB: This is list is NOT exhaustive).
