### ISSUE TITLE
compile successful but getting error Classpnp.sys when formatting

### ISSUE THREAD

**Issue by maxmod** [pbatard/rufus#1722]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

Sir,
I don't know whats ﻿the main issue when using https://github.com/pbatard/rufus/releases/download/v3.13/rufus-3.13.exe all fine usb get format easily but when i am comping myself after that when using compiled version  of rufus it start and stop on format blue screen Classpnp.sys when formatting please tell me what i am doing wrong i am using visual basic 2019
Thank You

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Sorry, but I'm afraid I have no idea why your specific environment would fail with a `classpnp.sys` error when using your own compiled version of Rufus.

I have never seen that error, and I have not had reports of anybody else getting it. Therefore it looks like your problem is linked to something __specific__ to your environment, that you will have to troubleshoot yourself.
