### ISSUE TITLE
It took me 12 hours for a Windows To Go bootable USB (Even haven't done yet)

### ISSUE THREAD

**Issue by WinkeyCheng** [pbatard/rufus#1742]
![image](https://user-images.githubusercontent.com/73391218/119988173-6a3b5500-bff8-11eb-8c15-7b2f0cf40bf0.png)

**Comment by WinkeyCheng** [comment]
No way, Microsoft is so garbage!!!
Im using USB3.2 Port and 24GB RAM and also AMD RYZEN 4800 CPU
HOWWWWWWWWWWW COME

**Comment by WinkeyCheng** [comment]
I HAVE ALREADY HANGED MY PC FOR 12 HOURS FROM MORNING TO THE TIME I SLEEP

**Comment by pbatard** [comment]
> Is that really real?

Are you accusing me to __lie__ when it comes to results that can be tested independently by anyone?

Again, get a better USB drive or a better PC. I am locking this thread.
