### ISSUE TITLE
15 HOURS ALREADY AND I HAVEN'T LIE

### ISSUE THREAD

**Issue by WinkeyCheng** [pbatard/rufus#1743]
![image](https://user-images.githubusercontent.com/73391218/120014381-91078480-c014-11eb-84d1-231aaee33f6a.png)
It really shows that I have 24GB RAM and also AMD Ryzen 4800H
Also USB 3.1
I AM NOT KIDDING
ALREADY 15 HOURS

**Comment by pbatard** [comment]
And you are banned.
