### ISSUE TITLE
Using rufus on Window 7 32bit Starter

### ISSUE THREAD

**Issue by LocTran016** [pbatard/rufus#1745]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I ran into a problem while I was trying to make a bootable USB to install Window 10 20H1 in Window 7 32bit Starter (VMWare on MacOS) but it ran to a problem here:
![Screen Shot 2021-05-30 at 20 03 13](https://user-images.githubusercontent.com/64778285/120105929-1f027d00-c185-11eb-83f1-78ccbea23dae.jpg)

Log
----

```

Format operation started
Requesting disk access...
Will use 'E:' as volume mountpoint
Deleting partitions:
● Partition 1 (offset: 1048576, size: 14.9 GB)
● Partition 0 (offset: 15979187200, size: 512 KB)
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (GPT)...
● Creating Main Data Partition (offset: 1048576, size: 14.9 GB)
● Creating UEFI:NTFS Partition (offset: 15979187200, size: 512 KB)
Writing UEFI:NTFS data...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Unable to locate FormatEx() in fmifs.dll: [0x0000007F] The specified procedure could not be found.
Format error: [0xC003007F] The specified procedure could not be found.
Re-mounted volume as E: after error

Found non-USB removable device 'VMware, VMware Virtual S SCSI Disk Device' => Eliminated
Found USB 2.0 device 'PNY USB 3.0 FD USB Device' (154B:6008)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1942, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {01F45424-F8E4-44D8-B15E-37CA0948F466}
Max parts: 128, Start Offset: 17408, Usable = 15980263936 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  ID: {AB32384A-D78C-4B85-B2F8-AD9023EC54A1}
  Size: 14.9 GB (15978138624 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2 (UEFI:NTFS):
  Type: Microsoft Basic Data Partition
  Name: 'UEFI:NTFS'
  ID: {147B624A-0C79-497B-89E5-2263B1809BA6}
  Size: 512 KB (524288 bytes)
  Start Sector: 31209350, Attributes: 0x0000000000000000
Found non-USB removable device 'VMware, VMware Virtual S SCSI Disk Device' => Eliminated
Found USB 2.0 device 'PNY USB 3.0 FD USB Device' (154B:6008)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1942, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {01F45424-F8E4-44D8-B15E-37CA0948F466}
Max parts: 128, Start Offset: 17408, Usable = 15980263936 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  ID: {AB32384A-D78C-4B85-B2F8-AD9023EC54A1}
  Size: 14.9 GB (15978138624 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2 (UEFI:NTFS):
  Type: Microsoft Basic Data Partition
  Name: 'UEFI:NTFS'
  ID: {147B624A-0C79-497B-89E5-2263B1809BA6}
  Size: 512 KB (524288 bytes)
  Start Sector: 31209350, Attributes: 0x0000000000000000
Found non-USB removable device 'VMware, VMware Virtual S SCSI Disk Device' => Eliminated
Found USB 2.0 device 'PNY USB 3.0 FD USB Device' (154B:6008)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1942, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {01F45424-F8E4-44D8-B15E-37CA0948F466}
Max parts: 128, Start Offset: 17408, Usable = 15980263936 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  ID: {AB32384A-D78C-4B85-B2F8-AD9023EC54A1}
  Size: 14.9 GB (15978138624 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2 (UEFI:NTFS):
  Type: Microsoft Basic Data Partition
  Name: 'UEFI:NTFS'
  ID: {147B624A-0C79-497B-89E5-2263B1809BA6}
  Size: 512 KB (524288 bytes)
  Start Sector: 31209350, Attributes: 0x0000000000000000
Found non-USB removable device 'VMware, VMware Virtual S SCSI Disk Device' => Eliminated
Found USB 2.0 device 'PNY USB 3.0 FD USB Device' (154B:6008)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1942, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {01F45424-F8E4-44D8-B15E-37CA0948F466}
Max parts: 128, Start Offset: 17408, Usable = 15980263936 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  ID: {AB32384A-D78C-4B85-B2F8-AD9023EC54A1}
  Size: 14.9 GB (15978138624 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2 (UEFI:NTFS):
  Type: Microsoft Basic Data Partition
  Name: 'UEFI:NTFS'
  ID: {147B624A-0C79-497B-89E5-2263B1809BA6}
  Size: 512 KB (524288 bytes)
  Start Sector: 31209350, Attributes: 0x0000000000000000
```

**Comment by pbatard** [comment]
`Unable to locate FormatEx() in fmifs.dll: [0x0000007F] The specified procedure could not be found.`

I'm afraid your installation of Windows is crippled, as Rufus relies on `fmifs.dll` to work, and yours is either missing or lacking the relevant API calls.

You can try <kbd>Alt</kbd>-<kbd>V</kbd> in Rufus to force the use of VDS for formatting, but I'm afraid I have no plans to try to support versions of Windows where `fmifs.dll` doesn't work as expected, even more so if it's Windows 7 (which has been obsoleted by Microsoft by more than a year now).

As such I will close this issue.

**Comment by LocTran016** [comment]
> `Unable to locate FormatEx() in fmifs.dll: [0x0000007F] The specified procedure could not be found.`
> 
> I'm afraid your installation of Windows is crippled, as Rufus relies on `fmifs.dll` to work, and yours is either missing or lacking the relevant API calls.
> 
> You can try Alt-V in Rufus to force the use of VDS for formatting, but I'm afraid I have no plans to try to support versions of Windows where `fmifs.dll` doesn't work as expected, even more so if it's Windows 7 (which has been obsoleted by Microsoft by more than a year now).
> 
> As such I will close this issue.

I download that file from Microsoft, the Window 10 21H1 ISO but may be I should check again, thanks for your advice

**Comment by pbatard** [comment]
> I download that file from Microsoft, the Window 10 21H1 ISO

This is irrelevant. I was talking about the OS that you use to run Rufus on, which is Windows 7 Starter edition running inside a Virtual Machine on MacOS. The ISO you are trying to use has no impact on that.

If you were running Rufus on Windows 8 or 10 and on real hardware, that would be a different story. But you are not, and there's only so much support I can provide for the type of configuration you are using to run Rufus.
