### ISSUE TITLE
add new window

### ISSUE THREAD

**Issue by LievreAI** [pbatard/rufus#1753]
hey guys i want to add a new windows to the application like windows server 2016

**Comment by pbatard** [comment]
The Windows downloads proposed by Rufus are handled by the [Fido script](https://github.com/pbatard/Fido).

I happily accept patches for the Fido script if you have any.

Note that the ISOs being proposed must come from a public link offered by Microsoft, such as the ones from https://www.microsoft.com/en-gb/software-download/windows10ISO. Are the Windows Server 2016 ISOs publicly available?

**Comment by pbatard** [comment]
Since this is a Fido issue, and OP has not replied to the public availability of Windows Server 2016 ISOs, I will close this issue.
