### ISSUE TITLE
Feature request: portable version updates should download the portable version

### ISSUE THREAD

**Issue by TheBicPen** [pbatard/rufus#1758]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
The portable version should download the portable version when there is an update.
Currently it downloads the non-portable version (at least when checking for updates manually).
This isn't a major issue since it's the same file anyway, but it would be nice if it stayed consistent.

Log
---
```
Rufus x86 v3.14.1788 (Portable)
Windows version: Windows 10 64-bit (Build 19042.1083)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'Seagate Portable USB Device' (0BC2:2300)
Device eliminated because it was detected as a Hard Drive (score 33 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Using autorun.inf label for drive G: 'Run Debian GNU/Linux'
1 device found
Disk type: Removable, Disk size: 2.1GB, Sector size: 512 bytes
Cylinders: 251, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x2158826F
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 1.7 GB (1789917696 bytes)
  Start Sector: 2048, Boot: Yes
Partition 2:
  Type: GNU/Linux (0x83)
  Size: 261.0 MB (273659904 bytes)
  Start Sector: 3497981, Boot: No

```

**Comment by pbatard** [comment]
From [this entry of the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#What_is_the_difference_between_the_portable_and_the_regular_version):

> This is also the reason why when Rufus downloads an update, it always picks the "regular" version, even if the version you were running was the "portable" one, as you would already have a rufus.ini, therefore, the new "regular" version that is downloaded will continue to run in portable mode.
