### ISSUE TITLE
windows 7 ultimate boot corrupts my drive 

### ISSUE THREAD

**Issue by sandeepyadav1478** [pbatard/rufus#1762]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>
after successfully installation on usb. On system boot its not catching usb content but showing in bootable devices menu.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
> On system boot its not catching usb content but showing in bootable devices menu. 

So your BIOS/UEFI is listing the USB drive as a bootable device, but you can't boot from it?
In the absence of a log, which you were supposed to provide, I can only consider that the drive was properly created, and therefore that your issue has to do with your BIOS/UEFI settings. As such I will close this issue, as you simply did not provide enough information to demonstrate that this might have anything to do with Rufus.

Also, you are attempting to create a Windows 7 boot drive, which is something I can no longer support, as Windows 7 was officially retired by Microsoft more than one year ago. Therefore, as far as Windows 7 and Rufus are concerned, and just like with Vista or XP, my stance is: If it works, great. If it doesn't, you're on your own.
