### ISSUE TITLE
Windows XP 64 bit (with SP2)- Rufus gives error message and fails to create Bootable USB Image

### ISSUE THREAD

**Issue by arvindcodes** [pbatard/rufus#1765]
Hi,

THe error message is this- "The image is either non-bootable, or it uses a boot or compression method that is not supported by Rufus".

The image is here--(ISO of Windows XP 64 bit SP2)--> https://archive.org/download/en_win_xp_pro_x64_with_sp2_vl/en_win_xp_pro_x64_with_sp2_vl_x13-41611.iso

Please let me know how to resolve this issue?

Thanks,
Arvind.

**Comment by JonnyTech** [comment]
The information is in the FAQ which you chose to ignore:

https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED

**Comment by arvindcodes** [comment]
Hello JonnyTech,

I am so sorry for my mistake.

Thanks and sincerely,
Arvind.
