### ISSUE TITLE
0 Laufwerke gefunden

### ISSUE THREAD

**Issue by Dasproblembinich** [pbatard/rufus#1772]
Ich möchte rufus verwenden bekomme aber immer unten angezeigt 0 Laufwerke gefunden
﻿
![Screen Shot 08-27-21 at 10 41 AM](https://user-images.githubusercontent.com/89634822/131102002-afd8fb0e-6901-40fc-b338-2978db53ff57.PNG)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected
