### ISSUE TITLE
can't see all of rufus 3.13 screen

### ISSUE THREAD

**Issue by as-muncher** [pbatard/rufus#1780]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I'm using rufus 3.13p in Windows 7 safe mode, and the lowest I can see of the rufus window is the part that says "check device for bad blocks".  I don't know if it's VGA mode or what, but I would like some scroll bars on the side so that I can actually see the rest of the rufus window.  And resizing by dragging the corner of the window doesn't work.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
This has been asked a couple of times, but the cost/benefit ratio of supporting this is just not worth it.

Rufus does __not__ support low resolutions.
