### ISSUE TITLE
0 device found problem rufus 3.15 on ubuntu. I want to switch windows by using iso file in my pendrive. but rufus show 0 device found. but I enabled usb debug :( please help

### ISSUE THREAD

**Issue by marufjs** [pbatard/rufus#1787]
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
<FULL LOG>
```

**Comment by marufjs** [comment]
Rufus x86 v3.15.1812 (Portable)
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: CoCreateInstance failed; hr = 80040154
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because a compatible PowerShell version was not detected on this system.
0 devices found
0 devices found
0 devices found
0 devices found
0 devices found
0 devices found
0 devices found
0 devices found
0 devices found
0 devices found
0 devices found

**Comment by pbatard** [comment]
Rufus is a Windows application that is __NOT__ compatible with wine (and most likely other methods of trying to emulate/virtualise Windows on Linux).

I will only support Rufus if you run it in a real non-emulated Windows environment. So, if you attempt to run Rufus on Ubuntu, you are 100% on your own.
