### ISSUE TITLE
my usb disk unusable after using rufus

### ISSUE THREAD

**Issue by tngebog** [pbatard/rufus#1788]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>
i had a fully working 32gb flash drive then i used rufus on it and now i cant do anything on the flash now
diskpart clean, partitioning, returning to non bootable, nothing works on this please help
it used to say no label no it just says no media on disk. is there a way to salvage this drive or its gone for good

Log
---
```
<FULL LOG>
Rufus x86 v3.15.1812
Windows version: Windows 10 64-bit (Build 18363.1082)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found
Found USB 2.0 device 'GENERIC USB Mass Storage USB Device' (0C76:0005)
Device eliminated because it appears to contain no media
0 devices found

```

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Rufus_cant_detectformat_my_drive_and_reports_that_it_is_readonly_or_contains_no_media
