### ISSUE TITLE
Please convert the interface of Rufus to use WinUI.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [pbatard/rufus#1792]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Issue description
-----------------
[WinUI is being planned for the next version of the interface of Rufus.](http://github.com/pbatard/rufus/issues/1453#issuecomment-856731860), which I am very supportive of, not least because it shall remediate [the lack of dark support](http://github.com/pbatard/rufus/issues/1453). Consequently, I am hoping that this issue shall be used as the tracker for this feature.

**Comment by pbatard** [comment]
See also https://github.com/microsoft/WindowsAppSDK/blob/main/docs/roadmap.md#Unpackaged-Desktop-Apps, where we will need both XAML islands and elevation support, none of which are currently supported by the SDK. We're not even at the 1.0 release yet, so it's still way too soon for win32 applications like Rufus to be thinking about transitioning to WinUI.
