### ISSUE TITLE
documentation (faq issue #openbsd)

### ISSUE THREAD

**Issue by b-user** [pbatard/rufus#1796]
https://github.com/pbatard/rufus/wiki/FAQ#openbsd
It's probably sane to change "Use the installXX.fs or cdXX.fs " on "Use the XX.img"

https://www.openbsd.org/faq/faq4.html#Download
https://cdn.openbsd.org/pub/OpenBSD/7.0/amd64/install70.img

**Comment by pbatard** [comment]
Thanks for the suggestion. I edited the FAQ. For the record, any GitHub user can edit the FAQ, so you could have made that change yourself. 😉
