### ISSUE TITLE
rufus

### ISSUE THREAD

**Issue by esmer2021** [pbatard/rufus#1798]
rufus kullanı yorum hata veriyor ıso ayrıştırma yapıyor yani yuklemiyor neyapmam lazım

**Comment by esmer2021** [comment]
AMD Ryzen 5 3600X 6-Core Processor                3.79 GHz 16 gb ram var  acaba amd işlemci olduğundanmı hata veriyor

**Comment by pbatard** [comment]
Did not follow the check list &rarr; Closed. I genuinely can't help you if you don't follow the check list.
