### ISSUE TITLE
Unable to install from CentOS 7 based ISO - dracut-initqueue[779]: Warning: dracut-initqueue timeout

### ISSUE THREAD

**Issue by jumpapex** [pbatard/rufus#1820]
﻿Issue description
-----------------
use rufus 3.17p to write a customized CentOS 7 based ISO to USB disk. and boot from it.
the booting process is stuck with
...
[  193.845250]  dracut-initqueue[779]: Warning: dracut-initqueue timeout - starting timeout scripts
[...]
[  198.557262]  dracut-initqueue[779]: Warning: dracut-initqueue timeout - starting timeout scripts
[  198.557679]  dracut-initqueue[779]: Warning: Could not boot.
[  200.161146]  dracut-initqueue[779]: Warning: /dev/root does not exist
[  200.170895]  systemd[1]: Starting Dracut Emergency Shell...
...

I'm sure the original ISO image is fine.

So what can I do to help fix the issue, or do you need more information? I could provide you the ISO file also.

Thansk!

Paul

**Comment by pbatard** [comment]
I'm afraid that it is up to you to identify the exact part that deviates from the properly booting original CentOS image and fix it.

Please understand that, while the application is free, my time isn't and I have exactly zero interest or time to help fix __custom__ ISOs that people created, that somehow fail to boot, and that are derived from ISOs that do work. It's just way too easy, if you don't have a good grasp of what's needed to boot from USB, to screw up a boot process, and I just don't have the luxury to go over every person's custom image to tell them what's wrong.

Instead, I will point you to [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Preamble) and indicate that, unless there is an actual problem with the official CentOS, it's going to be entirely up to you to fix it.
