### ISSUE TITLE
What happened to backing up a usb drive to ISO?

### ISSUE THREAD

**Issue by tamusjroyce** [pbatard/rufus#1828]
﻿What happened to backing up a usb drive? the save disk icon isn't showing anymore.

**Comment by pbatard** [comment]
1. That's not a backup to ISO, that's a backup to VHD
2. This is an advanced control so it only displays when the _Show advanced drive properties_ section is enabled.

**Comment by tamusjroyce** [comment]
**Show advanced drive properties** - it moved from all the tutorials and screenshots I had been finding to here. Up too late and my eyes missed this menu. Yes, I meant VHD, not ISO. Thank you @pbatard!
