### ISSUE TITLE
Compiling Rufus for different OSes

### ISSUE THREAD

**Issue by Stehlampe2020** [pbatard/rufus#1833]
I tried to compile Rufus for Ubuntu by `git` cloning it to my computer, running the `./compile` script and then running `make` inside the directory git created. But there are packages missing which are hard to get. Could please somebody who has the needed packages installed compile Rufus for Ubuntu linux and put it on the "releases" page?

**Comment by pbatard** [comment]
Rufus is Windows-only.

See https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS

**Comment by Stehlampe2020** [comment]
Now I do at least know that it's not intended to bw compiled for linux...
