### ISSUE TITLE
[Request]Ability to back up the current USB memory as a .usb file (disk image).

### ISSUE THREAD

**Issue by SysVR** [pbatard/rufus#1834]
Under "Device" in [Drive Properties]
Add a backup function for the device.

It is a function to compress the entire drive and save it as a * .usb file.
This makes it easy to back up a USB memory that has multiple partitions.

Restoration can be done by loading the * .usb file from [Select].

**Comment by pbatard** [comment]
The feature you want is [already there](https://github.com/pbatard/rufus/wiki/FAQ#Saving_an_existing_drive_to_VHD):

![Image1](https://user-images.githubusercontent.com/1206968/143682961-4858fdb2-f5e1-4163-a94e-d515b52f1e41.png)

And there is __no__functional difference between an uncompressed VHD and a flat `.usb` image, as you can use both with the `dd` command if you wish.

**Comment by SysVR** [comment]
There was insufficient confirmation.
I'm sorry.
