### ISSUE TITLE
ISO → ESP mode timeout on v3.17.1846

### ISSUE THREAD

**Issue by BoxuanZng** [pbatard/rufus#1855]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I was trying out the Write in ISO → ESP mode feature of Rufus version 3.17 and this message popped up a while after I clicked start:
`Error:[0xC00305B4] This operation returned because the timeout period expired.`

Log：
-----
```
Rufus x86 v3.17.1846
Windows version: Windows 11 Pro, 64-bit (Build 22471.1000)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0804 (zh-CN)
Will use default UI locale 0x0804
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'zh-CN'
Found UAS (USB 3.0) device 'ACASIS  SCSI Disk Device' (152D:1561)
Device eliminated because it was detected as a Hard Drive (score 23 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
Found USB 2.0 device 'OffSec Kali Live USB Device' (FFFF:5678)
No logical drive found (unpartitioned?)
1 device found
No volume information for drive 0x82
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3824, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {E0A493D1-C10B-4B30-91A8-C83AA45DEB44}
Max parts: 128, Start Offset: 17408, Usable = 31457245696 bytes
Partition 1:
  Type: EFI System Partition
  Name: 'EFI System Partition'
  ID: {7C4B294B-A0AE-491C-BA3F-5D489EC64A9F}
  Size: 447 MB (468713472 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Local time: 13286684181
Next update check in 84038 seconds.
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'Black_PE'
  Size: 394.0 MB (Projected)
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
Using image: Black_PE_TEST.iso (611.5 MB)

Format operation started
Requesting disk access...
No drive letter was assigned...
Will use 'E:' as volume mountpoint
Opened \\.\PhysicalDrive2 for exclusive write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (GPT)...
● Creating EFI System Partition (offset: 1048576, size: 447 MB)
Waiting for logical drive to reappear...
Timeout while waiting for logical drive
Logical drive was not found - aborting

Found UAS (USB 3.0) device 'ACASIS  SCSI Disk Device' (152D:1561)
Device eliminated because it was detected as a Hard Drive (score 23 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
Found USB 2.0 device 'OffSec Kali Live USB Device' (FFFF:5678)
No logical drive found (unpartitioned?)
1 device found
No volume information for drive 0x82
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3824, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {5BAB630A-C50E-4ACE-9768-7162F7CA15CC}
Max parts: 128, Start Offset: 17408, Usable = 31457245696 bytes
Partition 1:
  Type: EFI System Partition
  Name: 'EFI System Partition'
  ID: {63112EF3-D366-4786-9149-8AAD2297B923}
  Size: 447 MB (468713472 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Saved C:\Users\Administrator.AI-202107230820\Desktop\rufus.log
```

**Comment by pbatard** [comment]
Thanks for the report. I can replicate the issue with Windows 11 release, and it seems to be a Windows 11 specific issue, where (as usual) Microsoft made it even harder to work with ESPs...

I'll see what I can do, but seeing how Microsoft is actively preventing applications from accessing ESPs, it might be quite tricky...
