### ISSUE TITLE
Rufus cannot detect new USB (Fat32 by default)

### ISSUE THREAD

**Issue by xTrayambak** [pbatard/rufus#1872]
Greetings, so I have been trying to format my USB drive but Rufus seems to not detect it, yes, I've formatted it, yes, I've tried ALT+F, but nothing seems to work. Rufus simply refuses to detect it. My PC detects it just fine, but it doesn't. Whenever I try to format it using disk manager, I get the following error:
"Virtual Disk Manager: Access denied". Is this the cause? I've run Rufus with admin privileges but still, it fails to detect the drive.

**Comment by pbatard** [comment]
I'm afraid I can't help you if you choose not to follow the check list.
