### ISSUE TITLE
Added support to select desired window version from iso file to create bootable usb

### ISSUE THREAD

**Issue by kid1485** [pbatard/rufus#1887]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

I hope rufus support select session eg window 11 pro or window 11 home from iso file to create bootable USB like "index" index parameter in dism

**Comment by pbatard** [comment]
Already does for Windows To Go. And for regular install, it is supported natively through the Windows installation process.

I would appreciate if you tested, or spent some time looking around for information, before asking about features, thank you.
