### ISSUE TITLE
Damage to flash drive when you cancel formatting

### ISSUE THREAD

**Issue by D143n** [pbatard/rufus#190]
I used a super talent 4gb switch blade for this . When formatting , I unclicked the quick format option. It took 11 mins and was still not done formatting. I canceled the format and my usb is unreadable now.

**Comment by fachrim** [comment]
Excuse me bro  I Got the same prob with u Exactly same 
How did you do that to fix it bro  ...???
Pleaseee help me

**Comment by D143n** [comment]
never got it fixed. I just gave up.

**Comment by Tmp341** [comment]
Try HP Usb Disk Storage Format Tool.If that won't work, then try your flash drives low level format tool.

**Comment by pbatard** [comment]
>  I can't verify that my drive's issues stemmed from using it with Rufus

From your report, I think we can logically deduce that they didn't:

1. You were able to create the drive successfully without error in Rufus, which means that no write issues were detected.
2. You were able to install Windows using the drive that was created by Rufus, which pretty much means that the Windows installation process was able to successfully read all the data that was written to your drive by Rufus without issue.

Therefore, we can conclude that, by the time you were finished using your drive, it was in perfect working condition and therefore, whatever happened later on had nothing to do with using Rufus.

> The symptoms on my device did not appear until the next time I plugged the drive in at home, multiple days later (though within 1 week).

This seems to further confirm that what you experienced was a standard hardware failure, that would have happened regardless of the software being used. I think it is my duty to point that out, considering that there appear to be a lot of very vociferous people out there who, while experiencing exactly the level of failure one can expect from using flash memory media, are adamant to place the blame on Rufus, and may take your report as further "proof" that Rufus may damage drive, whereas, when reading your experience carefully, one can only conclude that it had nothing to do with using Rufus.

> the (...) method that worked for me began with Tmp341's suggestion to perform a low-level format on the flash drive. 

Thanks for posting these steps. Be mindful however that a drive that fails is usually an indication of a hardware issue, most likely with the flash memory cells, and that, while you may be able to seemingly "recover" the drive using manufacturer tools (which, as far as I understand, simply tend to reset the map of bad memory cells the drive's firmware has established from past failure), it is very likely that this recovery will be short lived. At the very least, you should always run a bad blocks check to ensure that every single flash block gets written and tested before you attempt to use your drive for data again.
