### ISSUE TITLE
Partition scheme and target system on rufus 3.18.1877.0 is grayed out.

### ISSUE THREAD

**Issue by EverettLThayer** [pbatard/rufus#1900]
Unable to create postmarketos mate bootable live usb with gpt/uefi, have tried in windows 10 uefi based laptop using gpt disk and windows 11 legacy with mbr disk still same. But for same os image with xfce4 it's open, please help anyone i needed mate desktop environment.

![Screenshot 2022-04-03 181150](https://user-images.githubusercontent.com/102916283/161437317-a752d6f4-5d35-4d38-b31d-4491678d58d2.png)

**Comment by pbatard** [comment]
It's an image file. So the partition scheme and target system are the ones defined by the makers of the image __and cannot be modified__. Therefore they are greyed out.

In Windows applications, a greyed out option is an option that does not apply.
