### ISSUE TITLE
Error message when creating a bootable USB with a ZIP file

### ISSUE THREAD

**Issue by Tom60chat** [pbatard/rufus#1903]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I'm traying to create a bootable USB with the ZIP version of file CloneZila and this appened:
![image](https://user-images.githubusercontent.com/25564492/162690842-f40b8e10-2178-4a70-a2ca-51aef09f86d6.png)
![image](https://user-images.githubusercontent.com/25564492/162689681-d23316da-2208-43df-9ccc-aaf30058f26f.png)

But using the ISO version everythings it's working fine.
But what got my attention is the Boot selection it's empty and the error it's about boot type.
I would like to do further testing when I got time, if you like.

Log
---
```
Rufus x86 v3.18.1877
Windows version: Windows 10 Pro, 64-bit (Build 19044.1586)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x040C (fr-FR)
Will use default UI locale 0x040C
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'fr-FR'
Found USB 3.0 device 'SanDisk Ultra USB Device' (0781:5581)
1 device found
Disk type: Removable, Disk size: 16 Go, Sector size: 512 bytes
Cylinders: 1869, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {29D73CB2-F392-49D7-8A1D-0B700E0729D1}
Max parts: 128, Start Offset: 17408, Usable = 15375965696 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: FAT32
  ID: {F9ED0484-5B01-43F4-B3C8-7C3D4D1A64FF}
  Size: 14.3 GB (15374934528 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  'C:\Users\Utilisateur\Downloads\clonezilla-live-2.8.1-12-amd64.zip' doesn't look like an ISO image
Disk image analysis:
Disk type: Removable, Disk size: 16 Go, Sector size: 512 bytes
Cylinders: 1869, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {29D73CB2-F392-49D7-8A1D-0B700E0729D1}
Max parts: 128, Start Offset: 17408, Usable = 15375965696 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: FAT32
  ID: {F9ED0484-5B01-43F4-B3C8-7C3D4D1A64FF}
  Size: 14.3 GB (15374934528 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Failed to scan image

Format operation started
Requesting disk access...
Will use 'D:' as volume mountpoint
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (GPT)...
● Creating Main Data Partition (offset: 1048576, size: 14.3 GB)
Waiting for logical drive to reappear...
Formatting to FAT32 (using IFS)
Using cluster size: 8192 bytes
Quick format was selected
Creating file system...
Format completed.
Writing Master Boot Record...
Using Rufus protective MBR
Writing protective message SBR
Found volume \\?\Volume{cf1e4e1f-b70b-11ec-b405-94c691f8d7aa}\
Re-mounted volume as D: after error

Found USB 3.0 device 'SanDisk Ultra USB Device' (0781:5581)
1 device found
Disk type: Removable, Disk size: 16 Go, Sector size: 512 bytes
Cylinders: 1869, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {961FEFF5-DA0E-4C7C-BDEE-5A26A689D9BB}
Max parts: 128, Start Offset: 17408, Usable = 15375965696 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: FAT32
  ID: {2A256D28-AEE0-4997-B83E-2A711DEF8438}
  Size: 14.3 GB (15374934528 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
No file system is selectable for this drive
```

**Comment by pbatard** [comment]
Thanks for the report.

I can't replicate your issue exactly, but I am indeed seeing issues (and a different assertion failed error) when selecting the `clonezilla-live-2.8.1-12-amd64.zip` image.

Note however that the .zip image functionality of Rufus is meant to be used only for zip file that contains a __single__ DD image, so what you are trying to accomplish will never work anyway, as it could only work if the Clonezilla folks had created a `clonezilla-live-2.8.1-12-amd64.img` and then compressed that single file into a `.zip` so that when you open the `.zip` you only see that single file.

There is definitely an issue in Rufus when selecting a file that cannot be used as a bootable image though, so I'll get that fixed for version 3.19.
