### ISSUE TITLE
Error while unpacking the ISO file in rufus 3.18

### ISSUE THREAD

**Issue by 0-qVxr23** [pbatard/rufus#1904]
I had the issue mentioned above in rufus 3.18, however, i could unpack the iso using rufus 3.17. Unfortunately, i cannot give any details how this error might have occurred. I can only say that I am using Windows 10.

**Comment by pbatard** [comment]
> Unfortunately, i cannot give any details how this error might have occurred.

Then I cannot help you. The log is mandatory and, in the absence of any other evidence to disprove it, I will assume that you are using a custom/nonstandard ISO, that was improperly mastered, and that this is the only cause of your problem.

&rarr; Closing on account that I have absolutely __NO DATA__ to work with.
