### ISSUE TITLE
Please Add SHA256 Check Sum To The Official Rufus Website/Download Location

### ISSUE THREAD

**Issue by Jibun-no-Kage** [pbatard/rufus#1905]
﻿Please Add SHA256 Check Sum To The Official Rufus Website/Download Location.  For example, after I downloaded Rufus versions, I calculated the SHA1 and SHA256 check sums, see below, how can I determine if this is correct?

SHA256 hash of rufus-3.18.exe:
22820692cb7295cd13bf62ab984a8f5b37e3cb09999b6aa2ad27a704e3380c48
CertUtil: -hashfile command completed successfully.
SHA1 hash of rufus-3.18.exe:
8422936c6ffca78b9fb332ad5d09d7ed8fde1b29
CertUtil: -hashfile command completed successfully.

With such tools, strongly suggested a method of download validation is possible.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Why_dont_you_provide_an_SHA256_for_the_Rufus_binary

**Comment by Jibun-no-Kage** [comment]
Ah, Ok... Thanks for the FAQ link.  Cool, love self-validating code!
