### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by kiencuongpo** [pbatard/rufus#1906]
The program can't start because DFSCLI.DLL is missing from your computer.

![image](https://user-images.githubusercontent.com/102970802/163596483-46bea6ba-4d9d-4270-b4e1-d696af4064e4.png)

The procedure entry point DFSCLI.NetDfsSetClientInfo could not be located in the dynamic link library NETAPI32.dll.

![image](https://user-images.githubusercontent.com/102970802/163596731-a34d4f91-8d4f-414e-a757-8e2025208ac7.png)

Windows 7 - 32bit

![image](https://user-images.githubusercontent.com/102970802/163597721-7ba5afd4-962f-4415-8f83-8188207b0f35.png)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED

Unless you can replicate this issue on a Windows 8+ platform, I'm afraid that I am not willing to spend any time investigating it.
Also, the check list is __not__ optional.
