### ISSUE TITLE
'LaCie XtremKey USB 3.0 USB Device' (059F:1079) detected as hard drive

### ISSUE THREAD

**Issue by thehatworks** [pbatard/rufus#1912]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
USB Key detected as USB Hard Drive. Also want to take the opportunity to thank you for the years of use & time saved I have to thank rufus for. Not submitting this because I expect it to get fixed, **only** because the log told me to e-mail you, and this seemed like a better place to drop the information. This is the only issue I have ever had with rufus in 10 years, and of course it is easily worked around by checking "list drives"... Feel free to close the issue and disregard if it isn't a priority.

Log
---
```
Rufus x86 v3.18.1877
Windows version: Windows 11 Pro, 64-bit (Build 22000.613)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 3.0 device 'LaCie XtremKey USB 3.0 USB Device' (059F:1079)
Device eliminated because it was detected as a Hard Drive (score 5 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
0 devices found
```

**Comment by pbatard** [comment]
Thanks for the report. I'll add an exception for this device for the next release.
