### ISSUE TITLE
I keep getting a error for access to device denied and the iso is not on the flash drive

### ISSUE THREAD

**Issue by SepticRedhead** [pbatard/rufus#1938]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

no matter what iso I use I get the error access to device denied

Log
---
```
Rufus x86 v3.18.1877 (Portable)
Windows version: Windows 8.1 Home, 32 bit (Build 9600.20371)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'Lexar USB Flash Drive USB Device' (05DC:A81D)
Found card reader device 'Hynix HCG8e '
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1947, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.04/20200816 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Debian 11.3.0 i386 n'
  Size: 472.3 MB (Projected)
  Uses: Syslinux/Isolinux v6.04
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system
  limitations. Because of this, some features from this image may not work...
Using image: debian-11.3.0-i386-netinst.iso (470 MB)
Will reuse 'ldlinux.sys' and 'ldlinux.bss' from 'C:\Users\STEVEN\Downloads\Rufus\syslinux-6.04\20200816\' for Syslinux installation

Format operation started
Requesting disk access...
Will use 'D:' as volume mountpoint
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has an unknown Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Write error [0x00000005] Access is denied.
Could not reset partitions
Re-mounted volume as D: after error

Found USB 2.0 device 'Lexar USB Flash Drive USB Device' (05DC:A81D)
Found card reader device 'Hynix HCG8e '
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1947, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Found USB 2.0 device 'Lexar USB Flash Drive USB Device' (05DC:A81D)
Found card reader device 'Hynix HCG8e '
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1947, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
```

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Error_0x00000005_Access_is_denied

I'm afraid that there's nothing more I can add to what is said in the FAQ entry. Your issue is not from Rufus but from an external application that is interfering from Rufus, so you will need to find what that application is.
