### ISSUE TITLE
Undetermined error RUFUS

### ISSUE THREAD

**Issue by TechHelp69420** [pbatard/rufus#1941]
Hey guys, so I figured out a way to fix the "Undetermined error" on Rufus!
 Step one: Download UUI (universal usb installer)

 Step 2: Open it

 Step 3: Select your OS

 Step 4: Select your iso

 Step 5: Select USB

 Step 6: Done!

Hope this helped!

**Comment by WindowsMI** [comment]
Hi, so I lost the email and password to my account so this is my other account. Anyways this is the log:
[rufus.log](https://github.com/pbatard/rufus/files/8841992/rufus.log)
