### ISSUE TITLE
After use of Rufus the card reader stops to be visible? 

### ISSUE THREAD

**Issue by Herky3D** [pbatard/rufus#1942]
Hello! After use of Rufus on PC Win10 the card reader stops to be visible on the USB ports. Another devices are visible and working, but this type of Card reader (both of two same) are not visible when connectin... strange thing is- I can heard sound of Win "USB connection" but no any other action.. but Rufus it still can "see" the card reader. Any sugestion to make it working normally again? Thanks!

**Comment by pbatard** [comment]
Next time don't ignore the check list that advises you to read the FAQ where this exact question is answered:
https://github.com/pbatard/rufus/wiki/FAQ#Help_how_do_I_restore_my_USB_to_how_it_was_before_I_created_a_bootable_drive
