### ISSUE TITLE
Windows User Experience dialog does not display when Partition scheme is set to MBR

### ISSUE THREAD

**Issue by senolfndk** [pbatard/rufus#1956]
Has the tpm bypass feature been removed in beta version?
![20220625_005122](https://user-images.githubusercontent.com/52818836/175698215-7f3a87e8-8a16-4e6b-9c99-1ed8a9631500.jpg)
![Ekran görüntüsü 2022-06-25 005738](https://user-images.githubusercontent.com/52818836/175698222-04dcb3d2-a21c-4665-a7a2-01a49f78fcf9.png)

**Comment by pbatard** [comment]
Press START. It was just moved to a different place:
![Image1](https://user-images.githubusercontent.com/1206968/175698678-f984ecd7-2de0-431c-9daa-e1a4934d8623.png)

**Comment by senolfndk** [comment]
When you press start, it switches to typing.
![ıj](https://user-images.githubusercontent.com/52818836/175699734-8729e42e-5a19-469f-b06b-73df4b0d21ff.png)

**Comment by pbatard** [comment]
Ah I see. You need to make sure that partition scheme is set to GPT, then you'll see it. I'll try to fix MBR for the release.

**Comment by senolfndk** [comment]
ok

**Comment by pbatard** [comment]
Fix has been applied for the release, but I will keep this issue opened for visibility.

**Comment by leonsk29** [comment]
> Ah I see. You need to make sure that partition scheme is set to GPT, then you'll see it. I'll try to fix MBR for the release.

I have selected GPT as the partitioning scheme in Rufus 3.19 BETA with Windows 11 install media and still doesn't show the Windows User Experience Dialog after clicking START, it just starts formatting and writing the image to the drive without asking anything else except confirmation.

![1](https://user-images.githubusercontent.com/96354594/175778573-ea394543-6aa0-4d9d-99bd-677df8deb7be.png)

![2](https://user-images.githubusercontent.com/96354594/175778578-fbfc17b0-b8ca-4bdb-9b64-dcf17f0b07a1.png)

**Comment by leonsk29** [comment]
> 

Oh, sorry, I posted seconds before you published the fix. I'll try it now. Sorry.

**Comment by pbatard** [comment]
@leonsk29, you should have seen it with GPT.
It seems you are using a custom ISO though.
Can you please post your log? The customization options are dependent on Rufus being able to read the Windows version an build number from the ISO (which it should do fine with __official__ ISOs, but which I cannot guarantee with unofficial ones).
You can access the log with <kbd>Ctrl</kbd>-<kbd>L</kbd> or the small log button left of `START`.
Please paste your log between triple backtick marks like this:
````
```
<Your log>
```
````

**Comment by pbatard** [comment]
Also where exactly did you get your Windows 11 ISO?

**Comment by senolfndk** [comment]
👍
![Ekran görüntüsü 2022-06-25 175005](https://user-images.githubusercontent.com/52818836/175778850-443b41b1-c757-4738-aa0b-af94d609409d.png)

**Comment by leonsk29** [comment]
> Also where exactly did you get your Windows 11 ISO?

You're right, I didn't remember that was a custom ISO involving Windows 10 setup media with a Windows 11 image. Now I tested it with a proper Windows 11 22H2 ISO and it shows up. So sorry for bothering you, my mistake.

**Comment by pbatard** [comment]
Thanks for the update, no worries.

A Windows 10 setup will definitely screw our version detection since we look into `sources/boot.wim` to find if we're dealing with Windows 11.

For the record, you want to see something like `Detected: Windows 11 ISO (Build 22621.1)` in the log when Rufus scans the image, because, if you don't get the report that Rufus detected Windows 11, you won't get the options.

**Comment by TP555** [comment]
Hi

Where i can get the 3,19.1907 Fixed version  ?

**Comment by pbatard** [comment]
> Where i can get the 3,19.1907 Fixed version ?

When it is released on July 1st (**or later**).

If you really can't wait, you can always pick the ALPHA build from the [MinGW Artifcats](https://github.com/pbatard/rufus/actions/runs/2560985467).

**Comment by pbatard** [comment]
Please don't close this issue. It is fixed, but I want to leave it open for visibility until the release.

**Comment by pbatard** [comment]
Locked, as I already explained why I want to keep that issue opened, and appear to be ignored.

**Comment by pbatard** [comment]
Closing this issue with the release of Rufus 3.19.
