### ISSUE TITLE
Rufus not show selection for bypass Microsoft account or any option for bypass TPM or Secure Boot on v3.19 BETA

### ISSUE THREAD

**Issue by georgesaumen** [pbatard/rufus#1959]
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Hello, 

I have used your Beta version and I have tried to bypass Microsoft account step in Windows 11 iso image but when I add Windows 11 iso image to Rufus 3.19 Beta I only see option Standard Windows option and Windows To Go, not see a option to bypass Microsoft account or TPM like you said on Release page. Maybe it have some bug with this Beta release ? Can you check it help me ?

Thanks!

![Untitled](https://user-images.githubusercontent.com/86090065/176153744-098c30c4-8d75-45fb-9d4c-d96c89d181b4.png)

**Comment by pbatard** [comment]
1. Make sure you leave GPT selected
2. Press `START`
3. See what you've been missing, that is described in the release notes for the BETA as _"Secure Boot and TPM bypass have now been moved to (a new) dialog"_
