### ISSUE TITLE
Issue #1956 remains in ALT+E mode (BIOS or UEFI)

### ISSUE THREAD

**Issue by alphadogmnk** [pbatard/rufus#1962]
Windows User Experience dialog does not display.

**Comment by leonsk29** [comment]
> Windows User Experience dialog does not display.

The same happened to me, and the issue was that I was using a custom ISO file and the software wasn't detecting a Windows 11 image. Is your ISO original? It doesn't matter if it was created using UUPDump, it's OK if that's the case.
