### ISSUE TITLE
Extended Intallation option not available in the latest update

### ISSUE THREAD

**Issue by deepindersinghbti** [pbatard/rufus#1976]
I want to create a Windows 11 bootable flash drive for unsupported PCs. I followed these steps:

1. Downloaded the latest version of Rufus from the official website
2. Plugged in my flash drive
3. Selected the Windows 11 ISO file which I had downloaded when Windows 11 was released (near to October 2021)
4. Clicked the **Image option** drop-down menu

According to various tutorials that I saw on YouTube and the internet, there should be aqn option named **Extended Windows installation**, but it is missing in my case. I see only 2 options: **Standard Windows Installation** and **Windows To Go**. Where is the Extended installation option? Has it been removed in the latest update?

![Screenshot (29)](https://user-images.githubusercontent.com/85491004/177945388-2f4077f1-b899-45a6-ad9d-7d5a38aa4555.png)

**Log:**
Rufus x86 v3.19.1911
Windows version: Windows 10 Pro, 64-bit (Build 19044.1806)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
NOTE: This device is a USB 3.0 device operating at lower speed...
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1881, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x2A447260
Drive has an unknown Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Detected File System: FAT32
  Size: 14.4 GB (15471493632 bytes)
  Start Sector: 63, Boot: Yes

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Help_I_no_longer_see_the_option_to_bypass_TPMSecure_Boot_with_Windows_11
