### ISSUE TITLE
Only detecting up to 63 Drives?

### ISSUE THREAD

**Issue by kuugan** [pbatard/rufus#1980]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------
<Please describe your issue here>
When messing around with virtual disks in windows, I decided to attempt making a copious amount of them and see how many of them would mount before windows would break, I know it's kind of dumb seeing that modern operating systems are built to handle that kind of stuff but key, I'm dumb so 🤷🏻‍♀️ 

I left the drives mounted while I'm still experimenting with the VHDs, and opened Rufus to make an installer, and noticed despite 148 "drives" being present, Rufus reports "63 devices found", same is shown in the Device list, where it will show 63 of the virtual disks, and as my usb drives that are connected at the moment are 145-148, they aren't showing in Rufus.

The solution is just to not be dumb like me and have over 63 "drives" connected but still thought it was a funny odd bug.
```

**Comment by pbatard** [comment]
I'm afraid Rufus is not designed for this kind of usage.

See https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want.
