### ISSUE TITLE
New Windows 11 Features

### ISSUE THREAD

**Issue by westlake-san** [pbatard/rufus#1983]
Hello,

Are you sure the new feature in Windows 11 is working well? I can't even find the options that were included in the previous version.
I wanted to see if I could actually get around the need for the account, but I couldn't.

![3 19](https://user-images.githubusercontent.com/53657167/178962352-cf1c2417-19aa-4230-8f70-d25d19c07517.png)

![3 18](https://user-images.githubusercontent.com/53657167/178962356-b976aed6-f76c-4fae-95b3-63bb16dee5e7.png)

Thanks!

**Comment by pbatard** [comment]
Next time, please follow the check list and [look at the FAQ to see if your question has already been answered](https://github.com/pbatard/rufus/wiki/FAQ#Help_I_no_longer_see_the_option_to_bypass_TPMSecure_Boot_with_Windows_11).
