### ISSUE TITLE
Create an ISO

### ISSUE THREAD

**Issue by sohail579** [pbatard/rufus#1984]
I use Ventoy to create a bootable USB so all i need is the ISO i like how Rufus allows you to mod the windows 11 ISO.  is there a way for Rufus to just out put a modified ISO from the Original rather than having to burn the image to a USB device

**Comment by JonnyTech** [comment]
Use [MediaCreationTool.bat](https://github.com/AveYo/MediaCreationTool.bat).

**Comment by sohail579** [comment]
> Use [MediaCreationTool.bat](https://github.com/AveYo/MediaCreationTool.bat).

Thanks will this allow me to also bypass the mandatory log in using a windows account?
