### ISSUE TITLE
[Feature request] Chrome os (Flex) download

### ISSUE THREAD

**Issue by shikulja** [pbatard/rufus#1985]
The original flash preparation utility doesn't work well, rufus can handle it better.

**Comment by pbatard** [comment]
Sorry, but I am not interesting in solving this specific issue in Rufus/Fido. The cost/benefit ratio seems way too high (see also [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want)). But if somebody else wants to solve ChromeOS ISO downloads for [Fido](https://github.com/pbatard/Fido) and send a Pull Request there, I may consider it.
