### ISSUE TITLE
New selection dialog for Windows 11

### ISSUE THREAD

**Issue by qo4on** [pbatard/rufus#1986]
Can you please clarify where to find this new selection dialog for Windows 11 setup customization? I would like to choose options without TPM and without UEFI.
![Untitled](https://user-images.githubusercontent.com/35609308/179672270-0fb43b92-a9e9-4a62-8051-ddc84df8d697.png)

**Comment by JonnyTech** [comment]
After the `START` button is pressed, if a valid Windows 11 ISO is detected then the relevant dialog shall be displayed.

**Comment by qo4on** [comment]
Thank you!
