### ISSUE TITLE
Non-existent bypass key

### ISSUE THREAD

**Issue by awuctl** [pbatard/rufus#1990]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

My "issue" is with https://github.com/pbatard/rufus/blob/master/src/rufus.c#L141.
Judging by #1791 and #1809, the author seems to care about not including things that are placebo and don't actually exist so I would like to report that `BypassStorageCheck` is not used by any official installer file and does not do anything, **ever**.

The function that utilizes the LabConfig keys is `Callback_ValidateHardwareRequirements` from `sources/winsetup.dll`.
This function calls four (relevant) others, in order:
1. `Callback_VerifyRAMRequirements`: Checks the amount of RAM and ignores it if `BypassRAMCheck` is present in LabConfig.
2. `Callback_VerifyProcessorSupported`: Checks the CPU core count and frequency, cannot be bypassed.
3. `Callback_VerifySecureBoot`: Queries the kernel for `SystemSecureBootInformation`, ignores the result as long as `BypassSecureBootCheck` is present in LabConfig.
4. `Callback_VerifyTPMSupported`: Queries TPM information with `tbs.dll` and verifies the TPM version, ignores the result if `BypassTPMCheck` is present in LabConfig.

These are the only functions where `Bypass[...]` LabConfig keys are used, nothing else cares. (Proof at the bottom)

There is also `Callback_ValidateInstallDrive`, responsible for checking the disk size - registered as a module for use by the "disk/partition chooser" part. The **only** reason it lets you go with less than 52 GiB is because the generic failure error for "disk too small" has, in this case, the severity bit set to SUCCESS instead of FAILURE (`0x0030001f` instead of `0x8030001f`, probably intended) - not because of some magical registry key that's never been used.

(`22000.esd` and `25163.esd` are both Pro en-US metadata ESDs from UUP dump)
![image](https://user-images.githubusercontent.com/61098069/180066958-6b8001d4-fc3d-4269-8944-fae38da6752f.png)

Log
---
Not Applicable

**Comment by pbatard** [comment]
LOL, the irony is that I reluctantly included `BypassStorageCheck` because people were pestering me about not seeing an option for it along the SB/TPM bypasses...

Of course, I never bothered to test it, but I thought since I was giving in and adding the RAM bypass, I might as well group it with the disk check to get rid of some of the _"Why don't you also include `BypassXXXCheck`?"_ requests I was getting.

Thanks a lot for confirming that this bypass is bogus. I'll make sure to remove it in the next version.
