### ISSUE TITLE
Windows 11 customization options not offered

### ISSUE THREAD

**Issue by maw136** [pbatard/rufus#2004]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
The new options dialog for Windows 11 customization is not offered. I have used current official ISO from Microsoft as well as the bleeding edge 25169 build creted with uupdump.net scripts.
I can use 3.18 version without an issue for bypassing TPM/SecureBoot but 3.19 simply has no option for bypassing

Log
---
```
Rufus x64 v3.19.1911 (AppStore version)
Windows version: Windows 11 Pro, 64-bit (Build 25163.1010)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: OpenLocalMachineGPO failed - error 800703ee
Localization set to 'en-US'
Notice: Windows VDS is unavailable
Found VHD device 'Microsoft Virtual Disk'
1 device found
Disk type: FIXED, Disk size: 10 GB, Sector size: 512 bytes
Cylinders: 1305, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x1CC2E1C4
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Detected File System: NTFS
  Size: 10.0 GB (10736369664 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'CCCOMA_X64FRE_EN-US_DV9'
  Detected: Windows 11 ISO (Build 22000.194)
  Size: 5.2 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.wim (version 0.13.1)
Using image: Win11_English_x64v1.iso (5.2 GB)
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'CCSA_X64FRE_EN-US_DV5'
  Detected: Windows 11 ISO (Build 25169.1000)
  Size: 4.1 GB (Projected)
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.wim (version 0.13.1)
Using image: 25169.1000.220723-1625.RS_PRERELEASE_CLIENTMULTI_X64FRE_EN-US.ISO (4.1 GB)


```
<img width="834" alt="image" src="https://user-images.githubusercontent.com/6883328/181767974-287da1a1-82da-440c-88fd-9d484e4e080a.png">
<img width="834" alt="image" src="https://user-images.githubusercontent.com/6883328/181768070-55424ada-5acc-44d3-bbcf-9efaa6cfc17d.png">

**Comment by pbatard** [comment]
> - [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.

{Really?](https://github.com/pbatard/rufus/wiki/FAQ#Help_I_no_longer_see_the_option_to_bypass_TPMSecure_Boot_with_Windows_11)

- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

[Oh, really???](https://github.com/pbatard/rufus/issues?q=TPM)
