### ISSUE TITLE
BCDW ISO (bcdw150z) support

### ISSUE THREAD

**Issue by z0hm** [pbatard/rufus#2009]
rufus don't write bootable usb flash from bootable iso, created with bcdw150z.

**Comment by pbatard** [comment]
Did not follow the check list.

**Comment by z0hm** [comment]
Sorry? Bootable CD Wizard [BCDW](http://bootcd.narod.ru/index_e.htm "Bootable CD Wizard")

![BCDW](http://bootcd.narod.ru/bcdw2.gif)
