### ISSUE TITLE
Rufus was pirated by this software

### ISSUE THREAD

**Issue by 258125** [pbatard/rufus#2018]
https://www.xiaote.com/disktool/

![image](https://s1.328888.xyz/2022/08/12/6JvkE.png)
![image](https://s1.328888.xyz/2022/08/12/6tEJJ.png)
![image](https://s1.328888.xyz/2022/08/12/6Jdlk.jpg)

**Comment by pbatard** [comment]
Well, they didn't remote the copyright or the licensing terms, so it doesn't look like piracy to me.
Anybody is free to create a derivative of Rufus (and name it whatever else they want or change the UI) as long as they respect the GPL.
