### ISSUE TITLE
LOC: Add Hebrew translation

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#204]
No volunteers yet. Will require RTL support: #192.

**Comment by pbatard** [comment]
Someone kindly volunteered to work on it.

**Comment by pbatard** [comment]
And translator appears to have dropped out... dammit!

**Comment by NSbuilder** [comment]
I want to try to translate rufus to hebrew but when mixing english and hebrew in the same line the text become hard to read ( I have to write some stuff in english like "MBR", "BIOS" etc...).
Also - need to make rufus RTL...

**Comment by pbatard** [comment]
Hi __NSbuilder__,

If you could do it, that would be __awesome__! Hebrew is the [last missing language](https://github.com/pbatard/rufus/wiki/FAQ#What_languages_are_natively_supported_by_Rufus) from the ones I want Rufus to be translated in.

For your information, Rufus already supports RTL as it already has Arabic or Persian translations. All you need is add a:
```
a "r"
```
line at the beginning of your `.loc` section.

Please me sure you have a look at the localization guide [here](https://github.com/pbatard/rufus/wiki/Localization), which should help you through the translation process.
RTL can be tricky, as [you may need to add `RIGHT-TO-LEFT EMBEDDING` and `POP DIRECTIONAL FORMATTING` marks within your translation](https://github.com/pbatard/rufus/blob/master/res/localization/rufus.loc#L851-L854), to get stuff like parenthesis display properly when mixing languages.

At any rate, thank you very much for wanting to give it a try! If you need help, don't hesitate to drop me a mail at: pete@akeo.ie.

**Comment by NSbuilder** [comment]
Is the loc file had been updated?

**Comment by pbatard** [comment]
Just one line at the end, but you can ignore it until I announce the new changes to all translators (#763). Any item newly added in the loc file is not final until I e-mail all translators to let them know that updates are needed, as they are subject to change...

**Comment by pbatard** [comment]
@NSbuilder,
Unless you indicate otherwise, I'm going to assume that you have given up on your proposal to provide a Hebrew translation for Rufus...

**Comment by pbatard** [comment]
For anyone wanting to carry on from where @NSbuilder left (who probably did 85% of the work already and that's awesome! 👏), you can find a `rufus.loc` with his changes [here](https://rufus.akeo.ie/testing/rufus_loc.7z).
