### ISSUE TITLE
Let's Connect You To a Network - No Networks Listed; Next is Greyed out.  No options.

### ISSUE THREAD

**Issue by Ghee36** [pbatard/rufus#2042]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Network is not connected or available, yet still being prompted by Microsoft to be infected with online account requirement. The setup page immediately displays the Network requirement page ( a momentary black rectangle pops up then disappears also) but lists no networks available without any option to continue the bypass. Please tell me I did something incorrect.  I am using the latest Windows 11 iso available; Win11_English_x64v1>

Log
---
```
<Rufus x86 v3.20.1929
Windows version: Windows 11 Pro, 64-bit (Build 21354.1)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found USB 3.0 device ' USB  SanDisk 3.2Gen1 USB Device' (0781:5581)
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3742, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {90197BD7-9483-4444-9B4C-F5AD733E9178}
Max parts: 128, Start Offset: 17408, Usable = 30784059904 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: FAT32
  ID: {83F3F69E-47DD-4398-AAD3-193FDEA9E9BC}
  Size: 28.7 GB (30781933056 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2 (UEFI:NTFS):
  Type: Microsoft Basic Data Partition
  Name: 'UEFI:NTFS'
  Detected File System: FAT12
  ID: {2213989F-2225-4BE2-95C2-78CB288E509C}
  Size: 1 MB (1048576 bytes)
  Start Sector: 60123011, Attributes: 0x9000000000000000
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'CCCOMA_X64FRE_EN-US_DV9'
  Detected: Windows 11 ISO (Build 22000.194)
  Size: 5.2 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.wim (version 0.13.1)
Using image: Win11_English_x64v1.iso (5.2 GB)

Stage 1: Examining basic file system structure ...
  1280 file records processed.
File verification completed.
 Phase duration (File record verification): 34.24 milliseconds.
  0 large file records processed.
 Phase duration (Orphan file record recovery): 0.51 milliseconds.
  0 bad file records processed.
 Phase duration (Bad file record checking): 0.45 milliseconds.

Stage 2: Examining file name linkage ...
  1486 index entries processed.
Index verification completed.
 Phase duration (Index verification): 140.95 milliseconds.
 Phase duration (Orphan reconnection): 1.52 milliseconds.
 Phase duration (Orphan recovery to lost and found): 0.03 milliseconds.
  0 reparse records processed.
  0 reparse records processed.
 Phase duration (Reparse point and Object ID verification): 1.73 milliseconds.

Stage 3: Examining security descriptors ...
Security descriptor verification completed.
 Phase duration (Security descriptor verification): 11.68 milliseconds.
  103 data files processed.
 Phase duration (Data attribute verification): 0.93 milliseconds.

Windows has scanned the file system and found no problems.
No further action is required.

  30060481 KB total disk space.
   5455388 KB in 953 files.
       344 KB in 105 indexes.
     43781 KB in use by the system.
     41168 KB occupied by the log file.
  24560968 KB available on disk.
      4096 bytes in each allocation unit.
   7515120 total allocation units on disk.
   6140242 allocation units available on disk.
Total duration: 193.89 milliseconds (193 ms).
NTFS Fixup completed.

Found USB 3.0 device ' USB  SanDisk 3.2Gen1 USB Device' (0781:5581)
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3742, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {4686E6A8-D612-4492-9C93-A323A361BFFF}
Max parts: 128, Start Offset: 17408, Usable = 30784059904 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: NTFS
  ID: {E41D04DA-4542-4728-A9B6-6D7823E117C6}
  Size: 28.7 GB (30781933056 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2 (UEFI:NTFS):
  Type: Microsoft Basic Data Partition
  Name: 'UEFI:NTFS'
  Detected File System: FAT12
  ID: {2625543E-7B25-46FD-A515-FAED2E12D9AA}
  Size: 1 MB (1048576 bytes)
  Start Sector: 60123011, Attributes: 0x9000000000000000
>
```

**Comment by pbatard** [comment]
>  I am using the latest Windows 11 iso available; Win11_English_x64v1

Then Rufus does not apply any bypass for the Microsoft online account so any issue related with online account setup are yours to solve.

The online account bypass applies to Windows 11 22H2 __only__, which has not officially been released by Microsoft yet, and you are using 21H2.

I'm going to assume that you tried to install Windows 11 __Home__ 21H2, which __requires__ an online account, and that I am not planning to do anything about in Rufus (because there's not much point to it when 22H2 is about to be released and Home users will be switching to installing this version, which Rufus should be able to bypass), which is why you are seeing your issue.

In that case, I will advise you to enable the _Set a local account option using the same name as this user's_ option in Rufus but that's all I can advise you to do.

Also, you did not provide the log of how you created the drive, which is what I am requesting. Providing the log after you created the drive does not help me, as it removes __critical__ information that I need to see about your drive creation process to actually be able to help you.

Because of this, I am going to assume that I have answered your question and close this issue.
