### ISSUE TITLE
Rufus format taking too long and not copying files

### ISSUE THREAD

**Issue by TheQuantumKukisMurftBoy** [pbatard/rufus#2044]
So, today I accidentaly damaged my Kali usb stick, so I formated it from Windows explorer and tried to reinstall Kali Live, but the format is taking TOO long, and it stops at "FORMATING 100.0%" and doens't starts copying files, pls help.

**Comment by pbatard** [comment]
Can't help you if you don't follow the check list and don't provide a log, sorry.
