### ISSUE TITLE
About remove Windows 11 22H2 installation restrictions

### ISSUE THREAD

**Issue by tkp206093** [pbatard/rufus#2048]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<I can't see about the no TPM option in win11 22H2 iso.
Also, can you bypass the mandatory requirement for a Microsoft account>

Log
---
Rufus x86 v3.20.1929 (Portable)
Windows version: Windows 11 Pro, 64-bit (Build 22621.521)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0404 (zh-TW)
Will use default UI locale 0x0404
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'zh-TW'
Found USB 3.0 device 'PNY USB 3.0 FD USB Device' (154B:6008)
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3850, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {16F58019-72DB-45B2-A997-3040D7CFA2D3}
Max parts: 128, Start Offset: 17408, Usable = 31675349504 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: FAT32
  ID: {C46495E8-6BE7-4530-9242-87FA34D496FA}
  Size: 29.5 GB (31674318336 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'CCCOMA_X64FRE_ZH-TW_DV9'
  Detected: Windows 11 ISO (Build 22621.1)
  Size: 5.1 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.wim (version 0.13.1)
Using image: Win11_22H2_Chinese(Traditional)_x64.iso (5.1 GB)

<FULL LOG>
Rufus x86 v3.20.1929 (Portable)
Windows version: Windows 11 Pro, 64-bit (Build 22621.521)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0404 (zh-TW)
Will use default UI locale 0x0404
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'zh-TW'
Found USB 3.0 device 'PNY USB 3.0 FD USB Device' (154B:6008)
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3850, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {16F58019-72DB-45B2-A997-3040D7CFA2D3}
Max parts: 128, Start Offset: 17408, Usable = 31675349504 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: FAT32
  ID: {C46495E8-6BE7-4530-9242-87FA34D496FA}
  Size: 29.5 GB (31674318336 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'CCCOMA_X64FRE_ZH-TW_DV9'
  Detected: Windows 11 ISO (Build 22621.1)
  Size: 5.1 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.wim (version 0.13.1)
Using image: Win11_22H2_Chinese(Traditional)_x64.iso (5.1 GB)

**Comment by JonnyTech** [comment]
> I can't see about the no TPM option in win11 22H2 iso.

https://github.com/pbatard/rufus/wiki/FAQ#Help_I_no_longer_see_the_option_to_bypass_TPMSecure_Boot_with_Windows_11

>  Also, can you bypass the mandatory requirement for a Microsoft account>

https://github.com/pbatard/rufus/wiki/FAQ#Help_I_dont_see_the_option_to_bypass_the_need_for_a_Microsoft_account_with_Windows_11

>  I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.

Really?
