### ISSUE TITLE
Version 3.20 doesn't have "no tpm + no secure boot" options.

### ISSUE THREAD

**Issue by sadmansajid** [pbatard/rufus#2053]
Version 3.20 does not have any op5on for bypassing tmp and secure boot for win11 iso. I downgraded to version 3.17 and got it working. 
The "windows to go" addition is sweet though.

**Comment by dobova86** [comment]
I had to use 3.18 Version as is the last supporting the noTPM option .. I hope this very helpful opt will come back!
