### ISSUE TITLE
Rufus can not work with this ISO.

### ISSUE THREAD

**Issue by Smichara** [pbatard/rufus#2063]
Rufus can not work with this ISO.
https://mega.nz/file/79hQSK5K#IAA9Q1d2VZSPwgKzj_JXZbQqHr4nRyAXj2MQb9KlU2w

**Comment by pbatard** [comment]
[Answered in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Im_trying_to_work_with_an_ISO_but_Rufus_says_its_unsupported). You'll find a DOS image under `[BOOT]`.
