### ISSUE TITLE
[feature suggestion][Windows 11] "BypassNRO" to allow offline installation (bypass internet connection requirement)

### ISSUE THREAD

**Issue by eladkarako** [pbatard/rufus#2066]
<details><summary>»</summary>

﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
<FULL LOG>
```

</details>

providing link, avoiding duplication..

<a href="https://github.com/ventoy/Ventoy/issues/1916">[feature suggestion] please add "BypassNRO" registry key to allow bypassing the new Windows 11 internet requirement (allows offline installation) #1916</a>

**Comment by pbatard** [comment]
It's __ALREADY__ there.

![](https://i.stack.imgur.com/5s1vg.png)

Was added in version 3.19, which was released months before the Windows 11 22H2 release.

**Comment by pineapple63** [comment]
The menu appears after you click start
