### ISSUE TITLE
Custom Flasch Drive Partition Size.

### ISSUE THREAD

**Issue by Galifor** [pbatard/rufus#2078]
Problem:
I have one Fake Flash that have only 16Gb from deklareted 64Gb.
I have create 16Gb partition on this Flash Drive and use it. 
But i can't use it with Rufus. 
It ist posible to create in Rufus Custom Parition?

Thanks.

**Comment by pbatard** [comment]
Next time, follow the checklist, which advised you to [search if your question had already been answered in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Why_does_Rufus_need_to_delete_all_partitionsvolumes_when_creating_a_drive).
