### ISSUE TITLE
Soften bug report acceptance criteria

### ISSUE THREAD

**Issue by powerbroker** [pbatard/rufus#2085]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
The criteria requires monkey work which can have totally no sense in bug reproduction. Moreover, the "full log" can bloat bug report out of max comment limit - 65536 characters.
E.g. #2083 and #2084 both definitely don't require the full log, bad blocks check, plugging USB to another port, replacing the stick and so on.

Log
---
```
Rufus x86 v3.20.1929 (Portable)
Windows version: Windows 11 (Unknown Edition 0xBF), 64-bit (Build 22000.1098)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'JetFlash Transcend 32GB USB Device' (8564:1000)

...........................................................................................

Oh, huck!!! - Comment is too long (maximum is 65536 characters)

There was an error creating your Issue: body is too long (maximum is 65536 characters).

me so sorry, guys, so sorry! i truly cannot help it..............

```

**Comment by pbatard** [comment]
> The criteria requires monkey work which can have totally no sense in bug reproduction.

You clearly haven't been trying to support thousands of users entirely for free, and therefore request them to provide the information you need to be able to help them.

If the log is too long, you can split it, paste it to some other web site or link it.

I do need to see the full log, __ALWAYS__, and I am not ever going to relax that rule.

It's really not that difficult to drag and drop a file to a GitHub issue:
[100kb.txt](https://github.com/pbatard/rufus/files/9976986/100kb.txt)

**Comment by powerbroker** [comment]
> I do need to see the full log, **ALWAYS**, and I am not ever going to relax that rule.

in most cases agree that it is. however, there are cases when it is not enough or not necessary.
e.g. #2084, where written in m$-way error message "Could not mount 'F:\sources\boot.wim [2]' on 'C:\Temp\Ruf70C9.tmp': [0x00000057] The parameter is incorrect." says nothing about the error. you need knowledge of context where error happens, which is not mentioned in full log. or in case of UI/cosmetic/i18n bug no need in full log, a screenshot is much helpful.

> You clearly haven't been trying to support thousands of users entirely for free, and therefore request them to provide the information you need to be able to help them.

an absolutely sound statement, but I will offer an addition to it. there are thousands of projects which a user may wish to help with testing while using them. in each case the user, in addition to find the way to reproduce bug and describe it have to:

1. register in project's bug tracker
2. learn how to use it
3. search for similar bug reports and increase the "requested" field
4. OR report the new issue
   4.1 learn the acceptance criteria of each project owner and fit the issue description to it

e.g. when you report a KiCad issue and include system information they require as additional comment( but not as part of the initial description), your report is **automatically** footballed out. but instead should be **automatically** sucked-in from additional comment and whole report re-formatted in the way developer is comfortable with.

the point is that not every user is qualified tester(to write ideal reports), and there is no single standard we all can follow - everyone invents own bicycle. the absolute comfort for developer may turn into "there are too hucking much obstacles to report a bug, so just huck it" for user. 
so, we are looking for a balance where it is convenient for all participants ;)

**Comment by pbatard** [comment]
This is bullshit. When you leave it to people to decide what information they __think__ they should provide, you always end up with missing data. I speak from experience.

It is simply not realistic to tell people "hey it's okay to provide the information you want when opening an issue report". Not realistic and actually not helpful for anybody, including the user requesting help, due to the extra back and forth that it induces.

If you want support "a la carte", and especially if you want it for software you didn't pay for, I will kindly request that you go look somewhere else, because if you believe that going through the "hurdle" of following a check list, __that is only designed to actually help the end user__ is too much, I will kindly ask that you do not use my software, because I genuinely don't have time for this.
