### ISSUE TITLE
[Feature] Add ability to flash to partition on the drive, as opposed to the whole drive.

### ISSUE THREAD

**Issue by ibay770** [pbatard/rufus#2097]
Some OS like Mac, require that the installer be flashed to the drive, or if you want multiboot, an installer per partition. So I'm wondering if its possible to just flash an image to the partition instead.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Why_does_Rufus_need_to_delete_all_partitionsvolumes_when_creating_a_drive
