### ISSUE TITLE
BSOD with a PAGE FAULT IN NONPAGED AREA error

### ISSUE THREAD

**Issue by free0n-cfh3** [pbatard/rufus#2109]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
Rufus x86 v3.21.1949
Windows version: Windows 10 Pro, 64-bit (Build 19044.1826)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0419 (ru-RU)
Will use default UI locale 0x0419
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'ru-RU'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
NOTE: The Russian (Русский) translation requires an update, but the current translator hasn't submitted one. Because of this, some messages will only be displayed in English.
If you think you can help update this translation, please e-mail the author of this application
Found USB 2.0 device 'JetFlash Transcend 16GB USB Device' (8564:1000)
1 device found
Disk type: Removable, Disk size: 16 ГБ, Sector size: 512 bytes
Cylinders: 1951, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {71479030-EA9E-47E8-BEB4-C883F8FA6607}
Max parts: 128, Start Offset: 17408, Usable = 16052609536 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: FAT32
  ID: {9ACE5060-C8A2-40E7-B7D0-39444C9E9921}
  Size: 14.9 GB (16051578368 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
```

Mini dump

<html><body>

Dump File | Crash Time | Bug Check String | Bug Check Code | Parameter 1 | Parameter 2 | Parameter 3 | Parameter 4 | Caused By Driver | Caused By Address | File Description | Product Name | Company | File Version | Processor | Crash Address | Stack Address 1 | Stack Address 2 | Stack Address 3 | Computer Name | Full Path | Processors Count | Major Version | Minor Version | Dump File Size | Dump File Time
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
121022-11093-01.dmp | 10.12.2022 17:08:29 | PAGE_FAULT_IN_NONPAGED_AREA | 0x00000050 | 00000000`047a9300 | 00000000`00000003 | fffff807`12627387 | 00000000`0000000f | ntoskrnl.exe | ntoskrnl.exe+3f8590 |   |   |   |   | x64 | ntoskrnl.exe+3f8590 |   |   |   |   | C:\windows\Minidump\121022-11093-01.dmp | 6 | 15 | 19041 | 2 036 028 | 10.12.2022 17:10:27

</body>
</html>

**Comment by pbatard** [comment]
Not enough data &rarr; Closed.
