### ISSUE TITLE
Powershell Script cannot be loaded because running scripts is disabled on this system.

### ISSUE THREAD

**Issue by jamesmc2000** [pbatard/rufus#2114]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
When I select download, nothing happens. I see it is an issue with PowerShell running scripts. I have modified the execution policy on my machine to be Allsigned. I also ran the script from PowerShell, and I was able to get it to run manually. 

Log
---
```
Rufus x86 v3.21.1949
Windows version: Windows 11 Enterprise, 64-bit (Build 22000.1219)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'SanDisk Firebird USB Device' (0781:5530)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 67 MB, Sector size: 512 bytes
Cylinders: 8, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Downloading https://github.com/pbatard/Fido/releases/download/v1.37/Fido.ps1.lzma
File length: 18.0 KB
Successfully downloaded 'Fido.ps1.lzma'
Download signature is valid ✓
Script signature is valid ✓
File C:\Users\jmcalister\AppData\Local\Temp\{F48EE862-7C7D-4DAA-8F27-646BF0F48435}.ps1 cannot be loaded because 
running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
Exited download script with code: 1

```

**Comment by pbatard** [comment]
Not much I can do for you. You are using a nonstandard Windows environment, and I am not going to spend time (that I genuinely don't have) trying to support those.
