### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gamesdj** [pbatard/rufus#2129]
![image](https://user-images.githubusercontent.com/46547176/211016367-c1f48262-83b2-41f1-a824-ffce1739cdf3.png)
![image](https://user-images.githubusercontent.com/46547176/211016259-14eff86c-360b-41b7-8bf9-79b3077ee95b.png)

**Comment by pbatard** [comment]
I've confirmed that this is a general issue and I have created #2130 (as well as pbatard/Fido/issues/52) to track it better.

Please make sure to look at #2130 where more information will be available when we have it.
