### ISSUE TITLE
Malware download showed up when googling Rufus

### ISSUE THREAD

**Issue by phyolim** [pbatard/rufus#2134]
I'm not sure if this is an appropriate place.

But here's what happened - I googled Rufus and clicked on the first result ( which was an ad )that showed up without looking too closely. It took me to an imposter link- `rufus <dash> en <dot> motorloz <dot> com`. Actual url is much longer. But the site that it took me looked the same as regular Rufus site. After I download and ran the file the window just disappeared. So I tried it a few times. Finally realized that it was an imposter site. Then I clicked on the second result ( the real Rufus site ) to download and create my bootable iso.
A few hours later, I got an email regarding a Google ad campaign. So I logged in to check and sure enough, there was a campaign with another imposter Rufus link created in MY Google ads account.. I think they might have hijacked the session on my pc with that fake Rufus exe. I reported the ad to Google. So it's gone now. Just thought I'd post here / document in case someone else come across the same situation.

**Comment by pbatard** [comment]
Thanks for the report. I edited your URL to not make it too easy to go to that site or advertise it further.

Unfortunately, with the success of Rufus, malicious people have been trying to peddle malware by creating these fake website that copy the homepage content exactly but serve a malicious link.

And unfortunately, Google seem to be turning a blind eye on this as, despite being reported over and over, they manage to get into ad results.

The only thing that can be done, sadly, is continue to report those as you did, and hope that Google will one day stop trying to make a quick buck on obvious scam that it should be able to filter out.

As this issue will remain in the tracker for people to see, I will close it.
