### ISSUE TITLE
XP x64 Permissions Issue - Doesn't Install with Rufus - Same ISO works fine when burned to DVD

### ISSUE THREAD

**Issue by own3mall** [pbatard/rufus#2147]
Issue description
-----------------
Windows XP x64 encounters a file permission denied error during installation via USB from a rufus written drive (written using rufus 3.20).  It will finish installing despite the error, but nothing in control panel works, and the entire OS is broken.  

I burned the same ISO to a DVD, and installation worked fine without running into a permissions issues.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED
