### ISSUE TITLE
Rufus not working 

### ISSUE THREAD

**Issue by Rishi1999-star** [pbatard/rufus#2150]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- `[x]` If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
Not detecting any of my usb
<So the rufus doesn't detect my usb. I have tried multiple times.In log it is showing that a device is eliminated because it didn't report itself as a disk>

Log
---

![16749354259091069493035928707234](https://user-images.githubusercontent.com/123836128/215287923-8b34d580-fc61-454c-921e-66688821043a.jpg)

**Comment by pbatard** [comment]
[Next time, follow the instructions. ](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Error_0x00000005_Access_is_denied)
