### ISSUE TITLE
HOW TO RECOVERY USB DRIVE AFTER USING RUFUS ?

### ISSUE THREAD

**Issue by UnrealKaraulov** [pbatard/rufus#2157]
HOW TO RECOVERY USB DRIVE AFTER USING RUFUS ??

(DVD PLAYER CAN'T SEE FILES)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Help_how_do_I_restore_my_USB_to_how_it_was_before_I_created_a_bootable_drive
