### ISSUE TITLE
After creating a bootable flash drive, the ability to interact with it disappeared

### ISSUE THREAD

**Issue by Zver98** [pbatard/rufus#2158]
Hello!
Tried today to make bootable linux stick with Rufus with Constant Partition Size
Specified the image, did everything as usual
The formatting process has begun, after which the recording has begun
While the process was going on, I walked away, when I returned, it was written ready, but when I tried to close the program, a warning appeared that if I stopped the process, the flash drive might be damaged, so I didn’t stop anything, I pressed no, after which, an error followed image recording and the flash drive began to behave strangely.
When connected to a computer, it is determined, shows the name of the volume, the amount of memory of one of the volumes.
But when you try to access the flash drive somehow, there is a shutdown sound and the name of the device changes
I already tried to format it in every way, I tried to restore it through the off program of the manufacturer - to no avail.
Unfortunately, Rufus did not save the magazine, because. At first, I didn't understand what happened.
Any ideas how this could have happened and is it possible to fix it?
jetflash transcend 64gb
Volume: D:
Controller: Silicon Motion SM3265 AC
Possible Memory Chip(s): Not available
Chip F/W: ISP NONE
MP: ::::::P
MPTOOL Ver.: 196.90.177
VID: 090C
PID: 3265
Manufacturer: Silicon Motion,Inc. 
Product: SM3265AB MEMORY BAR 
Query Vendor ID: SMI     
Query Product ID: USB MEMORY BAR  
Query Product Revision: 1000
Physical Disk Capacity: 0 Bytes
Windows Disk Capacity:  0 Bytes
Internal Tags: 8VAE-ASFL
USB Version: 3.00
Declared Power: 504 mA
ContMeas ID: E1A0-01-EE
Microsoft Windows 10 x64 Build 22621
------------------------------------
http://www.antspec.com/usbflashinfo/
Program Version: 9.4.0.645

I am attaching a video with the behavior of the flash drive.

https://user-images.githubusercontent.com/3184772/217036417-204ea238-4bcd-48d7-9cac-6a159dbfa4b5.mp4

**Comment by pbatard** [comment]
Not much that can be done. Your drive looks dead. Next time, please try to follow the check list.
