### ISSUE TITLE
I would like to be able to add direct write capabilities for SATA and Nvme drives instead of USB transfer

### ISSUE THREAD

**Issue by ghost** [pbatard/rufus#2162]
I would like to be able to add direct write capabilities for SATA and Nvme drives instead of USB transfer
我希望能够增加SATA和Nvme硬盘的直接写盘功能而非USB转接

Sometimes I want to use Rufus for local SATA or Nvme hard disk direct writing, but I find that Rufus does not support it, and it is really difficult for me to find other tools, hoping to add this feature
有时候我想要使用Rufus进行本地SATA或Nvme硬盘直接写盘我发现Rufus并不支持，寻找其他工具对我来说属实很费事情，希望能够增加此功能

**Comment by pbatard** [comment]
If your SATA drive is set as hot-plug in your BIOS, you can use the **UNSUPPORTED** and undocumented cheat mode <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>F</kbd>.

That's as much support for SATA drives as you're gonna get and whether you can set the drive as hot-plug or whether your BIOS supports it is up to you to find.

[That's as much support as you're ever going to get for intenal drives](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Do_you_plan_to_support_internal_HDDsSSDs).
