### ISSUE TITLE
Run rufus from command line

### ISSUE THREAD

**Issue by pabansal** [pbatard/rufus#2170]
Hi All,

I am want to run rufus from command line as I am automating the burning of my image file to USB.

I used below command :
rufus-3.3 -i __image file path

But this opened the window where I have to click on start.
I do not want to click on start but it should automatically start burning USB after I run the command.

Can you please guide me how to do it.
So in short, I want to automate my USB burbing process using command line options.

Thanks,
Pallavi Bansal

**Comment by pbatard** [comment]
Per #111, there is **no** full commandline support in Rufus, and it is only a full UI application for now.

I have some plans to dry to add this kind of functionality **eventually**, but it requires a lot of work, and the demand for a non UI Rufus is minimal, so it will most likely take at least 2 to 5 years before I get there.

This means that you cannot use Rufus to "automate my USB burbing process using command line options".

See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_cant_you_just_add_the_feature_I_want
