### ISSUE TITLE
The small question mark at target system doesn't work? 

### ISSUE THREAD

**Issue by longtth** [pbatard/rufus#2181]
When using Rufus, I see a small question mark when chosing target system = UEFI (non CSM), 
is it intended to open a website with definition about UEFI? 

![image](https://user-images.githubusercontent.com/1010849/220399496-efedf067-f2fd-42f7-a7ec-5d05fa3d333c.png)

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: 3.18.1877` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
It's supposed to show you additional information when hovering your cursor over it. That's all:

![Image1](https://user-images.githubusercontent.com/1206968/220411786-2e85d141-7c41-4ee4-b2fd-37f6631d9fbd.png)
