### ISSUE TITLE
Windows 11 extraction failure

### ISSUE THREAD

**Issue by Aayushman210310** [pbatard/rufus#2190]
I have downloaded Windows 11 iso from microsoft official website and when I tried to flash on my usb pendrive it shows "iso image extraction failure"
![Screenshot (2)](https://user-images.githubusercontent.com/86190496/222045056-00402839-ac22-4e9e-8917-bdde7a0fda09.png)

**Comment by JonnyTech** [comment]
Please complete the new issue checklist, especially the following:

```
If you are reporting an issue when trying to run Rufus, or when trying to boot a media created by Rufus, you *MUST* provide a log, 
```

No log?

```
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.
```

No verification?

**Comment by pbatard** [comment]
Since you did not provide a log and did not produce the checksum, I am going to have to guess corrupted drive or corrupted ISO.

Next time, **if** you actually want people to help you, please follow what's requested of you because we can't "guess" your issue from just a screenshot.
