### ISSUE TITLE
Add support for .bin image. Would like to create ChromeOS Flex bootable usb drive.

### ISSUE THREAD

**Issue by 49studebaker** [pbatard/rufus#2196]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Could you make it possible to create a bootable usb drive from a .bin file? Google distributes ChromeOS Flex as a .bin instead of .iso image.

https://support.google.com/chromeosflex/answer/11541904?hl=en&ref_topic=11551271

Latest ChromeOS Flex installer image:
https://dl.google.com/chromeos-flex/images/latest.bin.zip

Thanks.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Already supported. Heck, you don't even need to decompress the image. You just need to select that `.bin` or `.bin.zip` in Rufus:

```
Rufus x86 v3.21.1949
Windows version: Windows 11 Pro for Workstations, 64-bit (Build 22621.1344)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0809 (en-GB)
Will use default UI locale 0x0809
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Could not get node connection information for 'USB\VID_0781&PID_5580\AA011124161316440239': [0x0000001F] A device attached to the system is not functioning.
Found USB device 'SanDisk Extreme USB Device' (0781:5580) [ID]
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3818, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x009D377F
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Detected File System: FAT32
  Size: 29.2 GB (31405899776 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  'D:\Imgs\chromeos_15117.112.0_reven_recovery_stable-channel_mp-v2.bin.zip' doesn't look like an ISO image
Disk image analysis:
  Image is a compressed bootable disk image
Using image: chromeos_15117.112.0_reven_recovery_stable-channel_mp-v2.bin.zip (1.1 GB)

Format operation started
Requesting disk access...
No drive letter was assigned...
Will use 'F:' as volume mountpoint
Opened \\.\PhysicalDrive9 for exclusive write access
Requesting logical volume handle...
Writing compressed image:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Opened \\.\PhysicalDrive9 for shared write access
Remounted \\?\Volume{a73998c8-bb56-11ed-8ebc-f0038c9a2e6f}\ as F:

Could not get node connection information for 'USB\VID_0781&PID_5580\AA011124161316440239': [0x0000001F] A device attached to the system is not functioning.
Found USB device 'SanDisk Extreme USB Device' (0781:5580) [ID]
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3818, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x41259EAD
Drive has an unknown Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Detected File System: FAT16
  Size: 64 MB (67108864 bytes)
  Start Sector: 102400, Boot: Yes
Partition 2:
  Type: GPT Protective MBR (0xee)
  Detected File System: (Unrecognized)
  Size: 512 bytes (512 bytes)
  Start Sector: 1, Boot: No
```
