### ISSUE TITLE
No windows user experience on Windows 7

### ISSUE THREAD

**Issue by sobu-mm** [pbatard/rufus#2198]
Tried to make a Windows 11 bootable usb stick, but the "windows user experience" box doesn't show. When I press the "start" button I only get the warning message. 
![w7](https://user-images.githubusercontent.com/127146997/223218314-5227a7a1-8d6b-4987-b6c9-ffb4839ab18c.jpg)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED
