### ISSUE TITLE
windows 10/11 cannot detect hard drive when bootable disk using rufus 3.21

### ISSUE THREAD

**Issue by antony3165** [pbatard/rufus#2201]
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>
why on rufus 3.21 version create bootable for windows 10 and when install the windows 10 cannot detect hard drive?

Log
---
```
<FULL LOG>
```

**Comment by pineapple63** [comment]
If you expect anyone to help you, then you will need to provide more information
And you didn’t include the log from Rufus

**Comment by pbatard** [comment]
In the absence of enough data, I will consider that [this](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Help_my_USB_drive_is_not_detected) answers your question and close this issue.

If that is not the case, then bear in mind that we can **not** help you if you decide to ignore the check list.

**Comment by pineapple63** [comment]
Some of the potential causes of this could be:

Something went wrong when the image was being written to the USB

Something wrong with the ISO used (could have been corrupted or altered)

The required storage drivers aren’t included in the Windows ISO you used, and so you need to load them manually (this can be the case even with official ISOs, although as to how likely it is, i am not sure)

Without more information (especially as you didn’t include the log), it’s impossible to say which of these, if any, it is
