### ISSUE TITLE
Another malware/bait domain (rufuse.org)

### ISSUE THREAD

**Issue by rainyskye** [pbatard/rufus#2204]
Issue description
-----------------
I searched for "Rufus" on DuckDuckGo, and the top link was instantly fishy from `rufuse.org`, just under that is the official domain, and the fake/malicious link appears to be down, but just wanted to make sure you're aware.

Thanks,
-s

**Comment by pbatard** [comment]
As usual, I can only point to https://safebrowsing.google.com/safebrowsing/report_badware/ to report these malicious websites.
