### ISSUE TITLE
rufus' progress meter does not reflect actual file writing state

### ISSUE THREAD

**Issue by roytam1** [pbatard/rufus#2215]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
From my observation with `procmon`, rufus' progress meter only reflecting file creation (writing files with 2KB blocks in progressing offsets), and not the actual writing file state (shown in procmon writing file with 1MB blocks).
As a result, users may think there is problem in either software(rufus/operating system) or hardware(USB ports/device) but actually there is no problem(just writing files slowly).

Tested on: Win7 x64 SP1 and Win10 LTSC 2019 x64.

Log
---
```
(not providing log since it is unrelated)
```

**Comment by pbatard** [comment]
Not planning to do anything about this, since progress is indicative and whether there is some delay in reporting or not is quite irrelevant (as long as the progress eventually does reflect the completion of the operations).

You are however welcome to provide a patch if you think it is that critical.
