### ISSUE TITLE
1TB pendrive

### ISSUE THREAD

**Issue by PSevenTech** [pbatard/rufus#2220]
Well, I'm having problems with rufus downloaded from the Web, my problem is to try to put persistence pro Kali Linux on a 1TB pendrive, Rufus does the formatting but at the time of putting the ISO in the endrive gives an error, and basically just cleans my pendrive, today coincidentally I witnessed your Rufus on the first page of github and I hope I do not have this problem, but could you give me a hint with the 1TB pendrive?

**Comment by pbatard** [comment]
No update &rarr; Closing.
