### ISSUE TITLE
Invalid partition table

### ISSUE THREAD

**Issue by neheb** [pbatard/rufus#223]
I just used Rufus 1.3.4 to recreate my USB DOS bootdisk to update a BIOS but I got an error saying Invalid Partition Table. Any thoughts as to what the issue might be? I only have Windows 8.1 installed.

**Comment by weedy** [comment]
I just ran into this trying to make a DOS/bios update stick and trying to boot windows or linux USBs.
"Floppy" mode was useless on my motherboard, forcing "Hard drive" boot everything just fine.

Thank you for coming back to reply.
