### ISSUE TITLE
feature request: add option to disable automatic edrive provisioning (self encrypting drive)

### ISSUE THREAD

**Issue by petecs** [pbatard/rufus#2253]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Please add the option to apply the following registry change before installing Windows 10 or Windows 11:

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EnhancedStorageDevices]
"TCGSecurityActivationDisabled"=dword:00000001

The above is a similar but different registry option to this feature request:

https://github.com/pbatard/rufus/issues/2121

The default causes problems because it will prevent you from using Secure ATA commands such as Secure Erase until you perform a PSID revert on the drive.

PSID revert requires that you physically remove the drive to retrieve the PSID and then input it into a program that can perform the PSID revert such as SEDutil, Samsung Magician, or Parted Magic.

See the following links for reference:

https://answers.microsoft.com/en-us/windows/forum/windows8_1-hardware/sed-edrive-unprovisioning/87148920-e749-4e8a-b674-d8d8d551981d

https://www.bleepingcomputer.com/forums/t/700136/reboot-loop-due-to-locked-ssd/

https://old.reddit.com/r/techsupport/comments/c6ylc0/reboot_loop_due_to_locked_ssd/

https://forums.lenovo.com/t5/Lenovo-C-E-K-L-M-N-and-V-Series-Laptops/v330-ssd-auto-encryption-when-installing-win-10-pro/m-p/4153402?page=1#4195595

https://forums.anandtech.com/threads/secure-erasing-840-evo-e-drive-can-it-be-done.2366848/

https://github.com/Drive-Trust-Alliance/sedutil/issues/212

https://sedutil.com/

Thank you

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Well, this looks way too super-specific to ask for a full blown user-facing single option, so, I hope that the following, which will be generated when the user selects to disable bitlocker in the UI, will work, as I am not planning to test it (can't) and this is as far as I'm going to go for this issue:
```
  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-SecureStartup-FilterDriver" processorArchitecture="amd64" language="neutral" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" publicKeyToken="31bf3856ad364e35" versionScope="nonSxS">
      <PreventDeviceEncryption>true</PreventDeviceEncryption>
    </component>
    <component name="Microsoft-Windows-EnhancedStorage-Adm" processorArchitecture="amd64" language="neutral" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" publicKeyToken="31bf3856ad364e35" versionScope="nonSxS">
      <TCGSecurityActivationDisabled>1</TCGSecurityActivationDisabled>
    </component>
  </settings>
```

Again, this, being tied to the user having checked to disable BitLocker is the best you're going to get, coz anything more is not going to fly and if users have to manually remove their SSDs for a situation that (currently) few people are expected to be faced with, so be it.
