### ISSUE TITLE
rufus doesn't show windows releases

### ISSUE THREAD

**Issue by RavenRidge0** [pbatard/rufus#2256]
I cannot choose windows release that I need in rufus, there is only one version. What should I do?
![Снимок экрана (220)](https://github.com/pbatard/rufus/assets/106819388/bf4e44d0-5ee5-4797-bad2-6ffae748a1b2)

**Comment by pineapple63** [comment]
The older versions were removed because Microsoft have started blocking attempts to download older versions

**Comment by pbatard** [comment]
Yes, that's because Microsoft recently removed older releases from their servers.

Obviously, since Rufus downloads the ISOs directly from Microsoft, it can only download what is available there. And the older releases are no longer being made available by Microsoft.

See pbatard/Fido#67

**Comment by pbatard** [comment]
Note that, as an alternative, you can try https://tb.rg-adguard.net/public.php or https://uupdump.net/known.php to generate rather than download an ISO. Whether you will be able to generate the ISO you want is another story...

**Comment by RavenRidge0** [comment]
> Note that, as an alternative, you can try https://tb.rg-adguard.net/public.php or https://uupdump.net/known.php to generate rather than download an ISO. Whether you will be able to generate the ISO you want is another story...

Thanks for the reply.
What should I do? How do I install older windows version?

**Comment by Virtualmachine2020** [comment]
That's sad.
