### ISSUE TITLE
USB disconnects while partitioning (MBR and GPT)

### ISSUE THREAD

**Issue by eddisch** [pbatard/rufus#2257]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [X] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective. (Won't even start lol)
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
USB will just disconnect after/while partitioning (MBR and GPT).
Even in balenaEther.
Picture after failure: (disk 1)
![image](https://github.com/pbatard/rufus/assets/73175017/6fe2c3a4-1e43-4291-a098-58624790b1b7)

Log
---
```
Rufus x64 v4.0.2035
Windows version: Windows 11 Pro x64 (Build 22623.1325)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'Generic Mass Storage USB Device' (31C0:1234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 64 GB, Sector size: 512 bytes
Cylinders: 7699, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.04/20191223 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Zorin OS 16 Pro 64bit'
  Size: 4.7 GB (Projected)
  Has a >4GB file
  Has a >64 chars filename
  Uses: Syslinux/Isolinux v6.04
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system
  limitations. Because of this, some features from this image may not work...
Using image: Zorin-OS-16-Pro-64-bit-R1.iso (4.7 GB)
Will reuse 'ldlinux.sys' and 'ldlinux.bss' from 'C:\Users\Ed\AppData\Local\Rufus\syslinux-6.04\20191223\' for Syslinux installation

Format operation started
Requesting disk access...
No drive letter was assigned...
Will use 'D:' as volume mountpoint
Opened \\.\PhysicalDrive1 for shared write access
Analyzing existing boot records...
Drive has an unknown Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (MBR)...
● Creating Main Data Partition (offset: 1048576, size: 59.0 GB)
● Creating UEFI:NTFS Partition (offset: 63332898304, size: 1 MB)
Writing UEFI:NTFS data...
Write error [0x000001B1] A device which does not exist was specified.
Retrying in 5 seconds...
Write error [0x00000037] The specified network resource or device is no longer available.
Retrying in 5 seconds...
Write error [0x00000037] The specified network resource or device is no longer available.
Retrying in 5 seconds...
Write error [0x00000037] The specified network resource or device is no longer available.
Write error: [0x00000037] The specified network resource or device is no longer available.
\\?\GLOBALROOT\Device\HarddiskVolume6\ was successfully mounted as D:
Re-mounted volume as D: after error

Found USB 2.0 device 'USB Flash Drive USB Device' (CDAB:1024)
Device eliminated because it is smaller than 8 MB
0 devices found
```

**Comment by pbatard** [comment]
> Even in balenaEther.

This clearly indicate that this is an issue that is specific to your USB/computer.

Furthermore, applications like Rufus/Etcher don't access USB drives directly, but rely on Windows for access, so if your drive gets disconnected by Windows, there's really nothing we can do here.

I would strongly suggest that you check your hardware and especially that your USB connections are not flaky and that your USB ports receive adequate power. You may also want to check for third party applications, such as security solutions, that may hinder access to your drive.

As this is the extent of the advice I can provide, I will close this issue.

**Comment by eddisch** [comment]
Thanks!
