### ISSUE TITLE
Rufus in few editions. 

### ISSUE THREAD

**Issue by seba2282** [pbatard/rufus#2260]
I see Rufus from official site, from GitHub and from Microsoft Store. Which are differences between them?

**Comment by pbatard** [comment]
All those releases are built at the same time from the same source.

The GitHub and official site releases are identical. The Store release is somewhat repackaged from the store (but again, built from the exact same source).

In short, outside of some restrictions when using the Store version (that has to do with how Microsoft __prevents__ Store apps from having full access to the Windows APIs) all of these are the same and it doesn't matter which one you use.

**Comment by seba2282** [comment]
Thank you for informations.
