### ISSUE TITLE
can't find the download button

### ISSUE THREAD

**Issue by oijqws** [pbatard/rufus#2263]
I can't find dowload button also, the FAQ showed there should a down arrow on SELECT, but mine does not have that.

![image](https://github.com/pbatard/rufus/assets/38936048/894e705f-a507-4bd8-b922-e00467a93eab)

![image](https://github.com/pbatard/rufus/assets/38936048/1c354b48-29ab-478c-a94c-96ec0540b7cc)

**Comment by pbatard** [comment]
Please don't double post. Also the log, which you ignored, would have told you why the button is not showing.
