### ISSUE TITLE
No other option for older versions Windows 11/Windows 10 isos.

### ISSUE THREAD

**Issue by Virtualmachine2020** [pbatard/rufus#2271]
If I go to Win11/Win10, the only available download options are the latest isos.
Any info on the older Windows isos removed?

```
![Screenshot 2023-06-30 181912](https://github.com/pbatard/rufus/assets/138261858/c5a1fc92-4d96-49bb-bc5d-be6620a2140c)
![Screenshot 2023-06-30 181837](https://github.com/pbatard/rufus/assets/138261858/1cf05b9a-ea4e-4ee3-9b04-7b9157b05cfe)

**Comment by JonnyTech** [comment]
https://github.com/pbatard/rufus/issues/2256#issuecomment-1566139366

**Comment by Virtualmachine2020** [comment]
> If I go to Win11/Win10, the only available download options are the latest isos. Any info on the older Windows isos removed?
> 
> ```
> ![Screenshot 2023-06-30 181912](https://github.com/pbatard/rufus/assets/138261858/c5a1fc92-4d96-49bb-bc5d-be6620a2140c)
> ![Screenshot 2023-06-30 181837](https://github.com/pbatard/rufus/assets/138261858/1cf05b9a-ea4e-4ee3-9b04-7b9157b05cfe)
> ```

`
