### ISSUE TITLE
ER: Add support for UEFI/NTFS

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#228]
As reported by **alphanumeric** [here](http://www.eightforums.com/tutorials/15458-uefi-bootable-usb-flash-drive-create-windows-27.html#post309665), some UEFI firmwares (such as the one for an ASUS K75DE laptop) appear to support NTFS for boot, and the Windows 7 USB DVD download tool appears to support the creation of NTFS UEFI bootable UFDs.

This needs to be investigated further, and if confirmed, Rufus should add UEFI/NTFS support.

**Comment by chrcoluk** [comment]
So how does this feature work? When I create a GPT usb disk using NTFS it doesnt have a fat32 partition and wont boot from UEFI.

**Comment by pbatard** [comment]
Have a look [here](https://github.com/pbatard/uefi-ntfs). It contains an explanation of how it works.
