### ISSUE TITLE
Windows logo is hidden/replaced when I make USB bootable in UEFI mode, but not with legacy, why?

### ISSUE THREAD

**Issue by GauravSahare1993** [pbatard/rufus#2281]
When I make USB bootable in UEFI mode for Windows 8.1, 10 and 11, and connect to another computer for installation, then Windows is installing, but I noticed that Windows logo has replaced from Motherboard's manufacturer logo during installation, and logo is hidden when I login.
But this thing not happening when I make USB bootable in legacy mode. 
So what is the reason? Is there a bug from Microsoft or from Rufus?

**Comment by pineapple63** [comment]
With UFEI systems, it is normal for the manufacturers logo to show instead of the Windows logo when the system starts up or reboots
