### ISSUE TITLE
Inaccurate translation of "persistent partition"

### ISSUE THREAD

**Issue by radjah** [pbatard/rufus#2284]
https://github.com/pbatard/rufus/blob/master/res/loc/po/ru-RU.po#L837C5-L837C5

Replace "Постоянный размер раздела" with "Размер persistent-раздела" or something similar

**Comment by pbatard** [comment]
I'm going to leave to the current translator to decide what they want to do in the next translation round, especially as "раздела" is used in other places, so it would make little sense to replace it with "persistent" just here.

As such, I will close this request.
