### ISSUE TITLE
Feature Request: Limine Bootloader support

### ISSUE THREAD

**Issue by josue-beauregard** [pbatard/rufus#2285]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I'd like to feature request to supports Limine Bootloader on Rufus

https://wiki.archlinux.org/title/Limine

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Okay, I'm not seeing much progress on the Limine usage for bootable media front (especially now that [systemd-boot](https://wiki.archlinux.org/title/Systemd-boot) has entered the frey), so I'm just going to close this request, as I genuinely don't expect much usage, if any of Limine.

At any rate, **if** that changes in the future, and Limine gains actual traction, I should be well placed to notice it and add support for it in Rufus.

&rarr; Closing.
