### ISSUE TITLE
Windows To Go with Windows Vista and 7: BSOD 0xc000007B error

### ISSUE THREAD

**Issue by Minionguyjpro** [pbatard/rufus#2294]
Hello,

I tried to make a bootable Windows To Go drive for Windows Vista and 7. I boot using UEFI, which should be supported with UEFI class 2 systems (I have). I did manage to get Windows 7 up and running on UEFI on my internal drive. However, never on a USB drive as it just gives a BSOD in CSM and pure UEFI. Windows Vista should have the same behavior I think. It atleast gives a BSOD too when trying to boot the created bootable drive.

**Comment by pbatard** [comment]
Next time please read the FAQ:

https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED
