### ISSUE TITLE
windows download problem

### ISSUE THREAD

**Issue by AndreDavis909** [pbatard/rufus#2301]
Hello! No access to download windows 11, can you fix it?
![](https://i.imgur.com/PKFvFpD.png)

**Comment by AndreDavis909** [comment]
There was no such problem before.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO
