### ISSUE TITLE
Question regarding the Windows User Experience dialog

### ISSUE THREAD

**Issue by LOUDER97** [pbatard/rufus#2303]
Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [X] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [X] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
At some point I loaded a Win7(and Win10 some time afterwards) ISO, and Rufus(I don't recall what version, probably pre-3.22) prompted the Windows User Experience dialog.
Today I intended to use that feature to create a main user with the name "Administrator" for a very specific aplication, which I DID manage to do before, with the help of Rufus, but with a different Win7 ISO(I can't seem to find the old one).
This is not available through normal means, ie. define the user "Administrator" during the windows installation. 
This time I did not see any prompts regarding WUE. I tried with 4.2, 3.22 and 3.20. It goes directly to the data erase prompt, without the WUE dialog.
I did run a SHA-1 checksum, and the ISO is genuine.
I did look through FAQ and did find [a single entry about WUE](https://github.com/pbatard/rufus/wiki/FAQ#windows). I know that Win7 development has been discontinued, but shouldn't WUE still be available in older versions of Rufus?
I did look through the changelog and I found entries about it on 3.22, 3.21, 3.20, but nothing about WUE being removed, or excluded from Win7 installations, just that Win7 ISO won't be available to download from 3.22 onwards.
I provided the full log, in hopes you could enlighten me whether is related to the win build, GPT/MBR partitioning, standard/win to go installation, or something else I missed in the logs.
I am also providing a screenshot with the Rufus window in that matter.
![image](https://github.com/pbatard/rufus/assets/14253086/c2ad7404-35a9-47b8-8866-532eab2b4f16)

Log
---
The body of the message exceeds the maximum length, I have to attach it as file
[rufus.log](https://github.com/pbatard/rufus/files/12321124/rufus.log)

**Comment by pbatard** [comment]
>  I know that Win7 development has been discontinued,

It has. And that is __FINAL__.

> but shouldn't WUE still be available in older versions of Rufus?

WUE was designed, from the get go, to never be proposed for anything older than Windows 10. There are checks in the code to make sure of that. So, if you still insist on trying to have WUE work with Windows 7 ISOs, I'm afraid you are 100% on your own. I will not help you.
