### ISSUE TITLE
I can't make a Bootable USB with Windows 11

### ISSUE THREAD

**Issue by iMariin79** [pbatard/rufus#2304]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I cannot make a Bootable USB with Windows 11 Ultralight, Previously I had Windows 7 Home Premium 64-bit on the USB, today I wanted to record Windows 11 for an experiment and I get this error that appears in the logs

Log
---
```
Rufus x86 v3.16.1836
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0C0A (es-ES)
Will use default UI locale 0x0C0A
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'es-ES'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 4GB, Sector size: 512 bytes
Cylinders: 489, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {D9B6D326-88EA-41F9-AC7C-71FC17DAFBFD}
Max parts: 128, Start Offset: 17408, Usable = 4026497536 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  ID: {2CE7B5BE-16F1-4D5B-BF8A-8D6A5E35D9AB}
  Size: 3.7 GB (4025466368 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Unable to locate InternetCrackUrlA() in WinInet.dll: Windows error code 0x0000007F
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'WindowsXLite-FBConan'
  Size: 1.6 GB (Projected)
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.wim (version 0.14.0+)
Using image: Windows 11 Ultralight (22621.1245) 'Divinity' By FBConan.iso (1.6 GB)

Format operation started
Requesting disk access...
Will use 'G:' as volume mountpoint
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (GPT)...
● Creating Main Data Partition (offset: 1048576, size: 3.7 GB)
Waiting for logical drive to reappear...
Formatting to FAT32 (using IFS)
Unable to locate FormatEx() in fmifs.dll: Windows error code 0x0000007F
Format error: Windows error code 0xC003007F
Re-mounted volume as G: after error

Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 4GB, Sector size: 512 bytes
Cylinders: 489, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {EA139CFB-F9CD-4132-B7DD-0B862FE59EA1}
Max parts: 128, Start Offset: 17408, Usable = 4026497536 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  ID: {95DC7CD0-18A8-47DC-B7D7-5F4F07A67B2D}
  Size: 3.7 GB (4025466368 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 4GB, Sector size: 512 bytes
Cylinders: 489, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {EA139CFB-F9CD-4132-B7DD-0B862FE59EA1}
Max parts: 128, Start Offset: 17408, Usable = 4026497536 bytes
```

**Comment by pbatard** [comment]
I'm afraid I no longer support anything that has to do with Windows 7, be it running Rufus on Windows 7 to create a Windows installation drive, regardless of whether it's a recent version of Windows (your case) or running Rufus on a recent version to create a Windows 7 drive.

See https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED.
