### ISSUE TITLE
Get the following error message on screen

### ISSUE THREAD

**Issue by Apache060** [pbatard/rufus#2316]
`Hello,`
I have the following issue rufus  I can burn the iso file to usb stick, but when I try to boot from the USB stick the following message appears on the screen.
Please see screen shot belo 

![IMG_0016](https://github.com/pbatard/rufus/assets/115584842/8ed6e972-52ea-492b-9e46-63a3b64cb4c7)

**Comment by JonnyTech** [comment]
The detailed message on screen has clear instructions - I suggest that you read and follow them.

**Comment by pbatard** [comment]
See also this [very relevant FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#user-content-ERROR_BIOSLEGACY_BOOT_OF_UEFIONLY_MEDIA).

Since you chose not to provide a log of how you created the media, despite being very explicitly asked to do so, there really is no extra advice we can provide.

**Comment by Apache060** [comment]
Hello,
The error message is gone, the issue now is that the pc will say booting from Device then the screen goes blank and all I get is a white dash flashing on the screen.

**Comment by Apache060** [comment]
The issue is now fixed.

Thanks for your help
