### ISSUE TITLE
Insert Media #1 for the task sequence <TS Name>

### ISSUE THREAD

**Issue by vvccjj111** [pbatard/rufus#2318]
I have meet this error during the installation of OS "Getting error ‘Insert Media #1 for the task sequence "
I have used MDT and created bootable USB, I find one wired things ( with same image)
on HP elite book 840 , with rufus 4.2 it works, but with rufus 3.2 not, I got the error above
on HP Zbook power G9, with rufus 3.2 it works, but with rufus 4.2 not, I got the error above
I can't indicate where the problem is, does someone has the similar issue?

**Comment by pbatard** [comment]
No log &rarr; closed.

As was clearly indicated when you opened the issue, if you fail to provide the base elements that can help investigate your issue, the issue will __not__ be investigated.
