### ISSUE TITLE
W11 Installation fails

### ISSUE THREAD

**Issue by R2R29** [pbatard/rufus#2327]
﻿

Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [X] Using a different USB drive.
  -  [X] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
@pbatard 
Hi, 
I can't upgrade from Windows 10 Pro to Windows 11 Pro. 

I had Windows 10 Home that came with my laptop and i bought a Windows 10 Pro key (retail). 
It was working fine but I wanted to upgrade to W11 Pro. Since Microsoft decided that my cpu (Intel i7-6700HQ) is not compatible, a friend told me about Rufus.

I used Rufus to download the ISO of W11 and create a bootable usb pen but by mistake, instead of opening the usb drive and run the setup to upgrade, I performed a clean install. 
The truth is that it worked, I was able to install W11 but Home Edition and not the Pro. So I went again to Rufus and created a bootable pen using Windows 10 ISO downloaded from Microsoft. Installed it and changed again from Home to Pro successfully. Then made all the updates available.

Back again to Rufus, created a bootable usb pen with W11 and run the setup while on Windows "environment". It search for updates, then it shows the screen with the checkmarks for upgrading to Windows 11 Pro and to maintain my files. I hit "next" and it shows the installation screen but after 4 seconds, it says that the instalation failed.

After it fails, I can't even execute the setup again; I have to reboot the pc to be able to. 

Can anyone help me, please!

(I don't have logs since my problem is not while creating the bootable pendrive) 

Thanks!!!!

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
I'm afraid that this is a pure Microsoft licensing issue so you need to contact Microsoft support, which this issue tracker does not substitute for.

From the moment you perform the Windows installation, and you don't encounter an error while doing so (which you don't, again, this is a Windows license matter), whatever problem you face ceases to be something that I have scope to support you with and I also have to stress out that, as opposed to what many seem to believe, I don't have more in depth knowledge compared to the next random Windows users about the internals of the Windows installation or activation process. Only someone working from Microsoft can have that, and I do __not__ work for Microsoft.

So please report this issue directly to the Microsoft support department or post it on a Windows user forum.
