### ISSUE TITLE
USB Bootable Windows 7 Keyboard and mouse stuck

### ISSUE THREAD

**Issue by MichaelAndrianai** [pbatard/rufus#2337]
Hello there,

I have create a windows 7 usb bootable with rufus, but actually I'm stuck at langague select cause Keyboard and mouse not working. My desktop has 4 usb 3.0 (only usb 3.0). Any one can help me please?

Thank you

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED
