### ISSUE TITLE
[Optimization]After completing the task, there was no prompt, and the interface looked ready to start again.

### ISSUE THREAD

**Issue by WangZhenCN** [pbatard/rufus#2343]
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Inside the green progress bar, it displays "Ready to start," and the start button is clickable. It can easily lead to accidental operation for someone who is not present at the computer. I suggest adding a completion notification for the task.>

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
> It can easily lead to accidental operation for someone who is not present at the computer.

I disagree. You get a full progress bar when the operation is complete, as a the time the operation did take to complete in the bottom right corner, which is indication enough that you did start the operation and that it completed successfully.

If you cannot remember whether you started an operation in Rufus before coming back to the computer, and cannot identify 2 clear visual cues that indicate that you did start an operation and that it completed successfully, this is your problem, not the application's.

Furthermore, you can always check the log with the small log button, left of `START` (or with <kbd>Ctrl</kbd>-<kbd>L</kbd>), if you need further indication that an operation was launched and completed.

&rarr; Rejected.
