### ISSUE TITLE
Prompt user to install PID.txt into sources folder of Windows Installation Media.

### ISSUE THREAD

**Issue by jerrywoo96** [pbatard/rufus#2344]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Hi,

I was reinstalling windows pro to a laptop with a windows non-pro key baked into the uefi firmware. I was wondering if rufus can prompt the user if they would like to force install a specific version of windows using the PID.txt method, so they can override which edition of windows to choose to install the the laptop.

Scenario:
Laptop has a built in windows non-pro key.
Windows does not prompt user which edition to install and instead automatically selects non-pro edition of windows as non-pro key is found in uefi firmware of the laptop.

Desired Rufus improvements:
Prompt user to select edition of windows to install on creation of windows installation media, and depending on which edition is selected, rufus creates PID.txt in the sources folder with the correct generic key, so that the windows installation media reads the PID.txt instead of the one baked into the UEFI firmware and installs the user-desired edition.

Optional improvements:
On laptops with windows key baked into the uefi firmware, prompt user for a genuine valid windows key to use to install instead of the one baked into the uefi firmware.

Windows generic keys:
USE RTM KEYS.
https://gist.github.com/jhermsmeier/5959110

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
That falls outside of the mandate of what and who I am designing Rufus for.

Rufus is aimed at regular users, and the very few regular users who might have to change edition, to a different version than the one that was autoactivated, can do so post install, so I see little need to provide the means to mass-change licensing keys.

Please read https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_cant_you_just_add_the_feature_I_want and especially points 2. and 3.

Besides, licensing matters are Microsoft's to solve, not Rufus.

&rarr; Rejected.
