### ISSUE TITLE
Entries in Windows User Experience are lacking technical references

### ISSUE THREAD

**Issue by davidhedlund** [pbatard/rufus#2349]
![Screenshot 2023-10-27 121427](https://github.com/pbatard/rufus/assets/6416073/7209d4ae-88b8-4833-acea-906f382536df)

# Example
I think all entries should have techinical references, this section is just used to demonstrate a use case for a specific entry.

Add " (oobe\bypassnro)" after the text in the second entry in the above screenshot so it becomes:  _Remove requirement for an online Microsoft account (oobe\bypassnro)_ -- "(oobe\bypassnro)" can be hidden in a tooltip for a "?" symbol if you want to save space, which is especially useful to list multiple technical references, and Windows versions/builds if they vary.

This will help people to web search "bypassnro". For example "windows 11 22H2 bypassnro" which will inform them that in order for bypassnro to work in Windows 11 version 22H2, public internet connections must be disabled before the computer is started (unplug the Ethernet cable, disconnect from public Wifi). Reference (big thanks to pbatard):
* https://github.com/pbatard/rufus/issues/2346

Settings that require special considerations, but that are lacking a technical reference, will easily confuse users to think that Rufus is broken.

**Comment by pbatard** [comment]
No. Contrary to what you posit, this will not speak to anyone, and this relies on Microsoft or Rufus not ever changing the way it bypasses the online requirement, which we may very well (have to) do from one version to the next.

As I explained to you earlier, the WUE dialog is designed to be short and to the point, without extra confiusing flourish.

So I will kindly ask that you stop trying to have me tailor the Rufus UI to __your tastes__, by trying to pretend that your tastes are somehow going to be shared with everybody.
