### ISSUE TITLE
[Feature request] Add option for compacting Windows installation 

### ISSUE THREAD

**Issue by uliar** [pbatard/rufus#2352]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Would it be possible to add an (maybe hidden) option in the Windows User Experience dialog for compacting Windows installation? This is very useful for users with small SSDs like many users with Chromebooks hitting EOL and installing Windows on their machines with the help of MrChromebox UEFI firmware replacement, chromebooks have non-upgradable soldered eMMC chips
Apparently this can be enabled on the installation https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/compact-os 

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
I can understand your reasoning for wanting this, but I'm afraid I am not planning to add the feature you request on account that:
1. The WUE dialog is targeted primarily at removing the annoyances that prevent a streamlined installation of Windows (i.e. all the various popups you get between the time you start booting the media to the time you actually get to an installed version of Windows you can interract with). The dialog is not and will never be intended as something that should ultimately give users the ability to fine tune all the various Windows installation parameters, such as compacting the installation, as there are way too many of these, and if I started to cherry pick the __many__ user requests I get to add more options, I would never see the end of "But you added _feature X_ for that user, so why can't you add _feature Y_ for me?"
2. Rufus is not targeted at a power-users or sysadminis. If you are one of these, I estimate that you should either have or be able to obtain the knowledge you need to perform the kind of operations you want. Thus, even if it may look to you like it should be tangentially related, it will never be Rufus' job to solve your specific syadmin/power-user installation woes. 

See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_cant_you_just_add_the_feature_I_want.
