### ISSUE TITLE
Feature Request - Add MS Server ISO downloads

### ISSUE THREAD

**Issue by rgiuffre** [pbatard/rufus#2355]
I was wondering if you can add the MS Server options to the download drop downs. I don't know if the ISOs are available for download, but it would be great if they were options.

Thank you!

**Comment by brian6932** [comment]
https://uupdump.net/

**Comment by pbatard** [comment]
Last time I checked, the Windows Server ISOs required a Microsoft account to be downloaded, so they cannot be added as downloads in Rufus/Fido.
