### ISSUE TITLE
Stuck @ This Screen (Rufus v3.22) (UEFI + GPT + NTFS)

### ISSUE THREAD

**Issue by casioforever** [pbatard/rufus#2358]
![ab7e8cc5-96c6-41a7-b21d-ae2ff8243105](https://github.com/pbatard/rufus/assets/148558396/852b52ab-1418-4f91-b62f-d732ce7139ed)

Windows 7 ultimate
INSTALL.WIM = 4.56 GB
No CSM - Windows 10 OS Support
Legacy USB Support = Enabled

**Comment by pineapple63** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED

also, Windows 7 does not support pure efi booting

**Comment by pbatard** [comment]
Yes, Windows 7 is no longer supported. If you use Windows 7 in any way, you're on your own.
