### ISSUE TITLE
UI copy improvement: Quick format

### ISSUE THREAD

**Issue by jbebe** [pbatard/rufus#2362]
Checklist
---------
- [x] I looked at Rufus

Issue description
-----------------

![image](https://github.com/pbatard/rufus/assets/1939926/07bdb817-3ba8-4473-9bef-167c63ec728d)

I usually just brute-force my way through Rufus to install an OS quickly and don't bother with reading the manual.
As I already deleted every partition on the pendrive I wanted to use manually, I thought Rufus should skip the quick format step because the file system is already gone. I unchecked the Quick format checkbox. Instead of skipping it, the "slow" format has started. That's not an issue in itself but the UI has bad user experience because starting the slow format step is a totally implicit behavior.

My advice: Use a radio button or a dropdown to select Quick or Normal format. This way the user understands what is going to happen, the other method won't be hidden.

Log
-

**Comment by pbatard** [comment]
>  I thought Rufus should skip the quick format step

You are assuming wrong. And you are reading what the option does wrong. The "quick" part of "Quick format" is not an irrelevant addon but what the option applies to.

When someone deselects a "X Y" option, where X is a qualifier of Y, they should not assume that Y will be disabled altogether but instead that the Y version of X will be disabled. Else there would be no qualifier, just "Y".

&rarr; Rejected.
