### ISSUE TITLE
EastFun 8GB Flash Drives Are Not Compatible With Rufus [Version 3.22 Tested]

### ISSUE THREAD

**Issue by ErikWOlson2** [pbatard/rufus#2363]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
EastFun 8GB flash drives are not compatible with Rufus 3.22 (Windows 7 Professional, Windows 7 Home tested).
Issue is _not_ related to anti-virus or other software(s). Safe Mode generates identical error.
Other report found at this link:  forum [dot] puppylinux [dot] com/viewtopic.php?p=65926  (see confirmation post dated Fri Sep 09, 2022 3:08 pm).
Substituting an 8GB Kingston flash drive results in immediate success.

Suggest you add a note in the FAQ section for error "Error [0x00000005] Access is denied" mentioning deficient flash drives as a potential cause.

Log
---
```
Rufus x86 v3.22.2009
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because your version of Windows is too old.
Found USB 2.0 device 'General USB Device' (ABCD:1234)
1 device found
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 979, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.04/20200816 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Debian 12.2.0 amd64 1'
  Size: 3.8 GB (Projected)
  Has a >64 chars filename
  Uses: Syslinux/Isolinux v6.04
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system
  limitations. Because of this, some features from this image may not work...
Using image: debian-12.2.0-amd64-DVD-1.iso (3.7 GB)
Will reuse 'ldlinux.sys' and 'ldlinux.bss' from 'C:\Users\Username\AppData\Local\Rufus\syslinux-6.04\20200816\' for Syslinux installation

Format operation started
Requesting disk access...
Will use 'E:' as volume mountpoint
Opened \\.\PhysicalDrive2 for exclusive write access
Analyzing existing boot records...
Drive has an unknown Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Write error [0x00000005] Access is denied.
Could not reset partitions
Re-mounted volume as E: after error

Found USB 2.0 device 'General USB Device' (ABCD:1234)
1 device found
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 979, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Found USB 2.0 device 'General USB Device' (ABCD:1234)
1 device found
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 979, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned


```

**Comment by pbatard** [comment]
Considering that, per the FAQ, I have stopped supporting Windows 7 in any way shape or form, and the only reports I am seeing are from Windows 7 users, I am not planning to do anything about this.
