### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by jazzson** [pbatard/rufus#2364]
Hey, rufus is a great tool, it can create large file boot disks and simplify a lot of installation work through advanced options. I have a suggestion, I wonder if rufus can add an option to disable Windows Defender in the advanced options?

**Comment by pbatard** [comment]
The purpose of the advanced options/Windows User Experience dialog is to remove the hindrance that prevent a streamlined installation.

Disabling defender does not fall into that category so I have no plan to add it.

See also: https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_cant_you_just_add_the_feature_I_want
