### ISSUE TITLE
Crashing when clicked, when clicked on boot. 

### ISSUE THREAD

**Issue by AbrahimZaman360** [pbatard/rufus#2366]
I have downloaded the latest win11 iso, which is working on another laptop via mbr but on mine which is gpt base isn't working even can't create bootable usb.
Getting "image has no boot marker". 
After selecting iso, it crashed.

**Comment by pbatard** [comment]
No log, can't helpt you.

**Comment by pbatard** [comment]
Also please check the SHA-1 of the ISO you are using and provide it here.

**Comment by AbrahimZaman360** [comment]
Thanks for your software and suggestions! I downloaded ISO again and changed the port and updated my other system, and it worked! (💯
