### ISSUE TITLE
Is it possible to add a safe backup mode?

### ISSUE THREAD

**Issue by jazzson** [pbatard/rufus#2367]
I have a backup under windows 11 and sometimes when restoring it prompts that the file is corrupted. rufus can you help me to add a safe backup mode where I can go into the restore kind of safe mode ，reboot computer then into rufus for the backup?

**Comment by pbatard** [comment]
I'm afraid that your request is out of scope of what Rufus should concern itself about.

See [also](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_cant_you_just_add_the_feature_I_want)
