### ISSUE TITLE
Feature request: Select desired Windows edition on ISO creation

### ISSUE THREAD

**Issue by guzelonur** [pbatard/rufus#2398]
Hi folks,

As you know, when trying to install a multi-edition Windows 10/11 ISO downloaded from Microsoft servers, which is generally so common, the setup process detects corresponding license type embedded in BIOS/UEFI and installs Windows with detected edition **without** asking you to choose either Pro, Home or Enterprise.

This can be solved by putting such modified "**ei.cfg**" file in sources folder in ISO file, allowing user to select the desired Windows edition to install.

So can Rufus contain this feature providing a simple checkbox on **user interface** without having to do it by ourselves manually everytime?

Best regards.

**Comment by pbatard** [comment]
This has been suggested many times before, but from where I stand, this would only be useful for a very limited number of users (people who have a license and then want to change it) which is not the target audience, and AFAIK once installed, Windows does allow you to change the license if you go through the official channels.

See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Could_you_add_support_for_removing_ltWindows_option_Xgt_in_the_Windows_User_Experience_dialog. The only options I consider for the WUE dialog are ones that prevent a streamlined installation of Windows. Changing the license does not fall under this category.
