### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by AHCREATION** [pbatard/rufus#2402]
If possible, please add multiple boot support so that with one bootable media we can use for different Windows versions as per choice. Normally, we need multiple USB bootable drives, or we have to format the drive to use different versions of Windows.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Do_you_plan_to_add_multiboot_support

Next time, please don't ignore the check list, that explicitly asks you to look if your question is answered in the FAQ.
