### ISSUE TITLE
Error download

### ISSUE THREAD

**Issue by Pompom009** [pbatard/rufus#2408]
![Unbenannt-1](https://github.com/pbatard/rufus/assets/150674318/c45977b6-cb26-4a49-93ab-3e34e105e121)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO

Next time, don't ignore the check list and look at the FAQ as requested.
