### ISSUE TITLE
Windows 11 Setup

### ISSUE THREAD

**Issue by Bari1951** [pbatard/rufus#2410]
I'm using Rufus 4.4 on different laptops.
The first laptop HP Elitebook 850 G5 the Windows 11 23H2 update succeeded.
The second laptop also HP Elitebook 850 G5 the Windows 11 23H2 wasn't succesful.
I tried it several times, but everytime I got the same message.
We cannot determine if your PC is ready to continue installing Windows 11. Restart setup.
I also edit my registry with
HKEY_LOCAL_MACHINE\SYSTEM\Setup\MoSetup
New > DWORD (32-bit) AllowUpgradesWithUnsupportedTPMOrCPU Value  1
and
HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig
with DWORDs BypassTPMCheck and BypassSecureBootCheck and set each to 1

What is going wrong, that the setup isn't working.

**Comment by pbatard** [comment]
No log &rarr; Closed.
