### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by icinemagr** [pbatard/rufus#2427]
---------------------------
File download
---------------------------
This system's SSL library is too old to be able to access this website.
---------------------------
OK   
---------------------------

Time to move to https://etcher.balena.io/#download-etcher
I cannot understand Why a Non Internet APP who writes data to a disk stop working 
Pathetic

**Comment by pbatard** [comment]
I cannot understand why people expect third party developers to support OSes __forever__, when they have been officially obsoleted by their manufacturer.

The problem is 100% of your making insisting on using an __obsolete__ OS.
