### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by dandunckelman** [pbatard/rufus#243]
First off, this is a sweet lil tool.

I just wanted to say that I just used this to make a Windows 7 bootable USB from an ISO on a Windows Vista machine.  Unfortunately, this particular machine had a faulty keyboard and touchpad...so I don't have any input source unless I plug in a usb keyboard/mouse.

Being that I love using the keyboard exclusively, I thought I'd be cool and only plug in a keyboard.  So, I open the open, but as soon as I open it, I can't use the keyboard to do anything (except maybe starting the process with all default settings).

I hope this makes sense.  Definitely, this is a nice to have feature and not a big requirement.  I just had to plug in a mouse I had lying around to interact with the app's menus.

Thanks again and happy weekending!

**Comment by pbatard** [comment]
Adding the following issue when using Jaws, reported today by __Aman Singer__:

> If I click the box to select UEFI as the partition type, I can move with the arrows among the choices, which is good, but then I have to move the mouse around and if that mouse cursor lands on the previous choice, the box switches to the choice the mouse is on.

**Comment by pbatard** [comment]
Adding the following issue when using nvda screen reader, reported by __Mike Coulombe__:
> When I open the program I get no speech telling me which box i'm on when I press tab or arrow keys. However, pressing space does open the current menu and I can then use tab to make the choices because I get speech. Would you be able to get the main menu to also work with nvda?
