### ISSUE TITLE
Feature Request: Create an administrator account. 

### ISSUE THREAD

**Issue by ahaoboy** [pbatard/rufus#2431]
Rufus currently supports creating local accounts. Could an option be added to create an administrator account? Developers often encounter situations where they need administrator privileges to execute some commands, and currently, the workaround is to restart the terminal with administrator and then run the commands. If the option to set the account as an administrator could be included during the account creation process, it would save a lot of hassle with permissions. Of course, this might introduce security concerns, but I believe users opting for this feature would be aware of and willing to manage the associated risks.

**Comment by pbatard** [comment]
Please see https://github.com/pbatard/rufus/wiki/FAQ#user-content-Could_you_add_support_for_removing_ltWindows_option_Xgt_in_the_Windows_User_Experience_dialog.

The goal of the WUE options in Rufus is not to allow users to configure every available Windows option under the sun, but only the ones that hinder/halt a streamlined user experience **when installing Windows**. This does not fall under that category.

I also don't see that much real demand for this in the first place anyway.

As a result, I will not add the feature you request.
