### ISSUE TITLE
Working only on a single USB port. Why?

### ISSUE THREAD

**Issue by Guybrush3pw00d** [pbatard/rufus#2435]
My best regards and first of all thanks for your efforts on such a great piece of software! I have successfully set a Windows To Go installation (Win7 X64, UEFI with CSM because without, at least by what I've understood, it doesn't work like with other similar tools which create WTG installations) up by Rufus but I've had some issues at the beginning. I created it on an USB port which suited me because of its location but then it didn't boot leaving me with just BSODs (STOP : 0x0000007B (0xFFFFF880009A97E8, 0xFFFFFFFFC0000034, 0x0000000000000000, 0x0000000000000000).
I've made some externsive research and it seems something related to USB 3.0 ports 

https://us.informatiweb.net/tutorials/it/windows/windows-7-installation-on-an-usb-support--2.html

(so I believe a driver issue being USB 3.0 drivers not present in the Windows 7 setup media). I've then thought to swap ports and found the only one which is actually working up to the task. The strange thing is that:

1) The ports that don't work aren't USB 3.0 ports
2) The external hard drive works only on ONE port from the same two ports block (so I assume connected to the same USB Hub) while the other doesn't. As written in the title, it works on that single port among all the ones present in my laptop, even after completing the setup and having installed all the needed drivers so with all the USB ports working fine, not at boot time as it seems.

Here comes my main concern: what if I use that WTG installation on another laptop? I believe it would be unlikely to boot fine if on mine it works on one port only. Is it something related to Win7 only or a widespread issue with WTG installations?
I'd like to underline I haven't thought for a single second it is an issue with Rufus but I've posted here to undestand the reasons behind if possible and maybe find a solution with your help. Thanks in advance and have a nice day! :)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED

Please direct Windows 7 related question to Windows 7 user forums. This is not one of them.
