### ISSUE TITLE
Feature Suggestion: SSE4.2 CPU Instruction Bypass for BlissOS Android-x86 Distros

### ISSUE THREAD

**Issue by MainUserA** [pbatard/rufus#2437]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I was wondering if you could possibly add an option to bypass the SSE4.2 CPU instruction support requirement for BlissOS android-x86 distros just like you did with Windows 11 only if that instruction is NOT ACTUALLY USED by the OS of course.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Too niche, not enough of a userbase to make it worth it.

See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_cant_you_just_add_the_feature_I_want.

**Comment by MainUserA** [comment]
> Too niche, not enough of a userbase to make it worth it.
> 
> See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_cant_you_just_add_the_feature_I_want.
Why? It would increase the amount of users with extremely old machines and also the android-x86 and other alternative lightweight OSes are meant to bring life to old machines.

**Comment by MainUserA** [comment]
> > Why? It would increase the amount of users with extremely old machines
> 
> _extremely_ is the keyword here. You have to have a Core 2 CPU for this to be useful, which, as I stated, makes it beneficial only to a very niche section of users.
> 
> In the same manner as, despite repeated pleas to do so, I just don't see it beneficial to go out of my way to try to support Windows 7 users, because the cost/benefit is simply no longer worth it, I don't see it beneficial to go out of my way to support potential users of BlissOS on _extremely_ outdated CPUs.

Understood.

**Comment by MainUserA** [comment]
I understand that you're not interested in this but can you at least type me probably a .bat file that patches that requirement?

**Comment by MainUserA** [comment]
I'm totally aware that this is time consuming and also aware that your time is not free as the software you provide that's why I'm just wondering and hoping for you to do this as a small favor not more than that. Also, I apologize if I was rude and disrespectful.

**Comment by pbatard** [comment]
Sorry but you are __not__ asking for a "small favor" here. 

It seems you are also under the impression that, if I look at the BlissOS data for 5 minutes, I'll be magically able to produce some kind of magical script that sorts out the SSE4.2. What I envision however, since this is a complete black box to me, is that even if I agreed to undertake this small favour, it would take me __days__ to come up with the kind of script you want.

Or, to put it more succinctly: _Everything you don't have to do yourself looks like a 5 minutes job_

**Comment by MainUserA** [comment]
> Sorry but you are **not** asking for a "small favor" here.
> 
> It seems you are also under the impression that, if I look at the BlissOS data for 5 minutes, I'll be magically able to produce some kind of magical script that sorts out the SSE4.2. What I envision however, since this is a complete black box to me, is that even if I agreed to undertake this small favour, it would take me **days** to come up with the kind of script you want.
> 
> Or, to put it more succinctly: _Everything you don't have to do yourself looks like a 5 minutes job_

I understand, sorry for wasting your on this but I actually took a great advice here from that last sentence. And again, I apologize if I was disrespectful to you.
