### ISSUE TITLE
U disk partition identifies the entire u disk

### ISSUE THREAD

**Issue by YuanJie2001** [pbatard/rufus#2440]
hello,everybody.
My u disk has a pe boot partition and an ordinary file storage partition. I divide the free space of ordinary files into a third zone. I hope to use the third area to make a linux boot disk to install the linux system. But when burning, it recognizes the entire u-disk system and cannot select one of the partitions to make the linux startup program.Of course, I have also tried floppy disk access and ventoy.They're the same.
![bf95ba7f4c69317ca8740799536e195a](https://github.com/pbatard/rufus/assets/82219481/75741a6d-7da1-4e9c-9c28-191bf7b0a0ea)

**Comment by pineapple63** [comment]
The reason the software doesn't recognise individual partitions, is because the software has to format the drive in order to ensure it will boot (especially with older systems)

**Comment by pbatard** [comment]
See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_does_Rufus_need_to_delete_all_partitionsvolumes_when_creating_a_drive

If you need software that preserves partition while creating bootable media, I will kindly ask that you use something else than Rufus, as it will never be designed for your usage scenario.
