### ISSUE TITLE
Porting Rufus

### ISSUE THREAD

**Issue by GermanAizek** [pbatard/rufus#2443]
@pbatard, 
Hi, are there plans to port to Linux and BSD?

**Comment by pbatard** [comment]
__YES__, the checklist that explicitly told you to search the FAQ before creating an issue, did apply to __YOU__!

https://github.com/pbatard/rufus/wiki/FAQ#user-content-Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS
