### ISSUE TITLE
Norwegian/minor misspelling.

### ISSUE THREAD

**Issue by Legendarion** [pbatard/rufus#2453]
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------

I forgot to mention a minor misspelling on my first thread.

The word "instillinger" are missing an N (correct way: innstillinger).

![Misspelled](https://github.com/pbatard/rufus/assets/62836893/e3bbe258-6daf-405f-b113-a50b03f8b7c3)

And the sentence "Tilpasse Windows installasjonen?" would have looked nicer if it was written "Tilpass Windows installasjon." (Customize the Windows installation) with the word 'Valgfritt' (Optional) in parenthesis instead without the asking.
It would have looked more proper that way.

Log
---
```
Rufus x64 v4.4.2103
Windows version: Windows 10 Home x64 (Build 19045.4239)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0414 (nb-NO)
Will use default UI locale 0x0414
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'nb-NO'
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
0 devices found
```

**Comment by pbatard** [comment]
Applied. Thanks!
