### ISSUE TITLE
"Access to the device is denied" - can be caused by zeroing the partition table and allowing Windows to reformat

### ISSUE THREAD

**Issue by philpem** [pbatard/rufus#2454]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

(None of the additional steps were applicable)

Issue description
-----------------
This is a suggestion for an FAQ update, not a bug.

I was having issues with Rufus throwing an error (the annoying code 5 "access is denied" one), and found a way to cause it on Windows 7 in a way which isn't covered by the FAQ entry.

  - The USB stick was previously used so I put it in a Linux system and used the "dd" command to zero the first GB of the drive
  - After doing so I put it in the Windows system (a virtual machine). Windows asked to format the disk and I allowed this.
  - Unbeknownst to me, Windows somehow created the drive as a raw NTFS volume with no partition table!
  - On running Rufus, I got "Access is denied [0x5]" errors when trying to write the XP 32bit image to the disk

Solution:

I tried using Disk Management to reformat but this was fruitless. Rather than play with Diskpart, I put the drive back into the Linux machine which showed what Windows had done:

```
$ sudo fdisk /dev/sdi

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

The device contains 'ntfs' signature and it will be removed by a write command. See fdisk(8) man page and --wipe option for more details.
```

To fix this, I rewrote the partition table:

```
$ sudo fdisk --wipe always /dev/sdi

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x79f58998.

Command (m for help): w
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
```

I then ran FDISK a second time, created an NTFS partition, and moved it back to the Windows PC which was running Rufus.

On running Rufus I had no issues, the bootdisk was created successfully.

It may be helpful to add a note that disks with improper disk layout (no partition table / MBR) can cause the Access Denied error with Rufus.

The attached log covers both the initial failure and the resolution. For brevity it's just a Rufus format operation; when I was having issues both normal (nonbootable) formatting and XP bootdisk creation would fail.

Log
---
```
Rufus x86 v3.22.2009
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because your version of Windows is too old.
Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5406)
1 device found
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 977, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Checking for Rufus updates...
Checking release channel...
No new release version found.

Format operation started
Requesting disk access...
Will use 'E:' as volume mountpoint
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has an unknown Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Write error [0x00000005] Access is denied.
Retrying in 5 seconds...
Cancelling
Write error [0x00000005] Access is denied.
Could not reset partitions
Re-mounted volume as E: after error

Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5406)
1 device found
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 977, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5406)
1 device found
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 977, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
0 devices found
Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5406)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 977, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x79F58998
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Detected File System: (Unrecognized)
  Size: 7.5 GB (8035237376 bytes)
  Start Sector: 2048, Boot: No

Format operation started
Requesting disk access...
Will use 'E:' as volume mountpoint
Opened \\.\PhysicalDrive1 for exclusive write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (MBR)...
? Creating Main Data Partition (offset: 1048576, size: 7.5 GB)
Waiting for logical drive to reappear...
Formatting to FAT32 (using IFS)
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing Master Boot Record...
Using Zeroed MBR
Found volume \\?\Volume{23a0ae02-f154-11ee-8c0e-806e6f6e6963}\
Created: E:\autorun.inf
Created: E:\autorun.ico
Successfully remounted \\?\Volume{23a0ae02-f154-11ee-8c0e-806e6f6e6963}\ as E:

Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5406)
Using 'autorun.inf' label for drive E: '8 GB'
1 device found
Disk type: Removable, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 977, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Detected File System: FAT32
  Size: 7.5 GB (8035237376 bytes)
  Start Sector: 2048, Boot: No
```

**Comment by pbatard** [comment]
I'd expect the issue to be fixed by using Rufus to zero the drive <kbd>Alt</kbd>-<kbd>Z</kbd> first because this tends to be fairly impervious to denies access errors (this is usually how I solve them when I experience one).

At any rate, I'm afraid I don't support anything that has to do with Windows 7, and it looks like you only experienced this on Windows 7.
