### ISSUE TITLE
Android version request

### ISSUE THREAD

**Issue by ydlmz** [pbatard/rufus#2469]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Need Android ARM version of Rufus, because it couldn't start on Wine - error 40E (Unsupported hardware). Also, unofficial analogs (Rufus Tool (Unofficial)) also couldn't work even with Root. 

Log
---
```
Wine Android ARM 64 version 3.3
Running on Android 10
Running Win2k3-freeboot-reactos
+++
Rufus version: 2.18 (ARM)
rufus.akeo.ie

Device found: JETTRAVELER_8G at OTG0

Format be—
+++
SIGTERM received from 0x4F106
The system will now halt
Error code: 40E [HARDWARE_FAIL_UNSUPPORTED]
Killing Win2k3-freeboot-reactos

Error 40E - Hardware unsupported. Wine will close now
```

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS
