### ISSUE TITLE
no tpm no secure boot options for some reason.

### ISSUE THREAD

**Issue by B1gSlammu** [pbatard/rufus#2479]
﻿I am following the steps that I normally do to install win11 no tpm no secure boot but it does not show me the options in the latest version. In fact I have tried several and it does not do so, it continues directly with the standard installation

**Comment by thecatontheceiling** [comment]
can you please provide a log or the filename of the ISO?

**Comment by pbatard** [comment]
No log &rarr; Closed. You were explicitly warned to provide a log but **chose** not to do so.
