### ISSUE TITLE
Очень долго строятся пути сохранения gpt, что делать?

### ISSUE THREAD

**Issue by Fufelschmerc** [pbatard/rufus#2489]
﻿Здравствуйте!
Установил последнюю версию Руфус и после приложения от Майкрософт начал делать переносной Флэш накопитель с Виндоус, но очень долго идёт строение путей GPT

**Comment by pbatard** [comment]
Didn't follow the check list. No log. I don't know what your issue is.

**Comment by Fufelschmerc** [comment]
![Uploading IMG_20240606_195422.jpg…]()
