### ISSUE TITLE
Install Windows 11 to any computer by using Rufus and Virtualbox

### ISSUE THREAD

**Issue by Lumipyry** [pbatard/rufus#2526]
**This is not an issue - but instead a short solution of how to use Rufus in Virtualbox to create a Windows 11 installation media and to install Windows 11 to any computer.** 

My objective was to create a Windows 11 USB installation media (an USB ISO -file) which would bypass TMP2.0 requirement and which would be capable of installing Windows 11 to an old computer.

I used a virtual Windows 11 in Virtualbox in a Linux computer (Ubuntu 24) for this purpose with Rufus. However 
I had an issue  while creating this installation media. Rufus did not show the option "Windows User Experience" and therefore the newly created USB installation media did not have the option to bypass TMP2.0 and Windows 11 could not be installed to an old computer.

****The fault/issue was not in Rufus but in my  inadequate knowledge of Virtualbox** shared folders behaviour.** I created an USB ISO by both Rufus and Windows 11 ISO being in Virtualbox shared folders - which was a mistake.

INSTEAD the correct way is to move both Rufus and the ISO from shared folders to somewhere INSIDE the virtual Windows 11, for example to files or desktop. 

The same may - or may not - apply to Apple Parallels virtualization program, as you suggested in issue [https://github.com/pbatard/rufus/issues/2268]

..........

**By applying this TMP.2.0. bypass option to Rufus **you, Pete Batard,  **have personally  and solely saved millions of Windows 10 computers to becoming an electronic waste!****** - I repeat - You have saved millions of computers of being an Electronic Waste!

It seems that Microsoft does not care a bit about wasting nature resources, environment, climate change or saving out Planet - but they leave it to you to do single handed the job of a multi billion company... There is not a Nobel Prize for Saving Environment yet - but if there will be - You will certainly be a Candidate...

**Therefore  I'd like to express my gratitude to you, Pete Batard** for creating this program and making it possible for people to update their computers to Windows 11. 

Personally I'd like all the Windows 10 users to switch to Linux - but it is not an option for everyone, especially for the elderly people or for those who are afraid of installing an OS.

Yours sincerely,
Mr. Sami Saarinen
M.Sc. (Engineering) in Materials Science in Pyro Metallurgy and Semiconductor Manufacturing
Suomi   (called abroads as Finland, Finnland, Finlande, Finlandia etc)  ... but please all the foreigners... call my country as Suomi instead of all these names - as we natives do.

[rufus4.5.log](https://github.com/user-attachments/files/16383436/rufus4.5.log)

**Comment by pbatard** [comment]
Thanks for the report.

I will close this issue, but it will of course remain in the issue tracker so that other people (and search engines) can find it.
