### ISSUE TITLE
Windows to Go is not working on Windows 7

### ISSUE THREAD

**Issue by acoul** [pbatard/rufus#2527]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Issue description
-----------------
**Windows to Go is not working on Windows 7**

I have created a Rufus Windows to Go on my USB3/sata disk with a fresh [Windows 7 MDL AiO ISO](https://forums.mydigitallife.net/threads/mdl-win-7-tool-for-simplix-updatepack-aio-iso-with-install-wim-esd-creation.79421/)

but I was not able to successfully boot this on a USB3 hardware due to a 0x0000007B BSOD

I then connected that disk to the SATA port of my motherboard and the installation completed successfully

I then tried to boot that disk out of USB3 again with the same 0x0000007B BSOD error

using the free version of [WinToUSB](https://www.majorgeeks.com/files/details/wintousb.html) on this Windows 7 MDL AiO ISO is working just fine. in the very first boot, the installation completes successfully and the system boots fine on any USB3

Back to Rufus, I was able to resolve this issue of not booting out of USB3 by connecting my Rufus created Win7 to Go USB3/sata disk on another system and running this [set_7_usb_boot.cmd](https://gist.github.com/AlexanderPavlenko/2278427#file-set_7_usb_boot-cmd) script

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED
