### ISSUE TITLE
Rufus Crash in Windows 10 

### ISSUE THREAD

**Issue by MominIqbal-1234** [pbatard/rufus#2531]
![image](https://github.com/user-attachments/assets/d073f90a-04ea-4b19-acbe-f3ad0cd1e833)

both version not working 
click start button rufs  Crash

**Comment by TCFFan123** [comment]
Attach the log

**Comment by pbatard** [comment]
Yes, the checklist, which you ignored, and which explicitly requests a log, documented how you can produce a log even if the application crash using DebugView. And at any rate, you could copy the log from Rufus itself before you press START.

I'm afraid I have *no* time for people who cannot follow a simple checklist, do not even provide the name of the ISO or Boot selection mode they were using, and wrongly assume that, if they experience an issue, then everybody will be able to replicate it.

As a result, and as you were explicitly warned when you opened your request, I will close this issue.
