### ISSUE TITLE
Identifies as if which process is using the device

### ISSUE THREAD

**Issue by moshe625** [pbatard/rufus#2532]
During the initialization the software stops, then an error message arrives that there is some process that uses the device. Although there is no known process that is used and in particular it is after the device has been erased and rebooted. I tried restarting and it didn't help.

**Comment by pbatard** [comment]
During the creation of an issue you are asked to fill a check list. When users choose to ignore that check list and fail to produce a log, it is simply IMPOSSIBLE to help them.

By choosing to disregard the check list, you have also chosen to indicate that you do not genuinely want to receive help. As such I will close this issue.
