### ISSUE TITLE
Rufus wrong size detection

### ISSUE THREAD

**Issue by ikerrg** [pbatard/rufus#2535]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I am trying to write the ISO image in DD mode to a 2 GB USB, but Rufus does not allow to reach the DD selection menu because it wrongly reads the size of the ISO (it is a hybrid ISO, you can download here: "https://dl.acronis.com/s/AcronisTrueImage.iso"). Rufus should check the real size of the ISO file when the DD mode is going to be used, not the size of the files inside the ISO. I know other people asked about Acronis ISOs, but my question is not about Acronis specifically, but about the correct detection of the size when using DD mode.

Log
---
```
Rufus x64 v4.5.2180 (Portable)
Windows version: Windows 10 Pro x64 (Build 19045.4651)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.12
System locale ID: 0x0C0A (es-ES)
Will use default UI locale 0x0C0A
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'es-ES'
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Found USB 2.0 device 'General USB Flash Disk USB Device' (8644:800B)
1 device found
Disk type: Removable, Disk size: 2GB, Sector size: 512 bytes
Cylinders: 243, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has an unknown Master Boot Record
Partition 1:
  Type: EFI System Partition (0xef)
  Detected File System: FAT16
  Size: 762.5 MB (799541248 bytes)
  Start Sector: 232, Boot: Yes
Scanning image...
ISO analysis:
libcdio: Auto-expanding the size of 1-Boot-NoEmul.img
  Image is an ISO9660 image
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'ACRONIS_MEDIA'
  Size: 1.9 GB (Projected)
  Uses: EFI
Using image: AcronisTrueImage.iso (1.1 GB)

Computing hash for 'D:\Descargas\CopiarAdiscoBackup\Acronis\AcronisTrueImage.iso'...
  MD5:    a58797148cb42b054fb97e70fdb0cc08
  SHA1:   5a5c68b05af99a6919c0d2e319960e55e39f4a86
  SHA256: 8e2edc2ad489e047a01f68d10eab0e49186f7f34523e34042c2788d8510e0ce4

```

**Comment by pbatard** [comment]
I'm afraid I'm not going to fix this. The cost/benefit ratio, when it is expected to affect an exceedingly small number of people, is just not worth it.

This will introduce too much complexity (having to have different paths on size checks depending on whether the user will ultimately choose to write in DD or ISO mode) for very little benefit, when few people are going to be using drives that are too close to the file size of the ISO.

I know this is not the answer you wanted to hear, but I have limited development time to invest on features and fixes, which means there will always be a watershed of what I consider worth investing on, and this is just not one of these items.

I will therefore ask you to use a larger drive. Or, if you're going to use Rufus in DD mode, just use one of the many DD writing alternatives.

&rarr; NeverFix
