### ISSUE TITLE
UEFI Win 7 USB fails to boot

### ISSUE THREAD

**Issue by rhampong** [pbatard/rufus#254]
Created a Win7  X64 UEFI GPT boot/install USB. FAT 32 option.
I had to disable Secure Boot.  When I boot, the files are installed (screen  message bar). The Windows logo appears and then distorts. Stays on Starting Windows forever.

My machine is operating on UEFI Win 8 GPT. Rufus run from this machine and boot with the USB was tried on same machine.

**Comment by unlockboot** [comment]
I have success with the new version of Rufus http://www.downloadrufus.com

**Comment by opssemnik** [comment]
I know this is 5 years old, but may happen who is googling this issue (as it is the first link)
Windows 7 bootloader is a legacy one, but it also has UEFI installation files for a uefi installation, you need to enable Legacy support and boot on the UEFI option

**Comment by nagor** [comment]
@opssemnik i am rising a mug of beer to you! Enabling legacy support **did** help. Thanks

**Comment by Mike-Correa** [comment]
@opssemnik thank you so much! I thought i would have to my disc and format in mbr, but thanks to you it worked! You are the only one who actually got the solution for this issue, i couldn't find a solution anywhere else! Thanks for posting it here for us!

**Comment by zxdawn** [comment]
There's another option: Partition system(MBR) and Target system(BIOS).
