### ISSUE TITLE
[Bug] 官方镜像通过Rufus刷写后，提示“由你的组织管理”

### ISSUE THREAD

**Issue by ukhack** [pbatard/rufus#2541]
我使用rufus将最新的23h2刷入优盘，并且开启了类似跳过最低内存检查等一些设置。
插入优盘更新了我的系统，最终系统变成了“由你的组织管理”
![image](https://github.com/user-attachments/assets/3cac147b-a77b-433a-95c9-7f189284299e)

![image](https://github.com/user-attachments/assets/8eba9542-af7f-495b-98e4-bdf37c1620e4)

很多设置都被ban掉了，类似如通过防火墙的按钮都无法点击确认
Many settings are baned

**Comment by thecatontheceiling** [comment]
Rufus doesn't set any policies in the ISO file, even if you use the User Experience check boxes.

https://github.com/pbatard/rufus/blob/20881ceea6f4e941dc4441a448866fb8292f5ef8/src/wue.c

**Comment by pbatard** [comment]
Please be mindful that the **automatic** license activation, that is applied by Microsoft and that is tied to your hardware, ultimately controls what features of Windows are allowed or not.

For instance, if your machine was ever activated for a Windows S Mode license, **Microsoft** will drastically restrict what you can do with Windows, and, again, this is 100% controlled by the type of license that was installed for your machine and **not** how you installed Windows.

At any rate I can guarantee that Rufus had nothing to do with your issue (and you didn't produce a log anyway) so I will close this issue.
