### ISSUE TITLE
ISO image scan failure error with official Windows ISO

### ISSUE THREAD

**Issue by luca-mora** [pbatard/rufus#2549]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I am trying to install Windows 11 on an external SSD to be booted from a computer with no TPM 2.0. However, it seems like Rufus cannot read any of the ISO files I used. The ISO files are:
- Win11_23H2_EnglishInternational_x64v2 (downloaded from the official Windows website)
- Win11_23H2_English_x64v2 (downloaded using rufus' "DOWNLOAD" option, instead of the "SELECT" option)

The error I'm getting after running the media creation process is "ISO image scan failure".
I am running Rufus in Windows 10, from an Intel MacBook Pro that's booting into another external SSD.
Please let me know if additional details are needed.

Log
---
```
Rufus x64 v4.5.2180 (Portable)
Windows version: Windows 10 Home x64 (Build 18363.1556)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.12
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found 517 officially revoked UEFI bootloaders from embedded list
WARNING: Could not parse this system's SkuSiPolicy.p7b for additional revoked UEFI bootloaders
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found UAS (USB 3.1) device 'SanDisk Extreme SSD UAS Device' (0781:558C)
Device eliminated because it was detected as a Hard Drive (score 3 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found UAS (USB 3.0) device 'SanDisk Extreme SSD UAS Device' (0781:55A8)
Device eliminated because it was detected as a Hard Drive (score 18 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
0 devices found
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found UAS (USB 3.1) device 'SanDisk Extreme SSD UAS Device' (0781:558C)
Removing C: from the list: This is the system disk!
Found USB 3.0 device 'Generic MassStorageClass USB Device' (05E3:0749)
Device eliminated because it appears to contain no media
Found UAS (USB 3.0) device 'SanDisk Extreme SSD UAS Device' (0781:55A8)
1 device found
Disk type: FIXED, Disk size: 1TB, Sector size: 512 bytes
Cylinders: 121601, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x004B7B7C
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Detected File System: NTFS
  Size: 931.5 GB (1000203821056 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
Could not mount image 'C:\Users\lucam\Downloads\Win11_23H2_EnglishInternational_x64v2.iso': [0x00000079] The semaphore timeout period has expired.
Could not mount Windows ISO for build number detection
ISO label: 'CCCOMA_X64FRE_EN-GB_DV9'
  Size: 6.3 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.wim (version 0.13.1)
Using image: Win11_23H2_EnglishInternational_x64v2.iso (6.3 GB)

Computing hash for 'C:\Users\lucam\Downloads\Win11_23H2_EnglishInternational_x64v2.iso'...
  MD5:    0a5cccedf724a631ae181e3d0ba042c8
  SHA1:   4138eca827754ba308e4a3eb8d11e86ae5331369
  SHA256: 705ac061688ffd7f5721da844d01df85433856eafaa8441ece94b270685ca2db
WIM extraction method(s) supported: 7-Zip, wimgapi.dll
WIM apply method supported: wimgapi.dll
Could not mount image 'C:\Users\lucam\Downloads\Win11_23H2_EnglishInternational_x64v2.iso': [0x00000079] The semaphore timeout period has expired.
Could not mount ISO for Windows To Go selection

```

**Comment by pbatard** [comment]
> in Windows 10, from an Intel MacBook Pro

There's your issue. You are running Windows on hardware that is not designed to run Windows, and, as you are experiencing, some features of Windows that Rufus relies on (such as the ability to use the Windows native APIs to mount ISOs) will not work, whereas these same capabilities will work just fine on a regular PC.

As you may appreciate, I have zero interest in expanding time trying to troubleshoot issues that are specific to custom environments, and that users running a *regular* installation of Windows on a *regular* PC will not experience.

As a result, I'm afraid that I will close your issue since this is purely specific to your custom nonstandard Windows system.
