### ISSUE TITLE
can support macos 

### ISSUE THREAD

**Issue by dddachui** [pbatard/rufus#2553]
i use macbook pro ，but can not use rufus

**Comment by thecatontheceiling** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS

**Comment by thecatontheceiling** [comment]
You can try using CrossOver but I won't guarantee it'll work:
https://www.codeweavers.com/products

**Comment by pbatard** [comment]
Closing as answered.
