### ISSUE TITLE
Rufus bungles its attempt to start rufus.com when using PowerShell

### ISSUE THREAD

**Issue by michaelmmason** [pbatard/rufus#2556]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
If you start *rufus.exe* from PowerShell, you get an error message. The reason for this is that PowerShell requires a dot-slash in front of the executable name, so you have to type `.\rufus.com` and not just `rufus.com`.

If you start Rufus by typing `.\rufus.exe` at the PowerShell prompt, Rufus starts, then `rufus.com` is echoed at the prompt, you get the error message and then the prompt returns. At that point you can start *rufus.com* by entering `.\rufus.com` and it runs as intended - that is, it hogs the command line until you close the GUI at which point Rufus deletes it.

So I think Rufus needs to execute `.\rufus.com` to make things work as intended.

Log
---
```
Rufus x64 v4.5.2180
Windows version: Windows 10 Pro x64 (Build 19045.4780)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.12
System locale ID: 0x0809 (en-GB)
Will use default UI locale 0x0809
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found 517 officially revoked UEFI bootloaders from embedded list
Found 0 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Found USB 3.0 device 'WD Elements 2620 USB Device' (1058:2620)
Device eliminated because it was detected as a Hard Drive (score 43 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
Found UAS (USB 3.0) device 'Seagate Portable UAS Device' (0BC2:2344)
Device eliminated because it was detected as a Hard Drive (score 53 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives under 'advanced drive properties'
0 devices found
```

**Comment by pbatard** [comment]
Thanks. I should be able to fix this in the next version.
