### ISSUE TITLE
USB Drive dead after interrupted iso flash

### ISSUE THREAD

**Issue by NolonQ** [pbatard/rufus#2559]
﻿

Checklist
---------
- [x ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x ] I also tried one or more of the following:
  - [x ] Using a different USB drive.
  - [x ] Plugging the USB into a different port.
  - [x ] Running Rufus on a different computer.
- [x ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>
I was using rufus to flash a linux iso on a 64GB samsung usb drive.
During the process i found out about ventoy that would allow me to boot the iso live instead of booting it from bios, so i pressed the cancel option in rufus while the iso flashing was still ongoing, for few seconds rufus was loading but then the process finished.
Now when i try to use rufus again on the same usb drive to format it selecting non bootable and making sure a volume name is added, rufus always gives me the same error "error partitioning drive", hmm is there a bad block on the usb now and if so what can i do?

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Please provide the log.

**Comment by pbatard** [comment]
No log &rarr; Closed.
I will also direct you to https://github.com/pbatard/rufus/wiki/FAQ#user-content-Help_Rufus_damaged_my_flash_drive.
