### ISSUE TITLE
bypass the error : This pc's processor doesn't support a critical feature (SSE4.2) during Windows 24H2 installation. 

### ISSUE THREAD

**Issue by rakshit1223** [pbatard/rufus#2578]
Bypass the error : This pc's processor doesn't support a critical feature (SSE4.2)  during Windows 24H2 installation. 
![GHPAqrsX0AAi9tj](https://github.com/user-attachments/assets/d152a2db-d1c0-49a6-bba5-8f7d5a24fb56)

**Comment by pbatard** [comment]
As mentioned in #2568, I am not planning to do anything about this in Rufus.

**Comment by rakshit1223** [comment]
Okay 🙃
