### ISSUE TITLE
I found an issue on rufus-4.6_BETA at installation of Windows 11 24h2 on at unsupported device.

### ISSUE THREAD

**Issue by makjohn1987** [pbatard/rufus#2585]
Good morning 
I updated Windows 11 23h2 to 24h2 thought USB stick I made with rufus-4.6_BETA.exe. The installation was a success. When i try to update my system, I had an error on Windows update 0x800f0825. To fix it, I used this command on Windows terminal dism /online /cleanup-image /restorehealth and sfc /scannow

**Comment by pbatard** [comment]
OK
