### ISSUE TITLE
Rufus 4.6 version writes win11 24H2 image. Unable to enter the installation interface. After waiting for a few minutes, the computer restarts infinitely.

### ISSUE THREAD

**Issue by t-o-n-y-w** [pbatard/rufus#2592]
Rufus 4.6 version writes win11 24H2 image. Unable to enter the installation interface. After waiting for a few minutes, the computer restarts infinitely.

**Comment by pbatard** [comment]
In the absence of checklist data, I'm going to conclude that's it's a Microsoft issue, not a Rufus issue and close this query.
