### ISSUE TITLE
Press any key to boot from usb

### ISSUE THREAD

**Issue by McMedcpr** [pbatard/rufus#2596]
I ran the in place upgrade with beta BEFORE noticing there was a registry fix. Upon Inplace upgrade reboot, disk was not found. 

Unable to repair MBR, tried booting with 4.6 and 24H2 and get stuck at press any key to boot. When I try with 4.5 23H2 I can bypass the press any key to boot from usb screen. 

However, I get a message that I was in the process of upgrading (24H2 presumably). Do I want to continue upgrading? Yes (reboots) or No (clean install).

**Comment by pbatard** [comment]
No log. No check list. Nothing to do with Rufus.
