### ISSUE TITLE
ER: Add support for UEFI/exFAT

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#260]
Like UEFI/NTFS (#228), this needs to be investigated and added if there is demand for it.

Suggested by @cookieboyeli.

**Comment by WK-jun** [comment]
Hello Pete!

I wasn't sure whether to reopen this one or open a new issue/request. Sorry for bothing again, though.

I'd kindly like to ask if there is any progression in this matter after more than two years as UEFI and exFAT becomes more and more established.

Thanks to you I am able to install Win7 on BIOS-based PCs with my exFAT formatted stick. As for UEFI I'm stuck with NTFS. Much better than FAT32 of course, but exFAT is superior to NTFS as THE filesystem for flash media: it was designed for it, is faster, adds to data integrity, has no pointless security overhead and therefore less wear per write.

Your reasons back then were fully understandable, although my opinion is that not the boot process per se requires exFAT for anything, but it is the best choice for a stick as filesystem and the rest of the stick can reasonably be used as data storage (and files >4GB - although you've misspelled exFAT for FAT32 in your last post concerning that).

In sheer desperation I've tried my luck by modding the uefi-ntfs.img and exchanged the ntfs_x64.efi for exfat_x64.efi. It could and should have worked, if the bootloader wouldn't check specifically for NTFS and support its counterpart.

It sounds like not much further work to do, but I could underestimate your expenses here.

Thanks in advance and best regards,
Wilhelm

**Comment by pbatard** [comment]
Well, apart from the points I made in earlier posts, one of the pain points is that I'd have to add an exFAT UEFI driver for IA32, X64, ARM and possibly AA64 in the UEFI:NTFS partition, so that would add to the size of the Rufus download, which I am trying to keep small for various reasons, one of which being that, with 3 million downloads/month, anything that adds size but that's not going to be used by many people is probably not something I'd like to include.

Also, exFAT is encumbered by patents and therefore it doesn't seem like people are as eager to provide as good support for it compared to NTFS. As a result, I'm kind of considering that, if I can push people towards __NOT__ using a file system that was more or less designed towards not being Open Source friendly, that may avoid more patented crap to be thrown against end-users, which isn't that bad a deal.

Finally, it seems to me that people are under the impression that using NTFS will greatly reduced the life expectancy of their flash memory, compared to exFAT, which is quite ridiculous, as flash drives have circuitry that is designed to balanced cell usage, and therefore you're not going to see much wearout from updating allocation tables, compared to what you will get from, say, writing a 4GB file (such as an `install.wim`).

All in all, I'm afraid I still don't see much of a convincing case from exFAT and I can pretty much guarantee that if your flash drive fails when using an NTFS file system, it wouldn't fare that much better when using exFAT.

**Comment by WK-jun** [comment]
Thanks a lot for your in-depth thoughts and technical reasons on that matter. It really must be a dull subject for you by now.
Actually I couln't find any hard proof of how much NTFS' overhead wears off flash memory more than exFAT. More or less, I think it is my main motive to use the "most convenient" or "right" file system all over while maintaining rather one than two or even three file systems on my sticks.
Of course a separate version / download is out of the question for uncommon guys like me and considering the license and driver pain not worth a try.

**Comment by Shivanshu156** [comment]
I use windows to go only to use windows on my mac. Also I have a 1 TB HDD, which I can not use on my mac, once I created a windows to go NTFS HDD.  I am really helpless at this time. Please add option for FAT32 atleast if exFAT is not possible.

> Well, apart from the points I made in earlier posts, one of the pain points is that I'd have to add an exFAT UEFI driver for IA32, X64, ARM and possibly AA64 in the UEFI:NTFS partition, so that would add to the size of the Rufus download, which I am trying to keep small for various reasons, one of which being that, with 3 million downloads/month, anything that adds size but that's not going to be used by many people is probably not something that should be present.
> 
> Also, exFAT is encumbered by patents and therefore it doesn't seem like people are as eager to provide as good support for it compared to NTFS. As a result, I'm kind of considering that, if I can push people towards **NOT** using a file system that was more or less designed towards not being Open Source friendly, that may avoid more patented crap to be thrown against end-users in the future, which isn't a bad goal to try to achieve.
> 
> Finally, it seems to me that people are under the impression that using NTFS will greatly reduce the life expectancy of their flash memory, compared to exFAT, which is quite ridiculous, as flash drives have circuitry that is designed to balanced cell usage, and therefore you're not going to see much wearout from updating allocation tables, compared to what you will get from, say, writing a 4GB file (such as an `install.wim`).
> 
> All in all, I'm afraid I still don't see much of a convincing case from exFAT and I can pretty much guarantee that if your flash drive fails when using an NTFS file system, it won't fare that much better when using exFAT, if that's really what you are after.
