### ISSUE TITLE
Windows 11 won't boot if the processor doesn't support SSE 4.2

### ISSUE THREAD

**Issue by fmarol20** [pbatard/rufus#2600]
﻿Windows 11 will automatically restart the device on unsupported devices based on Twitter user testing.

He wrote: "UPDATE: Since Windows 11 build 26080, a CPU with the SSE4.2 instruction is ALSO REQUIRED to boot Windows 11 Version 24H2!!

Attempting to boot build 26080+ on systems without the SSE4.2 instruction present will cause an automatic reboot once it reaches the boot screen stage."

Microsoft has added SSE4.2 as a blocker to the compatibility list. This means that updates to Windows 11 24H2 will not be offered on systems that do not support SSE4.2
![processor-support-sse4 2](https://github.com/user-attachments/assets/1d31df0e-fe2d-4cb4-b15a-6413a184157d)

**Comment by pbatard** [comment]
**YES**, the check list that you ignored and that ask you to search the FAQ for a relevant entry **did apply to you**.

https://github.com/pbatard/rufus/wiki/FAQ#user-content-This_PC_doesnt_currenty_meet_Windows_11_system_requirements
