### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by thekat883** [pbatard/rufus#2604]
- [x] I have been made aware that if my problem can be summarized as _"I've created or tried to create a media using Rufus, and ..."_, and I am not including a log, **this issue will be summarily closed**.
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: 4.6.2208` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I wanted to create an installation disk but Rufus froze at the moment "cleaning MBR/PBR/GPT structures" I had to close it after which my flash drive died, it won't format, I can't create a volume either, CHKDSK can't do anything either, is there any way to fix the flash drive?

Log
---
```
Rufus x64 v4.6.2208
Windows version: Windows 11 Pro x64 (Build 22631.4317)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.12
System locale ID: 0x0419 (ru-RU)
Will use default UI locale 0x0419
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'ru-RU'
Found 517 revoked UEFI bootloaders from embedded list
Found USB 2.0 device 'General USB Flash Disk USB Device' (090C:1000)
1 device found
No volume information for drive 0x83
Disk type: Removable, Disk size: 32 ГБ, Sector size: 512 bytes
Cylinders: 3824, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found 5 additional UEFI revocation filters from remote SBAT
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200

Format operation started
Requesting disk access...
Will use 'F:' as volume mountpoint
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Opened \\.\PhysicalDrive3 for exclusive write access
Analyzing existing boot records...
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Write error [0x00000079] The semaphore timeout period has expired.
Retrying in 5 seconds...
Write error [0x00000079] The semaphore timeout period has expired.
Retrying in 5 seconds...
Write error [0x00000079] The semaphore timeout period has expired.
Retrying in 5 seconds...
Write error [0x00000079] The semaphore timeout period has expired.
Could not reset partitions
Re-mounted volume as F: after error

Found USB 2.0 device 'General USB Flash Disk USB Device' (090C:1000)
1 device found
No volume information for drive 0x83
Disk type: Removable, Disk size: 32 ГБ, Sector size: 512 bytes
Cylinders: 3824, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 2.0 device 'General USB Flash Disk USB Device' (090C:1000)
1 device found
No volume information for drive 0x83
Disk type: Removable, Disk size: 32 ГБ, Sector size: 512 bytes
Cylinders: 3824, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
```

**Comment by pbatard** [comment]
Your drive looks dead. You will have to replace it.
