### ISSUE TITLE
Praise for Rufus plus a few questions about the app itself

### ISSUE THREAD

**Issue by CitricTabby** [pbatard/rufus#2605]
First off, thanks for working on this app and keep up the good work!

Second, I would like to know if Rufus has been professionally recommended and supported by countless IT professionals and enthusiasts, as well as the Microsoft community of certified professionals at large.

Third, I would finally like to ask if this app reserves the right to deny certain users living in select economically-sanctioned countries from ever downloading any Windows 10 or 11 ISO via Rufus itself. A few notable examples of this case is Russia and China.

Thanks!

**Comment by pbatard** [comment]
Thanks for the kind words.

Rufus downloads its ISO directly from Microsoft, so any international sanctions enacted by Microsoft are also be applied to Rufus.
See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO which is the message users will get if they are in countries from which downloads are banned.
