### ISSUE TITLE
Still USB not showing up after cancelling formatting

### ISSUE THREAD

**Issue by nguyen-cc** [pbatard/rufus#2613]
﻿

Checklist
---------
- [x] I have been made aware that if my problem can be summarized as _"I've created or tried to create a media using Rufus, and ..."_, and I am not including a log, **this issue will be summarily closed**.
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I tried to make a bootable USB writing in DD image mode. However, after waiting for an hour, it just showed 0% and didn't do anything. I tried cancelling it, even though Rufus said the USB would be in an inoperable state. I plugged in the USB again and it didn't show up on Explorer and Rufus, only on the system tray icons. I tried everything such as plugging the USB on other devices and ports, pressing Alt + F and changing boot selection to non-bootable. I opened Device manager and couldn't find the device. Please help!

Log
---
```
![Screenshot 2024-11-14 091918](https://github.com/user-attachments/assets/8d56f1d4-e52b-4b93-bf41-2eba4e427513)
![Screenshot 2024-11-14 090733](https://github.com/user-attachments/assets/3b38123d-2f01-49a2-bbd6-afdcde168fcc)
Rufus x64 v4.6.2208
Windows version: Windows 11 Pro x64 (Build 22631.4317)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.12
System locale ID: 0x0809 (en-GB)
Will use default UI locale 0x0809
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found 517 revoked UEFI bootloaders from embedded list
Processing Hub 1:
  Hub[1] = '\\?\usb#root_hub30#4&cb12d54&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[155]: USB\VID_0B05&PID_1854\5&16BDD27B&0&3
  Found ID[206]: USB\VID_8087&PID_0A2A\5&16BDD27B&0&9
  Found ID[135]: USB\VID_1EA7&PID_0064\5&16BDD27B&0&6
  Found ID[078]: USB\VID_13D3&PID_5666\NULL
  Found ID[116]: USB\VID_3151&PID_4002\5&16BDD27B&0&2
  Found ID[152]: USB\VID_ABCD&PID_1234\2409072136434887089008
Processing IDs belonging to 'USBSTOR':
  USB\VID_ABCD&PID_1234\2409072136434887089008
Processing 'SCSI' device:
  Hardware ID: 'SCSI\DiskSanDisk__SD8SN8U128G1002X413'
Could not get children of 'USB\VID_ABCD&PID_1234\2409072136434887089008'
Found non-USB non-removable device 'SanDisk SD8SN8U128G1002' => Eliminated
Processing 'SCSI' device:
  Hardware ID: 'SCSI\DiskHGST_____HTS725050A7E630GS2O'
Could not get children of 'USB\VID_ABCD&PID_1234\2409072136434887089008'
Found non-USB non-removable device 'HGST HTS725050A7E630' => Eliminated
0 devices found
```

**Comment by pbatard** [comment]
> However, after waiting for an hour, it just showed 0% and didn't do anything. 

So your USB drive was already dead by then.

> I plugged in the USB again and it didn't show up on Explorer and Rufus, only on the system tray icons. 

Your drive is dead.

USB flash drives are A LOT more unreliable than people realise and fail all the time, regardless of what you do (or the application you use to write to the drive). You will have to replace your drive.
