### ISSUE TITLE
Mounting WintoGo with Custom Windows ISO

### ISSUE THREAD

**Issue by pitolu1212** [pbatard/rufus#2618]
i try mount windowstogo with my personalized windows ISO but before finish trip a message "Unable to Patch/Setup files for Boot".
i try mount wintogo with the oficial windows iso file and not have any problem.
I can install normally my personalized ISO to any pcs .

**Comment by pbatard** [comment]
You had been warned your issue would be closed if you **chose** not to follow the check list and provide a log.
