### ISSUE TITLE
I suggest adding a new feature to install Windows 11

### ISSUE THREAD

**Issue by VladislavBanitsky** [pbatard/rufus#2628]
Checklist
---------
- [x] I have been made aware that if my problem can be summarized as _"I've created or tried to create a media using Rufus, and ..."_, and I am not including a log, **this issue will be summarily closed**.
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
When trying to install Windows 11 24H2 on a computer without SSE 4.2 and PopCnt, it is not possible to boot from a USB flash drive. When trying to use the old Windows PE, the installation is successful, but the system is cyclically rebooted on the screen with the system logo. My processor is Intel Pentium Dual-Core E5700. I've tried all the workarounds I know, but none of them worked. I don't want to throw my old computer in the trash, and it's not interesting to use old versions of Windows or Linux. Please solve this problem together!

Log
---
```
Rufus x64 v4.6.2208
Windows version: Windows 11 Pro x64 (Build 26100.2454)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.12
System locale ID: 0x0419 (ru-RU)
Will use default UI locale 0x0419
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'ru-RU'
Found 517 revoked UEFI bootloaders from embedded list
0 devices found
Found 5 additional UEFI revocation filters from remote SBAT
Checking for Rufus updates...
Checking release channel...
No new release version found.
```

**Comment by thecatontheceiling** [comment]
Pretty sure this is in the FAQ
