### ISSUE TITLE
WIndows 7 live boot flash how to enable ntbtlog.txt?

### ISSUE THREAD

**Issue by ruthan** [pbatard/rufus#2638]
Hi, 
i have problem, i installed some but probably storage drive within my bootable Rufus Windows 7 boot flash. I want to try to remove it through dism commands, problem is that i have to know which driver to remove and for it i need ntbtlog.txt.
   
   I have tried it enable through bcd, but it seems that standard enabling process is not working for bootable rufus flash.. i dont now, maybe booting part is some live archive, which i have to edit.

  If my memory serves i used this tutorial:
  https://www.partitionwizard.com/news/rufus-no-windows-to-go-option.html

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED
