### ISSUE TITLE
Is it safe to use multithreading with DISM APIs to remove multiple items from an image simultaneously?

### ISSUE THREAD

**Issue by Hemerson322** [pbatard/rufus#2640]
I lost a **lot** of time trying to figure out why my call to [WIMCreateFile](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/wim/dd851934(v=msdn.10)?view=windows-11) was failing, luckily i found this:

https://github.com/pbatard/rufus/blob/3d5ab84ec15cbe03a4b54e9002d8fe9c3eb782b8/src/vhd.c#L600

I share from you rant as Microsoft should have documented this flag.

I didn't find anything on the documentation if its safe to perform multithreaded calls to [DismRemovePackage](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism/dismremovepackage-function?view=windows-11), [DismRemoveCapability](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism/dismremovecapability?view=windows-11), [DismDisableFeature](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism/dismdisablefeature-function?view=windows-11), i mean, attempt to remove multiple "things" from the image at once.

I'm getting in contact to ask if you have any information about this.

**Comment by pbatard** [comment]
I'm afraid I just don't have any insight on this question. Sorry.
