### ISSUE TITLE
How to enable inbuilt Administrator account as default account instead of creating new account in windows 11

### ISSUE THREAD

**Issue by RameshGokamalla** [pbatard/rufus#2645]
Hi,

Recently, I made my Pendrive bootable with a Windows 11 ISO. Before making it bootable, I chose the create local account option and removed the necessary Microsoft account option from the menu. However, I didn't like having one extra local account even though there are multiple local accounts by default those are disabled but I want an administrator account as my my default account. I know deleting unwanted accounts but I didn't like creating new accounts. Can anyone help me in this?

**Comment by pbatard** [comment]
This is outside of the scope of what I can support in Rufus. If you want to do this using Rufus, you will have to delete the local account afterwards.
