### ISSUE TITLE
Running RUFUS under WinPE x64 fails

### ISSUE THREAD

**Issue by dcolpitts** [pbatard/rufus#2647]
When attempting to run Rufus 4.6 and earlier in WinPE under a pure x64 environment (so no x86 subsystem), Rufus pukes with:

 ".\rufus.com
 This version of rufus.com is not compatible with the version of Windows you're running." 
 
Rufus will then open, however it's not possible to select a Disk or ISO image.

Procexp64 indicates that rufus.com is 32-bit, while rufus-4.6.exe is 64-bit.

Would it be possible to have pure x64 build?

**Comment by pbatard** [comment]
I do not support running Rufus from commandline on systems that don't have the x86 layer.

Either you run Rufus by double clicking on it or you make sure that you install the x86 emulation layer. I will not go out of my way for the corner cases you describe.
