### ISSUE TITLE
Booting with 64KB Cluster Size in NTFS causes "disk read error occurred"

### ISSUE THREAD

**Issue by cookieboyeli** [pbatard/rufus#286]
I don't know if this applies for BIOS, UEFI or both. I haven't tested any other Cluster sizes or combos other than:
MBR for BIOS & UEFI 64KB (error)
MBR for BIOS & UEFI 4KB (no error)

Conclusion: 64KB Cluster Size = not faster.

**Comment by pbatard** [comment]
All things considered, I'm not going to do anything about this one, as, if it affects Windows bootloaders, Microsoft might very well fix it (or already have fixed it) in later versions of Windows, and, as is the case for FreeDOS vs MS-DOS for 64K FAT32, I don't see any reason for a properly designed bootloader not be able to support 64K.

Potentially preventing people from using something that might work is not a good idea, and trying to detect the actual configurations where it doesn't work would be way too much effort for an issue that's only ever going to affect a handful of people (who will be able to find this issue if they search for "disk read error occurred", "NTFS" and "Rufus") &rarr; Not worth it.
