### ISSUE TITLE
ISO image extraction failure

### ISSUE THREAD

**Issue by VoidIndigo** [pbatard/rufus#289]
I'm trying to create a bootable Windows 7 USB on a Windows 7 system. I searched through the messages and didn't see anything exactly like this, so I'm posting... hoping it's something I'm just missing. 

Every time I run Rufus, I get the same error. "Error: ISO image extraction failure". I'm using Rufus v1.4.3.385 ... and the log file looks like this:

```
Format operation started
Requesting disk access...
Caution: Opened drive \\.\PHYSICALDRIVE3 for write access
Will use 'H:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Rufus master boot record
Drive has an unknown partition boot record
Deleting partitions...
Closing existing volume...
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Creating file system: Task 1/12 completed
Creating file system: Task 2/12 completed
Creating file system: Task 3/12 completed
Creating file system: Task 4/12 completed
Creating file system: Task 5/12 completed
Creating file system: Task 6/12 completed
Creating file system: Task 7/12 completed
Creating file system: Task 8/12 completed
Creating file system: Task 9/12 completed
Creating file system: Task 10/12 completed
Creating file system: Task 11/12 completed
Creating file system: Task 12/12 completed
Format completed.
Writing master boot record...
Drive has a zeroed master boot record
Set bootable USB partition as 0x80
Using Rufus MBR
Found volume GUID \\?\Volume{21b80d14-44fe-11e2-a5b7-d4bed9ba630e}\
Caution: Opened drive \\?\Volume{21b80d14-44fe-11e2-a5b7-d4bed9ba630e} for write access
Writing partition boot record...
Using Standard NTFS partition boot record
Confirmed new volume has an NTFS boot sector
Successfully remounted Volume{21b80d14-44fe-11e2-a5b7-d4bed9ba630e}\ on H:\
Copying ISO files...
Extracting files...
Disc image is an UDF image
Extracting: H:\autorun.inf (122 bytes)
Extracting: H:\boot\bcd (256.0 KB)
Extracting: H:\boot\boot.sdi (3.0 MB)
Extracting: H:\boot\bootfix.bin (1.0 KB)
Extracting: H:\boot\bootsect.exe (110.0 KB)
Extracting: H:\boot\en-us\bootsect.exe.mui (15.5 KB)
  Error reading UDF file \boot\en-us\bootsect.exe.mui

Found USB device 'Generic- Multi-Card USB Device' (0BDA:0158)
Device eliminated because it appears to contain no media
Found USB device 'hp v165p USB Device' (03F0:5307)
1 device found
Sector Size: 512 bytes
Cylinders: 1988, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x1B0630BE
Drive has a Rufus master boot record
Partition 1:
  Type: NTFS (0x07)
  Size: 15.2 GB (16357720064 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
```

I suspect it has to do with "Error reading UDF file \boot\en-us\bootsect.exe.mui" ... but I have created a bootable DVD with this ISO image (I downloaded the image straight from Microsoft) and it seems to boot and run OK. The reason I'm trying to create a bootable USB is the system I'm installing on has driver issues with the DVD drive... so I was really hoping this would get around that problem.

Any help?
## Thanks in advance!!

Scott

**Comment by LazyTitan266** [comment]
Hello people,Yeah its not rufus problem,i have had the same problem with my USB,When i tried with an another usb it actually worked.Try using another USB.

**Comment by AhmedFathyAttia** [comment]
I get the same problem,and I re-downloaded  windows 10 and used another flash drive

**Comment by pbatard** [comment]
Just remember that you can check the SHA-1 from your ISO in Rufus, by clicking the `#` button at the bottom of the interface. If you then google for the SHA-1 computed by Rufus and get no hits, then either your ISO is corrupted, or it's a very custom ISO, and you should try to get your hands on a Microsoft official one.

**Comment by johniee** [comment]
My antivarious waw the cause of iso image extraction faliure.... :(

**Comment by samayo** [comment]
I am bew to rufus. It worked like a charm two three times but now all I get is the above error. I have tried two usbs. I did 'check device for bad blocks but all is ok'

**Comment by rlweiner** [comment]
I had the same problem. For some reason Rufus selected FAT32 with a cluster size of 4096 when it started up, even though FAT is the default. I switched it to FAT with the default cluster size and that worked.

**Comment by estumn** [comment]
I recently had a similar incident as a perpetrator software found the Power ISO installation it`s only just now blocked Power ISO x64 as the malware software by built-in smart screen filter Windows 10, I avoid this error by using alternative programs from Rufus website named Rufus portable instead of standart recommend tryhttp://rufus.akeo.ie/downloads/rufus-2.15p.exe if not work then download this file manually called Rufus Portable. There was been similar post i was wrote github.com/pbatard/rufus/issues/155.

**Comment by Ranveer24** [comment]
I fixed this issue by extracting that iso using Winrar
And the deleting Autorun.inf from extracted folder

And again compressing that folder into iso 

And making bootable again it doesn't Giving that error


Sorry for my bad English

**Comment by ruizsj1967** [comment]
How did you put everything back into an ISO?

**Comment by estumn** [comment]
There is lot of ways to put everything back into ISO file:
1) Using 7-zip
2) Using any ISO burners I suggest to try one which doesn`t contains viruses like Opencandy and so on.

1) If you choose 7zip it`s virus free just add all selected files to one file by archiving them make sure there is no hidden files in your file collection, choose file format *.7z, delete it in suggested save address bar, like from C:\myfiles.7z delete 7z and in it`s place type iso, now you can use it as iso CD\DVD
2) Personally I suggest to use ISO burner software you can try free iso burner at site:
http://www.ntfs.com/iso_burner_free.htm

**Comment by Surgikill** [comment]
I had the same issue. Disable windows defender.

**Comment by ibuprophen1** [comment]
An excellent ISO software that I've used for quite a long time is MagicISO. Rufus and MagicISO are my 2 primary goto softwares.

**Comment by arubinofaux** [comment]
I just had this issue and i fixed by manually reformatting the usb to ntfs

**Comment by JStoreInTheHills** [comment]
The failure is caused by antivirus during extraction.
