### ISSUE TITLE
Empty device list in RUFUS 1.4.4.416

### ISSUE THREAD

**Issue by f4ll3nl0rd** [pbatard/rufus#290]
When running RUFUS 1.4.4.16 I've got following screen 
![2014-02-23 21_03_50-new issue pbatard_rufus](https://f.cloud.github.com/assets/42253/2241215/c38c7f5c-9cc5-11e3-9b24-7efbd4d51511.jpg)

OS: Windows 7 x64 Proffesional 
USB: Kingston 1GB

I any other RUFUS version USB was found immediately.

**Comment by Anonymus1** [comment]
still broken for me.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected
