### ISSUE TITLE
USB fixed disks are not being detected in Rufus 1.4.4

### ISSUE THREAD

**Issue by BishopRez** [pbatard/rufus#292]
In Rufus 1.4.4.425 I have the following error:

```
Found USB device 'SanDisk Cruzer Glide USB Device' (0781:5575)
Could not get device number for device \\?\usbstor#disk&ven_sandisk&prod_cruzer_glide&rev_1.26#20052444101b33536f11&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}: [0x00000001] Incorrect function.
A device was eliminated because it didn't report itself as a disk
0 devices found
```

The USB key is new and is recognized in Windows 7 as a fixed disk.

Please help

Dominique

**Comment by milesj098** [comment]
it is still giving me the same thing on rufus 1.4.12

**Comment by NoxMortem** [comment]
Alt+F shows fixed discs altough in some issue here on github it said this mode is "not supported". Still: Thank you so very much for the developement of Rufus and the fixed disc feature as well as in general... Rufus just really saved me when all I had to fix a notebook without any boot options anymore was a fixed disc external drive and an iso file!

**Comment by pbatard** [comment]
> altough in some issue here on github it said this mode is "not supported"

That's because it is "not supported". The option is available in Rufus, but if you encounter any issue when writing to an USB HDD (as opposed to writing to a regular USB Flash Drive), you're on your own.
