### ISSUE TITLE
Error: Could not open media

### ISSUE THREAD

**Issue by cturner6907** [pbatard/rufus#293]
I'm getting this error when trying to mount HBCD iso onto a usb stick: `Error: Could not open media. It may be in use by another process. Please re-plug the media and try again.`

I've tried a few different sticks.
Formatted the sticks using a variety of methods: diskpart fat32, diskpart ntfs etc.
I've verified nothing is running or open from the sticks when running rufus.
Using Rufus 1.4.5.427 on a win 8 x64 machine.

from the log, the error comes at this point:

```
Could not get exclusive access to device \\?\Volume{e4935c07-3beb-11e3-be95-7845c40f7de8}: [0x00000005] Access is denied.
Could not lock volume
```

here is the log:

```
Rufus version: 1.4.5.427
Syslinux versions: 4.07, 5.10
Windows version: Windows 8.1 64-bit
Locale ID: 0x0409
Found USB device 'Kingston DataTraveler 2.0 USB Device' (0930:6545)
1 device found
Sector Size: 512 bytes
Cylinders: 3794, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.1 GB (31212961792 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes

Format operation started
Requesting disk access...
Caution: Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'F:' as volume mountpoint
I/O boundary checks disabled
Could not get exclusive access to device \\?\Volume{e4935c07-3beb-11e3-be95-7845c40f7de8}: [0x00000005] Access is denied.
Could not lock volume
Re-mounted volume as 'F:' after error

Found USB device 'Kingston DataTraveler 2.0 USB Device' (0930:6545)
1 device found
Sector Size: 512 bytes
Cylinders: 3794, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.1 GB (31212961792 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Found USB device 'Kingston DataTraveler 2.0 USB Device' (0930:6545)
1 device found
Sector Size: 512 bytes
Cylinders: 3794, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.1 GB (31212961792 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes

Format operation started
Requesting disk access...
Caution: Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'F:' as volume mountpoint
I/O boundary checks disabled
Could not get exclusive access to device \\?\Volume{e4935c07-3beb-11e3-be95-7845c40f7de8}: [0x00000005] Access is denied.
Could not lock volume
Re-mounted volume as 'F:' after error

Found USB device 'Kingston DataTraveler 2.0 USB Device' (0930:6545)
1 device found
Sector Size: 512 bytes
Cylinders: 3794, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.1 GB (31212961792 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Found USB device 'Kingston DataTraveler 2.0 USB Device' (0930:6545)
1 device found
Sector Size: 512 bytes
Cylinders: 3794, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.1 GB (31212961792 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
```

**Comment by Imtiaz16** [comment]
I had the " Error: Could not open media. It may be in use by another process. Please re-plug the media and try again." problem too.  I used several versins of rufus but none worked. Then i used the 1.4.5 versions as suggested here. It also started to work but then suddenly it stopped and showed a message but i forgot the message. I have saved the log though. Here is the log :
[rufus 1 new.txt](https://github.com/pbatard/rufus/files/244160/rufus.1.new.txt)
Then i again tried but it started to show the first error again.
Wgat can i do now ?

**Comment by Imtiaz16** [comment]
I checked for the SHA1 of the iso in rufus. Here is what i got in the result : 
MD5 : d51601aa9a9d3c5656fe1ac008d4d0e6
SHA1 : cf3011728abe3a17d4ff9083b053c9a844593bd9

**Comment by pbatard** [comment]
The core of the issue is that you have __another__ application that is blocking access to your USB. There isn't much I can do yo help you out with that unless you identify it.
You may also try the <kbd>Alt</kbd>-<kbd>,</kbd> [cheat mode](https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes), to see if that helps, but that's about the best I can suggest. And no, the fact that you once got it working with 1.4.x is unlikely to be significant. If the application that's blocking access decided to relinquish it for whatever reason, then you may find that any version of Rufus works, only to be denied access later on, regardless of the version.

So, again, it is up to you to identify which application is blocking access, and disable it.

**Comment by pbatard** [comment]
Oh, and for the record, SHA1 `cf3011728abe3a17d4ff9083b053c9a844593bd9` does not appear to match any official Microsoft Windows 10 ISO.
