### ISSUE TITLE
Report processes that might be using device on access error

### ISSUE THREAD

**Issue by LeoLevosky** [pbatard/rufus#312]
Every time I try to use Rufus it tells me that another process is using the drive I'm trying to write to, but it doesn't tell me which process. I assume there must be a way of finding out which process is using the device as I understand that Process Explorer from SysInternals can show this information.

It would be so much nicer if Rufus showed this information and offered to close the process. Each time I insert a new USB flash drive something on my system is using it but I don't have the expertise to use Process Explorer correctly. I have tried and just get lost. Something on Windows is clearly using every USB drive I plugin but I have no idea what.

**Comment by pbatard** [comment]
This is more tricky than it looks. I tried to play with [Restart Manager](https://msdn.microsoft.com/library/cc948910.aspx) as documented on [_The Old New Thing_](http://blogs.msdn.com/b/oldnewthing/archive/2012/02/17/10268840.aspx), but it doesn't seem to be able to yield information about what application might be locking a drive...

**Comment by pbatard** [comment]
For people affected with this issue, note that, if you are __really__ sure that whatever application is holding the lock to the USB is not going to access its content (and screw up the partitioning/formatting process), a new <kbd>Alt</kbd>-<kbd>,</kbd> cheat mode will be added in version 2.5, to tell Rufus __not__ to attempt to lock the physical drive before repartitioning. I make not promise that it will alleviate these issues, especially if the lock if for the logical volume, but it might be worth a try.

**Comment by pbatard** [comment]
I'm going to close this issue. Unfortunately, Windows does not appear to provide any API calls allowing to find out what applications have taken a lock on a whole drive. With Restart Manager you can get this data for __individual files__, but there's nothing for drives, and almost all of the `[0x00000005] Access is denied` or similar errors I've seen happen when Rufus is trying to poke a whole drive.

I'm going to consider that, for the time being, the <kbd>Alt</kbd>-<kbd>,</kbd> cheat mode is good enough to try to work around these issues.

**Comment by budmc29** [comment]
I know this is quite old, but just wanted to provide this input as well.
The same issue happened to me, and it was because of Tune Up Utilities (trial version), which based was easy to fix by stopping that process while I used Rufus.

Rufus: 2.15.1117

**Comment by pbatard** [comment]
Thanks for the report.

Would you also be kind enough to provide a __FULL LOG__ of what Rufus reports when you attempt to format your drive when Tune Up is active?

The latest version of Rufus should provide some info about the blocking process in its log, and I'm very curious to see if it correctly identified Tune Up there...

**Comment by budmc29** [comment]
Sorry, reinstalled the Windows then and I don't have Tune Up now.
Next time I'll need to reinstall my Windows I'll paste the full log.
