### ISSUE TITLE
Add drag and drop support

### ISSUE THREAD

**Issue by Sopor-** [pbatard/rufus#316]
It would be great if i could drag and drop ISO images on the button instead of browsing inside Rufus. You often have the ISO already in front of you on your desktop or Explorer, so why browse one more time when it's much easier to drop it on the selection button?

**Comment by pbatard** [comment]
Will need [this](https://msdn.microsoft.com/en-us/library/dd388202.aspx) (`ChangeWindowMessageFilterEx`) if I'm ever going to add [drag and drop to an elevated application](http://blogs.msdn.com/b/patricka/archive/2010/01/28/q-why-doesn-t-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi.aspx) (which still isn't going to happen anytime soon)...
