### ISSUE TITLE
Device scanning fails to find USB drive

### ISSUE THREAD

**Issue by jtwill** [pbatard/rufus#32]
I have tried Rufus on two of my computers, both of which have two optical drives attached, and both have the same problem -- Rufus fails to find the USB drive.  These computers are running 64-bit Windows 7.

Rufus only displays "NO_LABEL (E:)" and all of the other boxes are blank. No other device choices are listed, just the E:, even though I have a SSD at C:, optical drives at D: and E:, and a USB drive at F:

**Comment by Exsilon** [comment]
Help please im very new at this this is the log information
