### ISSUE TITLE
Rufus with USBDLM

### ISSUE THREAD

**Issue by jslegers73** [pbatard/rufus#336]
I have a question. I use Rufus to create bootable USB sticks with iso files.
I also use USBDLM for the drive letters. When I use Rufus it formats the drive and when it copies the files to the usb stick. Only when it wants to copy the files the program reports that it is in use by an other program (probably  USBDLM) and can't continue.Because when it formats the drive it disconnects it from the drive letter. Is there an option for some kind of time out that i can use. If i uninstall the USBLM service the program responds correctly.  

I'm using version 1.4.7

**Comment by pbatard** [comment]
Added USBLDM to the list of incompatible software. Closing this issue.
