### ISSUE TITLE
Rufus Drop Down Boxes All Empty

### ISSUE THREAD

**Issue by jcmattson31** [pbatard/rufus#337]
I am running the latest version of rufus on Arch Linux with wine, and every drop down box is empty. I tried selecting List USB Hard Drives and that did not change anything. I have tried with my USB drive mounted and not mounted. Nothing in any of the boxes. Any tips?

**Comment by DaAwesomeP** [comment]
I know that Rufus isn't supported under Wine, and I can see why i may never be, but I would still like to try to get it to work. The dropdown boxes not working are most likely a problem with fonts missing, a missing system library, or the "wrong" library. Where can I find a list of all of the libraries, DLLs, and fonts that Rufus uses?

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/blob/master/src/rufus.rc for the fonts, along with whatever `CreateFont` calls are used in https://github.com/pbatard/rufus/blob/master/src/rufus.c. For the libraries, you may want to look at the `-l` sections of https://github.com/pbatard/rufus/blob/master/src/Makefile.am as well as perform a lookup of all the `PF_INIT` that are used in the source.

That's as far as I'm going to go to help you there - Rufus is 100% Free Source for crying out loud &rarr; so you can actually look up that information straight from the source. If I were to provide a blow by blow analysis of how Rufus does what it does, I wouldn't have a minute to do anything so, while the advice may sound harsh, either you __can__ pick up what you need from the source, or you shouldn't try to make Rufus work in Wine.

**Comment by DaAwesomeP** [comment]
Thanks for pointing me in the right directions! I'm not really a C developer, so your pointers to specific places in the source are very helpful. If I can't get it to work, then oh well. I don't plan to spend a crazy amount of time on this, but if I do get it to work, then I'll post my results to WineHQ. Thanks again for your help on something that you don't actually support.
