### ISSUE TITLE
Kali Linux v1.0.9 BIOS loading problem

### ISSUE THREAD

**Issue by nelegalno** [pbatard/rufus#374]
Kali Linux v1.0.7 worked fine, but when I tried to reformat the USB with v1.0.9 ISO initially everything went fine. It boots, displays the logo with the boot options and when I press enter it starts loading (displays the 2 lines of text) then there is a beep and a black screen with a blinking cursor. I copied the EFI folder from the efi.img and the USB loads fine under UEFI but it won't load under BIOS.

P.S. It's possible this is due the changes made in v1.0.8 for the EFI booting. 

Links:
http://www.kali.org/
http://cdimage.kali.org/kali-1.0.9/kali-linux-1.0.9-amd64.iso
http://images.kali.org/kali-linux-1.0.9-amd64.torrent

**Comment by cornfeedhobo** [comment]
For any one still plagued by this, I was also able to use LiLi ( http://www.linuxliveusb.com/ ) to get a bootable usb.
