### ISSUE TITLE
LOC: Add Persian translation

### ISSUE THREAD

**Issue by Tashvighi** [pbatard/rufus#384]
Hi
I would like the Persian language be added to the menu Rufus languages
If you agree please email me the file of words used in the program

**Comment by pbatard** [comment]
Note: A new translator is required as __Tashvighi__ has declined to produce a Persian translation.
If anyone is interested, please understand that translating Rufus is a bit more than translating a bunch of words and requires some investment in terms of time. Please see the [Localization guide](https://github.com/pbatard/rufus/wiki/Localization).

**Comment by pbatard** [comment]
Someone kindly volunteered - hopefully this one will stick!

**Comment by ziaa** [comment]
In an email conversation, @pbatard & I talk about translating Rufus into Persian. 
To give a report, I’m glad to say that the translation is in progress and about 30% of it is completed now.

**Comment by pbatard** [comment]
Thanks for the progress report @ziaa. Much appreciated!
