### ISSUE TITLE
"Error: write error" on format

### ISSUE THREAD

**Issue by grnassar** [pbatard/rufus#385]
Running Windows 8.1 (x64).  Rufus seems to refuse to write to my USB drive, using any settings.  Gives "Error: write error" as soon as a format begins.
Tried different file systems, "quick format" on/off, disabling everything but format.  Using "check device for bad blocks," 2 passes, returns no error.
Drive formats fine outside Rufus -- tried diskpart format, works flawlessly, disk reads properly after.  Trying to format drive in Rufus again after diskpart leads to same error.

Log:

> Rufus version: 1.4.10.514
> Syslinux versions: 4.07/2013-07-25, 5.10/2013-06-04
> Windows version: Windows 8.1 64-bit
> Locale ID: 0x0409
> Found USB 2.0 device 'CBM Flash Disk USB Device' (1976:6025)
> 1 device found
> Disk type: Removable, Sector Size: 2048 bytes
> Cylinders: 64, TracksPerCylinder: 255, SectorsPerTrack: 63
> Partition type: MBR, NB Partitions: 1
> Disk ID: 0x00000000
> read_sectors: Read error [0x00000057] The parameter is incorrect.
>   Read: 0, Expected: 512
>   StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
> Drive does not have an x86 Master Boot Record
> Partition 1:
>   Type: FAT16 (0x06)
>   Size: 2.0 GB (2129264640 bytes)
>   Start Sector: 64, Boot: Yes, Recognized: Yes
> 
> Format operation started
> Requesting disk access...
> Opened drive \.\PHYSICALDRIVE1 for write access
> Will use 'U:' as volume mountpoint
> I/O boundary checks disabled
> Analyzing existing boot records...
> read_sectors: Read error [0x00000057] The parameter is incorrect.
>   Read: 0, Expected: 512
>   StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
> Drive does not have an x86 Master Boot Record
> read_sectors: Read error [0x00000057] The parameter is incorrect.
>   Read: 0, Expected: 512
>   StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
> Volume does not have an x86 Partition Boot Record
> Clearing MBR/PBR/GPT structures...
> Erasing 128 sectors
> write_sectors: Write error [0x00000057] The parameter is incorrect.
>   Wrote: 0, Expected: 512
>   StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
> unable to zero MBR/GPT
> Re-mounted volume as 'U:' after error
> 
> Found USB 2.0 device 'CBM Flash Disk USB Device' (1976:6025)
> 1 device found
> Disk type: Removable, Sector Size: 2048 bytes
> Cylinders: 64, TracksPerCylinder: 255, SectorsPerTrack: 63
> Partition type: MBR, NB Partitions: 1
> Disk ID: 0x00000000
> read_sectors: Read error [0x00000057] The parameter is incorrect.
>   Read: 0, Expected: 512
>   StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
> Drive does not have an x86 Master Boot Record
> Partition 1:
>   Type: FAT16 (0x06)
>   Size: 2.0 GB (2129264640 bytes)
>   Start Sector: 64, Boot: Yes, Recognized: Yes
> Found USB 2.0 device 'CBM Flash Disk USB Device' (1976:6025)
> 1 device found
> Disk type: Removable, Sector Size: 2048 bytes
> Cylinders: 64, TracksPerCylinder: 255, SectorsPerTrack: 63
> Partition type: MBR, NB Partitions: 1
> Disk ID: 0x00000000
> read_sectors: Read error [0x00000057] The parameter is incorrect.
>   Read: 0, Expected: 512
>   StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
> Drive does not have an x86 Master Boot Record
> Partition 1:
>   Type: FAT16 (0x06)
>   Size: 2.0 GB (2129264640 bytes)
>   Start Sector: 64, Boot: Yes, Recognized: Yes

**Comment by nasirgg** [comment]
Rufus version: 2.16.1170 (Portable)
Windows version: Windows 10 64-bit (Build 15063)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0409
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'VendorCo ProductCode USB Device' (048D:1234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1958, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x004AE69F
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 15.0 GB (16105078784 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'J_CCSA_X64FRE_EN-US_DV5'
  Size: 3.8 GB (Projected)
  Uses: EFI
  Uses: Bootmgr
  Uses: Install.wim (version 0.13.1)
Using image: en_windows_10_multiple_editions_x64_dvd_6846432.iso

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE1 for exclusive write access
Requesting lock...
Will use 'H:' as volume mountpoint
Requesting lock...
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Volume does not have an x86 Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
Format error: Undetermined error while formatting.
Re-mounted volume as 'H:' after error

Found USB 2.0 device 'VendorCo ProductCode USB Device' (048D:1234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1958, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0052B3E0
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 15.0 GB (16105078784 bytes)
  Start Sector: 2048, Boot: Yes
Closed Windows format prompt
Checking for Rufus updates...
Checking release channel...
No new release version found.

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE1 for exclusive write access
Requesting lock...
Will use 'H:' as volume mountpoint
Requesting lock...
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Volume does not have an x86 Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 65536 bytes
Quick format was selected
Creating file system...
Error while formatting
Format error: Undetermined error while formatting.
Re-mounted volume as 'H:' after error

Found USB 2.0 device 'VendorCo ProductCode USB Device' (048D:1234)
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1958, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00564F17
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 15.0 GB (16105078784 bytes)
  Start Sector: 2048, Boot: Yes
Closed Windows format prompt

**Comment by nasirgg** [comment]
please help

**Comment by nasirgg** [comment]
i got an error while creating bootable usb.

**Comment by pbatard** [comment]
Please open a new issue and __follow__ the check list (by running the bad blocks check).

Also, what happens if you try to format your drive from Windows (i.e. not using Rufus).
The error you are seeing is likely to be due to a hardware problem, and is not something Rufus can fix.
