### ISSUE TITLE
Rufus Doesn't Recognize USB

### ISSUE THREAD

**Issue by scottthomas121** [pbatard/rufus#422]
I have formatted the new USB drive at NTFS several times, but Rufus doesn't recognize the USB.

Rufus version 1.2.0.183
Found drive 'SanDisk Cruzer Glide USB Device'
0 devices found.

**Comment by pbatard** [comment]
> Rufus version 1.2.0.183

The latest version is 1.4.12! You are using a very old version - please try the latest. You can download it at the official site: http://rufus.akeo.ie

If it still doesn't work, can you find out if the drive is listed in Windows Device Manager or Computer Management. If it doesn't appear there, it will never be listed in Rufus.

**Comment by scottthomas121** [comment]
downloading a newer version helped!!!  Thanks for the assistance.
