### ISSUE TITLE
Booting into both BIOS and UEFI

### ISSUE THREAD

**Issue by neheb** [pbatard/rufus#440]
Is this possible with a single USB drive? I just read the FAQ and saw that the first MBR option is designed to do only BIOS booting and the other ones UEFI only. However, many Linux ISO images can do both. Only one image needed.

Can the same be done with Rufus? Maybe through a hidden option?

edit: my question is geared towards Windows 8.1

**Comment by pbatard** [comment]
The dual EFI+BIOS is only disabled for Windows installation, as explained in the [FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Why_doesnt_Rufus_create_a_Windows_installation_USB_that_can_be_booted_in_both_BIOS_and_EFI_mode).
Linux and other distros should see their dual EFI+BIOS boot capabilities preserved.

You can enable dual EFI+BIOS boot for Windows images using `Alt-E`, if you use Rufus 2.0 or later.
