### ISSUE TITLE
device was eliminated because it didn't report itself as disk 1.4.12.535

### ISSUE THREAD

**Issue by milesj098** [pbatard/rufus#445]
![rufus](https://cloud.githubusercontent.com/assets/11010613/6201354/fef111f4-b469-11e4-817a-1f699bef85a9.png)

**Comment by pbatard** [comment]
1. Your image doesn't display
2. __PLEASE__ copy/paste a full log! There's __NOTHING__ I can do unless you provide a log.
3. If your device is an USB HDD then this is normal. See [here](https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected). And as the log indicates, you can easily get your device listed by going to the advanced mode.
4. If your device is not an USB HDD, then I will definitely need the log, as well as the details of your device (manufacturer and exact model).

**Comment by milesj098** [comment]
gimme a sec i tried to put it on but i guess it didnt
im trying to save the log but it wont work it keeps poping up url or somethin

**Comment by pbatard** [comment]
Just copy/paste the content of the log in your reply. Also please indicate if your device is an external HDD or something else.

**Comment by pbatard** [comment]
No update from OP &rarr; Closing.
