### ISSUE TITLE
Rufus 2.0 Beta 2 - Error to create Ubuntu/Xubuntu 64 14.04.02LTS

### ISSUE THREAD

**Issue by ygoralmeida** [pbatard/rufus#449]
While using Rufus 2.0 Beta 2 with Ubuntu64 iso 14.04.02LTS or Xubuntu64 cannot make it work on MBR FAT32 partition.

It creates like a charm, no error found, but when trying to boot on a legacy notebook ( no uefi ) it shows this error. 

boot/grub/i386-pc/normal.mod not found

With previous 1.4.XXX version so far not a single error, just with 2.0 i got this.

**Comment by pbatard** [comment]
Thanks for the report. I think BETA 3, available [here](https://rufus.akeo.ie/downloads/) should now fix this, so I'm going to close this issue. if you still see a problem, feel free to reopen it.
