### ISSUE TITLE
Speed up ISO extraction on small files

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#45]
The CloseHandle() calls are costly for small files as they appear to flush the USB buffer.
By delaying these calls and issuing them in bulk, it may be possible to speed up the writing of small files.

**Comment by yurikoles** [comment]
May be you should try to use WinSetupFromUSB method? E.g. extract just some files from ISO?

**Comment by pbatard** [comment]
After having reconsidered this, I don't think I will ever have time to spent on this kind of optimisation. It does sounds like a fun project, but I'll always have way too many things lined up and this can hardly be considered high priotity &rarr; Closed.
