### ISSUE TITLE
Enable Multiboot ISO feature

### ISSUE THREAD

**Issue by venusbahar** [pbatard/rufus#451]
Please add multiboot ISO feature for adding Windows ISO, Acronis ISO and others  such as:
XBoot: http://www.softpedia.com/get/System/Boot-Manager-Disk/XBoot.shtml
Yumi: http://www.pendrivelinux.com/yumi-multiboot-usb-creator/
WinSetupFromUSB: http://www.softpedia.com/get/PORTABLE-SOFTWARE/System/System-Enhancements/WinSetupFromUSB.shtml

**Comment by pbatard** [comment]
[NO](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiboot_support).

**Comment by skyleet** [comment]
## but why :(

**Comment by pbatard** [comment]
Have you clicked the link and read the FAQ entry on the subject? It explains why.
