### ISSUE TITLE
Support for Portable HDD

### ISSUE THREAD

**Issue by shinjitsunokami** [pbatard/rufus#454]
Rufus's already support many USB, but doesn't supprt portable HDD ( or HDD Enclosure + SSD/HDD)
Please support for portable HDD, too :(
![nh ch p man hinh 41](https://cloud.githubusercontent.com/assets/11254429/6430153/e177695c-c030-11e4-8fb4-28420c0383a6.png)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected
