### ISSUE TITLE
USB Boot

### ISSUE THREAD

**Issue by maxxc0m** [pbatard/rufus#456]
Connet Normal

**Comment by pbatard** [comment]
No idea what this is about &rarr; Closing.

**Comment by maxxc0m** [comment]
The end

**Comment by BMc08GT** [comment]
He is spamming issues trackers, did it to mine too

**Comment by pbatard** [comment]
Hehe, I was just about to reply on your issue to let you know as well.

@maxxc0m, please be mindful that github has the ability to report problematic users, so if you continue spamming issues with cryptic one liners, we will have no choice but to report them and possibly get you banned.
