### ISSUE TITLE
cannot open ISO file

### ISSUE THREAD

**Issue by esongxu** [pbatard/rufus#474]
below are log
```
Rufus version: 2.0.639
Windows version: Windows 7 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
0 devices found
Scanning image...
Disc image is an ISO9660 image
ISO label: ���ֻ�ɽ_GHOST_WIN7_X64
  Size: 3928410112 bytes
  Has a >64 chars filename: No
  Has Symlinks: No
  Has a >4GB file: No
  Uses Bootmgr: No
  Uses EFI: No
  Uses Grub 2: No
  Uses Grub4DOS: No
  Uses isolinux: No
  Uses KolibriOS: No
  Uses ReactOS: No
  Uses WinPE: No
```

**Comment by pbatard** [comment]
According to the log, your image uses neither of `bootmgr`, `EFI`, `Grub`/`Grub4DOS`, `WinPE` or `syslinux`/`isolinux` as its boot method.

These are the only boot methods Rufus is compatible with, as there exists many other custom boot methods that an ISO can use for booting, but it would be very prohibitive for an application like Rufus to try to support them all.
Therefore, as Rufus reports, your image is unsupported.

PS: For the record, an official Windows 7 ISO should be using either `bootmgr` or `EFI`. Your image uses neither.
