### ISSUE TITLE
Rufus and multiboot

### ISSUE THREAD

**Issue by balubeto** [pbatard/rufus#477]
Hi

 With this utility, it is possible to create a bootable USB stick multiboot with some customized editions of Windows 8.x whose ISOs exceed 4096MB? If so, how do I do this knowing that this USB stick will have to work on computers with BIOS or UEFI?

Thanks

 Bye

**Comment by pbatard** [comment]
I already answered you [here](http://www.eightforums.com/tutorials/15458-uefi-bootable-usb-flash-drive-create-windows-47.html#post487309).
