### ISSUE TITLE
Add DMG support

### ISSUE THREAD

**Issue by pgp** [pbatard/rufus#486]
It would be comfortable Rufus to support writing bootable DMG files to USB, without the need of software tools like Transmac.

**Comment by pbatard** [comment]
This has been requested before, but this requires HFS/HFS+ filesystem support, which means implementing access to a whole filesystem in Windows. Transmac probably had to spend a lot of time doing that, and there are no Free Software implementations of HFS/HFS+ for Windows that I could reuse without having to spend months on the feature...

Sorry, but in the present state, it's just not realistic for me to invest that much time on it...

Then again, Rufus if Free Source, so if someone wants to spend the time to do it, I'll gladly accept a patch.

Closing request.
