### ISSUE TITLE
don't force formatting the target drive

### ISSUE THREAD

**Issue by normadize** [pbatard/rufus#492]
This is a great little tool. I wanted to suggest that it would be great if it didn't force formatting the target drive. You can still do quite a lot yet preserve the existing files. This is of interest, for example, when one wants to switch from BIOS to UEFI or from bootmgr to grub4dos ... none of these operations require wiping the drive, which sometimes is too big to backup first.

RMprepUSB allows this (but that tool is quite a mess).

**Comment by pbatard** [comment]
Not gonna do it. It's a lot more trouble than people realize and it would introduce too many points of failure.
