### ISSUE TITLE
[INTERNAL] List of planned FAQ modifications

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#505]
__REMINDER: This topic is flagged as INTERNAL and is NOT a place to either comment on the topics being listed, or request something that is not in the list. As such, any comment will be instantly deleted.__

- [x] Why are the Portable and regular version identical?
- [x] Differences between regular and portable version
- [x] Access Denied error
- [x] Where to copy the Syslinux/Grub files when downloading them manually? See https://github.com/pbatard/rufus/wiki/Usage-Notes#Where_to_manually_copy_the_SyslinuxGRUB_files_if_Rufus_cant_download_them
- [x] Help, I formatted the wrong drive by mistake!
- [x] `Setup was unable to create a new system partition or locate an existing system partition` with some UFDs when installing Windows 7 or later.
- [x] It seems people still don't get why requesting multiboot is pointless
- [x] It really seems that people don't realize that NTFS + UEFI boot is entirely possible. This is getting annoying...
- [x] Reorder some entries. Does Rufus support NTFS compression should be way lower
- [x] Known incompatible images (Kaspersky, Kali, etc.)
- [x] Windows 10 custom ISO contain WIM files that are incompatible with Microsoft's own APIs (go figure...), which means that you **must** use retail/MSDN Windows 10 ISOs (such as the ones you can **legally and freely** download from [Microsoft's Tech Bench](https://www.microsoft.com/en-us/software-download/techbench)) to perform a _To Go_ installation &rarr; No longer needed as addressed with cc108213611febd63c58d7ac77c1f7a1d686bca5.
- [x] Error `[0x00000020]` The process cannot access the file because it is being used by another process.
- [x] Rufus says it can't download Syslinux
- [x] Explain the differences that may be added by Windows' automatic `System Volume Information\` creation on a FAT32 partition, after writing an image in DD mode.
- [x] ~~How can I confirm that my Windows ISO is uncorrupted (something like [this](https://www.reddit.com/r/buildapc/comments/4sp3y2/installing_windows/d5br7wc))~~ Well, Microsoft removed access to the MSDN listing for non subscribers, so this has become moot. Still, one can access the MSDN hashes by login in to https://msdn.microsoft.com/subscriptions/downloads/ and then applying the following in the console: `$("#SubMigratedMessageArea").remove(); $("#DownloadsArea").show();`

**Comment by nutpantz** [comment]
I'm looking for the syslinux files right now so I can download then manually.
Glad to see it's on the to do list. But not as glad as when it's on the been done list.

Thanks for your work.
