### ISSUE TITLE
Specify partition size

### ISSUE THREAD

**Issue by bulltorious** [pbatard/rufus#510]
Hello,

Great work!  Can you add an option to specify the partition size.  I just spent a few hours trying to make a bootable usb for windows 10 on Surface Pro 3.

I ended up having to do it from the command line using diskpart.

a. run diskpart.exe in elevated mode
b. list disk
c. select disk <#>
d. clean
e. create partition primary size=8192 
f. select partition 1
g. active
h. format quick fs=fat32
i. assign
j. exit

I believe I could not get it to work with Rufus because I was using a 64 GB USB drive and had to force the partition to 8192.

**Comment by pbatard** [comment]
Sorry, but I'm not planning to do that, as I don't believe it will be beneficial to that many people, and I estimate that the cost of supporting something that custom would be too high (it would require a UI change, which means ~30 new translations, and, as with many other features, I'd suddenly have to start answering A LOT of mail request about what the feature does, how one can use it, etc.).

If someone wants to create multiple partition, they should use a different tool.

See also [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#wiki-Why_cant_you_just_add_the_feature_I_want_I_mean_youre_a_developer__it_shouldnt_be_that_hard).
