### ISSUE TITLE
SD Card not in list

### ISSUE THREAD

**Issue by gustavopaes** [pbatard/rufus#518]
Hello, I am trying to create a bootable SD Card, but Rufus not list it.

I installed "Linux live usb creator" and the SD Card is listed there.

Is it some bug in Rufus?

**Comment by pbatard** [comment]
Rufus is meant to support USB devices (one of the 'U' of 'Rufus' stands for USB), so if your SD card reader is PCI/PCI-E based, it will not be listed.

This may look like an arbitrary limitation, compared to other tools, but other tools also usually list internal drives, which I consider too risky to do considering the number of people using Rufus and who might end up losing data by mistake as a result of being too permissive.
