### ISSUE TITLE
Rufus for linux

### ISSUE THREAD

**Issue by shivarajnaidu** [pbatard/rufus#520]
sir,
Rufus is an awesome utility...
And it is also an opensource application..

So it is very usefull to linux users, if you develope Rufus  for linux...

**Comment by pbatard** [comment]
Please read [the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxOS_XSome_other_OS) or [perform](https://github.com/pbatard/rufus/issues/515) [a](https://github.com/pbatard/rufus/issues/509) [search](https://github.com/pbatard/rufus/issues/485) before asking questions that have been answered over and over again.

**Comment by shivarajnaidu** [comment]
ok, and thanks for your kind response.
