### ISSUE TITLE
 Windows 10 - Windows to go: iso image extraction failure

### ISSUE THREAD

**Issue by pugan** [pbatard/rufus#521]
Tested on two ISO-s, both checked and well, with rufus-2.1p.exe and rufus-2.2p.exe - same error.
Same job lunched from Win81 system, this error is predicted with "bcryptprimitives.dll error" - I understand this like system compatibility problem.
Lunched from Win10, 32bit version, build 10074, on 99,8% repeat: "Error: iso image extraction failure"

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Windows_To_Go_issues
