### ISSUE TITLE
damaged USB Drive cause of Rufus!!!

### ISSUE THREAD

**Issue by bedouijesser** [pbatard/rufus#522]
![capture6](https://cloud.githubusercontent.com/assets/12767822/8014831/caccfdde-0bcb-11e5-8b6e-727a4ecb78fa.PNG)
I wanted to install an windows 8.1 by burning it to my USB Drive .it was going well until an error accrued .it seemed that my version was damaged. i wanted to erase and do it again with an Win 10 preview version .but the USB Drive was no longer readable 
''Windows version: Windows 7 SP1 32 bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x040C
Found USB device 'AX216 FLASH READER USB Device' (????:????) [ID]
Device eliminated because it appears to contain no media
0 devices found''
![capture](https://cloud.githubusercontent.com/assets/12767822/8014724/c3dc0160-0bca-11e5-80fc-e03b83222a7a.PNG)
![sans titre](https://cloud.githubusercontent.com/assets/12767822/8014779/58b05278-0bcb-11e5-9a16-e3ef6db293e5.jpg)
![capture5](https://cloud.githubusercontent.com/assets/12767822/8014794/83c95086-0bcb-11e5-8f2a-f804174ec90d.PNG)

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive and https://github.com/pbatard/rufus/wiki/FAQ#Rufus_cant_detectformat_my_drive_and_reports_that_it_contains_no_media.

USB drives are not everlasting and can fail whenever you copy data onto it. As explained __at length__ in the FAQ, formatting a drive is no more dangerous than copying files. It looks like your drive chose to fail when Rufus was copying data onto it and the same thing would have happened if you were using Windows Explorer.

There's nothing Rufus can do about hardware failures.

**Comment by Tmp341** [comment]
Try chipgenius, then after you see your drive's chip vendor, if there is a low level formatter tool, try it. If that isn't working, then try downloading it's firmware and try to flash.There are lots of stuff on Google.
