### ISSUE TITLE
"Could not reset partitions"

### ISSUE THREAD

**Issue by CaptainShadows** [pbatard/rufus#525]
Hello, I have been trying to bring a USB that had some formatting issues back to life. Windows simply refuses to format it, to the point that even trying to bring up the context menu nearly crashes explorer, and so I thought I might give it a try with Rufus. 

I know this is not it's intended purpose so feel free to close it without a second thought. However I would appreciate some help with this.

If you haven't closed the issue by this point, here is the error log:
```
Rufus version: 2.2.668
Windows version: Windows 8.1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
0 devices found
Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5530)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1946, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.9 GB (16008593408 bytes)
  Start Sector: 32, Boot: No, Recognized: Yes
 
Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE2 for write access
Will use 'E:' as volume mountpoint
Analyzing existing boot records...
read_sectors: Read error [0x00000002] The system cannot find the file specified.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have an x86 Master Boot Record
read_sectors: Read error [0x00000057] The parameter is incorrect.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Volume does not have an x86 Partition Boot Record
Deleting partitions...
Could not delete drive layout: [0x00000002] The system cannot find the file specified.
Could not reset partitions
Re-mounted volume as 'E:' after error
 
Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5530)
1 device found
No volume information for drive 0x82
Could not get geometry for drive 0x82: [0x00000002] The system cannot find the file specified.
Device was eliminated because it is smaller than 8 MB
No file system is selectable for this drive
Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5530)
1 device found
No volume information for drive 0x82
Could not get geometry for drive 0x82: [0x00000002] The system cannot find the file specified.
Device was eliminated because it is smaller than 8 MB
No file system is selectable for this drive
Found USB 2.0 device 'SanDisk Cruzer USB Device' (0781:5530)
1 device found
No volume information for drive 0x82
Could not get geometry for drive 0x82: [0x00000002] The system cannot find the file specified.
Device was eliminated because it is smaller than 8 MB
No file system is selectable for this drive
```
And here is how Rufus looks after it errors out:
![gnvvfcr](https://cloud.githubusercontent.com/assets/1206968/8133106/082a628c-111e-11e5-9e3d-e9e1e21e05a1.png)

Thanks for any time you have spent looking at this issue.

**Comment by NaoDarkness** [comment]
You could try this:
http://hddguru.com/software/HDD-LLF-Low-Level-Format-Tool/

Click on the : Download Windows Executable, that way you don't have to install anything.

I've used this before on USB's that don't show up in windows at all (no matter what I did to fix it) or when someone messed up a formatting. (Not saying you did) 

But be careful when you use it. It WILL erase everything on the drive you select.

**Comment by pbatard** [comment]
Personally, I think that trying to fix a drive that contains flash blocks that are __clearly__ defective (all signs above point to a flash hardware failure) is a complete waste of time. If you value your data, you will stop using this drive altogether and either get an RMA (if still under warranty) or recycle it.

I will close this issue now.

**Comment by CaptainShadows** [comment]
Ok, thanks. I was simply doing a favor for someone, the tool didn't recognize the drive so I guess that one is dead after all. Thank you very much for your assistance.
