### ISSUE TITLE
sparse iso file

### ISSUE THREAD

**Issue by tomatolog** [pbatard/rufus#538]
I've tryed to make Windows to go USB and always end up with "Could not open ISO" rufus error.
I work at Windows 8.1 and make Windows 8.1 WTG too.
Full log looks like

```
Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE4 for write access
Ignoring drive '\\.\F:' as it spans multiple disks (RAID?)
Will use 'J:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Rufus Master Boot Record
Volume has an unknown Partition Boot Record
Deleting partitions...
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
Adding extra partition
Reserved 33 tracks (1 MB) for extra partition
Writing UEFI:NTFS partition...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Set bootable USB partition as 0x80
Using Windows 7 MBR
Found volume GUID \\?\Volume{18afa742-010e-11e5-824f-806e6f6e6963}\
Opened drive \\?\Volume{18afa742-010e-11e5-824f-806e6f6e6963} for write access
Writing partition boot record...
Using Standard NTFS partition boot record
Confirmed new volume has an NTFS boot sector
Successfully remounted Volume{18afa742-010e-11e5-824f-806e6f6e6963}\ on J:\
Applying Windows image...
Windows To Go mode selected
WIM extraction method(s) supported: 7-Zip, wimgapi.dll
WIM apply method supported: wimgapi.dll
Could not open ISO 'F:\path2win8\WTG_windows_8_enterprise_x64.iso': [0xC03A0005] Отказано в доступе.
Could not mount ISO for Windows To Go installation

Found USB 2.0 device 'Leef Supra USB Device' (8644:8303)
NOTE: This device is an USB 3.0 device operating at lower speed...
Ignoring drive '\\.\F:' as it spans multiple disks (RAID?)
Ignoring drive '\\.\F:' as it spans multiple disks (RAID?)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1957, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x00ABFCA0
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 15.0 GB (16099808256 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Partition 2 (UEFI:NTFS):
  Type: EFI FAT (0xef)
  Size: 256 KB (262144 bytes)
  Start Sector: 31446986, Boot: No, Recognized: Yes
```

I got that iso via torrent app as loading iso via browser from miscrosoft site is very slow for me.
Mounting that iso in windows explorer failed too. After some investigation I found that iso has attribute 'P' that prevents it to be used natively on Windows. I've just copied that file to got rid of that sparse attribute and rufus succefully uses that copied iso.

It might be better to provide better error description or mention there about sparse case. As error "Could not open ISO [0xC03A0005]" leads to nothere in google.

**Comment by pbatard** [comment]
> error "Could not open ISO [0xC03A0005]" leads to nothere in google.

But now it does :smile: (which is __precisely__ the point of this issue tracker.

I don't believe that the 'sparse' attribute (NB: a sparse file is a file with one or more regions of unallocated data in it) is enabled by default on a system, so I would guess that your third party bittorrent application did set the flag on its own. However, when even the native Microsoft tools (such as ISO mounting, which is what Rufus also uses internally) don't seem to be able to handle 'sparse', I would advise not to use 'sparse' unless you really want to and are ready to issue an `fsutil sparse setflag "your_file" 0` before attempting to use it.

If I get reports that more people are using the 'sparse' attribute, I might add a specific check for it in Rufus, but I don't think I will bother adding support for 'sparse' file. However, at the moment, it looks like people who use official images are unlikely to be affected, so I will close this issue, knowing that people who google for that error will still be able to find it and fix it by either using `fsutil` or duplicating the file.
