### ISSUE TITLE
Port to linux

### ISSUE THREAD

**Issue by B3QL** [pbatard/rufus#550]
It will be nice to have rufus on linux :+1:

**Comment by Halamix2** [comment]
See #509 , #485 , #520 , #515 , #93 and most important:
[OFFICIAL FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxOS_XSome_other_OS)

Pete, don't close this one, because people will keep creating new issues otherwise.

**Comment by pbatard** [comment]
People can see closed issues if they do a search. And you should __always__ perform a search for similar issues. I'm not going to keep issues open, that I'm never planning to address, just because some people don't know the proper way to use an issue tracker.
