### ISSUE TITLE
BIOS + UEFI Mode Question (ALT + E)

### ISSUE THREAD

**Issue by Puremin0rez** [pbatard/rufus#555]
After activating it, what do I have to select for the boot scheme and file system?

**Comment by pbatard** [comment]
`MBR partition scheme for BIOS or UEFI`. The 2 other options are UEFI only.

**Comment by Puremin0rez** [comment]
I assume using NTFS as the file system too?

Thanks for the cool program!

**Comment by pbatard** [comment]
Try to use whatever Rufus selects for the file system after you pick the ISO. If the file system is incompatible, Rufus will tell you.

And for the record, it is OK to __try__ and see what works for you - short of sitting in front of the computer you will be booting with Rufus, there's only so much I can advise and you will have to fill the blanks by yourself.
