### ISSUE TITLE
Allow multiple ISO in same drive

### ISSUE THREAD

**Issue by nyroDev** [pbatard/rufus#556]
I don't know if it's possible and the work that it will require, but it will really great if we can create a boot with multiple ISO.
When booting, it will let me choose which ISO I want to load in Grub-like menu and then boot it from there.
Regarding the drive creation:
1) create a USB drive with an option "choose iso menu"
2) Add an ISO with an option "Add element to existing drive"

This will be really helpful in case of recovering computer. Only 1 USB drive to rule them all.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiboot_support

**Comment by nyroDev** [comment]
Thanks for the quick reply and the link you provided.
