### ISSUE TITLE
Damm small Linux distro Rufus USB boots on both computers but Windows Vista x86 only in one.

### ISSUE THREAD

**Issue by mametoc** [pbatard/rufus#566]
Sorry to insist but Windows Vista x86 whit YUMI-2.0.1.8 (wich do in FAT32) seems discontinued since 2014 i asked them but not response at the moment) at least appears a windows boot manager screen whit error BCD whit Rufus any windows think boot but: "disk error: press alt+ctrl+supr".

**Comment by pbatard** [comment]
Do __NOT__ double post.
