### ISSUE TITLE
error 0x0000045D 

### ISSUE THREAD

**Issue by zeitnoot** [pbatard/rufus#572]
there was  a big problem but there progran crushed at all ):

**Comment by pbatard** [comment]
???

I assume that your problem was resolved. If not, then you're not providing enough data for me to help.

**Comment by zeitnoot** [comment]
Sorry...
I resolved this problem by own but when I wanted to delete this message, I didn't find this button :D 
But...If you can answer me why error 0x0000045D occured when I tried to write ISO on the USB I will be grateful...

**Comment by pbatard** [comment]
`0x0000045D` is `ERROR_IO_DEVICE`.

This looks like a hardware error (bad cable, bad USB, bad flash?) and is unlikely to have anything to do with Rufus. You should try with a different USB key and make sure that you don't use any USB extension cables.

**Comment by zeitnoot** [comment]
Thank you for answer and sorry to disturb you.
