### ISSUE TITLE
access to nas hard disk

### ISSUE THREAD

**Issue by ironmanspcasa** [pbatard/rufus#582]
Hi: 
I have a nass dlink 320LW unit with a 3TB hdd with letter Z: in the system windows 8
Your soft is not able to get acces to this letter, the rest of units appears ok but this one no.
can you check it?
I hope the problem is with no local unit hdd

**Comment by pbatard** [comment]
Rufus is designed to eliminate hard drives by default (to prevent the accidental deletion of important backup data for instance).
Please see [here](https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected) to enable listing of USB HDDs. Note that internal (SATA, etc.) HDDs will still not be listed.

**Comment by pbatard** [comment]
Also, if this is a __network__ share, please see [this](https://github.com/pbatard/rufus/wiki/FAQ#Rufus_cannot_see_my_network_shares).
