### ISSUE TITLE
Add Feature

### ISSUE THREAD

**Issue by Aksam420** [pbatard/rufus#586]
Please add feature that can make usb bootable directly from downloaded esd file of microsoft windows

**Comment by pbatard** [comment]
Unless you can point me to an ESD media for Windows 10 in the [official MSDN repository](https://msdn.microsoft.com/en-us/subscriptions/downloads/#searchTerm=&ProductFamilyId=606&Languages=en&PageSize=10&PageIndex=2&FileId=0), I don't think I will do that.
