### ISSUE TITLE
Maintain file date / time

### ISSUE THREAD

**Issue by FysioVision** [pbatard/rufus#594]
Can Rufus maintain the file date and time on the files it is copying from the .iso?

**Comment by pbatard** [comment]
Yes. This has been implemented as a [cheat mode](https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes) (<kbd>Alt</kbd>-<kbd>T</kbd>) and it features prominently in the [__latest release notes__](https://rufus.akeo.ie/#changelog)...

Please do a little bit more search next time, okay?

**Comment by FysioVision** [comment]
Thanks Pete for your quick reply.

 

Next time I will check deeper. But now that I’ve read most of the log (even in Dutch) that would happen soon.

 

Regards, Thijs Ketelaar

 

Van: Pete Batard [mailto:notifications@github.com] 
Verzonden: zaterdag 12 september 2015 13:15
Aan: pbatard/rufus
CC: FysioVision
Onderwerp: Re: [rufus] Maintain file date / time (#594)

 

Yes. This has been implemented as a cheat mode <https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes>  (Alt-T) and it features prominently in the  <https://rufus.akeo.ie/#changelog> latest release notes...

Please do a little bit more search next time, okay?
