### ISSUE TITLE
Wont give me the ability to "Start"

### ISSUE THREAD

**Issue by mdamani** [pbatard/rufus#600]
The Device, Cluster and File System won't update

**Comment by pbatard** [comment]
I assume that what you are saying is that your device is not being listed by default.

Please try the 2.4 BETA [here](https://rufus.akeo.ie/downloads/).

If that still doesn't work, you are probably using a USB HDD (which is not listed by default), so see [here](https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected).

If you still can't see your drive, please reopen this call and provide a __FULL__ log from Rufus.
