### ISSUE TITLE
please let us use a normal storage (sata) to be the device.

### ISSUE THREAD

**Issue by rcarlos243** [pbatard/rufus#612]
Currently it is not possible to use a normal storage (like a sata hard drive or an ssd) as a device when making a bootable ISO.

The thing is a high quality USB drive (like Corsair Neutron GTX, Sandisk Extreme Pro, Supersonic Magnum, etc...) cost alot of money and they are not as fast as a normal SSD.

A really good 120GB sata SSD (like crucial m500) can be have for less than $60 and it is significantly faster than any USB drive.

I currently connect my sata SSD through a USB 3.0 enclosure but it is not possible to use it for rufus to make it act like a bootable USB drive.

**Comment by pbatard** [comment]
> I currently connect my sata SSD through a USB 3.0 enclosure but it is not possible to use it for rufus to make it act like a bootable USB drive.

But it is, if you indeed connect it through an USB enclosure.

If you display the advanced options, you can tell Rufus to list USB HDD enclosures:
![like this](https://github.com/pbatard/rufus/wiki/images/list_fixed_drive.png)

As to why SATA drives will never be listed, __[there is an entry in the FAQ about this](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_support_internal_HDDsSSDs_or_non_USB_card_readers)__.

Next time, please try to look at the FAQ to see if your questions have already been answered, okay?
