### ISSUE TITLE
Using Usb key thru bad quality hub

### ISSUE THREAD

**Issue by cool2014az** [pbatard/rufus#625]
For reference : "Device eliminated because it appears to contain no media"

JetFlash Transcend 16GB USB Device' (8564:1000) was connected to a low quality hub.
```
Rufus version: 2.4.757
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x040C
Found USB 1.1 device 'JetFlash Transcend 16GB USB Device' (8564:1000)
Device eliminated because it appears to contain no media
```
&rarr; then the device connected directly to my laptop : 
```
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1952, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has an unknown Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 15.0 GB (16055664640 bytes)
  Start Sector: 256, Boot: Yes, Recognized: Yes
Found USB 2.0 device 'JetFlash Transcend 16GB USB Device' (8564:1000)
```
I found this may help someone. Thanks.

**Comment by pbatard** [comment]
Thanks for the report. Likewise, Subpar USB extension cables can also be the source of issues.

I will close this issue now, but it it will of course still be available in the issue tracker for people to search for.
