### ISSUE TITLE
EasyBoot ISO Boot Support

### ISSUE THREAD

**Issue by Zardoz2293** [pbatard/rufus#638]
Requesting consideration for booting EZB Systems, EasyBoot created ISO images, www.ezbsystems.com/easyboot.

Receive message "Unsupported image: This image is either non-bootable, or it uses a boot or compression method that is not supported by Rufus..."

Thank you

**Comment by pbatard** [comment]
Too custom, not open & paying software &rarr; not worth it. __Anybody__ can create a custom bootloader, and I will only add support to the ones I deem likely to be used by a lot of people. This is not one of those. Also see [this](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want_I_mean_youre_a_developer__it_shouldnt_be_that_hard).

If you want to convert EasyBoot ISOs to USB, please, use UltraISO from the same manufacturer.
Or, considering that there seems to be Win98 DOS files included (in `DOS98.IMG` &mdash; Did those guys genuinely managed to obtain a license from Microsoft for MS-DOS redistribution? [Last time I checked](http://pete.akeo.ie/2011/12/why-windows-doesnt-let-you-create-usb.html), even HP was forced by Microsoft to remove their Win98 version of MS-DOS from their HPUSBFW utility), you might just be able to get what you want by simply formatting your USB to FreeDOS with Rufus, and then adding the ISO content in a manner similar to what is described here [here](https://github.com/pbatard/rufus/wiki/FAQ#Im_trying_to_work_with_an_ISO_but_Rufus_says_its_unsupported) (of course, each ISO is custom, so you may have to fiddle with the DOS config files to get the content working).

Declined.
