### ISSUE TITLE
Compile Error (VS2015)

### ISSUE THREAD

**Issue by Buzzroid** [pbatard/rufus#642]
I've got lots of the same errors as like,
```
Error   C2001   newline in constant (compiling source file ..\icon.c)   rufus   d:\ripper-projects\rufus\src\rufus.h    45
```
Thanks.

James

**Comment by pbatard** [comment]
How did you obtain the source? Did you clone from git? Somewhere else?

You are the only person reporting this issue, and I am using VS2015 for all Rufus development (and clone it from scratch on regular basis), so this is most likely an issue with your end.

**Comment by pbatard** [comment]
No update from OP &rarr; Closed.

**Comment by ljporljp** [comment]
My page code is 936(Chinese Simplified),i really cloned from git, and this problem confuses me long time!
Is the file-encoding problem?

**Comment by pbatard** [comment]
You probably misconfigured your git newline options. At any rate this is NOT a Rufus issue, and you will have to figure it out by yourself.

**Comment by ljporljp** [comment]
thinks a lot ! is that to say, the git config influences the file-encoding or not ?

**Comment by pbatard** [comment]
Yes it does. Please become familiar with git, Visual Studio, and newline handling. Google is your friend!

**Comment by ljporljp** [comment]
ok,i will search to learn all the things you said, but because of some policy limit, my country can not use google, -.-..thank you so much !

**Comment by zhengfish** [comment]
change System language locale to 'English'
