### ISSUE TITLE
Feature Request: Multi-boot ISOs

### ISSUE THREAD

**Issue by larsenlouis** [pbatard/rufus#643]
I'm wondering if there might be a possibility to burn several images to the target device(e.g. a Windows ISO, a Windows recovery disk and an Ubuntu ISO). When you boot from the target device, a menu pops up and you can choose from a list of ISOs to boot.

**Comment by blackcrack** [comment]
well, did i issue it also.. we need a multibootmenu ..with syslinux + iso/grub/bootmanager ..
but it is not whant

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiboot_support
