### ISSUE TITLE
Replace warning message when formatting USB

### ISSUE THREAD

**Issue by zakum42** [pbatard/rufus#653]
Currently, the message that is displayed when formatting a USB, previous to the image burn is:

- WARNING: ALL DATA [...] *WILL* BE DESTROYED

![c95a68d3050f14dc071a2bbab144c23e](https://cloud.githubusercontent.com/assets/1764493/11840461/64fae9e4-a3f6-11e5-9e00-1964ce190d0a.png)

I think the message should be change among the lines of:

- WARNING: ALL DATA [...] *IS LIKELY TO* BE DESTROYED

The intention of this change is to take into acount that if the 'Quick format' option is used, old data could be preserved in the USB even after burning the image file.

**Comment by pbatard** [comment]
The message is meant to dissuade people from not taking a format operation seriously. What if the drive was formatted as ReFS (which Rufus can do). Do you know of any ReFS recovery tools? Also, will you be the one having to support people e-mailing messages such as "Your popup indicated that my data was unlikely to be lost, so help me get my data back, *NOW*!"

Also, the message is meant to mirror the native Windows formatting message, which doesn't state anything about the likelihood of data being permanently deleted or not:

![image1](https://cloud.githubusercontent.com/assets/1206968/11843749/25a8a346-a403-11e5-8bca-9efad4556807.png)

When you consider all this, what you suggest does not really sound like a good idea. Yes, I could be pedantic about popups and other Rufus dialogs, but I really don't see how this will actually help the vast majority of users, if they start treating formatting operations as something they can afford not to be very careful about.

Rejected.
