### ISSUE TITLE
ini file support or registry backup

### ISSUE THREAD

**Issue by mikhaelkh** [pbatard/rufus#666]
To be truly portable, this tool lacks support config file instead of registry keys. So some [settings](https://github.com/pbatard/rufus/wiki/FAQ#List_of_Rufus_advanced_features_and_cheat_modes) rufus doesn't remember. Is it intentional?
As an alternative, you can add registry backup, this is even better.

**Comment by pbatard** [comment]
> this tool lacks support config file instead of registry keys

No it doesn't (but there are two versions of Rufus: the regular and the portable onw). Please download the portable version, which is clearly labelled as such on the homepage. You'll see it creates a `rufus.ini` file instead of using the registry.

> Some settings rufus doesn't remember. Is it intentional?

Very much so, yes.
