### ISSUE TITLE
Write protect errors on DOS USB sticks

### ISSUE THREAD

**Issue by Wuerfel21** [pbatard/rufus#677]
When writing to C: (the stick itself i guess?) on a FreeDOS or MS-DOS USB stick created by rufus results in this: (MS-DOS output shown, FreeDOS behaves similiar)
```
Write protect error writing drive C
Abort, Retry, Fail?
```

As the machine im using it on can't boot from USB, i used the floppy version of Plop boot loader to do so. Also the machine has no hdd.

**Comment by pbatard** [comment]
__Unless__ you see the same issue when not using plop boot loader, I'm gonna have to dismiss this as a non Rufus issue.

There is nothing in what Rufus does that prevents writing to the DOS disk, but of course, it you are not booting __directly__ from that USB, all bets are off.

I have no idea how plop sets its boot, but it does look to me like plop is most likely what it setting your __virtual__ drive read-only.

Unless someone reports the same issue with direct USB boot, I have no choice but to close your issue and invite you to ask the plop people about it.
