### ISSUE TITLE
Operation run time font color is hardcoded, and cannot obey Windows themes

### ISSUE THREAD

**Issue by cookieboyeli** [pbatard/rufus#683]
The font is hardcoded gray on all themes, breaking Windows High Contrast support.
(Sorry I know it's a PITA). It doesn't meet the required contrast values for official High Contrast support and can become completly invisible depending on background color.

 Here's some pictures to show the breakage:
![rufus bug3](https://cloud.githubusercontent.com/assets/5998991/12567118/4d703068-c38b-11e5-8e6d-b93188cbd934.png)
![rufus bug](https://cloud.githubusercontent.com/assets/5998991/12567124/5041b4a6-c38b-11e5-9819-864005fbd685.png)
![rufus bug2](https://cloud.githubusercontent.com/assets/5998991/12567125/522fcfd2-c38b-11e5-9261-4624f0e639cc.png)
Not even windows supports WIndows high contrast correctly. Switching between it and regular themes leaves a multitude of elements stuck on the old colors, some persisting through reboots and other theme changes! All these lovely bugs are in Windows 10 too. Great how they're trying to keep it familiar for the user. /s

**Comment by pbatard** [comment]
I'm gonna have to pass on that one, sorry, on account that:
1. The duration of the operation is not critical at all to Rufus operations.
2. I'll try to take a look at high contrast and following the user's font choices when I redesign the UI for Rufus 3.0 anyway
3. I have more important issues to deal with, and I'm already behind where I'd like to be for the 2.7 release.

**Comment by cookieboyeli** [comment]
Yup, no problem. It is a mostly trivial UI function. Just making sure it's on your radar.
