### ISSUE TITLE
Bad command or file name

### ISSUE THREAD

**Issue by Jim101** [pbatard/rufus#685]
tried to flash my bios get this message 

Bad command or file name. I did not type a command do I need to? Just typed the file name. 

what shoud I do?

**Comment by pbatard** [comment]
This is not a Rufus issue. You should use google to find posts from other users with the same type of hardware and the DOS command they used to flash their firmwares, or ask the manufacturer of your hardware how you should proceed.

Usually, you need a flashing application and a firmware file, so the command should be something like `FLASH.EXE SOMEFILE.ROM`. But you will need to find:
1. What `FLASH.EXE` should be called in your case
2. Where you can obtain `FLASH.EXE` (usually from the manufacturer site)
3. What command you need to use exactly

on your own...
