### ISSUE TITLE
How to create a Windows ISO?

### ISSUE THREAD

**Issue by Shohreh** [pbatard/rufus#69]
Hello

Sorry to ask this newbie question, but I didn't find a FAQ on the http://rufus.akeo.ie/ site.

I understand Rufus is an alternative to UniversalUSBInstaller, UNetBootIn, etc. to burn an ISO onto a USB keydrive.

But how do I create a Windows ISO? Should I convert the DVD that was provided by the mfg into an ISO file? Should I turn an installed Windows into an ISO file?

Thank you.

**Comment by whitewater76** [comment]
Whats up with the virus scan positive detection's?

**Comment by pbatard** [comment]
1. You shouldn't piggyback on a __completely__ unrelated issue if you want to report a false positive with your antivirus software. If you want to report something that is unrelated to what OP posted in this thread, please open a new issue, as, unbeknownst to most people, piggybacking creates HUGE issues when people try to make sense of two completely independent problems, and end up jumping to wrong conclusions that take a lot of effort to clarify. Piggybacking might seem innocuous to you. Yet, it is anything but...
2. You're going to have __WAY__ more specific than a one liner if you want your report to be take seriously. What AntiVirus solution have you been using? What version of Rufus were you using? Where did you download it from.

As far as I can tell, none of the major antivirus solutions are reporting any false positives for Rufus 3.5 (which is the latest release). See https://www.virustotal.com/#/file/9eceb45d0337dc070f147820048f3bf6279a771b56b814db6f696e6012dbbf20/detection.
