### ISSUE TITLE
Bug? - ISO larger than USB Capacity loads without warning

### ISSUE THREAD

**Issue by epcjay** [pbatard/rufus#698]
Not sure if this is a bug, but in the previous version 1.4.6 is the one I had before, it would prompt to say the ISO is larger than the USB.

However, the latest one doesn't and at times I'd flash a 16.5 gb image on a 16gb USB not realizing the ISO is too big for the USB.  It craps out at 95% with an unknown error, then I realize it was because of a size issue.

**Comment by pbatard** [comment]
The size check is still there. But you have to understand that it is only __approximative__ as it's only after you've extracted everything onto the target file system that you know for sure if the ISO content actually fits.

For instance, if you have a 4GB ISO with loads of small files, it may actually end up taking 5 GB on a FAT32 formatted USB. But short of virtually extracting everything first (or going through each file to find its size, and then compute how much it is likely to occupy on the selected file system, and compute the sum), it's impossible to say for sure that an ISO will actually fit.

Considering that most people will be using USBs that are much larger than any ISOs (are ISOs are usually limited to single sized DVD size, i.e. 4.3GB), and that the time and effort it would take to perform a proper check would be prohibitive, I'm not planning to do anything about that. If you are playing it a bit too close in terms of size, with the target drive you picked, you should accept the consequences.
