### ISSUE TITLE
rufus can't create bootable windows xp x32 usb stick

### ISSUE THREAD

**Issue by balanicamario** [pbatard/rufus#705]
I'm using NTFS filesystem. 
When I try to boot from USB appears a blinking _ and start OS from HDD.

**Comment by pbatard** [comment]
I'm afraid that, since Microsoft has retired Windows XP almost 2 years ago, I too am no longer supporting XP installation troubleshooting. See the first paragraph [of this entry of the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_installation_issues).
