### ISSUE TITLE
[FR] Add ability to pause log autoscroll

### ISSUE THREAD

**Issue by yurikoles** [pbatard/rufus#706]
Like in many console apps for linux and other unices there if you scroll up log it pauses autoscroll.

**Comment by pbatard** [comment]
I don't think I will spend time on that. The log is only meant to help me, the developer, troubleshoot issues so any additional feature besides allowing to retrieve internal information from a user session is not really something I plan to spend any time on.

Still, if someone wants to send a patch that pauses the log, I'll probably try to integrate it. But I don't think I'll be working on that at this stage.
