### ISSUE TITLE
Error creating partition

### ISSUE THREAD

**Issue by danieldsc** [pbatard/rufus#709]
Hi

I got the "error while formatting" and after reading this forum I downloaded last version of Rufus, 2.7, and tried the Alt+z to zero my device.
When I tried to create Windows 7 bootable device again I got the message "error creating partition" right after I clicked start. Then I formatted using windows (FAT32), which was OK, but then I got the same error while formatting message from Rufus. Now I am trying Rufus bad blocks checking, but any ideas about what it might be? I don't know where to get the log file. Please inform. I am running Windows XP.

Thanks

**Comment by pbatard** [comment]
To get the log, just click on the "Log" button (bottom left). A new Window will open with a "Save Log" button you can click (or you can just copy/paste the content).

It does look to me like your USB could indeed be defective, but without the log of the error you get when formatting, or the result of the bad blocks check, that's hard to say for sure.

**Comment by danieldsc** [comment]
Sorry, it was in portuguese and although I am brazilian I got confused with the word because of translation. Here it is (bad blocks checking still going):

Rufus version: 2.7.855
Windows version: Windows XP SP3 32 bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0416
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'GRMCULXFRER_BR_DVD'
  Size: 4292116480 bytes
  Has a >64 chars filename: No
  Has Symlinks: No
  Has a >4GB file: No
  Uses Bootmgr: Yes
  Uses EFI: No
  Uses Grub 2: No
  Uses Grub4DOS: No
  Uses isolinux: No
  Uses KolibriOS: No
  Uses ReactOS: No
  Uses WinPE: No
  Uses Install.wim: Yes (version 0.13.1)
Using image: W7-COMPLETO-x86-x64-AUTO-ATIVAÇÃO-downloadsfulltorrent.blogspot.com.iso

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'D:' as volume mountpoint
Analyzing existing boot records...
Drive does not have an x86 Master Boot Record
Volume does not have an x86 Partition Boot Record
Deleting partitions...
Could not delete drive layout: [0x0000001F] Um dispositivo conectado ao sistema não está funcionando.
Could not reset partitions
Re-mounted volume as 'D:' after error

Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'D:' as volume mountpoint
Analyzing existing boot records...
Drive does not have an x86 Master Boot Record
Volume does not have an x86 Partition Boot Record
Deleting partitions...
Could not delete drive layout: [0x0000001F] Um dispositivo conectado ao sistema não está funcionando.
Could not reset partitions
Re-mounted volume as 'D:' after error

Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'D:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has an unknown Master Boot Record
Volume has an unknown Partition Boot Record
Deleting partitions...
Bad Blocks: Checking from block 0 to 15769599
Bad Blocks: Using offset 0 for fake device check
Bad Blocks: Writing test pattern 0xAA
Bad Blocks: Reading and comparing

**Comment by danieldsc** [comment]
Now the complete log after bad blocks checking (still got the error while formatting):

Rufus version: 2.7.855
Windows version: Windows XP SP3 32 bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0416
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'GRMCULXFRER_BR_DVD'
  Size: 4292116480 bytes
  Has a >64 chars filename: No
  Has Symlinks: No
  Has a >4GB file: No
  Uses Bootmgr: Yes
  Uses EFI: No
  Uses Grub 2: No
  Uses Grub4DOS: No
  Uses isolinux: No
  Uses KolibriOS: No
  Uses ReactOS: No
  Uses WinPE: No
  Uses Install.wim: Yes (version 0.13.1)
Using image: W7-COMPLETO-x86-x64-AUTO-ATIVAÇÃO-downloadsfulltorrent.blogspot.com.iso

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'D:' as volume mountpoint
Analyzing existing boot records...
Drive does not have an x86 Master Boot Record
Volume does not have an x86 Partition Boot Record
Deleting partitions...
Could not delete drive layout: [0x0000001F] Um dispositivo conectado ao sistema não está funcionando.
Could not reset partitions
Re-mounted volume as 'D:' after error

Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'D:' as volume mountpoint
Analyzing existing boot records...
Drive does not have an x86 Master Boot Record
Volume does not have an x86 Partition Boot Record
Deleting partitions...
Could not delete drive layout: [0x0000001F] Um dispositivo conectado ao sistema não está funcionando.
Could not reset partitions
Re-mounted volume as 'D:' after error

Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive does not have an x86 Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 7.5 GB (8074035200 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'D:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has an unknown Master Boot Record
Volume has an unknown Partition Boot Record
Deleting partitions...
Bad Blocks: Checking from block 0 to 15769599
Bad Blocks: Using offset 0 for fake device check
Bad Blocks: Writing test pattern 0xAA
Bad Blocks: Reading and comparing
Bad Blocks: 13357056
Bad Blocks: 13357057
Bad Blocks: 13357058
Bad Blocks: 13357059
Bad Blocks: 13357060
Bad Blocks: 13357061
Bad Blocks: 13357062
Bad Blocks: 13357063
Bad Blocks: 13357064
Bad Blocks: 13357065
Bad Blocks: 13357066
Bad Blocks: 13357067
Bad Blocks: 13357068
Bad Blocks: 13357069
Bad Blocks: 13357070
Bad Blocks: 13357071
Bad Blocks: 13357072
Bad Blocks: 13357073
Bad Blocks: 13357074
Bad Blocks: 13357075
Bad Blocks: 13357076
Bad Blocks: 13357077
Bad Blocks: 13357078
Bad Blocks: 13357079
Bad Blocks: 13357080
Bad Blocks: 13357081
Bad Blocks: 13357082
Bad Blocks: 13357083
Bad Blocks: 13357084
Bad Blocks: 13357085
Bad Blocks: 13357086
Bad Blocks: 13357087
Bad Blocks: 13357088
Bad Blocks: 13357089
Bad Blocks: 13357090
Bad Blocks: 13357091
Bad Blocks: 13357092
Bad Blocks: 13357093
Bad Blocks: 13357094
Bad Blocks: 13357095
Bad Blocks: 13357096
Bad Blocks: 13357097
Bad Blocks: 13357098
Bad Blocks: 13357099
Bad Blocks: 13357100
Bad Blocks: 13357101
Bad Blocks: 13357102
Bad Blocks: 13357103
Bad Blocks: 13357104
Bad Blocks: 13357105
Bad Blocks: 13357106
Bad Blocks: 13357107
Bad Blocks: 13357108
Bad Blocks: 13357109
Bad Blocks: 13357110
Bad Blocks: 13357111
Bad Blocks: 13357112
Bad Blocks: 13357113
Bad Blocks: 13357114
Bad Blocks: 13357115
Bad Blocks: 13357116
Bad Blocks: 13357117
Bad Blocks: 13357118
Bad Blocks: 13357119
Bad Blocks: 13357120
Bad Blocks: 13357121
Bad Blocks: 13357122
Bad Blocks: 13357123
Bad Blocks: 13357124
Bad Blocks: 13357125
Bad Blocks: 13357126
Bad Blocks: 13357127
Bad Blocks: 13357128
Bad Blocks: 13357129
Bad Blocks: 13357130
Bad Blocks: 13357131
Bad Blocks: 13357132
Bad Blocks: 13357133
Bad Blocks: 13357134
Bad Blocks: 13357135
Bad Blocks: 13357136
Bad Blocks: 13357137
Bad Blocks: 13357138
Bad Blocks: 13357139
Bad Blocks: 13357140
Bad Blocks: 13357141
Bad Blocks: 13357142
Bad Blocks: 13357143
Bad Blocks: 13357144
Bad Blocks: 13357145
Bad Blocks: 13357146
Bad Blocks: 13357147
Bad Blocks: 13357148
Bad Blocks: 13357149
Bad Blocks: 13357150
Bad Blocks: 13357151
Bad Blocks: 13357152
Bad Blocks: 13357153
Bad Blocks: 13357154
Bad Blocks: 13357155
Bad Blocks: 13357156
Bad Blocks: 13357157
Bad Blocks: 13357158
Bad Blocks: 13357159
Bad Blocks: 13357160
Bad Blocks: 13357161
Bad Blocks: 13357162
Bad Blocks: 13357163
Bad Blocks: 13357164
Bad Blocks: 13357165
Bad Blocks: 13357166
Bad Blocks: 13357167
Bad Blocks: 13357168
Bad Blocks: 13357169
Bad Blocks: 13357170
Bad Blocks: 13357171
Bad Blocks: 13357172
Bad Blocks: 13357173
Bad Blocks: 13357174
Bad Blocks: 13357175
Bad Blocks: 13357176
Bad Blocks: 13357177
Bad Blocks: 13357178
Bad Blocks: 13357179
Bad Blocks: 13357180
Bad Blocks: 13357181
Bad Blocks: 13357182
Bad Blocks: 13357183
Bad Blocks: 13357184
Bad Blocks: 13357185
Bad Blocks: 13357186
Bad Blocks: 13357187
Bad Blocks: 13357188
Bad Blocks: 13357189
Bad Blocks: 13357190
Bad Blocks: 13357191
Bad Blocks: 13357192
Bad Blocks: 13357193
Bad Blocks: 13357194
Bad Blocks: 13357195
Bad Blocks: 13357196
Bad Blocks: 13357197
Bad Blocks: 13357198
Bad Blocks: 13357199
Bad Blocks: 13357200
Bad Blocks: 13357201
Bad Blocks: 13357202
Bad Blocks: 13357203
Bad Blocks: 13357204
Bad Blocks: 13357205
Bad Blocks: 13357206
Bad Blocks: 13357207
Bad Blocks: 13357208
Bad Blocks: 13357209
Bad Blocks: 13357210
Bad Blocks: 13357211
Bad Blocks: 13357212
Bad Blocks: 13357213
Bad Blocks: 13357214
Bad Blocks: 13357215
Bad Blocks: 13357216
Bad Blocks: 13357217
Bad Blocks: 13357218
Bad Blocks: 13357219
Bad Blocks: 13357220
Bad Blocks: 13357221
Bad Blocks: 13357222
Bad Blocks: 13357223
Bad Blocks: 13357224
Bad Blocks: 13357225
Bad Blocks: 13357226
Bad Blocks: 13357227
Bad Blocks: 13357228
Bad Blocks: 13357229
Bad Blocks: 13357230
Bad Blocks: 13357231
Bad Blocks: 13357232
Bad Blocks: 13357233
Bad Blocks: 13357234
Bad Blocks: 13357235
Bad Blocks: 13357236
Bad Blocks: 13357237
Bad Blocks: 13357238
Bad Blocks: 13357239
Bad Blocks: 13357240
Bad Blocks: 13357241
Bad Blocks: 13357242
Bad Blocks: 13357243
Bad Blocks: 13357244
Bad Blocks: 13357245
Bad Blocks: 13357246
Bad Blocks: 13357247
Bad Blocks: 13357248
Bad Blocks: 13357249
Bad Blocks: 13357250
Bad Blocks: 13357251
Bad Blocks: 13357252
Bad Blocks: 13357253
Bad Blocks: 13357254
Bad Blocks: 13357255
Bad Blocks: 13357256
Bad Blocks: 13357257
Bad Blocks: 13357258
Bad Blocks: 13357259
Bad Blocks: 13357260
Bad Blocks: 13357261
Bad Blocks: 13357262
Bad Blocks: 13357263
Bad Blocks: 13357264
Bad Blocks: 13357265
Bad Blocks: 13357266
Bad Blocks: 13357267
Bad Blocks: 13357268
Bad Blocks: 13357269
Bad Blocks: 13357270
Bad Blocks: 13357271
Bad Blocks: 13357272
Bad Blocks: 13357273
Bad Blocks: 13357274
Bad Blocks: 13357275
Bad Blocks: 13357276
Bad Blocks: 13357277
Bad Blocks: 13357278
Bad Blocks: 13357279
Bad Blocks: 13357280
Bad Blocks: 13357281
Bad Blocks: 13357282
Bad Blocks: 13357283
Bad Blocks: 13357284
Bad Blocks: 13357285
Bad Blocks: 13357286
Bad Blocks: 13357287
Bad Blocks: 13357288
Bad Blocks: 13357289
Bad Blocks: 13357290
Bad Blocks: 13357291
Bad Blocks: 13357292
Bad Blocks: 13357293
Bad Blocks: 13357294
Bad Blocks: 13357295
Bad Blocks: 13357296
Bad Blocks: 13357297
Bad Blocks: 13357298
Bad Blocks: 13357299
Bad Blocks: 13357300
Bad Blocks: 13357301
Bad Blocks: 13357302
Bad Blocks: 13357303
Bad Blocks: 13357304
Bad Blocks: 13357305
Bad Blocks: 13357306
Bad Blocks: 13357307
Bad Blocks: 13357308
Bad Blocks: 13357309
Bad Blocks: 13357310
Bad Blocks: 13357311
Too many bad blocks, aborting test
Bad Blocks: Check completed, 256 bad blocks found. (0/0/256 errors)
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
Format error: Undetermined error while formatting.
Re-mounted volume as 'D:' after error

Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x02B59E48
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 7.5 GB (8072986624 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x02B59E48
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: NTFS/exFAT/UDF (0x07)
  Size: 7.5 GB (8072986624 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes

**Comment by danieldsc** [comment]
After the bad blocks checking I used windows drive repairing tool, then I tried Rufus again and got this log after receiving same error while formaating message:

Rufus version: 2.7.855
Windows version: Windows XP SP3 32 bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0416
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x02B59E48
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 (0x0b)
  Size: 7.5 GB (8072986624 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'GRMCULXFRER_BR_DVD'
  Size: 4292116480 bytes
  Has a >64 chars filename: No
  Has Symlinks: No
  Has a >4GB file: No
  Uses Bootmgr: Yes
  Uses EFI: No
  Uses Grub 2: No
  Uses Grub4DOS: No
  Uses isolinux: No
  Uses KolibriOS: No
  Uses ReactOS: No
  Uses WinPE: No
  Uses Install.wim: Yes (version 0.13.1)
Using image: W7-COMPLETO-x86-x64-AUTO-ATIVAÇÃO-downloadsfulltorrent.blogspot.com.iso

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'D:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Volume has an unknown Partition Boot Record
Deleting partitions...
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
Format error: Undetermined error while formatting.
Re-mounted volume as 'D:' after error

Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x02BE7AB7
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 (0x07)
  Size: 7.5 GB (8072986624 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Found USB device 'Generic Flash Disk USB Device' (0011:7788) [GP]
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 981, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x02BE7AB7
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 (0x07)
  Size: 7.5 GB (8072986624 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes

**Comment by danieldsc** [comment]
I tried to use a different flash drive and now it is copying ISO file. I will report outcome.

**Comment by pbatard** [comment]
```
Bad Blocks: 13357056
Bad Blocks: 13357057
Bad Blocks: 13357058
Bad Blocks: 13357059
Bad Blocks: 13357060
Bad Blocks: 13357061
(...)
```
means your USB is defective. I cannot support you if you try to write to that drive as __it contains bad blocks__.

**Comment by danieldsc** [comment]
It worked out on a different flash drive. Thanks Pete! You may close this.

**Comment by pbatard** [comment]
Okay.
