### ISSUE TITLE
Wiki Update Incompatability

### ISSUE THREAD

**Issue by blade2005** [pbatard/rufus#722]
Got this error
```
Unable to create E:autorun.inf
NOTE: This may be caused by a poorly designed security solution. See http://rufus.akeo.ie/compatibility.

```

This was caused by Avira and Blocking autorun function, you can toggle this is General-> Security settings

**Comment by pbatard** [comment]
Updated the Wiki. Note that this is not a major issue, as `autorun.inf` is an optional file.
