### ISSUE TITLE
Bouton Démarrer

### ISSUE THREAD

**Issue by eikoni** [pbatard/rufus#728]
Bonjour
Nous utilisions très souvent RUFUS au lycée. Le problème, les élèves attendent le transfert de l'iso et
parfois ils cliquent à nouveau sur le bouton démarrer à la fin du processus. Ne serait'il pas judicieux d'ajouter un message à la fin du processus ou de désactiver le bouton démarrer ?
Sinon RUFUS est la référence dans le domaine. Merci et désolé d'exprimer ma requête en français.

**Comment by pbatard** [comment]
Avec la barre de complétion, qui indique quand le processus est fini, je ne vois pas vraiment de raison d'ajouter un dialogue supplémentaire, surtout quand il risque d'ennuyer la majorité des utilisateur.

Si vos élèves ne sont pas suffisamment attentifs au processus, ou ne comprennent pas comment un indicateur de progrès fonctionne, je vois difficilement en quoi c'est a Rufus de pallier a cette déficience. Au contraire, peut être le meilleur moyen d'apprendre comment les interfaces Windows fonctionnent, et à quels éléments il faut faire attention pour savoir si une tache est complétée est précisément de leur laisser faire leurs propres erreurs.

Rejeté.
