### ISSUE TITLE
Virus or false positive ?

### ISSUE THREAD

**Issue by Petrouchka** [pbatard/rufus#729]
I've got this alert : https://www.virustotal.com/fr/file/087a71eed63b3364fc3d3df5ea50d9d5c1b39286b59a6814f25901543a80ea5d/analysis/
Perhaps it's the same problem than with DVDstyler ? Its author solved it with a new version of the installer : https://sourceforge.net/p/dvdstyler/bugs/617/

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Antivirus_X_reports_that_Rufus_contains_malware
