### ISSUE TITLE
Partition Detection Issues

### ISSUE THREAD

**Issue by cajunitalian** [pbatard/rufus#735]
I partitioned a large USB Drive into a 2 GB and a 126 GB partition (one is the Linux installer and the other is large file storage for post installation tasking,code, delivery, etc)

The drive is 128GB USB split into two partitions, when launching RUFUS it just sees the one drive (128GB) and not two different partitions.

![screenshot 38](https://cloud.githubusercontent.com/assets/1809840/14431073/a283fa7e-ffc9-11e5-8cb4-6fda6d1237de.jpg)

**Comment by pbatard** [comment]
Rufus only deals with full drives, not partitions.

According to your log, Rufus properly detected the 2 partitions, but it only ever displays partitions that are accessible from Windows (therefore only `S:`).

If you format this drive however, you will get an extra warning about multiple partitions being present, which you must accept for Rufus to proceed (but of course, you will lose all existing partitions then).

[I have no plans to add multiple partition support or preserve existing partitions](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiple_partition_support). If you need something like this, I will kindly ask that you use another tool.

I will close this issue, as I believe this should answer your question. If that is not the case, feel free to comment further.
