### ISSUE TITLE
reverting the bootable usb...

### ISSUE THREAD

**Issue by CheLM0nster** [pbatard/rufus#736]
Is it possible to revert the bootable USB to it's original state?
In Windows 10, it only shows it as 32 GB when it should be 64 GB and in Rufus 2.8.886 (the same version I used to create the bootable USB) it says [64GB] in the device section.

Should I use Rufus to format the USB to have the full space available? 
I don't want to mess up my USB cause it's fairly new.

Thanks

**Comment by pbatard** [comment]
> Is it possible to revert the bootable USB to it's original state?

Yes. Just select the file system you want and uncheck _"Create bootable drive using..." in Rufus. It will reformat your drive as non bootable, to its full capacity.
