### ISSUE TITLE
Add to incompatibility list

### ISSUE THREAD

**Issue by bambus1980** [pbatard/rufus#737]
Program "Explorer++" is blocking usb-flash from locking by rufus. Many time were lost before I localize the problem. My OS Vista 32bit.

**Comment by pbatard** [comment]
Added to the list &mdash; thanks!

Note that you can try the <kbd>Alt</kbd>-<kbd>,</kbd> [shortcut](https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes) to try to disable drive locking, and see if it helps.

**Comment by bambus1980** [comment]
> Note that you can try the Alt-, shortcut 
Thank you, I'll try later.
