### ISSUE TITLE
Small script for update and pack source based on BSD UNIX or Msys tools

### ISSUE THREAD

**Issue by VictorVG** [pbatard/rufus#742]
Script if needed:
```
@echo off
cd ./rufus&git.exe pull origin -f&tar -czf ./rufus-src.tar.gz --exclude=.git --exclude-vcs ./
cd ../&git clone https://github.com/pbatard/rufus.git rufus-src&tar -czf ./rufus-src.tar.gz --exclude=.git --exclude-vcs ./rufus-src&rm -fr ./rufus-src
```
I use it :)

**Comment by pbatard** [comment]
Err..., thanks?

Not sure what you want me to do with that, but if it can help others.

I think there exists [better ways to create tar archives](https://git-scm.com/docs/git-archive) that exclude git specific files though.

**Comment by VictorVG** [comment]
No, I've been using this script and thought - suddenly someone more useful?
