### ISSUE TITLE
Rufus Version 2.8 (Build 886) Creates exFAT drives w/ Cluster Size TOO SMALL

### ISSUE THREAD

**Issue by Simon5577** [pbatard/rufus#745]
When I tried formatting a 64GB USB thumb-drive using the File system - exFAT, the selection drop-down menu doesn't show a default Cluster Size. No default Cluster size is present in the selection drop-down menu. Only 512 bytes is selected automatically as it is the 1st item in drop-down list. 512 bytes is WAY TOO SMALL. There is SIGNIFICANT performance issues during copying operations with such a small "default" cluster size.  Rufus makes proper default selections for ALL other file systems.

According to Microsoft at: https://support.microsoft.com/en-us/kb/140365

Default cluster sizes for exFAT is:

```
Volume size of: 7 MB–256 MB =====> 4 KB Cluster size
Volume size of: 256 MB–32 GB =====> 32 KB Cluster size
Volume size of: 32 GB–256 TB =====> 128 KB Cluster size
Volume size of: > 256 TB =====> Not supported
```

For my 64GB sized thumb-drive, the drop-down menu should have shown and selected:

`128 kilobytes (Default)`

What bothers me more is that for all my other thumb-drives that has already been formatted using Windows 10's format app as exFAT using the default 128 KB cluster size, is WRONGLY defaulted to and changed to 512 bytes cluster size when the drive is reformatted using Rufus v2.8.

Thanks for creating such fine software!

**Comment by pbatard** [comment]
I'll look into it. Thanks for the report.

**Comment by pbatard** [comment]
There was a typo in the exFAT default cluster selection for >32GB drives.
Instead of being set to 128KB it was set to 28KB, which of course didn't match any entry from the dropdown, therefore the default was never set. This will be fixed in the next version - thanks again for reporting the issue.
