### ISSUE TITLE
USB Manufacturers

### ISSUE THREAD

**Issue by jimshoe52** [pbatard/rufus#749]
Which thumb drive makes & models is Rufus **NOT** compatible with? For example, if I buy a USB 2.0 ScanDisk or Corsair from Walmart will there be any problems?

**Comment by pbatard** [comment]
Answered in the FAQ. See the end of https://github.com/pbatard/rufus/wiki/FAQ#List_of_software_and_hardware_Rufus_isnt_compatible_with

Right now, only Lexar JumpDrive Secure USB drives seem to be problematic. The rest should work.
