### ISSUE TITLE
create a bootable disk is  grey can not click

### ISSUE THREAD

**Issue by eromoe** [pbatard/rufus#782]
what should I do?
I even run it by admin.

**Comment by pbatard** [comment]
Can you paste a screenshot?

The most likely explanation is that your selected USB is using a File System that is not compatible with boot (such as exFAT, UDF or ReFS) in which case you first need to change the File System to FAT32 or NTFS, to be able to create a bootable disk.

**Comment by eromoe** [comment]
Year, my USB is `exFAT` . I think you should add a tooltip  for `create a bootable disk`
