### ISSUE TITLE
Rufus Access denied error potential fix

### ISSUE THREAD

**Issue by Foolanonymous** [pbatard/rufus#785]
So I was getting the Access denied error and couldn't figure out what program was sending out the issue as the common reply to this issue is that there is another program stopping Rufus from getting access when I realized my mistake... The iso file I was trying to mount was ON the usb device which was causing the error.

IF YOUR TRYING TO CREATE A BOOTABLE DRIVE DON'T PUT THE FILE ON THE USB DRIVE.

Don't be an idiot like me

**Comment by pbatard** [comment]
Thanks for the report.

**Comment by Tmp341** [comment]
You made me smile at this hour. 

I salute you. @Foolanonymous
