### ISSUE TITLE
amd64 version and command args

### ISSUE THREAD

**Issue by 447874437** [pbatard/rufus#786]
hello ，
       Thank you for sharing your soft.It is good and simple to use.
       Now I receive a request to auto create usb start up device on winpe with Amd64 architecture.
Will you prefer to  improve the soft at your convenience ?

thanks

**Comment by pbatard** [comment]
I have already received a request to produce a 64-bit version, but I don't think I will do that, on account that very few people actually need one, and if you really do, it's very easy to install Visual Studio 2015 (which you are fully entitled to do, for free) and recompile one. The effort in maintaining and uploading a 64-bit version is just not worth the very few number of users who actually need one (which is people running __restricted__ systems where 32-bit executables are locked out).

So a 64-bit release is not going to happen.

As to command args, I already have an enhancement logged (#111) but don't expect anything fast, as it's very low on priority.
