### ISSUE TITLE
make bootable USB from SeaToolsDOS223ALL.ISO

### ISSUE THREAD

**Issue by resortx** [pbatard/rufus#798]
SeaToolsDOS223ALL.ISO

Rufus version: 2.9.934
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta3
System locale ID: 0x0407
Will use default UI locale 0x0407
Found USB 2.0 device 'Kingston DataTraveler G3 USB Device' (0951:1643)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1950, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0094E1D8
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 14.9 GB (16046358528 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Scanning image...
ISO analysis:
  Image is an ISO9660 image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'SEAGATE'
  Size: 8867840 bytes

**Comment by pbatard** [comment]
Did not follow the checklist. If you did, you would have checked the FAQ. And if you did, you would have seen [this entry](https://github.com/pbatard/rufus/wiki/FAQ#Im_trying_to_work_with_an_ISO_but_Rufus_says_its_unsupported).

Closing.
