### ISSUE TITLE
Does not compile with MinGW becuse of localtime_s

### ISSUE THREAD

**Issue by AndersBillLinden** [pbatard/rufus#806]
With mingw 4.8.1, ./configure and make results in this error message:

````
In file included from bled.c:14:0:
libbb.h: In function 'localtime_r':
libbb.h:199:2: error: implicit declaration of function 'localtime_s' [-Werror=implicit-function-declaration]
  if (localtime_s(result, timep) != 0)
  ^
````

MinGW seems to not have localtime_s declared.
Is compatibility with MinGW dropped?

**Comment by pbatard** [comment]
Your version of MinGW is too old and not supported. Use [msys2](https://sourceforge.net/projects/msys2/) and `pacman -Syuu` to keep your MinGW up to date.

Anything else but msys2 with the __very latest__ MinGW is unsupported.
