### ISSUE TITLE
Could not set drive layout: [0x00000032] The request is not supported.

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#814]
You may see this issue with Rufus 2.10, if your drive was formatted without a partition table (in other words, the device is a single partition occupying the __full__ disk, instead of the data __after__ the partition table).

After that, Rufus or Windows may seem unable to reformat the disk.

If that is the case, you should try <kbd>Alt</kbd>-<kbd>Z</kbd> in Rufus, to zero the drive, then cancel it after a while, and try reformatting your drive again.

This issue will be fixed in Rufus 2.11.

**Comment by Theresnoglitch** [comment]
Cleaning and recreating MBR on the USB helped to solve the same issue: https://tails.boum.org/doc/first_steps/reset/windows/index.en.html
