### ISSUE TITLE
[QUESTION] What does  Alt-Z cheat mode supposed to do?

### ISSUE THREAD

**Issue by NSbuilder** [pbatard/rufus#815]
In the FAQ it says: 

> 
Alt-Z (v2.6 or later) - Zap (zero) the whole target device.
> 

What zero the target drive means? is it different than formatting the drive?

**Comment by pbatard** [comment]
> What zero the target drive means? 

It writes zeroes into every single sector of the drive.
This leaves the drive completely blank and unpartitioned.

If you insert such a drive, Windows will ask you to partition and format it before it can be used.

> is it different than formatting the drive?

Absolutely. Formatting and partitioning, creates boot records, partition records and file index records.

A zeroed drive has none of these, and you'll need to recreate those before you can use it.
