### ISSUE TITLE
Somewhere between 2.6 and 2.7, we screwed up the font for XP users

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#820]
Note to XP users: Between this and #810, I am __genuinely__ this close to dropping XP support altogether in Rufus 2.11...
__You have been warned!__

**Comment by pbatard** [comment]
This was probably introduced with 0f56c2d1ef90e754e17610110afeab690f13d767.

**Comment by NSbuilder** [comment]
Who is using Windows XP anyway?

**Comment by pbatard** [comment]
@NSbuilder,
People who send vocal complaints into my inbox...
