### ISSUE TITLE
Errors When Booting External HD

### ISSUE THREAD

**Issue by PCNoob** [pbatard/rufus#822]
<PLEASE READ THIS CAREFULLY: You *MUST* read and complete the checklist below, by placing an x into each [ ], BEFORE clicking on 'Submit new issue'. Failure to perform these steps, WHICH ARE ONLY THERE TO HELP *YOU*, will result in the issue being dismissed without warning.>

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive
  - [x] Plugging the USB into a different port
  - [x] Running Rufus on a different computer
- [x] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Boot Errors below the wall of text. Text is only there to provide background info. Thanks!

Ok so first off I just want to be open and honest that I entered an "x"in all of those boxes simply so I could ask my question. I am not even sure if this is rufus related but I figured if I wanted to get my question answered this would be the best place. I am going to describe this in as much detail as I can because in my experience it is always the little things that cause the most problems.

I recently bought a steam machine from a coworker for dirt cheap. It works perfectly but for some reason they thought it would be a good idea to make it linux based which doesn't allow us to play the windows version. I watched this really awesome video on youtube which is my go to if I don't know how to do something and he broke it down into steps how to install windows 10 on the steam machine. I got out my old external hard drive and wiped it, then I had to get the windows ISO file from microsoft but I read on this forum somewhere, at some point during my exploration phase, that the media tool microsoft has doesn't give a correct ISO file. I searched and searched and finally came across a comment on youtube. If I used agent switcher to make chrome think I was an android device microsoft would not reroute me to their media tool and I could download that standalone ISO. I did that and downloaded Rufus as well because that is the program the gentlemen used in the video.

I went through it step by and step. After it was finished I tried to boot from the external hard drive. After messing around with supervisor passwords and disabling secure boot (youtube) I got it to work. I was running windows 10 off of my external hard drive and I was giddy as hell. Of course I am doing this all at work using my friends laptop as I have none so now I can't wait to get home. I download a few essentials I know I will need for the steam machine and 2:30 comes and I am out of the door.

I get home and immediately turn on the steam machine to make sure it works. After I confirmed it was working I powered it down, plugged in my external hard drive, and booted to the boot menu. I selected my hard drive as the one I would like to boot too and I get a series of different messages after 3 boot attempts. I will list them in the order I received them.

Boot 1: Unmountable Boot_Volume

Boot 2: info: Boot disk blah blah
info: Disconnecting possible blocking drivers
info: Starting NTFS driver
info: Started driver: efifs NTFS driver v1.0 (grub 2.0)
info: Locating the first NTFS partrition on the boot device
info: Checking if partition needs the NTFS service
WARN: an NTFS service is already loaded
info: looking for NTDS EFI loader
info: Launching NTFS EFI loader

Boot 3: Preparing Automatic Repair

Seeing that this particular activity is your passion I was wondering if anyone could help me out with this? I have found nothing online that helps me, posting on a forum truly is my last resort.>

Log
---
```
<kjkjk>
```

**Comment by pbatard** [comment]
> Ok so first off I just want to be open and honest that I entered an "x"in all of those boxes simply so I could ask my question.

Don't do that. It makes people A LOT LESS likely to want to help you.

> I am not even sure if this is rufus related

It clearly isn't. It's a Windows issue.

> but I figured if I wanted to get my question answered this would be the best place.

Sorry but it's not &rarr; Closed.
