### ISSUE TITLE
Hash sum of latest Rufus build

### ISSUE THREAD

**Issue by dx486** [pbatard/rufus#824]
Could you please provide hash sum (for verification) of latest Rufus build on FAQ page at github? Github would be better because http://rufus.akeo.ie/ does not provide secure connection.

**Comment by pbatard** [comment]
You need to understand that providing hash sums for an executable that is already __digitally signed__ is completely pointless, as the signature validation process will perform an automatic hash verification.

Please see [this](https://github.com/pbatard/rufus/wiki/Security#Executable_signature).

Also, there's an https://rufus.akeo.ie if you like (though downloading a file through https doesn't make it any more secure than through http if it's compromised at the server).
