### ISSUE TITLE
Error: Could not copy files to target drive.

### ISSUE THREAD

**Issue by GreccoTM** [pbatard/rufus#831]
Issue description
-----------------

I'm trying to create MSDOS pendrive bootable, but get error on copy phase.
Follow the full log

```
Rufus version: 2.11.995
Windows version: Windows 8.1 64-bit (Build 9600)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta3
System locale ID: 0x0409
Will use default UI locale 0x0409
Found non-USB removable device 'ST500LT032-1E9142' => Eliminated
Found USB 2.0 device 'Kingston DataTraveler 2.0 USB Device' (0951:160E)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 977, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {E2786D41-4498-4080-B4C9-0767201FBE5F}
Max parts: 128, Start Offset: 17408, Usable = 8036252160 bytes
Partition 1:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Basic data partition'
  ID: {D1C4C23E-3BE4-495F-AC13-C12C4AF8CDFE}
  Size: 7.5 GB (8034189312 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Checking for Rufus updates...
Checking release channel...
No new release version found.

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'D:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (MBR)...
Adding extra partition
Reserved 1 tracks (31.5 KB) for extra partition
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (FAT32)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Set bootable USB partition as 0x80
Using Windows 7 MBR
Found volume GUID \\?\Volume{d1c4c23e-3be4-495f-ac13-c12c4af8cdfe}\
Opened drive \\?\Volume{d1c4c23e-3be4-495f-ac13-c12c4af8cdfe} for write access
Writing partition boot record...
Using Standard FAT32 partition boot record
Confirmed new volume has a primary FAT32 boot sector
Setting primary FAT32 boot sector for boot...
Confirmed new volume has a secondary FAT32 boot sector
Setting secondary FAT32 boot sector for boot...
Successfully remounted Volume{d1c4c23e-3be4-495f-ac13-c12c4af8cdfe}\ on D:\
Copying DOS files...
Patching COMMAND.COM...
Unable to create file 'D:\COMMAND.COM': [0x00000005] Access is denied.
\\?\Volume{d1c4c23e-3be4-495f-ac13-c12c4af8cdfe}\ was already mounted as D:\
Re-mounted volume as 'D:' after error

Found non-USB removable device 'ST500LT032-1E9142' => Eliminated
Found USB 2.0 device 'Kingston DataTraveler 2.0 USB Device' (0951:160E)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 977, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x00ACCD3E
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 7.5 GB (8036195328 bytes)
  Start Sector: 63, Boot: Yes
Partition 2:
  Type: Rufus Extra (0xea)
  Size: 31.5 KB (32256 bytes)
  Start Sector: 15695757, Boot: No
```

**Comment by pbatard** [comment]
This is probably an issue with your security solution. `Access is denied` means an EXTERNAL application is preventing access. You'll have to figure out what it is on your own. Also, next time, please follow the guidelines, as it makes people wore willing to help you.

**Comment by danieljethro** [comment]
hello im also having the smae problem 
it won't let me reformat. pls help. its 125gb flashdrive

\\?\Volume{23f7863e-e66e-11e6-82dc-c80aa950ad1f}\ was already mounted as G:\
Re-mounted volume as 'G:' after error

Found USB 2.0 device 'Generic- SD/MMC USB Device' (0EC2:2015)
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 16317, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: SFD (Super Floppy Disk) or Unpartitioned
Partition 0:
  Type: FAT32 LBA (0x00)
  Size: 0 bytes (0 bytes)
  Start Sector: 0, Boot: Yes

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'G:' as volume mountpoint
Analyzing existing boot records...
Drive has a Windows 7 Master Boot Record
read_sectors: Read error [0x00000057] The parameter is incorrect.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Volume does not have an x86 Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 2176 sectors
Deleting partitions...
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (Large FAT32)...
Opened drive \\?\Volume{23f7863e-e66e-11e6-82dc-c80aa950ad1f} for write access
Size : 125.0 GB 262141952 sectors
Cluster size 32768 bytes, 512 Bytes Per Sector
Volume ID is 1515:3010
32 Reserved Sectors, 31992 Sectors per FAT, 2 FATs
4094967 Total clusters
4094966 Free Clusters
Clearing out 64080 sectors for reserved sectors, FATs and root cluster...
Initializing reserved sectors and FATs...
FAT #0 sector at address: 32
FAT #1 sector at address: 32024
Writing partition boot record...
Using FreeDOS FAT32 partition boot record
Confirmed new volume has a primary FAT32 boot sector
Setting primary FAT32 boot sector for boot...
Confirmed new volume has a secondary FAT32 boot sector
Setting secondary FAT32 boot sector for boot...
Setting Label (This may take while)...
Could not set label: [0x00000057] The parameter is incorrect.
Format completed.
Writing master boot record...
Drive has an unknown Master Boot Record
Warning: converting a non FAT32 partition to FAT32 LBA: FS type=0x00
Set bootable USB partition as 0x80
Using Windows 7 MBR
Found volume GUID \\?\Volume{23f7863e-e66e-11e6-82dc-c80aa950ad1f}\
Warning: Failed to refresh label: [0x00000057] The parameter is incorrect.
Opened drive \\?\Volume{23f7863e-e66e-11e6-82dc-c80aa950ad1f} for write access
Writing partition boot record...
Using FreeDOS FAT32 partition boot record
read_sectors: Read error [0x00000057] The parameter is incorrect.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
New volume does not have a primary FAT32 boot sector - aborting
Successfully remounted Volume{23f7863e-e66e-11e6-82dc-c80aa950ad1f}\ on G:\
Copying DOS files...
Unable to create file 'G:\COMMAND.COM': [0x00000057] The parameter is incorrect.
.
\\?\Volume{23f7863e-e66e-11e6-82dc-c80aa950ad1f}\ was already mounted as G:\
Re-mounted volume as 'G:' after error

Found USB 2.0 device 'Generic- SD/MMC USB Device' (0EC2:2015)
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 16317, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: SFD (Super Floppy Disk) or Unpartitioned
Partition 0:
  Type: FAT32 LBA (0x00)
  Size: 0 bytes (0 bytes)
  Start Sector: 0, Boot: Yes
Saved C:\Users\Jeth\Desktop\rufus.log
