### ISSUE TITLE
Error Unable to patch/setup files for boot

### ISSUE THREAD

**Issue by bnbb2004** [pbatard/rufus#837]
<PLEASE READ THIS CAREFULLY: You *MUST* read and complete the checklist below, by placing an x into each [ ], BEFORE clicking on 'Submit new issue'. Failure to perform these steps, WHICH ARE ONLY THERE TO HELP *YOU*, will result in the issue being dismissed without warning.>

Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [X] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [X] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I keep receiving this error message when running Rufus portable for Win XP iso. I've tried 3 times with the same result.

Please see the following log for more details. 

Any help would be appreciated. TIA! :)

Log
---

See [attached](https://github.com/pbatard/rufus/files/503628/rufus.log.-.winxp.failure.txt)

**Comment by pbatard** [comment]
1. I no longer support XP installation issues. XP is dead, so please do __everybody__ a favour, and stop trying to install a dead and __insecure__ OS.
2. You're using a very old version of Rufus - latest version is 2.11.
3. You're using a __non official__ ISO: `en_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-73974 - thanh.iso`. Even if I was still supporting new XP installations, I wouldn't look into why this specific __unofficial__ image can't work with Rufus. Only official Microsoft ISOs are supported.

As such, I will close this issue.
