### ISSUE TITLE
Request: Multiple Flashdrive Support

### ISSUE THREAD

**Issue by jhaisley** [pbatard/rufus#849]
<PLEASE READ THIS CAREFULLY: You *MUST* read and complete the checklist below, by placing an x into each [ ], BEFORE clicking on 'Submit new issue'. Failure to perform these steps, WHICH ARE ONLY THERE TO HELP *YOU*, will result in the issue being dismissed without warning.>

Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [N/A ] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [N/A] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [N/A] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [N/A] I also tried one or more of the following:
  - [N/A] Using a different USB drive
  - [N/A] Plugging the USB into a different port
  - [N/A] Running Rufus on a different computer
- [N/A] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Would it be possible to support imaging multiple flash drives at once?  I use rufus for imaging computers at our school, and we typically make 10-15 flash drives at once.  

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
I'm afraid not. This is too specific a feature, that will only help too few people. See [here](https://github.com/pbatard/rufus/wiki/FAQ#wiki-Why_cant_you_just_add_the_feature_I_want_I_mean_youre_a_developer__it_shouldnt_be_that_hard) if you need more.
