### ISSUE TITLE
ER: Add tooltip with file info. to the status bar

### ISSUE THREAD

**Issue by SumatraPeter** [pbatard/rufus#853]
The status bar displays the name of the currently loaded ISO (or other) image, except of course that more often than not the name's truncated because of the app window's width. Would it be possible to add a tooltip that displays the full name (or better still the full path and name) of the loaded file? I know this info. is available in the log, but also having it available via a simple tooltip would be useful too. Thanks.

[Note: This is a UI issue so I didn't bother to include the log which is completely irrelevant. Please don't dismiss the issue outright because of this deliberate omission.]

**Comment by pbatard** [comment]
I'm planning to redesign the UI for Rufus 3.0, so I'll see what I can do.

**Comment by SumatraPeter** [comment]
Thanks for such a great utility and looking forward to 3.0 then. (Just curious though, what does "ER" expand to?)

**Comment by pbatard** [comment]
ER: Enhancement Request.

I use that to quickly differentiate enhancements from bugs when looking at the list.

**Comment by pbatard** [comment]
Since this is a small enhancement, I'm going to move it in the list of small enhancements for 3.0 and close this one.
