### ISSUE TITLE
Indicate launch mode in log

### ISSUE THREAD

**Issue by SumatraPeter** [pbatard/rufus#854]
Would it be possible to add a small indication to the log about whether Rufus is running in portable mode or not?

For example, where it normally says "Rufus version: 2.11.995", it could say "Rufus version: 2.11.995 (Portable mode)" or "Rufus (portable) version: 2.11.995" or whatever you deem fit.

**Comment by pbatard** [comment]
Done.  Thanks for the suggestion.

**Comment by SumatraPeter** [comment]
Thank you, I really appreciate it.
