### ISSUE TITLE
USB Problems

### ISSUE THREAD

**Issue by DatSWGuy** [pbatard/rufus#858]
I have an USB 1.0 7GB and if I usually get my files I will have to click on a shortcut in order to get to the files. Now since I know that is a worm Avira™ found the worm and moved it to quarantine. I saw that there was around 3GB left, My brain made me reformatted it and I stopped it after I realized my mistake after 10-20 seconds. The files are now in quarantine I suppose and my USB is left saying (Reformat this in order for it to work message) What should I do?

**Comment by pbatard** [comment]
I'm not sure how this relates to Rufus, and I'm afraid this is not a support forum about data recovery. Please look for data recovery help on the internet.
