### ISSUE TITLE
Is there any version for ubuntu ?

### ISSUE THREAD

**Issue by rasool-sb** [pbatard/rufus#863]
Hi, Is there any version of Rufus for ubuntu 16.10 ? I want to create a windows bootable usb disk from ubuntu using Rufus.., Thanks.

**Comment by pbatard** [comment]
You ignored the checklist and didn't look at the [FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxOS_XSome_other_OS) &rarr; Closed.
