### ISSUE TITLE
Installing W10 on USB stick: error lead to read-only + no format.

### ISSUE THREAD

**Issue by juxuanu** [pbatard/rufus#872]
Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [X] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [X] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [X] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
To start with, the log attached below is the output I get when trying to format my USB stick. The moment it got read-only and with no format has not been saved since I did not think about saving the log then, I just closed Rufus when error showed up.
The issue here is that at some point when I was using a W10 .iso file from Microsoft's website to create a bootable USB stick (to be used to install W10 on another PC) it found an error and stopped the operation. The USB stick is a 4GB's. After the error showed up and I closed Rufus, I went to the Windows Explorer and checked it. It had no letter assigned, so I went to Disk Manager and assigned one. I saw, afterwards, that it had no format. So I tried to format it from the Windows tool. 
It said and says that it is read-only, meaning is now useless: no format and read-only. I obviously tried (I think) all options in Rufus with no luck. Also tried with DiskPart the options that I came up with - no luck. Keeps saying it's read-only and I cannot find a way to revert this.
The Rufus version is the same as the log's.

Log
---
```
Rufus version: 2.11.995
Windows version: Windows 10 64-bit (Build 14393)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta3
System locale ID: 0x0403
NOTE: No Windows Language Pack is installed for English (English) on this system.
This means that some controls may still be displayed using the system locale.
Found USB 2.0 device 'USB Device' (058F:6387)
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 487, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: SFD (Super Floppy Disk) or Unpartitioned
Partition 0:
  Type: Small FAT16 (0x00)
  Size: 3.7 GB (4009754624 bytes)
  Start Sector: 0, Boot: No
Checking for Rufus updates...
Checking release channel...
No new release version found.
Found USB 2.0 device 'USB Device' (058F:6387)
1 device found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 487, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: SFD (Super Floppy Disk) or Unpartitioned
Partition 0:
  Type: Small FAT16 (0x00)
  Size: 3.7 GB (4009754624 bytes)
  Start Sector: 0, Boot: No

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'F:' as volume mountpoint
Analyzing existing boot records...
Drive does not have an x86 Master Boot Record
Volume does not have an x86 Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
write_sectors: Write error [0x0000045D] No se puede realizar la solicitud por un error del dispositivo de E/S.
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Could not reset partitions
Re-mounted volume as 'F:' after error
```

**Comment by pbatard** [comment]
This is answered in the FAQ:
https://github.com/pbatard/rufus/wiki/FAQ#Rufus_cant_detectformat_my_drive_and_reports_that_it_is_readonly_or_contains_no_media

I'm afraid that your drive is most likely dead.
