### ISSUE TITLE
When make Efi ntfs type, usb's mbr is unknown.

### ISSUE THREAD

**Issue by apple3000** [pbatard/rufus#899]
Version. Rufus 2.12.1054.
I tested below.
1. Efi system of mbr type.
I selected iso and ntfs format.
I Started.
All succeeded. But mbr of usb is unknown.
So it can not boot in mbr bios.
So i set mbr of usb to usbhdd+ or nt6(bootmgr).

I had same result when i set booting from iso and booting from efi:ntfs.

Why does rufus make mbr of usb?
I want it will be fixed.
I multiboot

**Comment by pbatard** [comment]
No log, no support. Please follow the guidelines.
