### ISSUE TITLE
ER: Enable compression for NTFS

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#9]

**Comment by pbatard** [comment]
Please see the [cheat mode section of the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes) and especially the one for <kbd>Alt</kbd>-</kbd>N</kbd>. You may also be interested in <kbd>Alt</kbd>-</kbd>S</kbd> if you use compression. Now, if that doesn't work, you are 100% on your own, as these cheat mode are unsupported.

**Comment by kriegste** [comment]
Ah, ok, thanks. I googled the feature and Google sent me here and not to the FAQ. That might be a problem also for other users if the feature is hidden too well...
