### ISSUE TITLE
Not issue, but feature request

### ISSUE THREAD

**Issue by marcellogianola** [pbatard/rufus#903]
I wish that Rufus, in the next version, can copy the Windows 10 ISO image in a bootable partition of hard disk drive, so that I can install Windows from HDD and not from USB flash drive.

**Comment by pbatard** [comment]
Asking for a feature doesn't preclude you from reading the FAQ to find out if your request has already been answered (which [it has](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_support_internal_HDDsSSDs).
