### ISSUE TITLE
Permission denied, even when running as Admin.

### ISSUE THREAD

**Issue by LMGN** [pbatard/rufus#907]
Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [X] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [/] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [X] I also tried one or more of the following:
  - [X] Using a different USB drive
  - [X] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I ran the program as admin, and it says no permissions. Tried rebooting, different usb, different flash drive. Same error.

Log
---
```
Rufus version: 2.11.995
Windows version: Windows 8.1 64-bit (Build 9600)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta3
System locale ID: 0x0409
Will use default UI locale 0x0409
Found UAS (USB 3.0) device 'WD My Passport 0820 SCSI Disk Device' (1058:0820)
Could not get device number for device \\.\D:: [0x00000001] Incorrect function.
Could not get device number for device \\.\D:: [0x00000001] Incorrect function.
Device eliminated because it was detected as a Hard Drive (score 23 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives in 'Advanced Options' (after clicking the white triangle)
Found USB 2.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
NOTE: This device is an USB 3.0 device operating at lower speed...
Could not get device number for device \\.\D:: [0x00000001] Incorrect function.
Could not get device number for device \\.\D:: [0x00000001] Incorrect function.
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 7651, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: exFAT (0x07)
  Size: 58.6 GB (62931337216 bytes)
  Start Sector: 2048, Boot: No
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'DVD'
  Size: 4044648448 bytes
  Uses: EFI
  Uses: Bootmgr
Using image: Windows 8.1.iso

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE3 for write access
Could not get exclusive access to device \\.\PHYSICALDRIVE3: [0x00000005] Access is denied.

Found UAS (USB 3.0) device 'WD My Passport 0820 SCSI Disk Device' (1058:0820)
Could not get device number for device \\.\D:: [0x00000001] Incorrect function.
Could not get device number for device \\.\D:: [0x00000001] Incorrect function.
Device eliminated because it was detected as a Hard Drive (score 23 > 0)
If this device is not a Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of Hard Drives in 'Advanced Options' (after clicking the white triangle)
Found USB 2.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
NOTE: This device is an USB 3.0 device operating at lower speed...
Could not get device number for device \\.\D:: [0x00000001] Incorrect function.
Could not get device number for device \\.\D:: [0x00000001] Incorrect function.
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 7651, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: exFAT (0x07)
  Size: 58.6 GB (62931337216 bytes)
  Start Sector: 2048, Boot: No
```

**Comment by pbatard** [comment]
> I looked at https://github.com/pbatard/rufus/wiki/FAQ

I don't think you did. There's a dedicated entry for the `[0x00000005] Access is denied` message.

> I performed a search in the issue tracker for similar issues, using keywords relevant to my problem

Likewise, I don't think you searched for ['Access denied' in the issue tracker](https://github.com/pbatard/rufus/issues?utf8=%E2%9C%93&q=access%20denied), as there are quite a few entries.

Your issue has nothing to do with admin rights, and since it is answered in the FAQ, I will close it.
