### ISSUE TITLE
support of chinese fake usb drives by setting actual number of blocks

### ISSUE THREAD

**Issue by armars374** [pbatard/rufus#909]
Hello.
probably many people and also I are using fixed chinese fake usb drives
(for ex. using MyDiskFix you can fix such drives and use it)

It will be useful rufus to set manually maximum capacity of creating drive

thank you

hope I could explain what I meant

**Comment by pbatard** [comment]
I have no interest in adding such a feature. Encouraging people to use fake drives will only encourage the practice of creating such hardware and __duping__ customers. There's __NO WAY__ I want to be any part of that.
