### ISSUE TITLE
please give me solution

### ISSUE THREAD

**Issue by zarib** [pbatard/rufus#933]
.
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'ESD-ISO'
  Size: 3.4 GB
  Uses: EFI
  Uses: Bootmgr
Using image: Windows.iso

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE1 [\Device\Harddisk1\DR5] for write access
Will use 'G:' as volume mountpoint
I/O boundary checks disabled
Could not get exclusive access to \\?\Volume{e32a48ef-067c-11e7-be1b-b01041120de0} [\Device\HarddiskVolume9]: [0x00000005] Access is denied.
Could not lock volume
Re-mounted volume as 'G:' after error

Found USB 2.0 device 'Generic Flash Disk USB Device' (0000:7777)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 3824, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x05828403
Drive has an unknown Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.3 GB (31457247744 bytes)
  Start Sector: 63, Boot: Yes

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE1 [\Device\Harddisk1\DR5] for write access
Will use 'G:' as volume mountpoint
I/O boundary checks disabled
Could not get exclusive access to \\?\Volume{e32a48ef-067c-11e7-be1b-b01041120de0} [\Device\HarddiskVolume9]: [0x00000005] Access is denied.
Could not lock volume
Re-mounted volume as 'G:' after error

Found USB 2.0 device 'Generic Flash Disk USB Device' (0000:7777)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 3824, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x05828403
Drive has an unknown Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.3 GB (31457247744 bytes)
  Start Sector: 63, Boot: Yes

**Comment by pbatard** [comment]
Next time, please follow the checklist. It is there [for a reason](https://github.com/pbatard/rufus/wiki/FAQ#Error_0x00000005_Access_is_denied).
