### ISSUE TITLE
Rufus does not recognize 2 terabytes flash drive in windows 10

### ISSUE THREAD

**Issue by marival** [pbatard/rufus#934]
Rufus does not recognize a flash drive of 2 Terabytes, I already tested it on several computers and he does not find it. Can me help!

**Comment by pbatard** [comment]
The check list is there for a reason. If you had followed it, you would have found [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected).
