### ISSUE TITLE
Can't access USB disks after upgrading to Windows  10 Creators Update (1703)

### ISSUE THREAD

**Issue by tsynik** [pbatard/rufus#939]
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.

Additionally (if applicable):
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive
  - [x] Plugging the USB into a different port

Issue description
-----------------
After upgrading Windows 10 from Annivesary Update (1607) to Creators Update (1703) I can't access disks in exteranal USB enclosures and flash disks too (blank list). Tried 2 different enclosures with various disks on various ports and few flash disks. They worked fine with the same Rufus version (2.14 1086) and same hardware before upgrade on 1607 build. It's on Rufus  2.14.1086 (Portable)

Log
---
```
Rufus version: 2.14.1086 (Portable)
Windows version: Windows 10 64-bit (Build 15063)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~rc2
System locale ID: 0x0419
Will use default UI locale 0x0419
Found UAS (USB 2.0) device 'ASMT 2105 SCSI Disk Device' (174C:5106)
NOTE: This device is an USB 3.0 device operating at lower speed...
Waiting for access...
Could not open \\.\PHYSICALDRIVE2 [\Device\Harddisk2\DR3]: [0x00000020]  The process cannot access the file because it is being used by another process.
Device eliminated because it appears to contain no media
0 devices found
...
Found USB 2.0 device 'ATA APPLE HDD HTS545 USB Device' (2537:1068)
NOTE: This device is an USB 3.0 device operating at lower speed...
Waiting for access...
Could not open \\.\PHYSICALDRIVE2 [\Device\Harddisk2\DR4]: [0x00000020] The process cannot access the file because it is being used by another process.
Device eliminated because it appears to contain no media
0 devices found
```

**Comment by tsynik** [comment]
Hm, found the case of this issue. After upgrade, I probably also updated Paragon ExtFS for windows to current release, but doesn't mentioned it, because Rufus worked on same machine just few hours ago before upgrade with old Paragon ExtFS version. I also have Paragon HFS+ for windows, but it doesn't affect Rufus functionality in drives detection thou listed as incompatibe.

**Comment by pbatard** [comment]
FYI, Paragon HFS+ is mentioned in the [List of software that is incompatible with Rufus](https://github.com/pbatard/rufus/wiki/FAQ#Software).
