### ISSUE TITLE
Rufus doesn't detect Imdisk-mounted images

### ISSUE THREAD

**Issue by alegrigoriev** [pbatard/rufus#942]
Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [X] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Rufus doesn't detect Imdisk-mounted images (as HDD or floppy, Removable or not) as valid formatting targets.

Backstory: I use DOS-bootable drives to mount on Raritan and iDRAC remote access controllers, to run diagnostic software on remote hosts. It's a hassle to have to use an USB stick for that, since I could run the actual Raritan or iDRAC client on another remote host through Windows Remote Desktop. It may not be possible to connect to SUT directly because of corporate firewalls not allowing HTTP (only RDP). I though maybe I mount an image with Imdisk, mount it to Raritan or iDRAC, and boot off the remote SUT off it. I tried to mount a VHD as a hard disk partition, but remote access clients don't present it as a bootable disk to SUT BIOS. Or it's because it doesn't have a boot record. I used Rufus to format a bootable MSDOS drive on a VHD, but the SUT would not boot off it. Only a USB or floppy would do.

THIS MIGHT AS WELL BE IMDISK BUG, though.

Log
---
```
Rufus version: 2.14.1086 (Portable)
Windows version: Windows 2012_R2 64-bit (Build 9600)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~rc2
System locale ID: 0x0409
Will use default UI locale 0x0409
0 devices found
0 devices found
```

**Comment by pbatard** [comment]
I'm afraid that's not gonna happen:

1. Rufus is not designed to be a Sysadmin/Power User tool. It is designed to be used by the general public. This means that adding Sysadmin/Power User friendly features is not something I can see myself taking time way for.

2. An ImDisk virtual mount does not appear in Disk Manager, and does not create a proper underlying virtual device that can be seen by the OS. Instead, it looks mostly like an Explorer hack. As such, I would have to add some super custom code just to support it, and furthermore, it is very unlikely that this would achieve what you want, as ImDisk appears to deal with volumes and not disks (which means no MBR, or partititioning, and stuff). Or maybe I'm wrong, as I just played 5 mins with ImDisk, but I'm not really willing to invest time to add support for a tool that, in all likelihood, will only really benefit one user.

3. The weekly download tally for ImDisk is just too low to add support for it.

__Rejected.__
