### ISSUE TITLE
Hello!  Please add

### ISSUE THREAD

**Issue by Alexander1414x** [pbatard/rufus#950]
Hello pbatard!  Please add new funtcion   Multiboot USB for Antivirus many  LiveCD Kaspersky, Dr.Web, BitDefender and all.

**Comment by pbatard** [comment]
Next time please follow the checklist and [check the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiboot_support).

**Comment by Alexander1414x** [comment]
Hello!  it is little problem add function rufus.=(

2017-05-08 18:35 GMT+03:00 Pete Batard <notifications@github.com>:
