### ISSUE TITLE
Permalink for download portable version.

### ISSUE THREAD

**Issue by Elgin675** [pbatard/rufus#966]
Hello :) !

Thank's for this great software ;).
I have a little request, not about the software, but for the site.

At _https://rufus.akeo.ie/downloads/_, exist a permalink for the install version, named "**_rufus.exe_**".
Can you add, please, a permalink for download the latest **portable** version (like **rufusp.exe**, for example) :) ?

Thank's ;) !

**Comment by Xeon3D** [comment]
Erm, the file is exactly the same. You can just download rufus.exe and rename it rufusp.exe. It autodetects the P in the filename and changes it's mode from portable or non-portable accordingly.

**Comment by Elgin675** [comment]
Hem...

I feel very stupid. Thank's for the answer ;).
PS : I hasn't read the FAQ before post my question... Very sorry, it's my fault :s.
