### ISSUE TITLE
Rufus and VMWare ESXi 5.X / 6.X

### ISSUE THREAD

**Issue by SYSADMIT** [pbatard/rufus#972]
Just to mention that I have tested rufus to generate a USB installation of VMware ESXi, versions 5 and 6:

[http://www.sysadmit.com/2017/06/vmware-esxi-instalar-desde-usb.html](url)

It works perfectly.

If you want, you can add it in the section of the web:

"(2) Non exhaustive list of ISOs Rufus is known to work with"

**Comment by pbatard** [comment]
The list is meant to be non exhaustive, so I tend to keep the ISOs that are commonly used by a lot of people or that I think are representative. I don't think ESX, which is only relevant for VM Sysadmins is that relevant, so I will have to reject this request. Besides, if I were to add every ISO that people would like to see in that list, the list would be longer than the rest of the page!
