### ISSUE TITLE
GUI enhancement to recognise IMG and DD formats?

### ISSUE THREAD

**Issue by stilez** [pbatard/rufus#988]
The Rufus GUI and file selector only lists "ISO and "DD" in the dropdown. 

In the file selector it lists "ISO" or "any" (*.*).

In fact it can handle more than these, in particular the .IMG format used for some memstick releases (Example:  pfSense-CE-memstick-2.3.4-RELEASE-amd64.img is recognised as a DD image and works fine).

The problem is that because the UI doesn't list "IMG" (or "DD; IMG"), and the file selector doesn't list "DD" or "IMG" at all, it's not clear to a user that Rufus handles these files, because they don't appear in the file selector.

It might be worth making a small UI change for user clarity - that the dropdown lists "ISO" and "DD, IMG" (2 entries) not just "ISO" and "DD", and the file selector lists all common extensions ("ISO; DD; IMG; CDE") not just "ISO", so it's clear to the user what file formats can usually be read. If the file isn't valid it'll say so anyway.

**Comment by pbatard** [comment]
You're not the first person to suggest this, and I'm planning to do just that as part of the 3.x UI redesign (but no sooner). As to when 3.x will see the light of day, your guess is as good as mine, as this will require a lot of time...
