### ISSUE TITLE
ER:  Allow a Custom Icon to be placed in rufus_files folder to be default icon after format.

### ISSUE THREAD

**Issue by aarcane** [pbatard/rufus#989]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [NA] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [NA] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Please enhance Rufus by allowing us to place a custom icon in the rufus_files folder that we would like used to icon our drives.  I like to brand mine with a custom icon so that I recognise them on public computers.  Perhaps even an option to pre-load a drive with certain files from a specified folder would be useful.

Log
---
```
Not Applicable
```

**Comment by pbatard** [comment]
That's a bit too custom a request, and I don't really have plans to add a feature like this. There's no real need for it (not having custom icons won't be a major hindrance to accomplishing your task), and I don't think that many people will benefit from it in the first place. You may also want to see [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want).

Plus you can easily set the icon you want manually, by replacing `autorun.ico` on the drive, so it's hard for me to see why this needs to be automated.
For what is worth, if your ISO already contains an icon (through the `autorun.inf` file), Rufus will use that one, so if you want specific icons, maybe you should add the creators of the ISO.
