### ISSUE TITLE
Windows 98SE iso no support format..

### ISSUE THREAD

**Issue by ruthan** [pbatard/rufus#995]
Issue description
-----------------
Pleas add support for this format.

**Comment by pbatard** [comment]
Too old. Not gonna happen. You may be able to install Win98 by creating a FreeDOS boot disk and then copying the files, but don't count on any more help here.

**Comment by NSbuilder** [comment]
Heh, I tested it too before.
However it's too old and you know, it wasn't designed to run from usb drive.
