### ISSUE TITLE
BayHubTech Integrated MMC/SD controller - SD cards not detected by Rufus 2.16

### ISSUE THREAD

**Issue by redstorm1** [pbatard/rufus#998]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] The SD is detected by windows and assigned a drive letter and the file system is browsable.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
SD card is not detected by Rufus, detected fine by Windows.
Controller is a "BayHubTech Integrated MMC/SD controller"
`Device ID: PCI\VEN_1217&DEV_8520&SUBSYS_380017AA&REV_01`

The disk gets get detected as a SCSI disk
`Device ID: SCSI\Disk___________________SDHC_0001`

Wondering if the SDHC would be a way to safely detect these types of removable drives.

Log
---
```
Rufus version: 2.16.1170 (Portable)
Windows version: Windows 10 64-bit (Build 15063)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0409
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found non-USB removable device ' SDHC  SCSI Disk Device' => Eliminated
0 devices found
Found non-USB removable device ' SDHC  SCSI Disk Device' => Eliminated
0 devices found
Found non-USB removable device ' SDHC  SCSI Disk Device' => Eliminated
0 devices found
Found non-USB removable device ' SDHC  SCSI Disk Device' => Eliminated
0 devices found
Found non-USB removable device ' SDHC  SCSI Disk Device' => Eliminated
0 devices found
Found non-USB removable device ' SDHC  SCSI Disk Device' => Eliminated
0 devices found
Found non-USB removable device ' SDHC  SCSI Disk Device' => Eliminated
0 devices found
Found non-USB removable device ' SDHC  SCSI Disk Device' => Eliminated
0 devices found
```

**Comment by pbatard** [comment]
Thanks for the report. Looks like I just need to add `_SDHC_` to the [list I already have](https://github.com/pbatard/rufus/blob/master/src/dev.c#L299) to get your card reader enumerated by default. I will do that for the 2.17 release.

Note that if you run with USB Debug enabled (<kbd>Alt</kbd>-<kbd>.</kbd>) and then use the <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>F</kbd> cheat mode, you should be able to get your device listed in Rufus 2.16.
